### ISSUE TITLE
internal/core/eval: value alias does not work with list value

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#1003]
_Originally opened by @myitcv in https://github.com/cuelang/cue/issues/1003_

### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version +37bf801b linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
exec cue export x.cue

-- x.cue --
package x

y: X = [1, 2, X[0]]
```

### What did you expect to see?

```
{
    "y": [
        1,
        2,
        1
    ]
}
```

### What did you see instead?

```
y.2: index out of range [0] with length 0:
    ./x.cue:3:17
```

My understanding from [the spec](https://tip.cuelang.org/docs/references/spec/#aliases) is that this should work, because only the value alias before a list _element_ is not yet implemented: this is before the list itself.

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/1003#issuecomment-847837827_

It is correct that this should be supported. At the present it is not, though.

**Comment by mpvl** [comment]
Analysis: list elements are arcs, from CUE perspective, but the compiler does not treat them as such. As a result, the "up counts" are out of sync in the case of value aliases. 

A fix for this would also make it possible to allow aliases for list elements.
