### ISSUE TITLE
cmd/cue: bad error message in the case bool value cannot be parsed

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#1011]
_Originally opened by @myitcv in https://github.com/cuelang/cue/issues/1011_

### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version +aa61ee7f linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
exec cue export file.cue --inject builtat=x

-- file.cue --
package x

built_at: bool @tag(builtat,type=bool)
```

### What did you expect to see?

An error message about being unable to parse `x` as a `bool` value.

### What did you see instead?

An unrelated error message about environment variables:

```
invalid boolean value "x" for environment variable builtat
```

**Comment by mvdan** [comment]
It seems to me like the error is already pretty good - I would perhaps just swap "environment variable" with "injected value", per the naming used in `cue help injection`. Otherwise, it already says "boolean value", "x", and "buildat".

**Comment by cedricgc** [comment]
@mvdan Would you be able to point me to the package/file where this error is generated? Trying to find where the tag validation happens to update the message

**Comment by mvdan** [comment]
@cedricgc it seems to be in `internal/cli`:

```
$ git grep 'invalid.*for environment variable'
internal/cli/cli.go:                "invalid number for environment variable %s", name)
internal/cli/cli.go:                "invalid boolean value %q for environment variable %s", str, name))
internal/cli/cli.go:            "invalid type for environment variable %s", name)
pkg/tool/os/env.go:         "invalid type %s for environment variable %s", k, name)
```

I'd fix up all three of those, since they should all replace "environment variable". I'm actually not convinced that "injected value" is the best naming, since

    invalid boolean value "x" for injected value buildat

is rather confusing - there is just one value "x", "buildat" is the name for the injection.

So perhaps "injection tag", and %q to also quote the name, like:

    invalid boolean value "x" for injection tag "buildat"

**Comment by cedricgc** [comment]
haha was trying to make the right regex to find the message earlier, thanks for that.

will take a crack

**Comment by cedricgc** [comment]
https://review.gerrithub.io/c/cue-lang/cue/+/1174026
