### ISSUE TITLE
cmd/cue: pkg directory treated like cue.mod/{pkg,gen,usr}

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#1014]
_Originally opened by @myitcv in https://github.com/cuelang/cue/issues/1014_

### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version +aa61ee7f linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
cd x
exec cue export x.cue

-- x/x.cue --
package x

import "example.com/component"

top: component.name
-- pkg/example.com/component/component.cue --
package component

name: "component"
```

### What did you expect to see?

```
> exec cue export x.cue
[stderr]
import failed: cannot find package "example.com/component":
    ./x.cue:3:8
```

### What did you see instead?

```
> exec cue export x.cue
[stdout]
{
    "top": "component"
}
```

Per @mpvl in https://github.com/cuelang/cue/issues/452#issuecomment-731582285 this is likely a legacy of pre-module support for imports. 

We should drop support for this mechanism entirely in favour of modules. 

cc @seh as a follow up to https://github.com/cuelang/cue/issues/452#issuecomment-829607855

**Comment by mvdan** [comment]
Done in https://review.gerrithub.io/c/cue-lang/cue/+/1173271 :) I wasn't aware of this issue when I wrote the cleanup patch, my apologies.
