### ISSUE TITLE
encoding/openapi: remove use of deprecated identifiers

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#1015]
_Originally opened by @myitcv in https://github.com/cuelang/cue/issues/1015_

### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version +aa61ee7f linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

Use of `encoding/openapi` requires using `cue.Runtime` and friends, all of which are deprecated. This triggers errors in tools like `staticcheck` that catch use of deprecated identifiers. 

### What did you expect to see?

An API which does not require using deprecated identifiers.

### What did you see instead?

As above.

Adding this as a tracking item; I will work on this as part of fixing up https://github.com/istio/tools/tree/master/cmd/cue-gen

**Comment by mvdan** [comment]
Even though this issue came first, I think it's best to tackle deprecation warnings as flagged by staticcheck in https://github.com/cue-lang/cue/issues/2480. Having one issue per package doesn't seem necessary to me.
