### ISSUE TITLE
cmd/cue: JSON parse error reports wrong position in file

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#1017]
_Originally opened by @rogpeppe in https://github.com/cuelang/cue/issues/1017_

commit aa61ee7f7c7c65900f63e9506ed42317757b627c

The error printed when parsing an invalid JSON file isn't tagged with the correct position information.

```
! exec cue export x.json
stderr 'x\.json:3:5'
-- x.json --
[
  {
    x: 5926
  }
]
```

The error message that's printed is:
```
invalid JSON for file "$WORK/x.json": invalid character 'x' looking for beginning of object key string:
    ./x.json:1:1
```
but the error is not on the first character of the first line.

**Comment by mvdan** [comment]
@rogpeppe created this issue again in https://github.com/cue-lang/cue/issues/3317, which is now fixed in master. Closing as a dupe.
