### ISSUE TITLE
cmd/cue: fmt does not handle lists consistently

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#1023]
_Originally opened by @uhthomas in https://github.com/cuelang/cue/issues/1023_

### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.4.0 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What did you do?

Given

```
a: [ "b"]
```

### What did you expect to see?

```
a: ["b"]
// or: (I don't know what cue fmt's preference is)
a: [ "b" ]
```

### What did you see instead?

No change.

**Comment by uhthomas** [comment]
Just coming here to say I see this all the time when working with cue. Formatting lists always has a leading space.

```cue
a: [             "b"          ]
```

becomes

```cue
a: [ "b"]
```
