### ISSUE TITLE
encoding/gocode(/gocodec): provide non-deprecated API

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#1035]
_Originally opened by @myitcv in https://github.com/cuelang/cue/issues/1035_

### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
v0.4.0
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

Tried to use the [`encoding/gocode/gocodec`](https://pkg.go.dev/cuelang.org/go@v0.4.1-0.20210601130059-0070bb104ee8/encoding/gocode/gocodec) or [`encoding/gocode`](https://pkg.go.dev/cuelang.org/go@v0.4.1-0.20210601130059-0070bb104ee8/encoding/gocode) APIs.

### What did you expect to see?

No `staticcheck` errors.

### What did you see instead?

Errors warning me that I am using deprecated `cue.Runtime` or `cue.Instance`. 

As part of this we should also address https://github.com/cuelang/cuelang.org/pull/183

**Comment by mvdan** [comment]
This was done in various steps over the last year or so, e.g. https://review.gerrithub.io/c/cue-lang/cue/+/556343 and https://review.gerrithub.io/c/cue-lang/cue/+/1174069.
