### ISSUE TITLE
cmd/cue: intermittent #FileInfo errors when parsing cue

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#1043]
_Originally opened by @tonyhb in https://github.com/cuelang/cue/issues/1043_

<pre>
v0.4.0
</pre>

### Does this issue reproduce with the latest release?
Yes

### What did you do?

```
	cfg := &load.Config{
		Dir:        "/",
		ModuleRoot: "/",
		Overlay:    map[string]load.Source{},
	}
	cfg.Stdin = strings.NewReader(input)
	instances := load.Instances([]string{"-"}, cfg)

	if len(instances) != 1 {
		return nil, errors.Errorf("unsupported number of instances: %!d(MISSING)", len(instances))
	}

	runtime := cuecontext.New()
	inst := runtime.BuildInstance(instances[0])
	if err := inst.Err(); err != nil {
		buf := &bytes.Buffer{}
		cueerrors.Print(buf, err, nil)
		return nil, errors.Wrap(ErrInvalidConfig, buf.String())
	}
```

Every 1 in ~8 times, Cue will error when validating it's _own_ cue files:

```
#FileInfo.definitions: could not parse arguments: cannot convert non-concrete value bool:
    types.cue:26:2
#FileInfo.optional: could not parse arguments: cannot convert non-concrete value bool:
    types.cue:27:2
#FileInfo.const
raints: could not parse arguments: cannot convert non-concrete value bool:
    types.cue:28:2
#FileInfo.keepDefaults: could not parse arguments: cannot convert non-concrete value bool:
    types.cue:29:2
#FileInfo.incomplete: could not parse arguments: cannot convert
non-concrete value bool:
    types.cue:30:2
#FileInfo.imports: could not parse arguments: cannot convert non-concrete value bool:
    types.cue:31:2
```

### What did you expect to see?

No errors, as the cue input is valid.

### What did you see instead?

Errors parsing cue's own internal definitions.

**Comment by cueckoo** [comment]
_Original reply by @tonyhb in https://github.com/cuelang/cue/issues/1043#issuecomment-857000980_

This is fixable if I update the `BuildFile` generated within an instance as follows, prior to building the instance:

```
	instances[0].BuildFiles[0].Encoding = build.CUE
	instances[0].BuildFiles[0].Form = build.Schema
	instances[0].BuildFiles[0].Interpretation = ""
```

This is because Cue short circuits here: https://github.com/cuelang/cue/blob/master/internal/filetypes/filetypes.go#L77-L80

However, by default, `Form` is an empty string and so evaluating does not short circuit.

This isn't so much a fix - the race condition/bug exists somewhere when parsing cue's builtin, using gob encoding.

**Comment by cueckoo** [comment]
_Original reply by @tonyhb in https://github.com/cuelang/cue/issues/1043#issuecomment-857353005_

That was a lie, my bad!  If I include packages, this transient error still exists.  Packages are never included with the correct file builds to skip this short circuit: https://github.com/cuelang/cue/blob/master/internal/filetypes/filetypes.go#L77-L80.

Instead, I had to reimplement dependency resolution and file parsing to generate instances for each file (and their depencency).

**Comment by myitcv** [comment]
@tonyhb apologies for the delay in getting round to this, we've been busy [migrating to a new home](https://github.com/cue-lang/cue/issues/1078).

Please can you provide a repro that gives the errors you are seeing above? I'm not able to reproduce this given the snippets included above. Thanks

**Comment by jgillich** [comment]
Also running into this:
```
could not parse arguments: #FileInfo.definitions: cannot convert non-concrete value bool
```
The weird thing is that it works when I run it via the cli. I've tried to simplify to get reproduction steps but so far I haven't been able to...

@tonyhb Did you find a solution to this? How did you reimplement the dependency resolution?

**Comment by jgillich** [comment]
Still no idea what's triggering this but what made it work for me is this:

```patch
--- a/internal/filetypes/types.cue
+++ b/internal/filetypes/types.cue
@@ -289,6 +289,7 @@ forms: data: {
 // encodings: "": error("no encoding specified")
 
 encodings: cue: {
+       forms.schema
        stream: false
 }
```

In the calls to `filetype.FromFile` the `b.Form` field was empty so the FileInfo was indeed never fully filled in.

**Comment by myitcv** [comment]
@jgillich please can you provide a full repro that shows the problem here?

Per my comment in https://github.com/cue-lang/cue/issues/1043#issuecomment-889213976 I haven't been able to reproduce this using the snippets above.

**Comment by jgillich** [comment]
@myitcv I've tried to make a repro but couldn't, although now I have. The issue was concurrent access of `cue.Build` and `load.Instances`, which use a shared runtime behind the scenes. This is why I've only been able to reproduce this issue from within my operator, and synchronizing access fixed it. A better fix would be using cuecontext (if not for #1484), but it can't be used with loader, right?

Here's that repro if you still want it: https://github.com/jgillich/cue-fileinfo

Remove the mutex calls and you should get either the FileInfo error or a `panic: not properly initialized`

**Comment by myitcv** [comment]
@jgillich @tonyhb - I've moved this to https://github.com/cue-lang/cue/issues/1746 which includes a repro. Thanks for helping to narrow down the problem here.

**Comment by roman-mazur** [comment]
@myitcv I see the `FileInfo error` even with the mutex in place with v0.4.3. 

We do `load.Instances` and then `cuecontext.New().BuildInstance`.

The first call does not panic with a global mutex, but we see a FileInfo error when we get a `Value` from the instance and check for an error. A fully unwrapped error is below
```
#FileInfo.definitions: could not parse arguments: cannot convert non-concrete value bool (from types.cue:26:2)
types.cue:27:2 #FileInfo.optional: could not parse arguments: cannot convert non-concrete value bool (from types.cue:27:2)
types.cue:28:2 #FileInfo.constraints: could not parse arguments: cannot convert non-concrete value bool (from types.cue:28:2)
types.cue:29:2 #FileInfo.keepDefaults: could not parse arguments: cannot convert non-concrete value bool (from types.cue:29:2)
types.cue:30:2 #FileInfo.incomplete: could not parse arguments: cannot convert non-concrete value bool (from types.cue:30:2)
types.cue:31:2 #FileInfo.imports: could not parse arguments: cannot convert non-concrete value bool (from types.cue:31:2)
types.cue:26:2 #FileInfo.definitions: could not parse arguments: cannot convert non-concrete value bool (from types.cue:26:2)
types.cue:27:2 #FileInfo.optional: could not parse arguments: cannot convert non-concrete value bool (from types.cue:27:2)
types.cue:28:2 #FileInfo.constraints: could not parse arguments: cannot convert non-concrete value bool (from types.cue:28:2)
types.cue:29:2 #FileInfo.keepDefaults: could not parse arguments: cannot convert non-concrete value bool (from types.cue:29:2)
types.cue:30:2 #FileInfo.incomplete: could not parse arguments: cannot convert non-concrete value bool (from types.cue:30:2)
types.cue:31:2 #FileInfo.imports: could not parse arguments: cannot convert non-concrete value bool (from types.cue:31:2)
types.cue:26:2 #FileInfo.definitions: could not parse arguments: cannot convert non-concrete value bool (from types.cue:26:2)
types.cue:27:2 #FileInfo.optional: could not parse arguments: cannot convert non-concrete value bool (from types.cue:27:2)
types.cue:28:2 #FileInfo.constraints: could not parse arguments: cannot convert non-concrete value bool (from types.cue:28:2)
types.cue:29:2 #FileInfo.keepDefaults: could not parse arguments: cannot convert non-concrete value bool (from types.cue:29:2)
types.cue:30:2 #FileInfo.incomplete: could not parse arguments: cannot convert non-concrete value bool (from types.cue:30:2)
types.cue:31:2 #FileInfo.imports: could not parse arguments: cannot convert non-concrete value bool (from types.cue:31:2)
```

So I think this one is separate from the concurrency issues.

Very hard to reproduce though...
We do these calls in the server logic. Once we see this error, all the subsequent attempts to get a value from the loaded instance result in this error.

**Comment by roman-mazur** [comment]
From what I understand, the file mentioned in this error is not supposed to be used in runtime at all: it's only used at CUE build time to generate `internal/filetypes/types.go`.

But somehow it's included in what is used to load an instance using the `load` package. So probably it depends on the `load.Config`. In my case, it looks like the following one:

```go
//go:embed some-config.cue
var cueSrc string

func doLoad() {
	space := filepath.Join(os.TempDir(), "config-space")
	cfg := &load.Config{
		Dir:     space,
		Overlay: make(map[string]load.Source),
	}
	cfg.Overlay[filepath.Join(space, "config.cue")] = load.FromString(cueSrc)

	instances := load.Instances([]string{}, cfg)
	value := cuecontext.New().BuildInstance(instances[0])
	log.Println(value.Err()) // Here we have the error.
}
```

I'm going to try to specify the `Package` field in the config. It will be different from the package declared in internal `types.cue` - hopefully, it will help to mitigate our issue.
