### ISSUE TITLE
encoding/yaml: datetime-like strings should be exported as quoted strings

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#1076]
_Originally opened by @lytedev in https://github.com/cuelang/cue/issues/1076_

### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version 0.4.0 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

It looks like I'm using the latest release.

### What did you do?

```
echo 'service: port_mappings: ["2222:22"]' | cue eval - --out yaml | yq
```

### What did you expect to see?

```
echo 'service: port_mappings: ["2222:22"]' | cue eval - --out yaml | yq
{
  "service": {
    "port_mappings": [
      "2222:22"
    ]
  }
}
```

### What did you see instead?

```
{
  "service": {
    "port_mappings": [
      133342
    ]
  }
}
```

# Reasoning

YAML supports some date/time formats, and the unquoted `2222:22` is interpreted as a base60 float. So any string in this format with a port on the right less than 60 will be interpreted this way.

Cue should either wrap all strings in quotes or detect this format and wrap it in quotes to protect you.

**Comment by cueckoo** [comment]
_Original reply by @lytedev in https://github.com/cuelang/cue/issues/1076#issuecomment-871728307_

Possibly related: https://github.com/go-yaml/yaml/issues/34

**Comment by cueckoo** [comment]
_Original reply by @lytedev in https://github.com/cuelang/cue/issues/1076#issuecomment-871733884_

My workaround for this, for anybody who cares, was to output JSON (`cue ... --out json`) which any YAML deserializer should handle just fine.

**Comment by cueckoo** [comment]
_Original reply by @verdverm in https://github.com/cuelang/cue/issues/1076#issuecomment-872440494_

This seems more like a problem with `yq` and Yaml 1.1 vs 1.2+ (looking through the go-yaml issue you linked

```
$ echo 'service: port_mappings: ["2222:22"]' | cue eval - --out yaml
service:
  port_mappings:
  - 2222:22
```

This looks to be valid YAML 1.2+

Also, which `yq` are you using

This one works fine https://github.com/mikefarah/yq/releases/tag/v4.9.6

```
$ echo 'service: port_mappings: ["2222:22"]' | cue eval - --out yaml | yq e -
service:
  port_mappings:
    - 2222:22
```

**Comment by cueckoo** [comment]
_Original reply by @lytedev in https://github.com/cuelang/cue/issues/1076#issuecomment-872497400_

This also happens with `docker-compose`, to be clear. I just used `yq` as a quick way to demonstrate the problem. Also, if you refer to this comment on the linked issue, you can see that these YAML deserializers/parsers are following the spec for parsing what my Cue intended to be a string as a base-60 float: https://github.com/go-yaml/yaml/issues/34#issuecomment-55772666

**Comment by cueckoo** [comment]
_Original reply by @verdverm in https://github.com/cuelang/cue/issues/1076#issuecomment-872545605_

It's been more than 10 years since YAML the 1.2 spec was written. Should the parsers be updated at this point? I'm not sure what CUE has said about how far back it supports various specs... not sure if there is a link anywhere. I only know for Go it is the same versions that the Go team supports.

---

Other libraries are specifically saying _no_ to supporting the base60 nonsense

- https://pkg.go.dev/gopkg.in/yaml.v2
- https://pkg.go.dev/gopkg.in/yaml.v3

Note that CUE is using the `yaml.v3` (https://github.com/cuelang/cue/blob/master/go.mod#L24) but may also have some custom yaml parsing around?

Are the python `yq` and `docker-compose` using the same python library which is supporting this? Is this primarily a python related thing? Looking at some other major languages, the top yaml libraries target v1.2 as well, some specifically calling out dropping the base60.

**Comment by cueckoo** [comment]
_Original reply by @niemeyer in https://github.com/cuelang/cue/issues/1076#issuecomment-872837133_

go-yaml has indeed never supported the float 60 representation as it's a bad idea (spec 1.2 confirms that), but it does marshal such values as quoted strings to prevent them from being interpreted incorrectly by old parsers. So it doesn't look like that specific output was generated by go-yaml v3.

Here is how it would handle it:

https://play.golang.org/p/Y0Qg72VW2p1

**Comment by cueckoo** [comment]
_Original reply by @verdverm in https://github.com/cuelang/cue/issues/1076#issuecomment-873151333_

@niemeyer is the general (simple?) idea to quote any string which has a colon when emitting?

**Comment by cueckoo** [comment]
_Original reply by @niemeyer in https://github.com/cuelang/cue/issues/1076#issuecomment-873224820_

No, we check the actual syntax of base 60 floats from the 1.1 spec. This is also far from being the only edge case in that regard. See bools on 1.1 vs. 1.2, for instance.

**Comment by myitcv** [comment]
Thanks @lytedev, @verdverm and @niemeyer for the exchange above. Apologies for the delay in replying (been catching up post the migration in #1078).

My understanding from the exchange above is that CUE's Yaml encoding should fall in line with `go-yaml` and marshal such values as quoted strings to prevent them from being interpreted incorrectly by old parsers, which is captured by the test:

```
exec cue export --out yaml x.cue
cmp stdout stdout.golden

-- x.cue --
service: "2222:22"
-- stdout.golden --
service: "2222:22"
```

which currently (ecb17c94) fails with:

```
> exec cue export --out yaml x.cue
[stdout]
service: 2222:22
> cmp stdout stdout.golden
[diff -stdout +stdout.golden]
-service: 2222:22
+service: "2222:22"

FAIL: /tmp/testscript491711293/repro.txt/script.txt:2: stdout and stdout.golden differ
```

Please shout if anyone disagree's with this conclusion.

**Comment by lytedev** [comment]
This sounds correct to me. The only reason to not properly quote string values when marshalling as YAML is because it looks pretty, but that can cause all sorts of nasty problems with YAML, so it's probably better to just be explicit about strings -- even in YAML.

**Comment by mpvl** [comment]
@niemeyer: CUE does use go-yaml v3, but it uses `SetString` on `Node`. How do I get the safely escaped strings using the `Node` API?

**Comment by verdverm** [comment]
The `Style` member of `Node` looks to have values which indicate that it controls string render style. A brief search through the code looks to have some switches on this: https://github.com/go-yaml/yaml/blob/496545a6307b2a7d7a710fd516e5e16e8ab62dbc/encode.go#L542

- https://pkg.go.dev/gopkg.in/yaml.v3#Node
- https://pkg.go.dev/gopkg.in/yaml.v3#Style

my best guess without writing code
