### ISSUE TITLE
internal/eval: call to json.Marshal with incomplete value doesn't report position information

### ISSUE THREAD

**Issue by alan-strohm** [cue-lang/cue#1082]
### What version of CUE are you using (`cue version`)?

cue version v0.4.0 linux/amd64
The cue playground has the same problem.

### Does this issue reproduce with the latest release?

I think so.

### What did you do?

https://cuelang.org/play/?id=KgN8ooVxxua#cue@export@json

call json.Marshal on a struct with an incomplete value.

### What did you expect to see?

A helpful error message with the name of the incomplete field similar to cue export:

failed to encode: Foo.id: incomplete value string

https://cuelang.org/play/?id=hE_XR6Rmp1q#cue@export@json

### What did you see instead?

An error message that didn't indicate which part of the struct had the problem:

failed to encode: cannot convert incomplete value "string" to JSON

**Comment by mpvl** [comment]
The first playground example is empty for me. The second playground example gives the error as expected.

**Comment by alan-strohm** [comment]
Woops, I messed up the link.  Sorry!  Here it is (also edited the original): https://cuelang.org/play/?id=KgN8ooVxxua#cue@export@json

I'm just getting started with Cue and am seeing a lot of places where the error reporting could be improved.  Let me know if you're not at a stage where you are ready for bugs like that.

**Comment by myitcv** [comment]
Thanks for providing more context, @alan-strohm - I agree the error reporting could be improved here.

With eb18b74c I see the following:

```
! exec cue export
stderr 'x.cue'

-- x.cue --
package a

import "encoding/json"

#Base: {
	id: string
}

Foo: #Base
Bar: json.Marshal(#Base)
```

which results in:

```
> ! exec cue export
[stderr]
cannot convert incomplete value "string" to JSON
Foo.id: incomplete value string
[exit status 1]
> stderr 'x.cue'
FAIL: /tmp/testscript259603441/repro.txt/script.txt:2: no match for `x.cue` found in stderr
```

i.e. we don't get any position information for either incomplete error (here, loosely represented by asserting that `stderr` should include `x.cue`)

**Comment by mvdan** [comment]
As of v0.6.0-beta.1, it seems like the position information is now properly displayed. Using Paul's reproducer from the previous comment, I see:

```

> ! exec cue export
[stderr]
Foo.id: incomplete value string:
    ./x.cue:6:6
cannot convert incomplete value "string" to JSON:
    ./x.cue:6:6
[exit status 1]
```
