### ISSUE TITLE
internal/eval: order of if clause appears to be significant

### ISSUE THREAD

**Issue by KostasKgr** [cue-lang/cue#1083]
### Discussed in https://github.com/cue-lang/cue/discussions/1075

<div type='discussions-op-text'>

<sup>Originally posted by **cueckoo** July  3, 2021</sup>
_Originally opened by @KostasKgr in https://github.com/cuelang/cue/discussions/1075_

Hello all, I wasn't sure if the right place for this is here, or in slack or in issues. Let me know!

I've been trying to model our multi customer configuration and whilst trying it I saw a behaviour that I didn't expect.

I'm trying to understand if it is an issue or not, but it definitely breaks composition of different files for the approach I was trying.

So to showcase this, i have two files:

feature_definitions.cue
```
package config

features: {
    myFeature: *false | bool
}

if features.myFeature {
    myService: {
        config: {
            replicas: 4
        }
    }    
}
```
regional_configs.cue
```
package config

region: "US"
if region == "US" {
    features: myFeature: true
}
```

If I include feature definitions before regional configs then I get an error, If i do it the other way around I get the intended outcome.
```
15:41 $ cue eval -c feature_definitions.cue regional_configs.cue 
cannot add field myFeature: was already used:
    ./regional_configs.cue:5:15
```

```
15:46 $ cue eval -c regional_configs.cue feature_definitions.cue 
region: "US"
features: {
    myFeature: true
}
myService: {
    config: {
        replicas: 4
    }
}
```

Does using expressions limit splitting out the definitions across multiple files and thus in random composition?
Is this an issue or the intended outcome?

Thank you!

</div>

You can use the following script to reproduce the issue:

```
cd $(mktemp -d)
(
set -e

cat <<EOD > feature_definitions.cue
package config

features: {
    myFeature: *false | bool
}

if features.myFeature {
    myService: {
        config: {
            replicas: 4
        }
    }    
}
EOD



cat <<EOD > regional_configs.cue
package config

region: "US"
if region == "US" {
    features: myFeature: true
}
EOD


# This works
cue eval -c regional_configs.cue feature_definitions.cue 

# This errors
cue eval -c feature_definitions.cue regional_configs.cue 
)
```

**Comment by mpvl** [comment]
The order shouldn't matter and as far as I can tell it should work in both directions.

**Comment by myitcv** [comment]
Confirmed against eb18b74c:

```
# Order 1
exec cue eval -c regional_configs.cue feature_definitions.cue
cmp stdout stdout.golden

# Order 2
exec cue eval -c feature_definitions.cue regional_configs.cue
cmp stdout stdout.golden

-- feature_definitions.cue --
package config

features: {
    myFeature: *false | bool
}

if features.myFeature {
    myService: {
        config: {
            replicas: 4
        }
    }
}
-- regional_configs.cue --
package config

region: "US"
if region == "US" {
    features: myFeature: true
}
-- stdout.golden --
region: "US"
features: {
    myFeature: true
}
myService: {
    config: {
        replicas: 4
    }
}
```

This script fails with:

```
# Order 1 (0.029s)
# Order 2 (0.026s)
> exec cue eval -c feature_definitions.cue regional_configs.cue
[stderr]
cannot add field myFeature: was already used:
    ./regional_configs.cue:5:15
```

which appears to show the order of the arguments to `cue eval` _is_ significant.

The significance here of comprehension order could well be related to https://github.com/cue-lang/cue/issues/1130

**Comment by myitcv** [comment]
Possibly related to https://github.com/cue-lang/cue/issues/1317
