### ISSUE TITLE
ci: workflow-related commits do not replicate from GerritHub to GitHub

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#1091]
Known issue with the GerritHub GitHub plugin. Being tracked and fixed via:

https://bugs.chromium.org/p/gerrit/issues/detail?id=14533

cc @lucamilanesio

**Comment by lucamilanesio** [comment]
@myitcv We have this issue in our Kanban board, we're working on it !

**Comment by myitcv** [comment]
Wonderful, thank you!

**Comment by myitcv** [comment]
This was fixed a long time ago! Thanks again @lucamilanesio
