### ISSUE TITLE
cmd/cue: --ignore flag no longer works for some (all?) errors

### ISSUE THREAD

**Issue by MikkelHJuul** [cue-lang/cue#1093]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.4.0 linux/amd64
</pre>
installed using `go install ...@latest`
on latest release

### What did you do?
you can see my steps to reproduce here:
https://cuelang.org/play/?id=tvkvPr6gTyH#cue@export@cue

### What did you expect to see?
I expect both(all) "errors" to be printed when I specify the `--ignore`-flag
The internal cue eval/fmt error printing is More acceptable, but I expect `vet` to be able to print all errors, so I don't have to manually "vet" my files removing lines or adding specific "untrue" conditions to the cue-file

### What did you see instead?
see https://cuelang.org/play/?id=tvkvPr6gTyH#cue@export@cue

### Other notes
slack discussion link: https://cuelang.slack.com/archives/CLT3ULF6C/p1625123020188600

**Comment by myitcv** [comment]
Thanks for the report @MikkelHJuul, and for following up from our Slack conversation.

Incidentally, for multi-file reproductions like this, I would encourage you to look through our wiki that gives tips on how to create self-contained reproducers: https://github.com/cue-lang/cue/wiki/Creating-test-or-performance-reproducers. For example, for the scenario you presented, my reproduction looks like this:

```
! exec cue vet some.json some.cue -d '#Something'
cmp stderr stderr.golden

# What should --ignore do? Exit with a zero exit code?
# Report all errors?
exec cue vet --ignore some.json some.cue -d '#Something'
cmp stderr stderr.golden

-- some.cue --
#Method: "AAA"
#angle:  "whatever"

#Something: {
	method: #Method
	angle:  #angle
}

a: #Something & {
	method: "Lilly"
	angle:  "Ellis"
}
-- some.json --
{"method":"ANYTHING","angle":"not whatever"}
-- stderr.golden --
a.angle: conflicting values "Ellis" and "whatever":
    ./some.cue:2:10
    ./some.cue:6:10
    ./some.cue:9:4
    ./some.cue:11:10
a.method: conflicting values "Lilly" and "AAA":
    ./some.cue:1:10
    ./some.cue:5:10
    ./some.cue:9:4
    ./some.cue:10:10
```

Some points from my brief analysis:

* `--ignore` does not appear to be particularly well documented with respect to what type of errors it ignores. Some clarity here would be useful.
* It's unclear whether `--ignore` is expected to return a zero exit code or not.
* As @MikkelHJuul it seems unlikely that `--ignore` should return just the first error.

There is potentially some interconnected behaviour/bug here, but there is definitely some improvements that could be made to the documentation.

I will discuss with @mpvl to ensure we get the relevant history behind the `--ignore` flag, but my suspicion is that `--ignore` should:

* give the same `stderr` output as `cue vet` without the flag;
* return a zero exit code.

@MikkelHJuul please can you give some details on why you are using the `--ignore` flag? In particular, what is the use case? That might well help to establish (in combination with the history from @mpvl) whether `--ignore` is actually what you want, or indeed something else.

**Comment by MikkelHJuul** [comment]
Hi @myitcv 

Thanks for the suggestions, I am trying to vet a json object, where the value of a field must be one of some value (enum-like) and as I am trying to do version-vetting of a file given a specification, I wanted the output to print all mismatches in the first call

to clarify, field : `some: field1: "val1" | "val2"` and `some: field2: int`. I would like to be able to use cue to evaluate a json that must comply to these rules, but I don't want to have to remove rules or manually remove fields and reiterate the vetting of the file until all errors if any are printed/fixed this way.

**Comment by myitcv** [comment]
Thanks @MikkelHJuul. Also pinging @mhratson from #1106. The issue here (and in #1106's "Also" section) appears to be that the `-i` flag is no longer working with respect to some (any?) errors. As I noted above, that's not helped by the fact that we don't have any tests capturing this behaviour. 

So I will repurpose this issue for the fix of `-i`. The best test case to demonstrate the problem comes from #1106 

```
exec cue eval -i bottom.cue

-- bottom.cue --
a: 4
a: 5

l: [ 1, 2]
l: [ 1, 3]

list: [0, 1, 2]
val: list[3]
-- stdout.golden --
list: [0, 1, 2]
a: _|_ // conflicting values 4 and 5
l: [1, _|_, // conflicting values 2 and 3
]
val: _|_ // index 3 out of bounds
```

This is broken as far back as 7f52c107b61980629c4c0d6751386a8ce360ddb9, which makes it all the more incredible this hasn't been spotted in all that time.

Thanks to you both for flagging this.

@MikkelHJuul I would suggest we revisit your use case to ensure you are seeing all the errors you expect after fixing this issue.

**Comment by iacore** [comment]
The flag isn't used at all

**Comment by juev** [comment]
Hello, flag `-E` do not work as expected.

After first error `cue vet` exit with error and do not proceed other errors on file.

**Comment by nzig** [comment]
I just hit this issue too. It's a little frustrating trying to learn by following the [tutorial](https://cuelang.org/docs/tutorials/tour/types/bottom/), when the example doesn't work.

**Comment by mpvl** [comment]
Was fixed in 

ab14c86: cmd/cue: fix --ignore errors flag …
https://review.gerrithub.io/c/cue-lang/cue/+/546243
