### ISSUE TITLE
text/template.Execute evaluates eagerly when it shouldn't

### ISSUE THREAD

**Issue by mxey** [cue-lang/cue#1095]
text/template.Execute expects concrete values when it shouldn't. It works fine when passing a struct with only a single field, but once the struct has 2 fields, template.Execute expects both fields to have concrete values. 

### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version 0.4.0 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

CUE v0.4.0 is the latest release.

### What did you do?

testscript:

```
exec cue version
exec cue eval in.cue

-- in.cue --
import (
	"text/template"
)

#T: {
	params: {
		x: string
		y: string
	}
	out: template.Execute("{{.x}} {{.y}}", params)
}
```

### What did you expect to see?

```
PASS
```

### What did you see instead?

```
> exec cue version
[stdout]
cue version 0.4.0 darwin/amd64
> exec cue eval in.cue
[stderr]
#T.params.x: error in call to text/template.Execute: cannot convert non-concrete value string:
    ./in.cue:10:7
    ./in.cue:7:3
#T.params.y: error in call to text/template.Execute: cannot convert non-concrete value string:
    ./in.cue:10:7
    ./in.cue:8:3
[exit status 1]
FAIL: /var/folders/yk/v64pl_sj1v98rtz0tz2y3zch0000gp/T/testscript040096134/-/script.txt:2: unexpected command failure
error running <stdin> in /var/folders/yk/v64pl_sj1v98rtz0tz2y3zch0000gp/T/testscript040096134/-

```

**Comment by mxey** [comment]
This worked in CUE v0.3.2 and according to git bisect, it's a regression from https://github.com/cue-lang/cue/commit/819cf955e574f3b6d17b3488299f3464f37e3149

**Comment by mxey** [comment]
This happens with multiple struct fields and not with a single one because the error becomes a `list`, which no longer provides the information, that it's an incomplete, where [processErr](https://github.com/cue-lang/cue/blob/master/pkg/internal/builtin.go#L193) could see it.

**Comment by myitcv** [comment]
Thanks for the report and analysis @mxey. Agree with everything above. Give this is a regression we will look to include it as part of `v0.5.x`.

**Comment by mpvl** [comment]
Analysis: single errors have an error level associated it. When there are multiple errors, these individual errors are ignored and the whole error is considered to be fatal in its entirety.

Is a fairly straightforward fix.
