### ISSUE TITLE
contributing: git-codereview does not know about -s flag

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#1099]
The [contribution guide](https://github.com/cue-lang/cue/blob/master/doc/contribute.md) was updated as part of the migration described in #1078. Part of this update included changing the project to use the [Developer Certificate of Origin](https://developercertificate.org/) instead of a CLA, something that requires users to sign-off each commit.

Generally speaking this is done with `git commit -s ...`. However, our Gerrit-based contribution guide talks in terms of `git codereview change ...`. The problem being that currently [`git-codereview`](https://pkg.go.dev/golang.org/x/review/git-codereview) does not know about the `-s` flag.

https://go-review.googlesource.com/c/review/+/334750 looks to add that flag, a change that should hopefully be uncontentious. 

When `git-codereview` learns about `-s`, we should:

* [ ] update the contribution guide to use `git codereview change -s` everywhere;
* [ ] update the [tips and tricks wiki](https://github.com/cue-lang/cue/wiki/Contribution-tips-and-tricks).

This issue tracks those changes.

**Comment by slewiskelly** [comment]
The contribution guide has been updated to use `git codereview change -s`. However the instructions tell contributors to install `git-codereview` via:

```
go install golang.org/x/review/git-codereview@latest
```

This installs the latest **tagged** version. The last [tag](https://github.com/golang/review/releases) applied was back in February, before the `-s` flag was added.

To work around it in the meantime, somebody can install via:

```
go install golang.org/x/review/git-codereview@master
```
