### ISSUE TITLE
releases: switch to using proxy mode of goreleaser

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#1100]
In https://github.com/goreleaser/goreleaser/pull/2129, @caarlos0 added support to `goreleaser` for building release assets from proxy-resolved modules, the benefit being that resulting binaries include full module fidelity information and sums from sum.golang.org. 

We should update the CUE `goreleaser` configuration to use that new setting.

**Comment by caarlos0** [comment]
I can work on that if you want, would love to contribute to cuelang :)

**Comment by myitcv** [comment]
Oh wow, that would be great! What better person to have contribute the fix :) Not only that, please feel free to point out if we could be doing things better etc.

Details in the [contributing guide](https://github.com/cue-lang/cue/blob/master/doc/contribute.md) - your choice on whether you submit a PR or go the Gerrit route. 

One point to note, you might well be the first person post-migration (#1078) to go through the slightly revised contribution process. So please ping me if you run into any issues. With the best will in the world, my testing was probably not complete.

**Comment by caarlos0** [comment]
@myitcv just opened the pr, was a breeze... but I did it via github so I didn't verify the gerrit steps.
