### ISSUE TITLE
gerrithub: fix up gitiles homepage

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#1101]
The navigation bar at the top of the gittiles homepage (https://review.gerrithub.io/plugins/gitiles/cue-lang/cue) is generic and can be made specific to CUE:

https://gerrit.googlesource.com/gitiles/+/HEAD/Documentation/markdown.md#Site-layout

**Comment by palmamartin** [comment]
Is this still desired? If nobody is working on it, I would like to help here.

**Comment by myitcv** [comment]
@palmamartin please do!

**Comment by palmamartin** [comment]
Just send a [CL](https://review.gerrithub.io/c/cue-lang/cue/+/527284). Its very basic. It adds a title with the CUE logo. If a more sophisticated navigation bar is preferred with links to documentation etc... please let mi know in the CL.

**Comment by myitcv** [comment]
@palmamartin - thanks for your patience on this. Now submitted... but it doesn't appear to have changed anything? Any ideas?

**Comment by palmamartin** [comment]
@myitcv It seems to me that the `navbar.md` will only be displayed when a markdown file is rendered, see: https://review.gerrithub.io/plugins/gitiles/cue-lang/cue/+/refs/heads/master/doc/install.md

Also "svg" is not a supported [image format](https://gerrit.googlesource.com/gitiles/+/master/Documentation/markdown.md#Images). Should I submit another CL for changing the image format? Does it need a new issue for that?

**Comment by myitcv** [comment]
> @myitcv It seems to me that the `navbar.md` will only be displayed when a markdown file is rendered, see: https://review.gerrithub.io/plugins/gitiles/cue-lang/cue/+/refs/heads/master/doc/install.md

Ah! That explains it, thank you for digging on that.





> Should I submit another CL for changing the image format?

Please.

> Does it need a new issue for that?

Nope, this one is just fine.

I suggest `filled.png` from:

https://github.com/cue-lang/cuelang.org/tree/master/static/images
