### ISSUE TITLE
x/tools: optimise runtrybot logic

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#1102]
CUE developers trigger the trybots (GitHub workflows) using the [`cueckoo`](https://github.com/cue-sh/tools/tree/master/cmd/cueckoo) command. However it is very basic.

* When triggering trybots/unity, we should only do so if we haven't previously triggered them for the same patchset.
* When a new patchset is submitted, we should [reset the labels on non-trivial rebases](https://gerrit-review.googlesource.com/Documentation/config-labels.html).

**Comment by myitcv** [comment]
I believe this has been solved by https://review.gerrithub.io/c/cue-sh/tools/+/1169892, and any further work in this space will be solved by switching to using labels to trigger trybots/other, and webhooks hanging off GerritHub to "see" the edge of a label being added.

cc @mvdan to confirm one way or the other, and close if required please!

**Comment by mvdan** [comment]
Agreed, this is definitely good enough for now given our current mechanism :)
