### ISSUE TITLE
doc: Yaml validation tutorial inconsistent with implementation

### ISSUE THREAD

**Issue by mhratson** [cue-lang/cue#1106]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version 0.4.0 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What did you do?

followed the example from [Yaml validation tutorial](https://cuelang.org/docs/integrations/yaml/#validate)

<details>

```cue
// dim.cue
import "encoding/yaml"

// Phrases defines a schema for a valid phrase.
#Phrases: {
    phrases: [string]: #Phrase

    #Phrase: {
        lang:         #LanguageTag
        text:         !=""
        attribution?: !="" // must be non-empty when specified

    }
    #LanguageTag: =~"^[a-zA-Z0-9-_]{2,}$"
}

// phrases is a YAML string with a field phrases that is a map of Phrase
// objects.
phrases: yaml.Validate(#Phrases)

phrases: """
    phrases:
      # A quote from Mark Twain.
      quote1:
        lang: en
        text: Never regret anything that made you smile.
        attribution: Mark Twain

      # A Norwegian proverb.
      proverb:
        lang: no
        text: Stemmen som sier at du ikke klarer det, lyver.
    """
```

</details>

### What did you expect to see?

as described in the tutorial:
```
$ cue vet dim.cue
phrases: error in call to encoding/yaml.Validate: conflicting values false and
LanguageTag (mismatched types bool and string):
    ./dim.cue:18:10
```

### What did you see instead?

```
$ cue vet dim.cue 
```

no output

## Also
Getting unexpected results on tutorials(my output shown below):
1. [Bottom/Error](https://cuelang.org/docs/tutorials/tour/types/bottom/)
```
$ cue eval -i bottom.cue 
a: conflicting values 5 and 4:
    ./bottom.cue:20:4
    ./bottom.cue:21:4
```
1. [Numbers](https://cuelang.org/docs/tutorials/tour/types/numbers/)
```
$ cue eval -i 11-numbers.cue 
c: conflicting values int and 4.0 (mismatched types int and float):
    ./11-numbers.cue:27:4
    ./11-numbers.cue:28:4
```

Printing is skipped according to the help, so i'm confused a bit how the tutorial shows the results…
```
$ cue eval -h
eval evaluates, validates, and prints a configuration.

Printing is skipped if validation fails.
```

**Comment by verdverm** [comment]
I think this is the classic issue with YAML and Norwegian (no)

Try quoting your language fields in the yaml

**Comment by mhratson** [comment]
> I think this is the classic issue with YAML and Norwegian (no)

@verdverm that's [part of the tutorial](https://cuelang.org/docs/integrations/yaml/#intro)

> See the problem? The language for the Norwegian proverb is set to no, which is interpreted as false in YAML.
Luckily, CUE can help catch those pesky YAML quirks quickly and swiftly.

**Comment by verdverm** [comment]
Sorry, missed some text on mobile. The `vet` no output does look to be an issue.

For your "Also" and printing question, the RHS in the tutorials is not verbatim what the `cue` tool will print, it's kind of line oriented in places.

**Comment by mhratson** [comment]
> For your "Also" and printing question, the RHS in the tutorials is not verbatim what the cue tool will print, it's kind of line oriented in places.

It's confusing at least as it uses the `cue …` invocation…

**Comment by myitcv** [comment]
Thanks for flagging this, @mhratson. This behaviour actually changed in https://github.com/cuelang/cue/commit/1c290428aabc19ba97b08d93bdaa665e282d20bb, which was in response to https://github.com/cuelang/cue/issues/512. 

It appears that rewriting this tutorial got missed in that change. 

(FWIW, we plan to have our tutorials be like Go test examples in the future, i.e. fully tested as part of each commit so the output can never go "bad" like this)

So I've retitled this issue to fix up that part of the docs (which will be a relatively significant rewrite given the `no` ambiguity forms a large part of the use case).

For you "Also" section, please see my comment in https://github.com/cue-lang/cue/issues/1093#issuecomment-882396835.

**Comment by haiwu** [comment]
This is still broken. Just hit the same issue with the doc, trying to go through the doc as tutorial, but it did not work.

**Comment by jpluscplusm** [comment]
I believe this is now resolved.

The replacement YAML page, at https://cuelang.org/docs/concept/how-cue-works-with-yaml/, now has output sections automatically generated from the input and commands specified, so they're strongly aligned and cross-checked by the site's build process.

The page at https://cuelang.org/docs/tour/types/bottom/ explicitly mentions the `-i` flag for `cue eval`, which is how the output is generated despite there being a unification failure in the underlying CUE file.
