### ISSUE TITLE
spec/comprehension: if clause is missing else

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#111]
_Originally opened by @xinau in https://github.com/cuelang/cue/issues/111_

atm. the only way to implement a `else` is to add the same `if` clause and negating the expression
```
foo: ["dragons"]

if ((foo & string) != _|_) {
  bar: foo
} 
if ((foo & string) == _|_) {
  bar: 20
} 
```
while this works, it feels strange from a user perspective coming from other languages.
I also checked the spec and it seems to be missing https://github.com/cuelang/cue/blob/master/doc/ref/spec.md#comprehensions

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/111#issuecomment-533691144_

It is not missing, it was deliberately omitted. I’m not entirely against adding it, but only after getting more data and experience with comprehensions and seeing how they develop. Conditional expression tend to lead to awful configurations, and although comprehensions are grammatically not expressions, they are getting close and just might develop into them.

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/111#issuecomment-533702982_

BTW, note that the above could be approximated as:
```
{
  foo: ["dragons"]

  {
    foo: string
    bar: foo
  } | {
    foo: [...] 
    bar: 20
  }
}
```
Disjunctions will often be a good approach for more complicated structural alternatives.

A more likely language extension, which would also be useful for JSON schema compatibility would be to allow `!string` or `not(string)` to mean `null | bool | number | bytes | {} | [...]`.

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/111#issuecomment-533790147_

You could even fully simulate `else` with default values:
```
{
  foo: ["dragons"]

 *{
    foo: string
    bar: foo
  } | *{
    foo: int
    bar: 10
  } | {
    bar: 20
  }
}
```
where only the else block is not marked as a default. Note you can have multiple defaults, which makes sense to use if there is a discriminator field, like in this case.

**Comment by cueckoo** [comment]
_Original reply by @xinau in https://github.com/cuelang/cue/issues/111#issuecomment-533851852_

@mpvl Thanks for the input.

**Comment by cueckoo** [comment]
_Original reply by @seh in https://github.com/cuelang/cue/issues/111#issuecomment-627965223_

> You could even fully simulate `else` with default values:

I [discovered today](https://cuelang.slack.com/archives/C012UU8B72M/p1589374295125500?thread_ts=1589330612.118000&cid=C012UU8B72M) that this example works up until the "foo" field has a value that's a string or an int. If it matches either of the first two disjunction alternatives, we have to ensure that it **doesn't** match the third as well.

We need something like the following in the third alternative:
```
foo: null | bool | bytes | float | [...] | {...}
bar: 20
```

**Comment by mvdan** [comment]
For those who might be following this thread, `else` is being added to v0.16: https://github.com/cue-lang/cue/issues/2122#issuecomment-3923674957
