### ISSUE TITLE
Cue eval (600-1800 seconds) - Performance issue on small config

### ISSUE THREAD

**Issue by grouville** [cue-lang/cue#1129]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version 0.4.0 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What did you do?

I implemented the below Cue config. And it appears to bring out a real performance issue:

```cue
-- reproduce.cue --
package main

#Op: {
	do: string
	...
}

#Artifact: {
	#up: [...#Op]
	_
	...
}

#Load: {
	do:   "load"
	from: _
}

#Container: {
	// If I remove the `| *null`, no more lag
	imges: #Artifact | *null
	// imges: #Artifact
	
	#up: [
		#Load & {from:imges},
	]
}

#Credentials: {
	ctr: #Container & {
	}

	otherInfo: {
		// if I comment the `string`, no more lag
		string

		#up: [
		// if I comment the #Load, no more lag
			#Load & {from: ctr},
		]
	} 
}

#Code: {
	creds: #Credentials & {
	}

	auth: {
		secret: creds.otherInfo
	}
}

#Function: {
	codi: #Code
}

func1: #Function & {
	codi: #Code & {
	}
}
```

### What did you expect to see?

A very fast `cue evaluation`.

The possibility of having 2 values for the `imges` key is very important in that case

### What did you see instead?

 When running the `cue eval` on above config, it loops for a very long time. (the maximum I waited is 1800seconds).
 However, if I remove the `| *null` from the `imges` value, the eval is immediate.

**Comment by grouville** [comment]
The workaround I found in that case is :
```cue
#Container: {
	// If I remove the `| *null`, no more lag
	imges?: #Artifact
	// imges: #Artifact
	
	#up: [
		#Load & {from:
		  if imges != _|_ {
		      imges
		  }
		  if imges == _|_ {
		      null
		  }
              },
	]
}
```
But I don't think it resolves the underlying issue

P.S: interested to learn/see how to debug that (if possible)

**Comment by TomChv** [comment]
Thanks for your research @grouville !
So we should not use `null` as default value anymore?

**Comment by grouville** [comment]
> Thanks for your research @grouville !
> So we should not use `null` as default value anymore?

We cannot infer that atm. Here, it's the use of 2 values that seems to cause the lag, but I just put `null` as an example

**Comment by myitcv** [comment]
@grouville @TomChv thanks for raising this. This is a known issue (https://github.com/cue-lang/cue/issues/803 amongst others) that will be addressed with upcoming changes that we refer to as structure sharing.
