### ISSUE TITLE
internal/eval: order of comprehensions appears to be significant

### ISSUE THREAD

**Issue by PierreR** [cue-lang/cue#1130]
### What version of CUE are you using (`cue version`)?

<pre>
cue version 0.4.0 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What did you do?

https://cuelang.org/play/?id=wnQXaPbpiHp#cue@export@cue

### What did you expect to see?

I expect these two snippets to be equivalent:

```
_stack: dev: bos: {}
_stack: prd: bos: {}
```
```
for c in [ "dev", "prd"] {
	_stack: "\(c)": bos: {}
}
```

#### 1. loop

```
for c in [ "dev", "prd"] {
	_stack: "\(c)": bos: {}
}
```
evaluates to
```
route: {}
``` 

#### 2. manual
```
_stack: dev: bos: {}
_stack: prd: bos: {}
```
evaluates to 
```
route: {
	"dev/bos-route": {
		kind: "Route"
	}
	"prd/bos-route": {
		kind: "Route"
	}
}
```
I must be missing something stupid but I don't see it.

**Comment by myitcv** [comment]
There are a couple of things going on here. First, here is my repro of your setup:

```
# Hidden fields are not shown by default
exec cue eval x.cue
cmp stdout non_hidden.golden

# Using the -H flag we can see them
exec cue eval -H x.cue
cmp stdout hidden.golden

-- x.cue --
package a

for c in [ "dev", "prd"] {
	_stack: "\(c)": bos: {
		a: 5
	}
}
-- non_hidden.golden --

-- hidden.golden --
_stack: {
    dev: {
        bos: {
            a: 5
        }
    }
    prd: {
        bos: {
            a: 5
        }
    }
}
```

So what you are running into here is that by default hidden fields are not shown. More on this later.

The second thing is that the playground is likely not in "sync" with the `cmd/cue` commands. Not only that, we don't have the various options (like `-H`). See #1150 for tracking that fix up. 

Regarding hidden fields not being shown by default. This relates closely to the discussion about different manifestations in #822. `cue eval` is a rather strange beast that lives somewhere between `cue def` and `cue export`. See "Printing modes" in that proposal for details on where we think we need to be specifically. 

As such, I don't think there is an issue here?

**Comment by PierreR** [comment]
@myitcv I will try to come up with a complete repro. In the end what I want to see is not hidden.
_stack looks like:
```
_stack: [Cluster=_]: [Stack=_]: {
	cluster: Cluster
	stack:   Stack
}

for cluster, i in _stack for stack, v in i {
       route: "myroute": {}
}

route: [ID=_]: kind: "Route"
```
Will be a good exercise on my side to use txtar ;-)

**Comment by verdverm** [comment]
It's worth noting that the nested for comp works if also nested in another struct. You can then reference this nested field

@PierreR see if this example contains a sufficient work around for you

https://cuelang.org/play/?id=jSgwuyIfmGR#cue@export@cue

@myitcv Not sure if this is a semantic difference when embedding / comprehending at the top (file) level or a real bug. I don't recall if this is one of those semantic differences that varies between file and instances (package)

**Comment by myitcv** [comment]
@verdverm I'm afraid you've lost me. Can you explain what difference you are seeing?

**Comment by verdverm** [comment]
@myitcv yeah, that was probably a little vague...

In the playground example, note that the route object is filled in as @PierreR desired. I did this by putting the `for` inside of a labelled struct, rather than at the top-level of the file. If you comment out line 25, then route becomes an empty struct again. Here you can see the `test: ` struct has the desired output, but the same loop at the top-level does not create the same output.

I'm wondering if the difference in output when `for ... { route ... }` is at the top-level vs nested is intentional semantics or a bug.

**Comment by verdverm** [comment]
ok, this is more bizarre

In this playground https://cuelang.org/play/?id=5qQ8hL3cvK3#cue@export@cue

move line 14-16 to line 5

The output is different?!

---

swapping the 2 for loops at the bottom results in different output, for `route:` while `test: route:` remains stable

```
$ cat tmp.cue 
_stack: [Cluster=_]: [Stack=_]: {
        cluster: Cluster
        stack:   Stack
}
route: [_]: {}


test: {
        for cluster, s in _stack for stack, v in s {
                route: "\(v.cluster)/\(v.stack)-route": {}
        }
}

for c in [ "dev", "prd"] {
        _stack: "\(c)": bos: {}
}

for cluster, s in _stack for stack, v in s {
        route: "\(v.cluster)/\(v.stack)-route": {}
}
```

Something about for loops embedded in the top-level (file instance)?

**Comment by myitcv** [comment]
Nice leg work, @verdverm. This is certainly a strange one. 

Perhaps the clearest reproducer is as follows:

```
# a.cue b.cue
exec cue eval x.cue a.cue b.cue
cmp stdout stdout.golden

# b.cue a.cue
exec cue eval x.cue b.cue a.cue
cmp stdout stdout.golden

-- a.cue --
package a

for c in [ "dev", "prd"] {
	_stack: "\(c)": bos: {}
}
-- b.cue --
package a

for cluster, s in _stack for stack, v in s {
	route: "\(v.cluster)/\(v.stack)-route": {}
}
-- x.cue --
package a

_stack: [Cluster=_]: [Stack=_]: {
	cluster: Cluster
	stack:   Stack
}
route: [_]: {}

test: {
	for cluster, s in _stack for stack, v in s {
		route: "\(v.cluster)/\(v.stack)-route": {}
	}
}
-- stdout.golden --
route: {
    "dev/bos-route": {}
    "prd/bos-route": {}
}
test: {
    route: {
        "dev/bos-route": {}
        "prd/bos-route": {}
    }
}
```

I'm sure this can be reduced down, but alternating the file order `a.cue` and `b.cue` makes it clear what's going on, with the same output expected in both cases.

This currently (eb18b74c) gives the following output:

```
# a.cue b.cue (0.024s)
# b.cue a.cue (0.025s)
> exec cue eval x.cue b.cue a.cue
[stdout]
route: {}
test: {
    route: {
        "dev/bos-route": {}
        "prd/bos-route": {}
    }
}
> cmp stdout stdout.golden
[diff -stdout +stdout.golden]
-route: {}
+route: {
+    "dev/bos-route": {}
+    "prd/bos-route": {}
+}
 test: {
     route: {
         "dev/bos-route": {}
         "prd/bos-route": {}
     }
 }

FAIL: /tmp/testscript480924871/repro.txt/script.txt:7: stdout and stdout.golden differ
```

**Comment by verdverm** [comment]
@myitcv does the cmd/txtar-test (or other name it may be called) have the ability to create the golden.output files and auto append them?

**Comment by myitcv** [comment]
@verdverm I think you're referring to [`cmd/testscript`](https://pkg.go.dev/github.com/rogpeppe/go-internal/cmd/testscript), and in particular its `-u` flag?

**Comment by verdverm** [comment]
Is that in the `rogpeppe` repo?

**Comment by PierreR** [comment]
@myitcv shouldn't this be flagged as a bug ? 
@verdverm  Thanks for the workaround. It is not that easy for us to apply such a workaround in the real code base. Hence we keep doing the loop "manually" even if it is less and less practical ;-)

As an extra note, this has nothing to do with the fact that a hidden field is used. Instead of `_stack`, it could be `#stack` or `stack`.

**Comment by mpvl** [comment]
The current stance of CUE is that comprehensions may not depend on the output of another comprehension within the same scope. There is a detection mechanism for this, but it is incomplete. See https://github.com/cue-lang/cue/issues/1083 for an example where a cycle _is_ detected.

The plan is to look to relax these constraints. But it is hard simply do static analysis here, as fields may be created dynamically. But clearly some work needs to be done to relax the rules when dependencies are allowed and detection when the rules are broken.

**Comment by mpvl** [comment]
FTR: it is usually quite easy to break such a violation by "pushing a comprehension down". So here, write:
```
_stack: {
    for c in [ "dev", "prd"] {
	    "\(c)": bos: {}
	}
}
```
instead of 
```
 for c in [ "dev", "prd"] {
	_stack: "\(c)": bos: {}
}
```
to solve it. In general, it is a good idea to move comprehensions to the most deeply nested struct to which they apply.

So, similarly, it would be nicer to write:
```
route: {
    for cluster, s in _stack for stack, v in s {
	   "\(v.cluster)/\(v.stack)-route": {}
    }
}
```

Clearly, again, this error should have been caught and reported. Also, in the future we may consider relaxing these rules.

**Comment by PierreR** [comment]
@mpvl it works like a charm. Thanks for the tip !
