### ISSUE TITLE
internal/eval: apparent cycle not reported

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#1142]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version +ecb17c94 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

Created off the back of investigation as part of https://github.com/cue-lang/cue/discussions/1134. 

```
! exec cue eval ./sub

-- cue.mod/module.cue --
module: "mod.com"
-- resource.cue --
package ocp

deployment: [_]: {
	apiVersion: "apps/v1"
	kind:       "Deployment"
	spec: {
		template: spec: containers: [...{
			_env: [string]: string | {}
		}]
	}
}

for k, v in deployment {
	for c in v.spec.template.spec.containers {
		if len(c._env) > 0 {
			deployment: "\(k)": spec: template: spec: containers: [ {
				env: [
					for x, y in c._env {
						if (y & string) != _|_ {name: x, value: y}
						if (y & {}) != _|_ {name: x, y}
					},
				]
			}]
		}
	}
}
-- sub/kibana.cue --
package ocp

_kibana: "its/elk-logging": _

_kibana: [ID=_]: _

for id, v in _kibana {
	deployment: "\(id)/kibana": {
		spec: template: spec: {
			containers: [{
				image: "cicd-docker.repository.irisnet.be/kibana"
				name:  "kibana"
				_env: XPACK_MONITORING_ENABLED: "True"
			}]
		}
	}
}
``` 

My understanding is that the above test should pass, because the `cue eval` call should fail because the definition of the `containers` field is in effect cyclic. However, the test fails because the `cue eval` call does _not_ fail:

```
> ! exec cue eval ./sub
[stdout]
deployment: {
    "its/elk-logging/kibana": {
        apiVersion: "apps/v1"
        kind:       "Deployment"
        spec: {
            template: {
                spec: {
                    containers: [{
                        image: "cicd-docker.repository.irisnet.be/kibana"
                        name:  "kibana"
                    }]
                }
            }
        }
    }
}
FAIL: /tmp/testscript626113823/repro.txt/script.txt:1: unexpected command success
```

### What did you expect to see?

The test to pass.

### What did you see instead?

As above.

**Comment by mpvl** [comment]
Could you please specify where you believe the cycle should be? I don't see one, tbh, but I may be missing something.

I'm coincidentally working on a clarification/update in the spec to be more specific about what kind of cycles are allowed in comprehensions.

**Comment by mpvl** [comment]
This is indeed a close call. The first comprehension inserts fields in the same struct over which it iterates. However, it doesn't invoke cycle detection because 1) it doesn't introduce new fields, and 2) it doesn't use `v`, so guaranteeing it won't trigger the evaluation of fields that later get specialized.

Note the first comprehension could be written something like (includes what I think is a bug fix in your example):
```
deployment: [string]: spec: template: spec: containers: [...{
	_env: _
	if len(_env) > 0 {
		env: [
			for x, y in c._env {
				if (y & string) != _|_ {name: x, value: y}
				if (y & {}) != _|_ {name: x, y}
			},
		]
	}
}]
```
which may help to understand why this is not a cycle.

**Comment by mpvl** [comment]
Not a cycle.
