### ISSUE TITLE
cmd/cue: vet behaves inconsistently with disjunction

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#1148]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version +ecb17c94 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
# vet a.json using #A
exec cue vet x.cue justa.cue a.json

# vet b.json using #B
exec cue vet x.cue justb.cue b.json

# Ensure a.json does not vet with #B
! exec cue vet x.cue justb.cue a.json

# Ensure b.json does not vet with #A
! exec cue vet x.cue justa.cue b.json

# vet a.json using #A | #B
exec cue vet x.cue both.cue a.json

# vet b.json using #A | #B
exec cue vet x.cue both.cue b.json

-- a.json --
{
	"a": "test"
}
-- b.json --
{
	"b": 42
}
-- both.cue --
package x

#A | #B
-- justa.cue --
package x

#A
-- justb.cue --
package x

#B
-- x.cue --
package x

#A: {a: string}
#B: {b: int}
```

### What did you expect to see?

The test to pass.

### What did you see instead?

```
# vet a.json using #A (0.028s)
> exec cue vet x.cue justa.cue a.json
# vet b.json using #B (0.029s)
> exec cue vet x.cue justb.cue b.json
# Ensure a.json does not vet with #B (0.030s)
> ! exec cue vet x.cue justb.cue a.json
[stderr]
field not allowed: a:
    ./a.json:2:2
    ./justb.cue:1:1
    ./justb.cue:3:1
    ./x.cue:1:1
    ./x.cue:4:5
[exit status 1]
# Ensure b.json does not vet with #A (0.028s)
> ! exec cue vet x.cue justa.cue b.json
[stderr]
field not allowed: b:
    ./b.json:2:2
    ./justa.cue:1:1
    ./justa.cue:3:1
    ./x.cue:1:1
    ./x.cue:3:5
[exit status 1]
# vet a.json using #A | #B (0.029s)
> exec cue vet x.cue both.cue a.json
[stderr]
field not allowed: a
[exit status 1]
FAIL: /tmp/testscript469010135/repro.txt/script.txt:14: unexpected command failure
error running repro.txt in /tmp/testscript469010135/repro.txt
```

Which demonstrates two problems:

* `cue vet x.cue both.cue a.json` failed when it should not have done (for completeness' sake, `cue vet x.cue both.cue b.json` does work as expected)
* `cue vet x.cue both.cue a.json` elides all the details from the error message (although this is something of a moot point because this command should not error)

**Comment by rycee** [comment]
I happened to run into this same issue (I believe) using

``` console
$ cue version
cue version 0.4.0 linux/amd64

$ ########

$ cat a.cue
#Test: { a: int } | { b : string }

test : #Test & { a: 3 }

$ cue export --out json -e test a.cue | tee a.json
{
    "a": 3
}

$ cue vet a.json a.cue -d '#Test'
#Test: field not allowed: a

$ ########

$ cat b.cue 
#Test: { a: int }

test : #Test & { a: 3 }

$ cue export --out json -e test b.cue | tee b.json
{
    "a": 3
}

$ cue vet b.json b.cue -d '#Test'

$ # OK exit status
```

My work-around for now is something along the lines of

``` console
$ jq '{v:.}' a.json > vettable-a.json ; cue vet vettable-a.json a.cue -d '{v: #Test}'
```

**Comment by myitcv** [comment]
Thanks @rycee, especially for the repro (FYI in case you are looking to provide multi-file reproducers, [this wiki](https://github.com/cue-lang/cue/wiki/Creating-test-or-performance-reproducers) provides some tips). Looks like this isn't limited to embedded disjunctions, a plain disjunction is sufficient.

**Comment by trantor** [comment]
@mpvl @myitcv I've most likely found a bug concerning disjunctions and @myitcv kindly referred me to this issue.
You can see the details at #1512 . I am not sure if the symptoms fit entirely, to be honest.
Can I do something else to help fix this?
Thanks in advance

**Comment by myitcv** [comment]
@trantor - this should be fixed in https://review.gerrithub.io/c/cue-lang/cue/+/532855.

**Comment by myitcv** [comment]
Just to be clear, that has not been merged yet, but will likely be very soon assuming no further issues come up.

**Comment by trantor** [comment]
Thanks @myitcv I've tested out the patched code and it seems to work with the examples mentioned above. I'll wait for the merge and the release. :wave:
