### ISSUE TITLE
cmd/cue: eval -c not triggering incomplete errors

### ISSUE THREAD

**Issue by verdverm** [cue-lang/cue#1152]
### What version of CUE are you using (`cue version`)?

`0.4.0`

### What did you do?

```
! exec cue eval -c foo.cue
-- foo.cue --
package foo

#SomeBaseType: {
 "a" | "b"
 #AUTO: "z"
}

V1: ("x" | "y") | *"z"
V2: ("x" | "y") | *#SomeBaseType.#AUTO
```

### What did you expect to see?

a failure about V2

### What did you see instead?

```
V1: "z"
V2: "x" | "y"
```

**Comment by myitcv** [comment]
Thanks for raising this @verdverm. 

I've updated the repro script to correctly assert the expected command failure, and added `exec` in front of `cue` so this script actually runs using [`cmd/testscript`](https://pkg.go.dev/github.com/rogpeppe/go-internal/cmd/testscript).

Confirmed with 370fac9b.
