### ISSUE TITLE
Check concreteness before encoding

### ISSUE THREAD

**Issue by verdverm** [cue-lang/cue#1154]
Given #1152 and #1153, does it make sense to check for concreteness before trying to encode to a given output format?

Today the outcome is inconsistent and sometimes hides the errors. Doing so may provide more revealing errors.

**Comment by myitcv** [comment]
My suggestion would be we first fix #1152 and #1153, because I suspect we will fix all related errors in so doing. The issue isn't so much one of concreteness AFAICT, but that incomplete errors are missed. 

Let's pick up discussion in either of the two issues you created.
