### ISSUE TITLE
Macports saying succesful installation but not installing

### ISSUE THREAD

**Issue by moneybagz1** [cue-lang/cue#1156]
when i try to download macports (big sur version), it tells me installation succesful but then i go to run it and it gives command not found on anything i write. anyone know how to help with this?

**Comment by verdverm** [comment]
See #1121 

Support was added by a user there, they may know more

These are the official and current  supported installation methods: https://cuelang.org/docs/install/

**Comment by myitcv** [comment]
See also https://github.com/cue-lang/cue/issues/1125 where we are discussing whether or not to make official MacPorts support. @moneybagz1 as @verdverm points out, that question is best directed to the maintainer of the MacPorts portfile.

**Comment by herbygillot** [comment]
Hey @moneybagz1, as @myitcv mentioned, your question is a problem with MacPorts, and not `cue`, so this is the wrong place to ask it.

I would recommending emailing your question to `macports-users@lists.macports.org`, but to answer your question, check whether `/opt/local/bin/port` exists after installation, and if it does, you need to add it to your `PATH`.  Something like the following would be added to your `bash` or `zsh` profile, or whichever shell you're using:

```bash
PATH="${PATH}:/opt/local/bin"
```
