### ISSUE TITLE
cuelang.org: right hand table of contents needs overflow indicator

### ISSUE THREAD

**Issue by nyarly** [cue-lang/cue#1169]
I was visiting https://cuelang.org/docs/references/spec/ and encountered the issue (again) that the table of contents on the right hand side doesn't indicate that there's more content, if you'll only scroll down to see it. A gradient or something at the bottom would be sufficient.

**Comment by f1rstmehul** [comment]
Hmm, This issue is related to the [docsy](https://github.com/google/docsy/) theme.The official [docsy site](https://www.docsy.dev/docs/adding-content/navigation/) shows the same.

**Comment by verdverm** [comment]
These might be better on this repo: https://github.com/cue-lang/cuelang.org

**Comment by myitcv** [comment]
@verdverm I actually transferred the issue from that repo as part of an experiment to see whether it works best to use a single issue tracker or not.

**Comment by mvdan** [comment]
I believe the new website, which includes the CUE Language Specification as well, has fixed this issue. The table of contents is on the left side and seems pretty short and clear to me. Please let me know if I'm missing anything. Thanks!
