### ISSUE TITLE
Adding multiple fields to a list

### ISSUE THREAD

**Issue by MikkelHJuul** [cue-lang/cue#1173]
When working with lists and conditional elements, when trying to add multiple conditional elements one has to wrap all of these with the condition.

This is the only valid syntax:
```CUE
asd: [
   "a",
   if _cond {
      "s"
   },
   if _cond {
      "d",
    },
]
```

There are two possible solutions:
allow multiple objects in the conditional
```CUE
asd: [
  "a",
  if _cond {
     "s",
     "d",
   },   //dangling comma??
]
```
or the slightly wider solution
"Multiple references to a list object appends to that list"  (sounds like a big change to the language)
```CUE
asd: [
   "a",
]
if _cond {
   asd: [
      "s",
      "d",
    ]
}
```
The latter would enable better separation of objects across files, but it seems like a thing that may be impossible to add without enabling/messing with the scope etc. of the internals.
I originally thought this solution was there in the language, it follows the thought of allowing reference of fields disjointly:
```CUE
a: b: string
a: c: string
```
but I do see that it's harder when you are referencing an array/list (opposed to a field -- in essence you are referencing the same field).

These help avoid having to use indirection, and list-flattening
```CUE
_listA: [...]
_listB: [...]
list: {
   if _cond {
      list.FlattenN([_listA,_listB], 1) 
   }
   if !_cond {
      _listA
   }
}
```

** Additional context **
I wrongfully tried it myself, and had to fix:
https://github.com/MikkelHJuul/ODIM-H5-Validator/commit/1e1aaa14f2e27bc5087e43b7b4f17ed42b3f9592

**Comment by myitcv** [comment]
@MikkelHJuul thanks for raising this. Please see https://github.com/cue-lang/cue/issues/165#issuecomment-873388976; there are plans for addressing this in the query extension proposal. Hence I'll mark this issue as closed, but please shout if you think I've missed something.

**Comment by MikkelHJuul** [comment]
> @MikkelHJuul thanks for raising this. Please see https://github.com/cue-lang/cue/issues/165#issuecomment-873388976; there are plans for addressing this in the query extension proposal. Hence I'll mark this issue as closed, but please shout if you think I've missed something.

Great, sorry for missing it, I searched for conditional and found nothing.  It looks like an implementation of a "spread" operator, very neat and that would certainly fix the issue

**Comment by myitcv** [comment]
> Great, sorry for missing it, I searched for conditional and found nothing.

Absolutely no apology required; finding things is hard at the best of times, let alone when the terminology might be different!
