### ISSUE TITLE
doc: revamp contribution guide (especially PR channel)

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#1198]
The [contribution guide](https://github.com/cue-lang/cue/blob/master/doc/contribute.md) should more clearly explain the different ways in which people can contribution to the project. Broadly speaking they are:

* Using CUE, reporting issues, bugs and feedback
* Helping to garden issues, respond to discussions (whether on GitHub, Slack or other channels)
* Contributing code in the form of PRs or GerritHub CLs

The [recent moved to GerritHub](https://github.com/cue-lang/cue/issues/1078) fixed the fundamentals of the Gerrit contribution process, but we should more broadly address what contributing means. In particular, we need to more clearly explain the PR process. 

This will likely follow an upcoming proposal on how we restructure the project's repositories etc (yet to be published).

**Comment by slewiskelly** [comment]
Recently going through the contribution guide, there are a couple of issues I've encountered.

As mentioned in https://github.com/cue-lang/cue/issues/1099: the contribution guide has been updated to use `git codereview change -s`. However the instructions tell contributors to install `git-codereview` via:

```
go install golang.org/x/review/git-codereview@latest
```

This installs the latest **tagged** version. The last [tag](https://github.com/golang/review/releases) applied was back in February, before the `-s` flag was added.

To work around it in the meantime, somebody can install via:

```
go install golang.org/x/review/git-codereview@master
```

Secondly, when going to mail the change, I received the following error:

```console
$ git codereview mail
git-codereview: failed to load Gerrit origin: Gerrit origin "https://review.gerrithub.io/a/cue-lang/cue" from "/path/to/cue-lang/cue/codereview.cfg" different than git origin url "https://review.gerrithub.io/cue-lang/cue"
```

I had cloned the repo from Gerrit using the documented process:

> Then visit https://review.gerrithub.io/admin/repos/cue-lang/cue, then click "HTTP" or "SSH" then copy the corresponding "Clone" command.

```console
$ cat codereview.cfg
gerrit: https://review.gerrithub.io/a/cue-lang/cue
github: https://github.com/cue-lang/cue
cue-unity: https://github.com/cue-lang/unity

$ git remote -v
origin	https://review.gerrithub.io/cue-lang/cue (fetch)
origin	https://review.gerrithub.io/cue-lang/cue (push)
```

**Comment by slewiskelly** [comment]
Recently going through the contribution guide, there are a couple of issues I've encountered.

As mentioned in #1099: the contribution guide has been updated to use git codereview change `-s`. However the instructions tell contributors to install git-codereview via:

```console
$ go install golang.org/x/review/git-codereview@latest
```

This installs the latest **tagged** version. The last tag applied was back in February, before the `-s` flag was added.

To work around it in the meantime, somebody can install via:

```console
$ go install golang.org/x/review/git-codereview@master
```

Secondly, when going to mail the change, I received the following error:

```console
$ git codereview mail
git-codereview: failed to load Gerrit origin: Gerrit origin "https://review.gerrithub.io/a/cue-lang/cue" from "/pathto/cue-lang/cue/codereview.cfg" different than git origin url "ssh://review.gerrithub.io:29418/cue-lang/cue"
```

I had cloned the repo from Gerrit, via SSH, using the documented process:

> Then visit https://review.gerrithub.io/admin/repos/cue-lang/cue, then click "HTTP" or "SSH" then copy the corresponding "Clone" command.

```console
$ cat codereview.cfg
gerrit: https://review.gerrithub.io/a/cue-lang/cue
github: https://github.com/cue-lang/cue
cue-unity: https://github.com/cue-lang/unity

$ git remote -v
origin	ssh://slewiskelly@review.gerrithub.io:29418/cue-lang/cue (fetch)
origin	ssh://slewiskelly@review.gerrithub.io:29418/cue-lang/cue (push)
```

This was resolved by using HTTP.

**Comment by myitcv** [comment]
@slewiskelly thanks very much for flagging these points. Will ensure they are addressed in the revamp. 

FWIW I'm planning to do a live stream in the very near future that covers both the GitHub PR flow (not currently well documented) and the GerritHub flow.

**Comment by myitcv** [comment]
All the major changes/ideas discussed here were covered off in dbf5992239cb8db8965636ceb0bff596e314d063. 

@slewiskelly the contribution guide should now be up to date with respect to the issues you raised, but please shout if not.
