### ISSUE TITLE
cmd/cue: improve performance of fmt

### ISSUE THREAD

**Issue by yujunz** [cue-lang/cue#1201]
**Is your feature request related to a problem? Please describe.**
`cue fmt` is too slow to run. It took nearly 1 minute on a medium size package.

**Describe the solution you'd like**
Improve the performance

**Describe alternatives you've considered**
N/A

**Additional context**
On MacBook Pro (15-inch, 2018) / 2.6 GHz 6-Core Intel Core i7 / 32 GB 2400 MHz DDR4

```
❯ time cue fmt ./...
cue fmt ./...  44.00s user 1.29s system 160% cpu 28.218 total

❯ tree . 
...
171 directories, 437 files
```

**Comment by myitcv** [comment]
@yujunz thanks for raising this.

Do you have a repro that you can share in this case?

**Comment by mvdan** [comment]
I believe this was fixed in recent releases like https://github.com/cue-lang/cue/releases/tag/v0.9.0-alpha.3. As one example, `cue fmt ./...` on the CUE repo itself went from ~14s to ~0.1s. If it's still too slow for you, please leave a comment or create a new issue.
