### ISSUE TITLE
internal/eval: regexp inconsistencies between CUE and Go (RE2)

### ISSUE THREAD

**Issue by verdverm** [cue-lang/cue#1221]
CUE uses Go's regexp library under the hood and I expected there to be equivalence in the supported patterns and results. 

I believe this is where the call to Go happens https://github.com/cue-lang/cue/blob/06484a39d8d44c656212ac2d3b5589f8aa9db033/internal/core/adt/expr.go#L644

### What version of CUE are you using (`cue version`)?

`0.4.0`

### What did you do?

Golang:

```
package main

import (
	"fmt"
	"regexp"
)

func main() {
	matched, err := regexp.MatchString(`(i?)\brestaurant\b`, "sushi restaurant")
	fmt.Println(matched, err)
}

---

Output:

true <nil>
```
https://play.golang.org/p/ekkfbz-av7n

CUE:

```
rule: =~ "(i?)\brestaurant\b"

rule: "sushi restaurant"

-- output --
_|_ // rule: invalid value "sushi restaurant" (out of bound =~"(i?)\brestaurant\b")
```
https://cuelang.org/play/?id=z2TbLlUmHpt#cue@export@cue

### What did you expect to see?

CUE matching the regexp and displaying the original string

```
rule: "sushi restaurant"
```

---

### More inconsistencies:

| value | description |
|---------|----------------|
| `\B` | supported in Go, invalid escape in CUE |

**Comment by myitcv** [comment]
I think you're after raw string literals, where the `\` is not interpreted:

```
exec cue eval x.cue
cmp stdout stdout.golden

-- x.cue --
rule: =~#"(i?)\brestaurant\b"#

rule: "sushi restaurant"
-- stdout.golden --
rule: "sushi restaurant"
```

Otherwise, `\b` is [interpreted as a backslash](https://tip.cuelang.org/docs/references/spec/#string-and-byte-sequence-literals), and `\B` is simply an invalid escape.

**Comment by verdverm** [comment]
Ah, probably worth mentioning this behavior in the regexp docs (https://cuelang.org/docs/tutorials/tour/expressions/regexp/)
