### ISSUE TITLE
ci: update Go versions

### ISSUE THREAD

**Issue by hrvolapeter** [cue-lang/cue#1225]
Update Release go version to at least 1.16 so that darwin arm64 target binaries can be released

Issue for PR #1223 that sparked more conversation

@myitcv commented: 

    There are a few things we probably want to address here:    
    - expanding the build matrix to include Go 1.17
    - building CUE release artefacts with the latest version of Go
    - expanding the release matrix to include new Go ports
    - testing all the above (somewhat related to goreleaser test goreleaser/goreleaser#2355))

@myitcv to @verdverm:

    we used to build with the latest version of Go. Looks like when I updated our build matrix from 
    1.16.0-rc1 to 1.16 I didn't flip to define 1.16 (at the time) as the latest stable version of Go. We 
    can fix that in whatever changes come from this discussion.

@verdverm:

    another update in 1.17 I was thinking might be helpful for API users is the dependency pruning. 
    That would require updating the Go directive in go.mod. Thoughts?

    Another thought, is there preference for including (or not) the patch version in the workflows? (i.e. 1.16 vs 1.16.5)
    Any implications on reproducibility, like a new patch version released between final commit testing and tagging for a release?

**Comment by myitcv** [comment]
Thanks for creating this @hrvolapeter 

I'd suggest we split this into a couple of changes (at least):

1) the aforementioned changes to the build matrix:
  a) adding Go 1.17
  b) ensuring that the latest version of Go is used for build artefacts
  c) adding new ports to the release targets
2) updating the `go` directive in `go.mod` to 1.17

@hrvolapeter - given you previously raised a PR for part of 1, would you like to tackle that?

**Comment by hrvolapeter** [comment]
@myitcv yes I can definitely take a look

**Comment by myitcv** [comment]
Great, thanks. Please feel free to ask any questions here, or on Slack in case you run into any issues.

**Comment by myitcv** [comment]
https://github.com/cue-lang/cue/commit/5cf1aa16369dffe7636e7bc72eb3f9fdda006540 landed earlier today which updated the build matrix (thanks @hrvolapeter).

https://github.com/cue-lang/cue/commit/ddd96c6692afd2f0ea1dbd2e3bbc55376b56f77f then updated the Go versions used in the build matrix, bumping the code generation version to `go1.15.15`. 

In https://review.gerrithub.io/c/cue-lang/cue/+/526442 I have bumped the GoReleaser version which should, per the commit message, ensure we have arm64 assets for all OSs. If either @hrvolapeter or @verdverm want to take a look that would be great.

**Comment by hrvolapeter** [comment]
I've run the CL locally and the goreleaser seems to be producing correct binaries.

**Comment by verdverm** [comment]
@myitcv the main thing that comes to mind is, should we have a release chore to bump Go / GoReleaser before tagging a new version?

While we will update this now, do we want to update each time Go / GoReleaser update, only when CUE releases a new version, or some combination of both?

**Comment by myitcv** [comment]
> should we have a release chore to bump Go / GoReleaser before tagging a new version?

I don't follow what you're suggesting here - please can you explain?

Note that once https://github.com/goreleaser/goreleaser/issues/2355 lands we will integrate a GoReleaser test into our CI.

> While we will update this now, do we want to update each time Go / GoReleaser update, only when CUE releases a new version, or some combination of both?

If there are reasons to update GoReleaser we should, but I don't think we necessarily want the churn of updating for every release (much like any dependency), especially whilst manual verification is required (pending https://github.com/goreleaser/goreleaser/issues/2355)

**Comment by verdverm** [comment]
1. We updated `release.yml` to Go 1.17.2 with https://github.com/cue-lang/cue/commit/ddd96c6692afd2f0ea1dbd2e3bbc55376b56f77f
2. Go 1.17.3 is released
3. CUE 0.5.0 is released, should this release on 1.17.2 or 1.17.3?

The top-level question is, "should CUE release with the most current version of Go at that time?"

- consideration given to minor vs patch updates of Go
- when should `release.yml` be updated, the idea of adding a chore before creating a new release tag seems OK.
- can `test.yml` use Go matrix without patches (so always the latest) and `release.yml` has a version with patch which is updated to the current patch sometime before (but close to) running the workflow (via adding a tag)
- GoReleaser, as separate from Go, seems like it would manage with less frequent updates. We might want to see what they do with Go 1.18 and the extended build information that will be embedded by Go automatically.

**Comment by myitcv** [comment]
> should CUE release with the most current version of Go at that time?

Ideally yes. Ideally we automate the process of updating to the latest version of Go when it is released, something that is made easier by we automating the testing of release artefacts with GoReleaser. And we are heading in that direction with changes we are making, issues raised with GoReleaser etc.

The reason we do not automatically track and use the latest version of Go via `actions/setup-go@v2` is that to do so would introduce a degree of uncertainty into tests/releases. i.e. locally I would be testing with, say, Go 1.17.2 but then CI could be running with Go 1.17.3. 

Clearly for any security related issues (a security policy is something we need to formalise) we would issue a new release if our infrastructure (broadly speaking) was in some way vulnerable. 

> We might want to see what they do with Go 1.18 and the extended build information that will be embedded by Go automatically.

I'm not sure what you mean here.

**Comment by verdverm** [comment]
> > We might want to see what they do with Go 1.18 and the extended build information that will be embedded by Go automatically.

> I'm not sure what you mean here.

https://github.com/golang/go/issues/37475

**Comment by verdverm** [comment]
is it ironic that they just released Go 1.17.3?

**Comment by myitcv** [comment]
> > I'm not sure what you mean here.
> 
> [golang/go#37475](https://github.com/golang/go/issues/37475)

I'm still not sure what you mean. What are you proposing the CUE project should do differently in light of https://github.com/golang/go/issues/37475?

**Comment by verdverm** [comment]
I would assume GoReleaser would take advantage of these changes, such that the vars / flags typically used to embed the same information are no longer needed. (https://github.com/cue-lang/cue/blob/master/.goreleaser.yml#L13).

At that point, the `cue version` command could be updated to pull everything from the embedded build information. (https://github.com/cue-lang/cue/blob/master/cmd/cue/cmd/version.go#L47)

**Comment by mvdan** [comment]
https://review.gerrithub.io/c/cue-lang/cue/+/536099 updated us to Go 1.18.x as the latest Go version we test on and release with. Like Paul said, we do pin the version that we release with, for the sake of reproducible release builds that don't change from underneath us.

Is there anything else to do here?

**Comment by myitcv** [comment]
I think we covered everything. https://github.com/cue-lang/cue/pull/1709 covers the switch to including VCS information in builds.
