### ISSUE TITLE
cmd/cue: strange behaviour where os.Environ expanded within definition

### ISSUE THREAD

**Issue by bLuka** [cue-lang/cue#1227]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.4.0 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes, it does

### What did you do?

```bash
cd $(mktemp -d)
cat <<EOF > foo_tool.cue 
package main

import (
        "tool/exec"
        "tool/os"
)

#Foo: {
        _env: os.Environ

        printEnv: exec.Run & {
                env: _env
                cmd: ["/usr/bin/env"]
        }
}

command: run: #Foo
EOF
bash -c "cue run"
```

### What did you expect to see?

Current shell environment

### What did you see instead?

```
command.run._env: field not allowed: _:
    ./foo_tool.cue:9:8
    ./foo_tool.cue:17:15
    tool/os:16:11
    tool/os:17:3
    tool/os:18:4
```

### Additional comments

Hello,

I've noticed this weird behavior happening in very specific circumstances. After investigation, I found this to be caused by multiple causes:
1. We get `tool/os.Environ` within a field of an entity declared with the hash symbol
2. We use the environment within the same entity
3. We are running `/bin/sh` or `/bin/bash` which exposes an environment variable named `$_`
4. We call the main entity as the command definition

If just a single of those condition changes, the bug does not happen. For instance, I do not notice this behavior using the fish shell (which does not expose `$_`), or by running it with `bash -c "env -i ~/go/bin/cue run"`. Renaming the entity from `#Foo` to `Foo` also works.

Surprisingly, those 3 examples also run correctly:

```cue
package main

import (
        "tool/exec"
        "tool/os"
)

#Foo: {
        _env: os.Environ
}

command: run: exec.Run & {
        env: #Foo._env
        cmd: ["/usr/bin/env"]
}
```

```cue
package main

import (
        "tool/exec"
        "tool/os"
)

_env: os.Environ
#Foo: {
        printEnv: exec.Run & {
                env: _env
                cmd: ["/usr/bin/env"]
        }
}

command: run: #Foo
```

```cue
package main

import (
        "tool/exec"
        "tool/os"
)

#Foo: {
        _env: os.Environ
}

#Bar: {
        printEnv: exec.Run & {
                env: #Foo._env
                cmd: ["/usr/bin/env"]
        }
}

command: run: #Bar
```

I am fairly new to CUE; I understand there it tries to evaluate `tool/os.Environ` and expand environment variables as fields of the entity.

What I don't get is:
- why would `_` be a forbidden field there?
- why does it only happens when I declare both the `_env` field and the `printEnv` in an entity which name starts with the hash sign?
- why would the error not happen when I do the declarations in distinct entities?

**Comment by rogpeppe** [comment]
This seems to have been fixed now (I verified by running the script - it did indeed print the current shell environment), so closing.
