### ISSUE TITLE
Expr() doesn't return correct value?

### ISSUE THREAD

**Issue by ying-jeanne** [cue-lang/cue#1245]
### What version of CUE are you using (`cue version`)?
0.4.0-alpha.2
<pre>
$ cue version
</pre>

### Does this issue reproduce with the latest release?
yes

### What did you do?
https://github.com/ying-jeanne/cue_test_cases/blob/bf84db6edba61d3479838967d7445f1775393fc3/main.go

### What did you expect to see?
........ the v expr() is: [*4 | int] and the length is: 2, ops is | (or doesn't matter)
........ the v expr() is: [*4 | int *7 | int] and the length is: 2, ops is : |
........ the v expr() is: [4 7] and the length is: 2, ops is : |

### What did you see instead?
........ the v expr() is: [*4 | int] and the length is: 1, ops is :
........ the v expr() is: [*4 | int *7 | int] and the length is: 2, ops is : |
........ the v expr() is: [4 7] and the length is: 2, ops is : |

PS:
it seems 
```
AType: *4 | int
Foo: {
	Baz: AType | *7
}
``` 
with Expr() I am getting 1 cue.Value in the return list, but with 
```
AType: *4 | int
Foo: {
	Baz: AType | *"pool"
}
```
I am getting 2 cue.Values in the return list...

**Comment by mpvl** [comment]
Analysis: The algorithm incorrectly removes defaults it believes are subsumed by non-default values.
