### ISSUE TITLE
yaml.Marshal and json.Marshal

### ISSUE THREAD

**Issue by b4nst** [cue-lang/cue#1253]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.4.0 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What did you do?

```textar
-- main.cue --
import (
	"encoding/json"
	"encoding/yaml"
)

b: foo: bytes & 'foo'

y: yaml.Marshal(b)
j: json.Marshal(b)
```

```shell
cue eval main.cue
```

### What did you expect to see?

Coherent marshaling between Json and YAML (base64 string)

### What did you see instead?

```
b: {
    foo: 'foo'
}
y: """
    foo: foo

    """
j: "{\"foo\":\"Zm9v\"}"
```

This is causing trouble when trying to export a Kubernetes Secret for example.

**Comment by verdverm** [comment]
It looks as though `yaml` works through the AST while `json` works through the ADT

- (yaml) https://github.com/cue-lang/cue/blob/master/internal/encoding/yaml/encode.go#L120
- (json) https://github.com/cue-lang/cue/blob/v0.4.0/cue/types.go#L937

The AST does not have as rich information as the ADT and thus cannot differentiate between a string and bytes.

I think there is a larger issue around consistency not only at the output point, but also in how the implementations work. There should probably be an effort to clean these up. Thoughts @mpvl @myitcv ?

**Comment by verdverm** [comment]
In the meantime, you can use the following to get more consistent output (i.e. manually base64 encode)

```
import (
        "encoding/base64"
        "encoding/json"
        "encoding/yaml"
)

b: _foo: bytes & 'foo'
b: foo: base64.Encode(null, b._foo)
b: bar: string & "bar"

y: yaml.Marshal(b)
j: json.Marshal(b)
```

```
$ cue eval 1253.cue
b: {
    foo: "Zm9v"
    bar: "bar"
}
y: """
    foo: Zm9v
    bar: bar

    """
j: "{\"foo\":\"Zm9v\",\"bar\":\"bar\"}"
```

**Comment by b4nst** [comment]
@verdverm thanks for the heads up. That workaround is not working when your definition is expecting an actual `bytes` type. Let's take Kubernetes secret for example (that's my current use case). The automatic generation of the Secret definition in `core/v1/` is:

```cue
#Secret: {
	metav1.#TypeMeta

	// Standard object's metadata.
	// More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	// +optional
	metadata?: metav1.#ObjectMeta @go(ObjectMeta) @protobuf(1,bytes,opt)

	// Immutable, if set to true, ensures that data stored in the Secret cannot
	// be updated (only object metadata can be modified).
	// If not set to true, the field can be modified at any time.
	// Defaulted to nil.
	// +optional
	immutable?: null | bool @go(Immutable,*bool) @protobuf(5,varint,opt)

	// Data contains the secret data. Each key must consist of alphanumeric
	// characters, '-', '_' or '.'. The serialized form of the secret data is a
	// base64 encoded string, representing the arbitrary (possibly non-string)
	// data value here. Described in https://tools.ietf.org/html/rfc4648#section-4
	// +optional
	data?: {[string]: bytes} @go(Data,map[string][]byte) @protobuf(2,bytes,rep)

	// stringData allows specifying non-binary secret data in string form.
	// It is provided as a write-only input field for convenience.
	// All keys and values are merged into the data field on write, overwriting any existing values.
	// The stringData field is never output when reading from the API.
	// +k8s:conversion-gen=false
	// +optional
	stringData?: {[string]: string} @go(StringData,map[string]string) @protobuf(4,bytes,rep)

	// Used to facilitate programmatic handling of secret data.
	// +optional
	type?: #SecretType @go(Type) @protobuf(3,bytes,opt,casttype=SecretType)
}
```

The data field expects `bytes`, but `base64.Encode` returns a string. I can transform that back into `bytes` but then it's the `json` export that will make no sense: base64 encoding a base64 value.

**Comment by verdverm** [comment]
@b4nst, are any of the following viable...?

- constrain the problem to output just JSON or Yaml
- supply a `-t encoder=[yaml|json]` flag as needed
- use the `stringData` field instead of `data`

**Comment by b4nst** [comment]
I took the first one - constraining Yaml - because people are often more comfortable with Yaml for k8s. `stringData` reveals its weaknesses with secret using funky characters and I find myself using those quite often, especially in secrets. Second solution is nice too, didn't think of this one. Thank you very much for your help @verdverm!

Also regarding the root cause, @mpvl @myitcv I'm eager to help if that seems doable.

**Comment by mpvl** [comment]
Need to do some more digging as to why these are different, but this is indeed not correct.

One remaining question is how to represent this in YAML. Should it be
```
foo: Zm9v
```
or
```
foo: !!binary Zm9v
```
or something else?

**Comment by mpvl** [comment]
@verdverm 
> It looks as though yaml works through the AST while json works through the ADT

Indeed. The YAML converter should also use the ADT, really. And also for reading. The latter would allow to interpret strings based on the schema types, just as how this is done for protobuf. This ability was added later, specifically for Proto, which cannot be interpreted without a schema, and thus the YAML implementation is trailing behind there.

Tip now converts the byte value from the example to `foo: !!binary Zm9v`.

**Comment by mpvl** [comment]
See https://review.gerrithub.io/c/cue-lang/cue/+/527375
