### ISSUE TITLE
Check if a value implements a specific definition.

### ISSUE THREAD

**Issue by amedeiros** [cue-lang/cue#1259]
**Is your feature request related to a problem? Please describe.**
While using the GO library and processing a compiled cue value I would like to check if this value implements a specific definition. As far as I can tell there is no way to compare if a value implements a specific definition or not.

**Describe the solution you'd like**
A value comparison to check if a value implements a definition or not.

**Describe alternatives you've considered**
I have tried to get the definition and perform an `Equals` between the definition and the value in question this returns false which I expected.

```go
personDef := cueSpec.LookupPath(cue.ParsePath("Person"))
contactValue.Equals(personDef)
```

**Additional context**

For example if I have the following
```
#Person: {
  firstName: string
  lastName: string
  phone?: string
}

contact: #Person & {
  firstName: "John"
  lastName: "Doe"
}
```

With the GO library when I come across the `contact` value I want to know if it implements the definition `#Person` or not.

**Comment by verdverm** [comment]
use `cue.Value.Unify` which is the equivalent of `&`. https://pkg.go.dev/cuelang.org/go@v0.4.0/cue#Value.Unify

If you are using the conjunction (`&`) in the parsed CUE, then you probably are looking for `cue.Value.Validate` with the correct options set. https://pkg.go.dev/cuelang.org/go@v0.4.0/cue#Value.Validate  (Click through to the function definition to see the defaults)

I believe mutual `Subsumes` may equate to equality. (@mpvl ?)

**Comment by verdverm** [comment]
Also note that the CUE GitHub repo has [discussions](https://github.com/cue-lang/cue/discussions) enable for question / answers
