### ISSUE TITLE
spec: unclear for $ and Identifier

### ISSUE THREAD

**Issue by verdverm** [cue-lang/cue#1264]
The spec seems to be unclear or incomplete to the usage of `$` in identifiers.

From : https://cuelang.org/docs/references/spec/#letters-and-digits

```
letter        = unicode_letter | "_" .
```

From: https://cuelang.org/docs/references/spec/#identifiers

```
identifier  = [ "#" | "_#" ] letter { letter | unicode_digit } .
```

However this second link has the following text which is unclear and contradicts(?) the `letter` rule:

> An identifier is a sequence of one or more letters (which includes _ and $) and digits, optionally preceded by # or _#. It may not be _ or $. The first character in an identifier, or after an # if it contains one, must be a letter. Identifiers starting with a # or _ are reserved for definitions and hidden fields.

The following are all valid in v0.4.0

```
_#$foo: {...}
#$foo: {...}
_$foo: {...}
$foo: {...}
```
(https://cuelang.org/play/?id=6pyd-MaoZ2j#cue@def@cue)

---

Based on this, it would seem that the first rule should include `$`

```
letter        = unicode_letter | "_" | "$" .
```

The paragraph may be clearer with some minor editing

An identifier is a sequence of one or more letters (which includes `_` and `$`) and digits, optionally preceded by `#` or `_#`.
- It may not be **a standalone** `_` or `$`.
- The first character in an identifier must be a letter. If the identifier is a definition, this applies to the first character after ~an~ the #.
- Identifiers starting with a `#` or `_` ~are reserved for~ **signify** definitions and hidden fields **respectively**.

**Comment by mpvl** [comment]
Good catch. Indeed, the rule should be
```
letter        = unicode_letter | "_" | "$" .
```
