### ISSUE TITLE
The testable example "ExampleContext" is not testing output

### ISSUE THREAD

**Issue by ameowlia** [cue-lang/cue#1267]
👋  Hello, 

I am investigating the golang issue: https://github.com/golang/go/issues/48362, where testable examples are causing false positives when the output comment block is not the last comment block example.

I ran a parser against the [top golang repos](https://github.com/kaxap/arl/blob/master/README-Go.md), including this repo, and I found this bug with your [ExampleContext testable example](https://github.com/cue-lang/cue/blob/e8550b89779d293bbc9b530d2c4c9f9cf4c6f3d0/cue/examplecompile_test.go#L24-L55).

The output comment blocks at the end should be combined like so:

```
func ExampleContext() {
	ctx := cuecontext.New()

	v := ctx.CompileString(`
		a: 2
		b: 3
		"a+b": a + b
	`)

	p("lookups")
	p("a:     %v", v.LookupPath(cue.ParsePath("a")))
	p("b:     %v", v.LookupPath(cue.ParsePath("b")))
	p(`"a+b": %v`, v.LookupPath(cue.ParsePath(`"a+b"`)))
	p("")
	p("expressions")
	p("a + b: %v", ctx.CompileString("a + b", cue.Scope(v)))
	p("a * b: %v", ctx.CompileString("a * b", cue.Scope(v)))

	// Output:
	// lookups
	// a:     2
	// b:     3
	// "a+b": 5
	//
	// expressions
	// a + b: 5
	// a * b: 6
}
```

I am happy to PR this in, but it will take a few days for me to get approval from my employer before I can submit it.

**Comment by mpvl** [comment]
> I am happy to PR this in, but it will take a few days for me to get approval from my employer before I can submit it.

Great!

**Comment by ameowlia** [comment]
I'm seeing you all over the place @mpvl 😄 . PR (finally) sent.

**Comment by mpvl** [comment]
@ameowlia Indeed. :) Thanks for the PR.

The PR importer is broken at the moment, but will submit asap.
