### ISSUE TITLE
Setting a value of a nested path from for loop in a tool.

### ISSUE THREAD

**Issue by iilyak** [cue-lang/cue#1276]
I have a list of users under `_users` key. Each user is a structure which has a `_ssh_authorized_keys` key. The `_ssh_authorized_keys` is a list. My goal is to develop a cue tool which would inject the `ssh_key` into `_users[name]._ssh_authorized_keys[*]`.

Here is the code structure 
```
command: "gen": {
	for user in _users {
		for _key in user._ssh_authorized_keys if _key.key == "{generate}" {
			"key-\(user.name)": file.Read & {
				filename: "identities/\(user.name).pub"
				contents: string
			}
		}
		// how do I append a new value into `ssh_authorized_keys` for each key for each user
	}
}
```

Questions:
- how to refer to a path to assign values (`_users[user.name]._ssh_authorized_keys: "something"` doesn't work)?
- how to use "key-\(user.name)" in a reference (`"key-\(user.name)".key` doesn't work)?
- how to iterate array and get current index so I can use `_users[idx]` to refer to the user structure?

**Comment by eonpatapon** [comment]
Would be better to post this kind of questions in the discussions section.

Anyway `file.Append` should do the job (https://pkg.go.dev/cuelang.org/go@v0.4.0/pkg/tool/file) - (not tested)

```cue
command: gen: {
	for user in _users {
		for _key in user._ssh_authorized_keys if _key.key == "{generate}" {
			"key-\(user.name)": file.Read & {
				filename: "identities/\(user.name).pub"
				contents: string
			}
                       "authorized_keys-\(user.name)": file.Append & {
                                filename: "/path/to/authorized_keys"
                                // this generates an implicit dependency to the above task
                                contents: gen["key-\(user.name)"].contents
                       }
		}
	}
}
```

**Comment by iilyak** [comment]
> Would be better to post this kind of questions in the discussions section.

Sorry I'll use discussion section. I never used this feature on github yet.

**Comment by iilyak** [comment]
moved to discussion https://github.com/cue-lang/cue/discussions/1278
