### ISSUE TITLE
cmd/cue: def emits invalid output with multiple list conjuncts

### ISSUE THREAD

**Issue by vikstrous2** [cue-lang/cue#1284]
### What version of CUE are you using (`cue version`)?
The web based emulator https://cuelang.org/play/#cue@export@yaml

### Does this issue reproduce with the latest release?
No, this is a bug reproducible only in the web based emulator.

### What did you do?
https://cuelang.org/play/?id=B2-EGA_qicy#cue@export@yaml

```
l: [...]
l: ["a",...]
l: ["a","b",...]
```

### What did you expect to see?
```
l: ["a", "b"]
```

### What did you see instead?
When output is set to yaml in the cloud emulator, this produces an error:
```
failed to encode: l: conflicting values ["a","b",...] and {} (mismatched types list and struct)
```

Weirdly, this actually works if the list is at the top level (not inside `l`):
```
[...]
["a",...]
["a","b",...]
```

This is a weirdly specific bug. There must be something special about the way the emulator runs. I can't reproduce it locally with any version of cue.

**Comment by antong** [comment]
This is not limited to the playground. I managed a kind of repro with v0.4.0. With the original input, cue def outputs: `l: [...] & ["a", ...] & ["a", "b", ...] & {}`. So it makes up an extra conjunct "{}" of type struct, which break things. Perhaps the playground does some extra round of cue def, which triggers this.

Here is a txtar/testscript repro with v0.4.0 (@myitcv , did I finally get this right ? ;-)

```
exec cue def x.cue
stdin stdout
exec cue export -

-- x.cue --
l: [...]
l: ["a",...]
l: ["a","b",...]
```

Gives:
```
l: [...] & ["a", ...] & ["a", "b", ...] & {}
> stdin stdout
> exec cue export -
[stderr]
l: conflicting values ["a","b",...] and {} (mismatched types list and struct):
    -:1:25
    -:1:43
[exit status 1]
```

**Comment by myitcv** [comment]
> Here is a txtar/testscript repro with v0.4.0 (@myitcv , did I finally get this right ? ;-)

🎉  great work! Just to check, do you use [`cmd/testscript`](https://pkg.go.dev/github.com/rogpeppe/go-internal/cmd/testscript) to validate them? I [tweeted recently](https://twitter.com/_myitcv/status/1453952459794051084) about some means by which we could (in an ideal world) have this be integrated as part of the issue tracker/discussions.

This issue really falls in the same bucket as https://github.com/cue-lang/cue/issues/1340, but will keep separate for now because I'm not totally clear they are one and the same "issue".

**Comment by antong** [comment]
> Just to check, do you use cmd/testscript to validate them?

I installed github.com/rogpeppe/go-internal/cmd/testscript, ran it, and fed it the input (txtar). Then I copy pasted the interesting part from the output to the comment/description.
