### ISSUE TITLE
encoding/yaml: no error position information for "empty" null values

### ISSUE THREAD

**Issue by Rots** [cue-lang/cue#1291]
### What version of CUE are you using (`cue version`)?

development after 0.4.0 at e8550b89779d293bbc9b530d2c4c9f9cf4c6f3d0

### Does this issue reproduce with the latest release?

Yes

### What did you do?

Try to validate [YAML](https://github.com/Rots/cue/blob/2dc29a280d054c7b7795e4b0ec4038dfe5ff6896/cmd/cue/cmd/testdata/script/null_yaml.txt#L10-L11) with "empty" null values, like this:

```yaml
a:
```
[Vet the yaml](https://github.com/Rots/cue/blob/2dc29a280d054c7b7795e4b0ec4038dfe5ff6896/cmd/cue/cmd/testdata/script/null_yaml.txt#L4) with a [cue schema](https://github.com/Rots/cue/blob/2dc29a280d054c7b7795e4b0ec4038dfe5ff6896/cmd/cue/cmd/testdata/script/null_yaml.txt#L6-L7):
`cue vet my.yaml my.cue`

[Full test](https://github.com/Rots/cue/blob/2dc29a280d054c7b7795e4b0ec4038dfe5ff6896/cmd/cue/cmd/testdata/script/null_yaml.txt):
```
! exec cue vet null.yaml schema.cue
cmp stderr null-stderr

! exec cue vet nonull.yaml schema.cue
cmp stderr nonull-stderr

-- schema.cue --
a:b:c: string
-- null.yaml --
a: null
-- nonull.yaml --
a:
-- null-stderr --
a: conflicting values null and {b:{c:string}} (mismatched types null and struct):
    ./null.yaml:1:5
    ./schema.cue:1:3
-- nonull-stderr --
a: conflicting values null and {b:{c:string}} (mismatched types null and struct):
    ./nonull.yaml:1:2
    ./schema.cue:1:3

```

### What did you expect to see?

Per the expectation in the `txtar`.

Result of the test run:
* first run with explicit null in the yaml file shows a useful error message
* second run shows `-` (does that mean stdin?) as the location of the conflict, instead of the expected `nonull.yaml` file

```
--- FAIL: TestScript (0.06s)
    --- FAIL: TestScript/null_yaml (0.11s)
        testscript.go:397: 
            > ! cue vet null.yaml schema.cue
            [stderr]
            a: conflicting values null and {b:{c:string}} (mismatched types null and struct):
                ./null.yaml:1:5
                ./schema.cue:1:3
            [exit status 1]
            > cmp stderr null-stderr
            > ! cue vet nonull.yaml schema.cue
            [stderr]
            a: conflicting values null and {b:{c:string}} (mismatched types null and struct):
                -
                ./schema.cue:1:3
            [exit status 1]
            > cmp stderr nonull-stderr
            --- stderr
            +++ nonull-stderr
            @@ -1,3 +1,3 @@
             a: conflicting values null and {b:{c:string}} (mismatched types null and struct):
            -    -
            +    ./nonull.yaml:1:2
                 ./schema.cue:1:3
            
            FAIL: testdata/script/null_yaml.txt:5: stderr and nonull-stderr differ
            
FAIL
FAIL    cuelang.org/go/cmd/cue/cmd      15.707s
FAIL
```

**Comment by mpvl** [comment]
The problem very likely is in the YAML decoder, which currently is in third_party/yaml.

We should move to the go-yaml.v3 decoder, but may be worth fixing if it is a quick fix.

**Comment by myitcv** [comment]
@Rots thanks for the testscript reproducer. Just a small nit that `cue` is not one of the standard commands, so running this through [`cmd/testscript`](https://pkg.go.dev/github.com/rogpeppe/go-internal@v1.8.0/cmd/testscript) results in:

```
> ! cue vet null.yaml schema.cue
FAIL: /tmp/testscript2556004649/-/script.txt:1: unknown command "cue"
```

Hence you need to use `exec cue` instead. I've updated the issue description repro accordingly.

That said, confirmed with 59bdbb50.

**Comment by mvdan** [comment]
The following testscript passes now as of c683420c0797090a1445b453e3318a4570fc4742:

```
! exec cue vet null.yaml schema.cue
cmp stderr null-stderr

! exec cue vet nonull.yaml schema.cue
cmp stderr nonull-stderr

-- schema.cue --
a:b:c: string
-- null.yaml --
a: null
-- nonull.yaml --
a:
-- null-stderr --
a: conflicting values null and {b:{c:string}} (mismatched types null and struct):
    ./null.yaml:1:4
    ./schema.cue:1:3
-- nonull-stderr --
a: conflicting values null and {b:{c:string}} (mismatched types null and struct):
    ./nonull.yaml:1:3
    ./schema.cue:1:3
```

This appears fixed by the new YAML decoder, and indeed `git bisect` points to https://review.gerrithub.io/c/cue-lang/cue/+/1193147 - before that commit, the second command would produce `-` rather than the YAML file for the position.

Note that in the first case, the position `1:4` appears correct, as `null` begins on the fourth byte in the line. I'm not sure why we used to give `1:5`, but that didn't seem quite right.
