### ISSUE TITLE
Cuelang.org expired and parked

### ISSUE THREAD

**Issue by sul3n3t** [cue-lang/cue#1302]
### What version of CUE are you using (`cue version`)?

N/A

### Does this issue reproduce with the latest release?

N/A

### What did you do?

Visit http://cuelang.org/ or https://cuelang.org/

### What did you expect to see?

The project website load

### What did you see instead?

For http, a GoDaddy parked domain. For https, connection failure.

<img width="850" alt="Screen Shot 2021-10-15 at 11 02 22 AM" src="https://user-images.githubusercontent.com/426982/137532467-a537089a-627e-47e6-bf3a-d863291f6d27.png">

**Comment by mpvl** [comment]
Thanks. Fixed!

Seems like Godaddy removed the payment method (Paypal). And no clear warnings on top of that.

Will switch registrar soon.
