### ISSUE TITLE
Panic in FillPath about not the same runtime

### ISSUE THREAD

**Issue by verdverm** [cue-lang/cue#1303]
All values in the example come from the same `cue.Context`. I'm assuming something like this should work and is likely related to the transition from Runtime to Context.

### What version of CUE are you using (`cue version`)?

v0.4.0 Go API

### What did you do?

`go run fillpath.go`

```go
package main

import (
	"fmt"

	"cuelang.org/go/cue"
	"cuelang.org/go/cue/cuecontext"
)

const orig = `
a: b: "c"
`

const replace = `
a: b: "C"
`

func main() {
	ctx := cuecontext.New()

	o := ctx.CompileString(orig)
	r := ctx.CompileString(replace)

	f := replacer(r, o, ctx)
	fmt.Println(f)
}

func replacer(replace, orig cue.Value, ctx *cue.Context) cue.Value {
	var result cue.Value

	switch orig.IncompleteKind() {
	case cue.StructKind:
		result = ctx.CompileString("")
		s, _ := orig.Fields()
		for s.Next() {
			sel := s.Selector()
			path := cue.MakePath(sel)
			r := replace.LookupPath(path)
			if r.Exists() {
				tmp := replacer(s.Value(), r, ctx)
				result = result.FillPath(path, tmp)
			}
		}

	case cue.ListKind:
		vals := []cue.Value{}
		l, _ := orig.List()
		for l.Next() {
		}
		result = ctx.NewList(vals...)

	default:
		p := orig.Path()
		r := replace.LookupPath(p)
		if r.Exists() {
			result = r
		}
	}

	return result
}
```

### What did you expect to see?

Not a panic

### What did you see instead?

```
panic: values are not from the same runtime

goroutine 1 [running]:
cuelang.org/go/cue.Value.FillPath({0xc000021ea0, 0xc00022d8c0, 0x0}, {{0xc000207be8, 0xc00022d3b0, 0x0}}, {0x9006a0, 0xc00000ea08})
        /home/tony/go/pkg/mod/cuelang.org/go@v0.4.0/cue/types.go:1652 +0xdfe
main.replacer({0xc000021ea0, 0xc00022d290, 0x0}, {0xc000021ea0, 0xc00022d5f0, 0x0}, 0xc000266270)
        /home/tony/cue/repro/gocode/fillpath.go:46 +0x425
main.replacer({0xc000021ea0, 0xc00022d440, 0x0}, {0xc000021ea0, 0xc00022cfc0, 0x0}, 0x200000003)
        /home/tony/cue/repro/gocode/fillpath.go:45 +0x3c5
main.main()
        /home/tony/cue/repro/gocode/fillpath.go:29 +0xec
exit status 2
```

**Comment by mpvl** [comment]
At first glance, this panic should indeed not happen.

**Comment by antong** [comment]
I'm not sure I entirely follow the code, but I think the innermost invocation of replacer() returns the zero value of cue.Value:
```
	tmp := replacer(s.Value(), r, ctx)  // returns zero Value
	result = result.FillPath(path, tmp) // result has context, but the context of tmp (zero Value) is different
```
This can happen in the default case of the switch statement in replacer():
```
	default:
		p := orig.Path()
		r := replace.LookupPath(p)
		if r.Exists() {  // false
			result = r
		}
	}

	return result // zero -> tmp above
```
So I'd say the panic is expected as not all values are from the same context.

**Comment by verdverm** [comment]
@antong good catch, I did not expect that case to be false given the example data. What is happening is that `Path` is returning the full path from the root during recursion, rather than being scoped to the value passed in.

The following does remove the panic. There are a few ways actually.

```go
	default:
		p := orig.Path()
		r := replace.LookupPath(p)
		if r.Exists() {  // false
			result = r
		} else {
			result = orig
		}
	}

	return result // zero -> tmp above
```

But does not give correct output for what I am trying to do. Need to process the orig.Path() to get the last component because there is not an easy way to get the current Value's label at present.

**Comment by myitcv** [comment]
@verdverm - I think from your analysis above, this can therefore be closed because there is no bug. But please say if otherwise.
