### ISSUE TITLE
lack of error message in `cue export` on incomplete value

### ISSUE THREAD

**Issue by joulaud** [cue-lang/cue#1304]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version 0.4.0 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
 yes

### What did you do?

```
cat <<'EOF' >x.cue
toto: {
       _current: *"toto" | string
	value:     *_|_ | _current
}
tata: "tata"
EOF

cue export x.cue
```

### What did you expect to see?
either error message on stderr like
```
toto: value: incomplete value *"toto" | string
```

or (better?) unified result on stdout
```
toto: value: "toto"
tata: "tata"
```

### What did you see instead?

unuseful error message on stderr
```
toto:
```

### full session
```
$ cat <<'EOF' >y.cue
toto: {
       _current: *"toto" | string
        value:     *_|_ | _current
}
tata: "tata"
EOF

$ cue export y.cue
toto: 

$ cue eval y.cue
toto: {
    value: "toto" | string
}
tata: "tata"
```

**Comment by mpvl** [comment]
This seems to be a bug, triggered by the combination of usage of `*_|_` and another nested disjunction with default value.

Reproducer:
```
toto: value: *_|_ | (*"toto" | string)
```

Judging from the output, it bails printing in an unexpected matter. Given that `eval` works fine, I expect this is an `export` bug.
