### ISSUE TITLE
cmd/cue: `cue get go` doesn't support `uintptr` type

### ISSUE THREAD

**Issue by vikstrous2** [cue-lang/cue#1305]
### What version of CUE are you using (`cue version`)?

<pre>
cue version v0.4.0 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes, on master

### What did you do?
```
go mod init tmp.com
go get istio.io/api/networking/v1alpha3
cue get go istio.io/api/networking/v1alpha3
cue eval ./...
```

### What did you expect to see?
success

### What did you see instead?
```
_#field: reference "uintptr" not found:
    ./cue.mod/gen/github.com/gogo/protobuf/proto/pointer_unsafe_go_gen.cue:11:10
package "reflect" not found:
    ./cue.mod/gen/github.com/gogo/protobuf/proto/properties_go_gen.cue:7:8
```

**Comment by derekcrovo** [comment]
I'm seeing this too, with the v1beta version (`cue get go istio.io/api/networking/v1beta1`).
I get the same error message from `cue eval`.

**Comment by slewiskelly** [comment]
`reference "uintptr" not found` is for the same reason as, and can be worked around by, what was described in https://github.com/cue-lang/cue/issues/1336.

**Comment by dave08** [comment]
I just had this with 0.4.2 also.

**Comment by marcellanz** [comment]
Hi 👋– I have this "issue" with `github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2` too and I found this issue here. I use cue 0.4.2 and used:
```
go get github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2
cue get go github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2
```
to validate instances of #CiliumNetworkPolicy

**Comment by rogpeppe** [comment]
It seems like this is a simple omission of the `uintptr` type from the Go import logic.
Here's a simple reproducer:

```
exec cue get go example.com/m
exec cue vet example.com/m

-- cue.mod/module.cue --
module: "example.com/c"
-- go.mod --
module example.com/m

go 1.18
-- m.go --
package m

type Foo struct {
	X uintptr
}
```

This fails currently:

```
> exec cue get go example.com/m
> exec cue vet example.com/m
[stderr]
#Foo.X: reference "uintptr" not found:
    ./cue.mod/gen/example.com/m/m_go_gen.cue:7:10
[exit status 1]
FAIL: /tmp/testscript362736862/x.txt/script.txt:2: unexpected command failure
error running /tmp/x.txt in /tmp/testscript362736862/x.txt
```
