### ISSUE TITLE
floating point bounds not as expected

### ISSUE THREAD

**Issue by danschan** [cue-lang/cue#1310]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version 0.4.0 windows/amd64

</pre>

### Does this issue reproduce with the latest release?
yes

### What did you do?

evaluated

```
foo: {
	"value": >=2.1 & <=1.0
}
```

### What did you expect to see?

foo.value: incompatible bounds >=2.1 and <=1.0

### What did you see instead?
```
foo: {
    value: >=2.1 & <=1.0
}
```

**Comment by verdverm** [comment]
Are you trying to say it must be outside of `(1.0,2.1)`?

What you have wrote is that it must be both >=2.1 and <=1.0 at the same time.

You may be looking for `value: >=2.1 | <= 1.0` (a disjunction, of which only one should be valid)

**Comment by danschan** [comment]
This is only an example for the issue.

If I evaluate ">=2.1 & <=1.1" or ">=2 & <=1" at the same time, cue correctly reports an error. For ">=2.1 & <=1.0" not.

Originally my values were derrived from multiple schemes, but this example reproduces the behaviour in the most simple way.

**Comment by verdverm** [comment]
Ah, this same unreported error happens for `>=number & <= int` (`>=2.1 & <=1`)

I have a hunch this has to do with mixed type comparison (number vs int) and that `1.0` is probably converted to `1` as an int rather than a decimal

**Comment by verdverm** [comment]
Also, just as an FYI, `cue` uses an arbitrary precision decimal and not floating point.

https://pkg.go.dev/cuelang.org/go@v0.4.0/internal/core/adt#Num

(the comment there looks to confirm `1.0` is really seen as `1` the int)

**Comment by mpvl** [comment]
Interesting. Should be easy to fix.

**Comment by antong** [comment]
I think the bug is around: https://github.com/cue-lang/cue/blob/3b0a537a2db6d49d1ae67631a31c45ad97c69078/internal/core/adt/simplify.go#L130
Decimal d.Int64() returns an error if d is not an integer, and SimplifyBounds returns nil. So if the difference between the high and low bound is not integral, then simplification is not done for floats.

```
>=22.1 & <2.0 // >=22.1 & <2.0
>=22.1 & <2.1 // _|_ incompatible bounds >=22.1 and <2.1
>=22   & <2.0 // _|_ incompatible bounds >=22 and <2.0
```

**Comment by mpvl** [comment]
@antong: the bug was indeed in that switch statement.
