### ISSUE TITLE
gocodec: Accept a Context instead of/in addition to Runtime

### ISSUE THREAD

**Issue by sagikazarmark** [cue-lang/cue#1318]
**Is your feature request related to a problem? Please describe.**
`cue.Runtime` is deprecated in favor of `cue.Context` according the Go code documentation, but `gocodec.New` still awaits a Runtime (and then internally converts it to a context). There are multiple internal functions taking care of this conversion, but none is available in the public API leaving us with manual conversion: `gocodec.New((*cue.Runtime)(c), nil)`

It's not too bad, but leaves behind a bad taste.

**Describe the solution you'd like**
Depending on your backward compatibility promises, either update the `gocodec.New` function to accept a Context, expose a new constructor that accepts a Context or provide an exported conversion function.

**Describe alternatives you've considered**
I'm not sure this is actionable now (ie. there is a plan in place to replace all Runtime usage when the time comes), but wanted to raise it nevertheless to make sure it's tracked (a quick 5 minute search didn't show any similar issues)

**Comment by mpvl** [comment]
It will be hard to support both without cluttering the API, but clearly we should support `cue.Context`.

Two options come to mind:
1)  make `cue.Runtime` an alias to `cue.Context`. This has some drawbacks, but probably is okay.
2) supply `go fix` rules to rewrite old Go code to use `cue.Context`.

**Comment by myitcv** [comment]
This still needs to be fixed. Clearing the milestone for now because it was listed against the now defunct v0.4.x

Per discussion with @mpvl, we could "fix" this using generics.

**Comment by rogpeppe** [comment]
Fixed by 1e760956c098e7d116a78f8aa5b7d709309fedb5.
