### ISSUE TITLE
encoding/yaml: investigate new Yaml spec

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#1331]
At a cursory glance, doesn't look like any impactful changes from our side, but creating this as a placeholder nonetheless:

https://yaml.com/blog/2021-10/new-yaml-spec/

**Comment by verdverm** [comment]
@myitcv That was my reading as well

**Comment by mpvl** [comment]
There doesn't appear to be anything material changed.

**Comment by myitcv** [comment]
Closing therefore.
