### ISSUE TITLE
cmd/cue: get go generates invalid CUE from byte type

### ISSUE THREAD

**Issue by james-maloney** [cue-lang/cue#1336]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.4.0 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

    package cuego

    import "github.com/google/uuid"

    type Bar struct {
	    ID uuid.UUID
    }

Generate Cue from Go package

    cue get go cuego

Output:

    $cat cuego/types_go_gen.cue
    
    // Code generated by cue get go. DO NOT EDIT.

    //cue:generate cue get go cuego

    package cuego

    import "github.com/google/uuid"

    #Bar: ID: uuid.#UUID

Vet

    cue vet gen/cuego/types_go_gen.cue
    #Domain: reference "byte" not found:
        ./gen/github.com/google/uuid/dce_go_gen.cue:8:10
    #Version: reference "byte" not found:
        ./gen/github.com/google/uuid/uuid_go_gen.cue:12:11
    #Variant: reference "byte" not found:
        ./gen/github.com/google/uuid/uuid_go_gen.cue:15:11
     
### What did you expect to see?

A valid cue file generated from the Go package

### What did you see instead?

An invalid cue file using an un-known `byte` type

    // Code generated by cue get go. DO NOT EDIT.

    //cue:generate cue get go github.com/google/uuid

    package uuid

    // A Domain represents a Version 2 domain
    #Domain: byte // #enumDomain

    #enumDomain:
    	#Person |
    	#Group |
    	#Org

    #values_Domain: {
    	Person: #Person
    	Group:  #Group
    	Org:    #Org
    }

    #Person: #Domain & 0
    #Group:  #Domain & 1
    #Org:      #Domain & 2

**Comment by slewiskelly** [comment]
In Go, but not in CUE, a `byte` is an alias for `uint8`. 

Using `uint8` in place of `byte` works as expected, so (naively) assume a similar translation needs to occur?

The only documentation I see about `byte` or `bytes` is when translating arrays or slices:

>  - slices and arrays convert to CUE lists, except when the element type is byte, in which case it translates to the CUE bytes type.

However, there is a note [here](https://github.com/cue-lang/cue/blob/0aaf4c69be6394bcb20c0a659382f48b9cffec33/internal/core/compile/predeclared.go#L84) which mentions why there is no `byte` builtin:

> Do not include an alias for "byte", as it would be too easily confused with the builtin "bytes".

**Comment by myitcv** [comment]
Thanks for the report, @james-maloney. 

Confirmed with e8550b89:

```
exec cue get go --local .
exec cue eval

-- go.mod --
module mod.com

go 1.16
-- main.go --
package cuego

type Bar byte
-- main_go_gen.cue --
// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go mod.com

package cuego

#Bar: byte
```

gives:

```
> exec cue eval
[stderr]
#Bar: reference "byte" not found:
    ./main_go_gen.cue:7:7
[exit status 1]
FAIL: /tmp/testscript009373651/repro.txt/script.txt:2: unexpected command failure
```
