### ISSUE TITLE
Issue about module and package

### ISSUE THREAD

**Issue by quovadis-7** [cue-lang/cue#1338]
In this part(https://cuelang.org/docs/concepts/packages/#location-on-disk), it says 
If a module identifier is defined and is a prefix of the import path, the package is located at the corresponding location relative to the module root.
Otherwise, the package contents looked up in the cue.mod/pkg, cue.mod/gen, and cue.mod/usr subdirectores.
If I do not have a module.cue in the cue.mod, when I import a package, is it mean it will find the package in the cue.mod/pkg, cue.mod/gen, and cue.mod/usr subdirectores?
For example I have a project layout like this:
```
APP-META/
  cue.mod/
    pkg/
      schemas/
        trains/
          track.cue
   main.cue
```
main.cue is as follows:
```cue
import (
	"schemas/trains:track"
)

B: track.#Track & {
	c : "xixi"
}
```
and track.cue is as follows:
```cue
package track

#Track : {
	a: 1
	b: 2
	c: string
	d: 2
}
```
When I execute cue export service.cue --out yaml, it report errors:
B: "schemas/trains:track".#Track undefined ("schemas/trains:track" is incomplete):
    ./service.cue:5:4

**Comment by verdverm** [comment]
I think you need a `cue.mod/modules.cue` for any type of import to work, besides stdlib. Module names should also start with something that looks like a domain name.

**Comment by quovadis-7** [comment]
> I think you need a `cue.mod/modules.cue` for any type of import to work, besides stdlib. Module names should also start with something that looks like a domain name.

So a module.cue is necessary if I want to import a package?

**Comment by quovadis-7** [comment]
> I think you need a `cue.mod/modules.cue` for any type of import to work, besides stdlib. Module names should also start with something that looks like a domain name.

I add a module.cue but it still report an error:
package "schemas/trains:track" not found:
    ./service.cue:4:3
after I add a parent directory "test.com "for schemas, it works. Now the layout is as follow:
```
APP-META/
  cue.mod/
    pkg/
      test.com/
        schemas/
         trains/
          track.cue
    module.cue
   main.cue
```
Why it works after I add "test.com"?

**Comment by verdverm** [comment]
> Why it works after I add "test.com"?

Because the first part is required to be a domain name. This mirrors Go module requirements, which has some nice properties for software supply chain security.

**Comment by myitcv** [comment]
> I think you need a `cue.mod/modules.cue` for any type of import to work, besides stdlib

Correct, per https://cuelang.org/docs/concepts/packages/#modules:

> The use of a module is optional, but required if one wants to import files.

(although "import files" is not particularly precise, that should be "import packages")
