### ISSUE TITLE
What does a keyword do?

### ISSUE THREAD

**Issue by quovadis-7** [cue-lang/cue#1342]
In this section, it says that CUE reserves all identifiers starting with __(double underscores) as keywords.
In which case I could use an identifier starting with __, can  you show me an example?

**Comment by verdverm** [comment]
[https://github.com/cue-lang/cue/search?q=__](https://github.com/cue-lang/cue/search?q=__) looks to have some breadcrumbs. As I understand it, they are largely internal and you shouldn't see them as a user.

You can use quotes to have labels which contain special chars

```cue
"#def": "not really a definition"
"_hid": "not really hidden"
"__foo": "not really a reserved identifier"
```

https://cuelang.org/play/?id=ysVprjTceqV#cue@export@json
