### ISSUE TITLE
Dependency tracking fails when using "tool/exec.Run" with "cmd" being an aliased list

### ISSUE THREAD

**Issue by addreas** [cue-lang/cue#1344]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version (devel) linux/amd64 
</pre>

The master branch at commit 0f53054da7243c7a312cd0ad54a1083d67c185d3

### Does this issue reproduce with the latest release?
Yes

### What did you do?

```
-- test_tool.cue --
package test

import (
	"strings"
	"tool/exec"
	"tool/file"
	"tool/cli"
)

command: test1: {
	task: dependency: file.Glob & {glob: "./*.cue"}

	task: dependant: exec.Run & {
		let alias = ["echo", "\(strings.Join(task.dependency.files, ", "))"]
		cmd: alias
	}
}

command: test2: {
	task: dependency: file.Glob & {glob: "./*.cue"}

	task: dependant: exec.Run & {
		let alias = ["echo", "\(task.dependency.files[0])"]
		cmd: alias
	}
}

command: test3: {
	task: dependency: cli.Ask & {prompt: "test"}

	task: dependant: exec.Run & {
		let alias = ["echo", task.dependency.response]
		cmd: alias
	}
}
```

### What did you expect to see?
The same as if the `cmd` wasn't aliased or was specified as a single string:
```
$ cue test1
test_tool.cue
$ cue test2
test_tool.cue
$ echo test | cue test3
test test
```

### What did you see instead?
```
$ cue test1                                               

$ cue test2                                               
test command.test2.task.dependant.cmd.1: invalid interpolation: index out of range [0] with length 0:
    ./test_tool.cue:23:24
    ./test_tool.cue:23:49
$ echo test | cue test3
command.test3.task.dependant.cmd.1: non-concrete value string
$ echo test | cue test3
command.test3.task.dependant.cmd.1: non-concrete value string
test $ echo test | cue test3
test command.test3.task.dependant.cmd.1: non-concrete value string
```
At first I only had the `file.Glob` examples, since that's where I originally stumbled upon this, but then I thought it would be interesting to try something else as a dependency and realized that with `cli.Ask` the result isn't even deterministic.

**Comment by myitcv** [comment]
Thanks for reporting, @addreas.

Confirmed that this is a variation on https://github.com/cue-lang/cue/issues/1088. i.e. we are not detecting all dependencies in all cases. 

So will close as a dup.
