### ISSUE TITLE
internal/core: struct with key/values and a field comprehension outputs keys in an un-intuitive/indeterminate order

### ISSUE THREAD

**Issue by janzheng** [cue-lang/cue#1348]
### What version of CUE are you using (`cue version`)?

<pre>
v0.4.0 Playground

$ cue version
cue version 0.4.0 darwin/amd64

</pre>

### Does this issue reproduce with the latest release?
Yes

### What did you do?

<pre>
ex: {
    for x,a in [1,2] {
        "loop_\(a)": "hi"
    }
    shouldbe: "at the end"
}

ex2: {
    thisis: "at the top"
    for x,a in [1,2] {
        "loop_\(a)": "hi"
    }
    shouldbe: "at the end"
}
</pre>

### What did you expect to see?

Expected output: where {shouldbe: "at the end"} appears at the end of the struct, instead of the beginning

```
// expected
ex: {
    loop_1:   "hi"
    loop_2:   "hi"
    shouldbe: "at the end"
}

ex2: {
    thisis:   "at the top"
    loop_1:   "hi"
    loop_2:   "hi"
    shouldbe: "at the end"
}

```

### What did you see instead?

Actual output: {something: "else"} appears first. A struct with key/values and a field comprehension outputs keys in an un-intuitive, indeterminate order.

This issue is related to #474 

```
// actual
ex: {
    shouldbe: "at the end"
    loop_1:   "hi"
    loop_2:   "hi"
}

ex2: {
    thisis:   "at the top"
    loop_1:   "hi"
    shouldbe: "at the end"
    loop_2:   "hi"
}

```

**Comment by janzheng** [comment]
#474

**Comment by janzheng** [comment]
For anyone that absolutely needs a struct ordered in a certain way, (e.g. for CSV output), here's a dirty way of sorting a struct by its keys in alphabetical order, by using the "Function" pattern from https://cuetorials.com/patterns/functions/ 

https://cuelang.org/play/?id=FkUiTP33ZyM#cue@export@json

```

import "strings"
import "list"


ex0: {
    aardvark: "oink"
    yyy: "why why why"
    for x,a in [1,2] {
        for y,b in ["A","B"] {
            "\(a)\(b)":"\(x),\(y)"
        }
        "after_\(a)": "hi"
    }
    zzzz: "else"
}
ex1: {
    for x,a in [1,2] {
        "loop_\(a)": "hi"
    }
    zis_shouldbe: "at the end"
}

ex2: {
    a_thisis: "at the top"
    for x,a in [1,2] {
        "loop_\(a)": "hi"
    }
    z_shouldbe: "at the end"
}



#SortByKey: {
	_input="in": {...}

	// set output
    sorted: {for _ in list.Sort([for x,y in _input {
        key: x
        val:y
    }], {x: {}, y: {}, less: x.key < y.key} )
    { "\(_.key)": "\(_.val)"}}
}

// Call SortByKey by "passing" it a value
_ex0_sorted: #SortByKey & {in: {ex0}}
ex0_sorted: _ex0_sorted["sorted"]

_ex1_sorted: #SortByKey & {in: {ex1}}
ex1_sorted: _ex1_sorted["sorted"]

_ex2_sorted: #SortByKey & {in: {ex2}}
ex2_sorted: _ex2_sorted["sorted"]


```

**Comment by verdverm** [comment]
If you can explicitly enumerate a known set of fields, you can unify with a definition based schema.

```cue
ordered: #Ordered & val
```

like `#DefB` in https://cuelang.org/play/?id=qCwEyaSRVQ1#cue@export@cue

`#DefA` gives an alternative and unintuitive ordering

Generally, CUE is using a topological ordering. Regular fields are treated differently than pattern constraints and comprehensions. That being said, seeing them interleave with regular fields is perplexing.

**Comment by myitcv** [comment]
@mpvl is currently reworking part of the comprehension implementation and so will revisit this issue (and other related issues) as part of that.

**Comment by mpvl** [comment]
The CUE spec currently follows the JSON semantics, where ordering of fields is unspecified.

That said, we do aim to tighten the spec to preserve a topological ordering of fields, though. See also #474.

**Comment by joulaud** [comment]
> The CUE spec currently follows the JSON semantics, where ordering of fields is unspecified.

If ordering is unspecified I suppose it means that ordering does not matter and that CUE can chose any ordering it wants in its output. Why not chose a default of sorting fields by their keys?
 
> That said, we do aim to tighten the spec to preserve a topological ordering of fields, though. See also #474.

Where can I find a definition of this "topological order"? The terms does not make sense for me, I must have skipped some computer-science class at some point ;-)

**Comment by jlongtine** [comment]
@joulaud My understanding is that "topological order" is related to [topological sorting](https://en.wikipedia.org/wiki/Topological_sorting):

> In computer science, a topological sort or topological ordering of a directed graph is a linear ordering of its vertices such that for every directed edge uv from vertex u to vertex v, u comes before v in the ordering. For instance, the vertices of the graph may represent tasks to be performed, and the edges may represent constraints that one task must be performed before another; in this application, a topological ordering is just a valid sequence for the tasks.

I believe that in the case of CUE, it's related the ordering of fields in the various conjuncts of a value. 

```cue
a: {
  one: 1
  two: 2
  three: 3
}
a: four: 4
a: {
  five: 5
  one: 1
}
```

The various ordering of fields in those conjuncts would impact the final ordering of the fields in the resulting value. I'm not quite sure _how_ that would be impacted, but hopefully that gives a general sense of the idea (which is the best I personally can provide right now 😄 ).

**Comment by myitcv** [comment]
We are doing a tidy up post the [CUE Community Call #1](https://github.com/cue-lang/cue/discussions/1958). I believe this issue is entirely covered by #474. Please let me know if that is not the case.
