### ISSUE TITLE
Validate the existence of fieldA xor fieldB

### ISSUE THREAD

**Issue by ChristianKniep** [cue-lang/cue#1349]
I started with cue-lang and aim to use it to validate YAML. I want either to have a field called `item` or `items`, but not both and I am wondering how I can achieve that...

My cue file looks like this:

```
item?: string
items?: [...string]
```
And I suppose I need to add a check that checks if either of them is set, but not both.
(Writing the issue is almost [rubber duck debugging](https://en.wikipedia.org/wiki/Rubber_duck_debugging) - I might resolve the issue tomorrow already; hope that helps someone else)

### Valid YAML
```yaml
item: abc
```
or
```yaml
items: [abc, cde]
```
### Invalid YAML
```yaml
item: abc
items: [abc, cde]
```

**Comment by seh** [comment]
See the `numexist` builtin function proposed in #822. It's not implemented today, but that's the _intended_ way to cover this case.

**Comment by verdverm** [comment]
You could use the anyOf work around with an upper limit as well.

https://cuetorials.com/patterns/fields/#anyof

The oneOf pattern there may be sufficient for your needs however

```cue
val: {
  { item: string } | { items: [...string] }
}
```

https://cuelang.org/play/?id=gdbxOmzwmMy#cue@export@cue

**Comment by myitcv** [comment]
Thanks for raising this @ChristianKniep 

@seh is right, this is covered in #822 so will close this as a duplicate.
