### ISSUE TITLE
cue: Kind constants not showing in docs

### ISSUE THREAD

**Issue by nyarly** [cue-lang/cue#1350]
I've been translating a `cue gen` tool into a Go program, which has been crucial to keeping performance issues at bay for the moment.

One stumbling block I ran across was that the cue.Kind constants aren't exported. I'm trying to replace an disjunction/defaults structure I got stuck with in order to serialize values to files. Specifically I need to distinguish strings and bytes from stucts and lists. For the moment, I've simply copied the const definition from cue itself, and have a case on `value.Kind()`

I understand the difficulty around exporting or making an ADT stable, but type constants that can be compared to the result of an exported method would be really be handy.

**Comment by antong** [comment]
Just checking that you didn't just miss the exported cue.Kind constants: https://pkg.go.dev/cuelang.org/go/cue#pkg-constants (https://github.com/cue-lang/cue/blob/v0.4.0/cue/types.go#L49):
```
const (
	// NullKind indicates a null value.
	NullKind Kind = adt.NullKind

	// BoolKind indicates a boolean value.
	BoolKind = adt.BoolKind

	// IntKind represents an integral number.
	IntKind = adt.IntKind

	// FloatKind represents a decimal float point number that cannot be
	// converted to an integer. The underlying number may still be integral,
	// but resulting from an operation that enforces the float type.
	FloatKind = adt.FloatKind

	// StringKind indicates any kind of string.
	StringKind = adt.StringKind

	// BytesKind is a blob of data.
	BytesKind = adt.BytesKind

	// StructKind is a kev-value map.
	StructKind = adt.StructKind

	// ListKind indicates a list of values.
	ListKind = adt.ListKind

	// NumberKind represents any kind of number.
	NumberKind = IntKind | FloatKind

	TopKind = adt.TopKind
)
```

These can be used to distinguish between bytes, strings, structs and lists, but did you mean something else?
```
package main

import (
        "fmt"

        "cuelang.org/go/cue"
        "cuelang.org/go/cue/cuecontext"
)

func main() {
        ctx := cuecontext.New()
        root := ctx.CompileString(`
                s: "foo"
                b: 'bar'
                xs: ["x", "x", "x"]
                m: {"pi": 3.14}
        `)
        field, err := root.Fields()
        if err != nil {
                panic(err)
        }
        for field.Next() {
                fmt.Println(field.Label(), "is", kind(field.Value()))
        }
        // Output:
        // s is just a string
        // b is just a sequence of bytes
        // xs is just a list
        // m is just a struct
}

func kind(v cue.Value) string {
        switch v.Kind() {
        case cue.StructKind:
                return "just a struct"
        case cue.ListKind:
                return "just a list"
        case cue.StringKind:
                return "just a string"
        case cue.BytesKind:
                return "just a sequence of bytes"
        default:
                return "something more involved"
        }
}
```

**Comment by myitcv** [comment]
This appears to be an issue in the way that `go doc` (and hence pkg.go.dev) treats constants. Despite the fact that `cue.Kind` is defined as an alias of `adt.Kind`, `go doc` only appears to see the values that are explicitly defined as type `cue.Kind`. This sort of makes sense, and the simple fix is to explicitly mark the constant values in the `cue` package as being of type `Kind`. Fix incoming.

**Comment by myitcv** [comment]
Now fixed as of https://pkg.go.dev/cuelang.org/go@v0.4.1-0.20211103053614-fca61f5bf104/cue#Kind
