### ISSUE TITLE
Arbitrary maps to store parameter

### ISSUE THREAD

**Issue by ChristianKniep** [cue-lang/cue#1366]
**Is your feature request related to a problem? Please describe.**
I would like to add a config field to my YAML that allows to store a string map with arbitrary depth.

**Describe the solution you'd like**

```yaml
field1: string
config:
  <unkown_yaml>
```
As long as it holds correct yaml I want cue to be fine with it.

**Describe alternatives you've considered**
I might use a struct that allows for a value (`string`) or another `[string]: string`. 

**Additional context**
The goal of that field is to allow for custom parameters within a CLI configuration file.

**Comment by verdverm** [comment]
There is likely a solution that can fit your needs, but will depend on what your users will be writing (and by proxy what the input you will be validating will be).

A simple solution might look like this: (https://cuelang.org/play/?id=CmwVCgwPdn7#cue@export@cue)

```cue
import "encoding/yaml"

#config: {  
    field: string
    custom: string
    // delete the '#' to see the value
    #valid: yaml.Unmarshal(custom)
}

config: #config & {
    field: "foo"
    custom: """
    a:
      b: c
    """
}
```

Here we are using a definition to act as a validating field which is not output. Users are writing Yaml as a string inside CUE. In a more complex setup, this string can come from outside of CUE and be added during validation.


Can you clarify or expand on the UX you are looking for?

**Comment by antong** [comment]
Perhaps you are looking for something like the following?
```
#schema: {
    field1: string
    config: {...}
}
```

**Comment by mpvl** [comment]
Or just use `_`, for "any" value?

**Comment by ChristianKniep** [comment]
Cool, `{...}` worked just fine. Thanks!
