### ISSUE TITLE
cmd/cue: import command with stdin unexpected behavior

### ISSUE THREAD

**Issue by b4nst** [cue-lang/cue#1367]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version 0.4.0 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What did you do?

```shell
> echo 'hello: world' | cue import yaml -
hello: reference "world" not found:
    -:1:8
```

### What did you expect to see?
Either import success or import not being able to take stdin

### What did you see instead?
```shell
hello: reference "world" not found:
    -:1:8
```
If I'm using `cue` syntax, I get no error, but no import generated either:
```shell
echo 'hello: "world"' | cue import yaml -
```

May relate to #116

**Comment by antong** [comment]
That is importing in CUE format. Try `cue import yaml: -`  instead.

**Comment by b4nst** [comment]
Thanks, it works! Shouldn't we properly document the use of the column? I couldn't find that anywhere (but maybe that's me not looking well).

**Comment by myitcv** [comment]
@b4nst see `cue help filetypes`. I'll close this for now - but please shout if anyone disagrees.
