### ISSUE TITLE
Add an option to quote all strings in YAML

### ISSUE THREAD

**Issue by ksamuel** [cue-lang/cue#1368]
Currently, exporting to YAML is a mine field, because most things well defined as strings in a CUE file will be exported unquoted in YAML.

Of course, because YAML interprets magically most unquoted things, this leads to plenty of issues. E.G:

- dates can be wrongly interpreted: https://github.com/cue-lang/cue/issues/1076
- the norway problem: https://hitchdev.com/strictyaml/why/implicit-typing-removed/
- the python 3.10 problem: https://github.com/actions/setup-python/issues/160

I think quoting all the strings in the resulting YAML should be the default behavior. However, this would probably cause a lot of troubles now that the old behavior is used everywhere.

Alternatively, a nice solution would be to provide an option to force cue to quote everything. This option could be turned on with either:

- a cli --flag
- an env var
- a directive in the cue file

**Comment by mpvl** [comment]
Cue should indeed always expiry valid yaml.

I agree always quoting strings is better than not outputting correct yaml.

Perhaps adding a check that reads back stings from yaml to determine if it still parses correctly may be an option. 

One issue with this is that the yaml semantics changes in backwards incompatible ways. For instance, "no" is no longer interpreted as a bool in yaml v1.2.

Another issue is that one can have custom types in yaml to customize interpretation. 

Ultimately, to ensure predictable behavior, we should record the yaml version and perhaps customizations at the cue module level.

**Comment by mpvl** [comment]
I'm personally less a fan of command line flags for this purpose, and even less of environment variables. But file-level directives to override module settings makes sense. 

Note that CUE currently uses YAML 1.2. So some of the issues you mentioned may be related to that.

**Comment by mpvl** [comment]
@ksamuel  Do you have a concrete example where things fail?

**Comment by ksamuel** [comment]
*CUE doesn't export invalid YAML, and this is not what this ticket is about.*

The problem is rather than YAML is a format with plenty of gotchas, such as fuzzy interpretation of data types, and that CUE is useful because it makes sane design decisions.

Unfortunately, CUE generates YAML without quoting strings, which means we output data in YAML that may be interpreted differently by a YAML parser than what we had initially in a CUE file. 

E.G:

Given the following CUE file:

```
country_code:  "NO"
port_mappings: "3333:33"
```

The `cue export -out yaml` command will outputs:

```
country_code: NO
port_mappings: 3333:33
```

Lots of YAML parsers will load such a file  as:

```
{'country_code': False, 'port_mappings': 200013}
```

**Not** as you would expect:

```
{'country_code': "NO", 'port_mappings': "3333:33"}
```

This is not because CUE is broken, but because the YAML spec is. It specifies that some values, if unquoted, can be magically interpreted as something else than a string.

To avoid this pitfall, *CUE should quote all strings when exporting to YAML*, and produce instead:

```
country_code: "NO"
port_mappings: "3333:33"
```

Which will have no risk of being wrongly interpreted.

Now regarding:

> I'm personally less a fan of command line flags for this purpose, and even less of environment variables. But file-level directives to override module settings makes sense.

This is convenient, but will let some users exposed to the problem. Indeed, you may use CUE to produce YAML from a CUE file that is not under your control. In that case, it would be inconvenient to expect one to edit such a file in order to get a non broken export. A CLI flag helps with this use case.

The env var settings helps in the case you want this export option to be the default for all your teams. You can't enforce easily to add an instruction in all cue files now and in the future, but you can easily provide an one time setup for env var for everyone.

Finally, the instruction in the file is also useful, because this way one can provide a file with the guaranty the export matches the author expectations.

All 3 switches are useful, because they don't address the same use case.

Alternatively, you can decide to not provide the switch at all, make the sane behavior the default behavior, with the risk that somebody rely somewhere on the existing buggy behavior.

**Comment by mpvl** [comment]
> CUE generates YAML without quoting strings

It should quote strings if reading it back would not be a string. For instance, `no` is not interpreted as `false` in YAML 1.2, which is what CUE supports.

But granted, it all depends on which schema a given YAML parser uses, so exporting strings as quoted is a safer option. Then users could perhaps specify a YAML schema to export to a different format. And this is aside from the notable incompatibilities between YAML parsers (http://matrix.yaml.io/).

Env variables are messy, but a command line option could specify the output format (yaml12core, yaml12json, yaml11, etc) perhaps.

**Comment by ksamuel** [comment]
Well, if you quote something in a CUE file, you are explicitly stating "this is a string". Therefor, there is no downside, and in fact it would be logical given the nature of making cue a sane configuration language, to output explicit strings in any format.

In fact, is there any benefit, outside of the better aesthetic (which is, I assume, not a priority over correctness) to not quote strings in all cases, no matter the format ? Asking that the output enforces the type you encoded in your schema seems like exactly what one would want from a tool that claims on its home page to "Be in control of your data".

**Comment by mpvl** [comment]
@niemeyer, @ksamuel:

As a first stab, I've implemented a much more aggressive quoter that quotes all strings that I could find in the YAML tag registry (i.e. YAML 1.1 strings that are no longer supported). This is a more aggressive algorithm than the go-yaml.v3 package. The idea is that as long as any value with a special meaning in YAML 1.1 is quoted, this should give compatibility with all the legacy YAML parsers.

I suggest we see how far this gets us. I'll keep this Issue open for now. In the long run I can imagine quoting all strings, as you suggested, unless a specific YAML version is defined.

https://review.gerrithub.io/c/cue-lang/cue/+/527375

**Comment by ksamuel** [comment]
Alright, I you need met to help with testing, I'll allocate some company time for that.

**Comment by mpvl** [comment]
BTW, one observation: quoting all strings also means quoting map keys. At that point, you might as well export everything as JSON.

**Comment by niemeyer** [comment]
@mpvl As you noted, SetString is typically the answer. It does the job of quoting when required, and also a few other things such as using the literal style when it's a multi-line string. Otherwise, one may freely manipulate the Style field as desired.

**Comment by ksamuel** [comment]
Having the default value not produce a pitfall instead of requiring the user to know about it and opt in might be preferable though.

**Comment by niemeyer** [comment]
@ksamuel Is that a reply to what I just said?  Sorry, I'm a bit confused as it seems a bit lost in context.

**Comment by ksamuel** [comment]
@niemeyer: apologies, I misread and though you were suggesting the end user should be calling some function in the CUE file to ensure proper quoting.

**Comment by niemeyer** [comment]
@ksamuel Ah, no worries. No, I was indeed referring to the SetString method in the intermediate Node representation in go-yaml.  Even there, this is not typically seen by normal usage, but rather only when fiddling with the representation.

**Comment by ksamuel** [comment]
@mpvl : well, one import use case for CUE is to only have one cue file, and to be able to export it to a variety of formats. One can have plenty of systems that only accept yaml, and have the choice of the export format, but that's what's great about CUE: they don't have to know about it :)

In fact, I always assumed exported files from CUE are seldom edited manually and mostly consumed by machines.

**Comment by mpvl** [comment]
@ksamuel: note that YAML is a superset of JSON, so the safest way to pass CUE to a YAML application is always to pass it as JSON.

I do think it makes sense, though, to quote all strings that were "special" in YAML 1.1 unconditionally, as it indeed seems that use of YAML 1.1 is still relatively commonplace. That's what that CL does.

**Comment by niemeyer** [comment]
@mpvl That's what the go-yaml package is supposed to do as well when you use SetString or when marshaling strings via the higher level APIs. The harder bit is on the reading side, as we need to pick which interpretation of the data to give when it's unquoted. For example, with version 1.1 of the spec `yes`, `no`, `on`, and `off` are valid booleans, while 1.2 restricts it to `true` and `false`, which seems like a good idea but incompatible.

On the go-yaml side, v2 has the 1.1 interpretation, and in go-yaml v3 I've bridged over by still accepting the old values as correct booleans when the type on the Go side hints that this is the desired interpretation, but when there are no hints these are taken as plain strings. On the way out when these values are used as strings they remain quoted to prevent misinterpretation by older parsers.

**Comment by ksamuel** [comment]
@mpvl: true, I haven't though of it that way. Worst case scenario, it's a handy workaround.

**Comment by mpvl** [comment]
@niemeyer: 
> That's what the go-yaml package is supposed to do as well when you use SetString or when marshaling strings via the higher level APIs.

It doesn't seem to do so. For `SetString` it does less then for marshaling, and neither implement the `v1.1` compatibility.  Either way, I've implemented it manually now. Maybe this was only supported in a later version?

> The harder bit is on the reading side

That is fine. CUE reads YAML v1.2, which is not hard, just a matter of choice. 

>  I've bridged over by still accepting the old values as correct booleans when the type on the Go side hints that this is the desired interpretation, but when there are no hints these are taken as plain strings

Ah yes, I could do that in CUE as well. This used to not be possible, but now it is, as it was necessary for protobuf support, which cannot be  interpreted without their schema. (Even text proto cannot be interpreted without a schema!!!)

**Comment by mpvl** [comment]
@niemeyer: a later version indeed seems to convert more strings. However, it still doesn't escape map keys as I would expect.

**Comment by mpvl** [comment]
Since I haven't heard anything, I'm assuming the latest changes are sufficient.

Closing for now but feel free to reopen.

**Comment by ksamuel** [comment]
I just tried it, and yes, it looks great.

Thanks a lot.
