### ISSUE TITLE
internal/core/adt: Go API ADT access: get BoundValue for a field with specified bounds

### ISSUE THREAD

**Issue by snassr** [cue-lang/cue#1374]
**Describe the solution you'd like**
For example:
If the schema contains `num_range: >0 & <100`
It would be great if one could get the bounds for that field, something that ultimately results in the following:
```
cue.Value().BoundValue().Bottom() == 0
cue.Value().BoundValue().Top() == 100
```

**Describe alternatives you've considered**
At the moment I convert value to a string and parse out the bounds
```v.Value() == >0 & <100```

Alternatively, another user suggested using the v.Value().Syntax() and parse the bounds from there.

Go API Access to the ADT is a suggested solution. The solution likely helps other cases where access to the ADT is required for value specifications.
https://pkg.go.dev/cuelang.org/go@v0.4.0/internal/core/adt#BoundValue

**Additional context**
slack chat: [https://cuelang.slack.com/archives/CLT3ULF6C/p1636567804079700](https://cuelang.slack.com/archives/CLT3ULF6C/p1636567804079700)

**Comment by myitcv** [comment]
Thanks for raising, @snassr 

Whilst the `internal/core/adt` might well offer a better API here, everything you want to do today is possible using the existing `cue` API. 

```
go mod tidy
go run main.go
cmp stdout stdout.golden

-- go.mod --
module mod.com

go 1.16

require cuelang.org/go v0.4.0

-- main.go --
package main

import (
	"fmt"
	"log"

	"cuelang.org/go/cue"
	"cuelang.org/go/cue/cuecontext"
)

const cueStr = `
num_range: >0 & <100
`

func main() {
	ctx := cuecontext.New()
	v := ctx.CompileString(cueStr)
	num_range := v.LookupPath(cue.ParsePath("num_range"))

	// Extract the & op
	andop, args := num_range.Expr()
	assertOp(andop, cue.AndOp)

	// cue.AndOp is a binary operator
	lhs, rhs := args[0], args[1]

	// Extract the < op
	gt, args := lhs.Expr()
	assertOp(gt, cue.GreaterThanOp)

	// cue.GreaterThanOp is a unary operator
	gtBound := args[0]

	lt, args := rhs.Expr()
	assertOp(lt, cue.LessThanOp)

	// cue.LessThanOp is a unary operator
	ltBound := args[0]

	fmt.Printf("lower bound: %v, upper bound: %v\n", gtBound, ltBound)
}

func assertOp(got, want cue.Op) {
	if got != want {
		log.Fatalf("expected op %v; got %v", got, want)
	}

}
-- stdout.golden --
lower bound: 0, upper bound: 100
```

That said, I have just raised to https://review.gerrithub.io/c/cue-lang/cue/+/527238 to make clearer the fact that whilst `cue.Op` aliases `adt.Op`, all the values defined by the latter are accessible via the former's API. 

As such I will close this issue because there isn't anything specific other than the broader "consider exposing the `adt` package" we are already aware of and considering.

**Comment by myitcv** [comment]
That CL is now merged, and the `cue.Op` docs now correctly reflect the const values of that type:

https://pkg.go.dev/cuelang.org/go@v0.4.1-0.20211112113036-72936e4358e2/cue#Op
