### ISSUE TITLE
Nested for loop caused unexpected conflict values error

### ISSUE THREAD

**Issue by chaodaiG** [cue-lang/cue#1375]
### What version of CUE are you using (`cue version`)?

4.0
### Does this issue reproduce with the latest release?

Yes, got it from Cue playground https://cuelang.org/play/?id=tBroDr3dFU6#cue@export@yaml

### What did you do?

```
[
    for tag in ["tag"] {
        "--tag=b/c:\(tag)",
        for postfix in ["postfix"] {
            "--tag=b/c:\(tag)-\(postfix)",
        }
    }
]
```

### What did you expect to see?

```
- --tag=b/c:tag
- --tag=b/c:tag-postfix
```

### What did you see instead?

```
failed to encode: 0: conflicting values "--tag=b/c:tag-postfix" and "--tag=b/c:tag"
```

However this works:
```
[
    for tag in ["tag"] {
        "--tag=b/c:\(tag)",
    }
    for postfix in ["postfix"] {
        "--tag=b/c:tag-\(postfix)",
    }
]
```

**Comment by mpvl** [comment]
That is correct. Nesting the loop in the first form has the effect of embedding another value within the same struct. You should consider the curly braces to be the scope of a single value.
