### ISSUE TITLE
Releases Should have checksums

### ISSUE THREAD

**Issue by nathanjsweet** [cue-lang/cue#1382]
Downloading a tar file from the releases page without a corresponding checksum file is frightening :fearful: . Maybe you could make them as part of your release process?

**Comment by verdverm** [comment]
https://github.com/cue-lang/cue/releases/download/v0.4.0/checksums.txt

**Comment by myitcv** [comment]
@nathanjsweet as @verdverm linked we already have the checksums included as part of our release assets so I believe this issue can be closed. Please do reply in case we've misunderstood.
