### ISSUE TITLE
cmd/cue: better document -l flag

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#1386]
Follow-up to https://github.com/cue-lang/cue/issues/1352.

The `-l` flag is not clearly documented as only applying to non-CUE files.

Also `cue help flags` has an outdated reference to the `::` syntax.

**Comment by mpvl** [comment]
> The -l flag is not clearly documented as only applying to non-CUE files.

at the top of the file, it does mention these flags are supposed to be for non-CUE files.
