### ISSUE TITLE
playground: WASM fails to load

### ISSUE THREAD

**Issue by verdverm** [cue-lang/cue#1392]
The WASM never loads

![image](https://user-images.githubusercontent.com/1390600/142665110-d0a84330-0ad9-4a5e-9706-b03d52e01163.png)

**Comment by jlongtine** [comment]
Seeing the same thing, @verdverm + @myitcv.

**Comment by myitcv** [comment]
Thanks for the report. Investigating.

**Comment by myitcv** [comment]
Analysis: this appears to be entirely Go-version related, specifically in the move to 1.17. Bisecting.

**Comment by myitcv** [comment]
Temporarily fixed via https://github.com/cue-lang/cuelang.org/commit/38a8ea46af8c0d1dd912580f32e682ab2c0481fb. Bisecting the Go bug related to this.

**Comment by rogpeppe** [comment]
Looks like this was fixed by https://github.com/cue-lang/cuelang.org/pull/207, so closing.
