### ISSUE TITLE
Some attributes do not appear to accumulate during unification via the Go API

### ISSUE THREAD

**Issue by sdboyer** [cue-lang/cue#1393]
### What version of CUE are you using (`cue version`)?

`v0.4.0`

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```go
package main

import (
	"fmt"

	"cuelang.org/go/cue"
	"cuelang.org/go/cue/cuecontext"
)

const src = `
base: "foo" @base(attr)

refwithout: base
refwith: base @attr(refwith)

s: {
	refwithout: base
	refwith: base @attr(srefwith)
}

unif: string @attr(unif)
sunif: {
	@sunif(decl)
	...
} @sunif(field)
`

func main() {
	ctx := cuecontext.New()

	v := ctx.CompileString(src)

	base := v.LookupPath(cue.ParsePath("base"))
	refwithout := v.LookupPath(cue.ParsePath("refwithout"))
	refwith := v.LookupPath(cue.ParsePath("refwith"))
	s := v.LookupPath(cue.ParsePath("s"))
	unif := v.LookupPath(cue.ParsePath("unif"))
	sunif := v.LookupPath(cue.ParsePath("sunif"))

	printAttrs("base", base)
	printAttrs("refwithout", refwithout)
	printAttrs("refwith", refwith)
	printAttrs("s.refwithout", s.LookupPath(cue.ParsePath("refwithout")))
	printAttrs("s.refwith", s.LookupPath(cue.ParsePath("refwith")))
	printAttrs("base & unif", base.Unify(unif))
	printAttrs("sunif", sunif)
	printAttrs("s & sunif", s.Unify(sunif))
	printAttrs("(s & sunif).refwithout", s.Unify(sunif).LookupPath(cue.ParsePath("refwithout")))
	printAttrs("(s & sunif).refwith", s.Unify(sunif).LookupPath(cue.ParsePath("refwith")))
}

func printAttrs(name string, v cue.Value) {
	fmt.Printf("ATTRS FOR: %s\n", name)
	for _, a := range v.Attributes(cue.ValueAttr) {
		fmt.Printf("\tNAME: %s\n", a.Name())
		fmt.Printf("\tCONTENTS: %s\n", a.Contents())
	}
	fmt.Println()
}

```

### What did you expect to see?

The spec [says that](https://cuelang.org/docs/references/spec/#attributes) attributes accumulate during unification, but this appears to only be the case for decl attributes.

So, i expect something like this:

```
ATTRS FOR: base
	NAME: base
	CONTENTS: attr

ATTRS FOR: refwithout
	NAME: base
	CONTENTS: attr

ATTRS FOR: refwith
	NAME: base
	CONTENTS: attr
	NAME: attr
	CONTENTS: refwith

ATTRS FOR: s.refwithout
	NAME: base
	CONTENTS: attr

ATTRS FOR: s.refwith
	NAME: base
	CONTENTS: attr
	NAME: attr
	CONTENTS: refwith

ATTRS FOR: base & unif
	NAME: base
	CONTENTS: attr
	NAME: attr
	CONTENTS: unif

ATTRS FOR: sunif
	NAME: sunif
	CONTENTS: field
	NAME: sunif
	CONTENTS: decl

ATTRS FOR: s & sunif
	NAME: sunif
	CONTENTS: decl

ATTRS FOR: (s & sunif).refwithout
	NAME: base
	CONTENTS: attr

ATTRS FOR: (s & sunif).refwith
	NAME: base
	CONTENTS: attr
	NAME: attr
	CONTENTS: srefwith
```

### What did you see instead?

The only attribute that appeared to actually accumulate through unification was the `@sunif(decl)` attribute on the `sunif` struct. Everything else is only the (value) attributes declared directly on the fields.

```
ATTRS FOR: base
	NAME: base
	CONTENTS: attr

ATTRS FOR: refwithout

ATTRS FOR: refwith
	NAME: attr
	CONTENTS: refwith

ATTRS FOR: s.refwithout

ATTRS FOR: s.refwith
	NAME: attr
	CONTENTS: srefwith

ATTRS FOR: base & unif

ATTRS FOR: sunif
	NAME: sunif
	CONTENTS: field
	NAME: sunif
	CONTENTS: decl

ATTRS FOR: s & sunif
	NAME: sunif
	CONTENTS: decl

ATTRS FOR: (s & sunif).refwithout

ATTRS FOR: (s & sunif).refwith
	NAME: attr
	CONTENTS: srefwith
```

**Comment by verdverm** [comment]
As I recall, this is expected behavior for FieldAttrs, they do not pass through references.

The example given by @mpvl to me was Protobuf inspired

```cue
foo: int @protobuf(1,int)

st: {
  a: string @protobuf(1,string)
  f: foo @protobuf(2,int)
}
```

If it passed through, then you would have a conflict for the `1` position between fields, and a field with two position values.

It is worth pointing out that FieldAttrs do pass through unification like this:

```cue
$ cat attr.cue 
a: {
        foo: string @attr(a)
}

b: bar: string @attr(b)

c: a & b

$ cue eval -A attr.cue 
a: {
    foo: string @attr(a)
}
b: {
    bar: string @attr(b)
}
c: {
    foo: string @attr(a)
    bar: string @attr(b)
}
```

---

Most likely the spec needs to be updated.

**Comment by sdboyer** [comment]
Hmm, reference vs. unification distinction is interesting. It appears that my goal of making a clearer illustration of the underlying problem, i may have obscured the actual behavior i was seeing - which does indeed appear to contradict this assertion:

> It is worth pointing out that FieldAttrs do pass through unification

i'll work on a new repro that illustrates the problem - though also, my concern here is with what the Go API returns, not with what `cue eval` produces.

**Comment by verdverm** [comment]
> my concern here is with what the Go API returns, not with what cue eval produces

They should be the same. If they are not, that is an issue

**Comment by sdboyer** [comment]
Verified, they are indeed the same! I'm gonna close this.

I'm still seeing an issue where an [interstitial unification](https://github.com/grafana/grafana/blob/8b95746f6376caf305223abb3e3f3906719f4605/pkg/cmd/grafana-cli/commands/cuetsify_command.go#L212) of [a schema](https://github.com/grafana/grafana/blob/main/public/app/plugins/panel/text/models.cue#L20-L30) with its [attribute-declaring meta-schema](https://github.com/grafana/grafana/blob/8b95746f6376caf305223abb3e3f3906719f4605/cue/scuemata/panel-plugin.cue#L9-L18) causes _some_ difference that affects attribute-governed output vs. when i put the attributes directly on the schema. But until i have a more isolated repro, i'm happy to blame it on sloppiness in our implementation in cuetsy. Which is, indeed, quite sloppy.
