### ISSUE TITLE
tools/flow: get final flow value

### ISSUE THREAD

**Issue by eonpatapon** [cue-lang/cue#1394]
Related to #1390

After a flow has been run I'd like to retrieve the "final" value that has been updated by the flow.

This can be useful for validation, using the values for other processing etc...

Unless I'm mistaken there is no API to retrieve the value. While most methods in the cue API take a `Value` and return a `Value` it's not the case with `flow.Run`.

@verdverm suggested that `TaskFunc` is receiving the final value at the end of the flow, so that's a way to retrieve the final value. However it seems to me that's due on how the values are walk down and passed to `TaskFunc`. This implementation might change and might not yield values like it is now.

I think it would be best to make `flow.Run` return the final value. But this breaks the current API (although I think the go API is not stable yet and can still be changed at this point).

Thoughts?

**Comment by verdverm** [comment]
One thing that just occurred to me, if we have tasks

A->B and A->C

Which is the last task? Afiak, flow is non deterministic in this sense, or that we might not know which is the last. That being said, this would seem to apply to my suggestion or your proposed returned final value. The TaskFunc method would leave more up to the user. Both ought to have consistent "final" result, the unified value after the last time TaskFunc runs, which seems to be set after all tasks have completed. Consistent as can be, given the external world constraints.

**Comment by mpvl** [comment]
I guess one backwards-compatible way to expose the value is to provide it as a method on `Controller` and declare it to be only valid after `Run` returns. That seems like a reasonable change.

I'm currently also working on a new cycle-detection algorithm which would remove any scratch fields from `Value` (or rather the internal `Vertex` and `Environment`), which would make it safe for concurrent reading. That means that in the future it would be possible to ask for the current `Value` even as a flow is processing. So arguably the backwards-incompatible API is also the most-desirable API, as there would be just one way to get the current `Value`.

**Comment by eonpatapon** [comment]
Adding a new method to retrieve the value works for me. 

Should we panic if the flow is not terminated ? This could be removed when the value is safe for concurrent reading ? But I guess writing would not be safe...

**Comment by jlongtine** [comment]
Having access to the value after `Run` returns would be helpful for the @dagger team. And we'd really love to have concurrent read access to the value during the run when that cycle detection algorithm update drops.

**Comment by mpvl** [comment]
I agree Panicing when it is not terminated is a good idea and allows for a clear transition to allowing it later.

The public API (`Value`) will always be read-only. Even `Fill` will just create new values. Right now this means everything is recomputed. In the future we want to do this incrementally. This model allows for fairly straightforward use of concurrency to the user.

The problem now is that even if a read-only value is mixed into a computation, it's underlying structures are temporarily modified during computation. Once this is removed, concurrency can become a lot easier.

**Comment by mpvl** [comment]
@jlongtine And reason you mention `Run` returning a `Value` versus a `Controller.Value` method?

**Comment by verdverm** [comment]
@mpvl I've done both like so: https://github.com/hofstadter-io/cue/commit/872db7b67672317c968c0fb6434beb24e82a7a91#diff-84e6cd356efdeb1aba444c8b036efcd3be2ede24b6981fddac334d5e58e450e3

Any reason to not have both? I think people are used to functions returning results and errors together

**Comment by mpvl** [comment]
@verdverm The obvious reason to not do both is that changing `Run` is a backwards incompatible change. I know we are not at v1 yet, but that doesn't mean one should break people gratuitously.

Also, I like the `Value` method on `Controller` better, in a way. I suspect that only a minority of users will care about the final value of the entire configuration.

**Comment by jlongtine** [comment]
> @jlongtine And reason you mention `Run` returning a `Value` versus a `Controller.Value` method?

@mpvl Sorry if it wasn't clear. I just meant being able to access it via `Controller.Value()` _after_ `Run` ends/returns, not returning it via `flow.Run` specifically.
