### ISSUE TITLE
cmd/cue: multiline yaml string causes odd import formatting

### ISSUE THREAD

**Issue by rogpeppe** [cue-lang/cue#1396]
commit 9217c4d0b6f86ba942e66ea6049e1517e43a7fdf

The example below formats strangely when using `cue import`.
The field names and values seem to get out of sync, e.g.

```
		b:
			"y", c:
			"x"
```
This behaviour doesn't happen when using `cue export` on the same file 
(I'd expect them to produce the same result).

Changing the contents of the multiline string (e.g. removing the trailing hyphen on the first line) changes the behaviour.

I saw this behaviour happen a lot in a real world import example.

```
exec cue import x.yml
exec cue export --out cue x.yml -o x-export.cue
cmp x.cue x-export.cue

-- x.yml --
x:
  d: |
   xxxxxxxxxxxx –
   xxxxxxxxx – xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
   xxxxxxxxxxxx – xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
   xxxxxxxxxx – xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

  p:
    - b: y
      c: x
```

Maybe related to #826.

**Comment by uhthomas** [comment]
Duplicate of #826

**Comment by mvdan** [comment]
Thanks, @uhthomas. For those not following along like me, Roger's example above uses non-ASCII unicode dashes, `U+2013`, hence it's #826 as it relates to bad positions and formatting with multi-byte characters in YAML.

**Comment by uhthomas** [comment]
This seems to be caused by the `–` (U+2013) character which is _not_ the ASCII `-` (U+002d).
