### ISSUE TITLE
cmd/cue: unhelpful "cycle error" message on incomplete value

### ISSUE THREAD

**Issue by rogpeppe** [cue-lang/cue#1407]
commit 9e7d4d63acf9cfcf7fdc33731dedfe420c0e2689

To reproduce, run `cue export` on the following CUE code:

```
foo: [_]: {
	entries: [_]: bool
	#ID: "\(string)"
}
foo: bar: entries: (foo.baz.#ID): true
foo: baz: {}
```

This produces the rather unhelpful error:
```
cycle error
```

Firstly there's no cycle in this code, just an incomplete value.
Secondly, the error doesn't print any identifying information to help
diagnose where the issue was encountered, such as path or file/line numbers.

**Comment by rogpeppe** [comment]
Here's a simpler example:

```
! exec cue vet -c main.cue
cmp stderr expect-stderr
-- main.cue --
a: {}
b: a.x != ""
if b {
}
-- expect-stderr --
b: undefined field: x:
    ./main.cue:2:6
```

This should pass (or at least produce some similar error), but instead it fails, printing just "cycle error"
as a failure, which is deeply unhelpful when dealing with large configurations.

```
> ! exec cue vet -c main.cue
[stderr]
cycle error
[exit status 1]
> cmp stderr expect-stderr
--- stderr
+++ expect-stderr
@@ -1,1 +0,0 @@
-cycle error
@@ -0,0 +1,2 @@
+b: undefined field: x:
+    ./main.cue:2:6

FAIL: /tmp/testscript3622712173/x.txtar/script.txtar:2: stderr and expect-stderr differ
```

Thanks to Yusan Kurban (@yusank) on the CUE Slack for providing the origin of the above example.

**Comment by mpvl** [comment]
@myitcv Any reason to add this to v0.5.0? Was this a regression since the last release?
