### ISSUE TITLE
Cue context should be able to have an independent index

### ISSUE THREAD

**Issue by leejanee** [cue-lang/cue#1414]
**Is your feature request related to a problem? Please describe.**

When using `cuelang` on the server side , the program needs to execute `cue file` continuously and concurrently, but now cue context use the shared index , and it is currently not thread-safe. 

**Describe the solution you'd like**

Cue context should be able to have an independent index. Actually you should use the same context if want to share the index.
```
import "cuelang.org/go/cue/cuecontext"

ctx:=cuecontext.New()
```
**Describe alternatives you've considered**

The `sharedIndex` is not concurrently safe, the following errors will occur.
![image](https://user-images.githubusercontent.com/74582607/144807289-c170950c-6be6-45bf-8486-3ab730ff0c07.png)

**Additional context**

**Comment by myitcv** [comment]
We have just cut https://github.com/cue-lang/cue/releases/tag/v0.4.1-rc.1 with a fix for this. 

Please test and let us know how you get on.
