### ISSUE TITLE
`--inject-vars` does nothing

### ISSUE THREAD

**Issue by pblkt** [cue-lang/cue#1416]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version 0.4.0 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes.

### What did you do?

```
➜ cat tmp.cue
a: string @tag(user)
➜ cue eval --concrete tmp.cue --inject user=cucumber
a: "cucumber"
➜ cue eval --concrete tmp.cue --inject-vars
```
### What did you expect to see?
```
a: "myusername"
```

### What did you see instead?
```
a: incomplete value string
```

**Comment by verdverm** [comment]
See the end of `cue help injection`

There are a limited set of injected variables with specific names.

You probably need something like `a: string @tag(user,var=username)`. This worked for me

**Comment by pblkt** [comment]
That did the trick, thanks!
