### ISSUE TITLE
Regression: disjuncts sometimes behave like conjuncts

### ISSUE THREAD

**Issue by extemporalgenome** [cue-lang/cue#1417]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.4.1-beta.6 darwin/amd64
</pre>

(also _fails_ in `v0.4.0` and `v0.3.0`, but `v0.2.2` _works as expected_)

### Does this issue reproduce with the latest release?

Yes

### What did you do?

https://cuelang.org/play/?id=WNVN_l84ouV#cue@export@cue

`disj-bug.cue`:
```cue
#ID: !~"^a" | =~"^ab$" | =~"^aB$"
#ID: =~"^a" | !~"[A-Z]"

IDExamples: [...#ID]
IDExamples: [
  "xyz",
  "ab",
  "aB",
]
```

### What did you expect to see?

Something similar to...

```
> cue-v0.2.2 eval disj-bug.cue
#ID: !~"^a" & =~"^a" | !~"^a" & !~"[A-Z]" | =~"^ab$" & =~"^a" | =~"^ab$" & !~"[A-Z]" | =~"^aB$" & =~"^a" | =~"^aB$" & !~"[A-Z]"
IDExamples: ["xyz", "ab", "aB"]
```

### What did you see instead?

```
> cue version
cue version v0.4.1-beta.6 darwin/amd64
> cue eval disj-bug.cue
IDExamples.1: 1 errors in empty disjunction:
IDExamples.2: 2 errors in empty disjunction:
IDExamples.1: invalid value "ab" (out of bound !~"^a"):
    ./disj-bug.cue:1:6
    ./disj-bug.cue:7:3
IDExamples.2: invalid value "aB" (out of bound !~"^a"):
    ./disj-bug.cue:1:6
    ./disj-bug.cue:8:3
IDExamples.2: invalid value "aB" (out of bound !~"[A-Z]"):
    ./disj-bug.cue:2:15
    ./disj-bug.cue:8:3
```

CUE v0.2.2 normalizes this definition into a very verbose form, but does behave as expected.

CUE v0.3.0 and later have a cleaner normalization (essentially it maintains something close to the input when running `def` or `eval`), yet appears to have a logically inconsistent way of evaluating constraints of the form shown in the CUE source above.

In the first error: `invalid value "ab" (out of bound !~"^a")`, CUE seems to be ignoring that `!~"^a"` is in a disjunction with `=~"^ab$"` (even though one of the disjuncts does not validate, the other does, thus the entire disjunct _should_ validate against `"ab"`).

The second error has the same issue as the first (same disjunct, wherein `=~"^aB$"` should clearly match, making the entire disjunction validate).

The third error applies to line 2: while `"aB"` does not validate against `!~"[A-Z]"`, it _should_ validate against the other constraint in the disjunction, `=~"^a"`, thus the entire disjunction, again, should validate because at least one of the disjuncts should succeed.

If I copy the denormalized definition output for #ID back into the CUE source, and use that instead, v0.4.1-beta.6 does succeed. The v0.2.2 denormalization does appear to be logically equivalent to the original constraints I specified.

Unquantified observations follow:

It does seem as though v0.3.0 and later do have some order dependence in some corner cases (not reproducible in the code for this issue), such that I have been able to copy-paste reorder disjuncts within a single line and get CUE to report a different "example" value as failing to validate compared to the other, should-be-logically-equivalent ordering.

It also appears that CUE error reporting/validation can get pathological in some cases (such as above), where disjuncts behave as though they were conjuncts.

**Comment by extemporalgenome** [comment]
Running `git bisect` leads to [0e401d66c8e5a7e64c667dfa64004cadca7cb871](https://github.com/cue-lang/cue/commit/0e401d66c8e5a7e64c667dfa64004cadca7cb871) as the commit that introduced this regression.

The command was (from cue repo root):

```
git bisect run sh -c 'go build -o cue.bin ./cmd/cue && ./cue.bin eval ~/src/sandbox/cue/2021-12.disj-bug/disj-bug.cue'
```

The bisect log is:
```
git bisect start
# good: [94db2eb171e7934e5d773d275bfe0d7558333c56] cmd/cue/cmd: include unexported constants for get go
git bisect good 94db2eb171e7934e5d773d275bfe0d7558333c56
# bad: [447606047bdd32f79029a4be5424af3a09ea15f2] cmd/cue/cmd: load import dependencies of tool files
git bisect bad 447606047bdd32f79029a4be5424af3a09ea15f2
# good: [e7e27e00355c32945da729f76875900dcdcfab7d] internal/core/export: allow showing recursive errors.
git bisect good e7e27e00355c32945da729f76875900dcdcfab7d
# bad: [6c3be7f896cf0a47d09b3aa59724764454b7e948] doc: fix typo in types tutorial (closed -> close)
git bisect bad 6c3be7f896cf0a47d09b3aa59724764454b7e948
# good: [9eee235e97eed8106cb11acba226967e55904ed0] internal/core/adt: remove special "tentative" mode
git bisect good 9eee235e97eed8106cb11acba226967e55904ed0
# bad: [9c5489fc66edf789372390847d4c3e10f047a005] internal/core/adt: fix memory leak
git bisect bad 9c5489fc66edf789372390847d4c3e10f047a005
# good: [826bd7bd782889a15bb8d1016d89cbaba2210855] internal/core/adt: fix regression in close builtin
git bisect good 826bd7bd782889a15bb8d1016d89cbaba2210855
# good: [08e814f8e10192d5443991ca8f13b2e4de02b837] internal/core/adt: add support info for trim
git bisect good 08e814f8e10192d5443991ca8f13b2e4de02b837
# good: [a8de61c6d5ede0ac2009371ac310a41fd374cd00] cue/testdata/cycle: fix another cycle bug
git bisect good a8de61c6d5ede0ac2009371ac310a41fd374cd00
# good: [0f570a9015a1e2abf460dffd0f1c7ea97d85a5db] internal/core/validate: pick up non-concrete values in defaults
git bisect good 0f570a9015a1e2abf460dffd0f1c7ea97d85a5db
# bad: [0e401d66c8e5a7e64c667dfa64004cadca7cb871] internal/core/adt: fix performance issue with disjunctions
git bisect bad 0e401d66c8e5a7e64c667dfa64004cadca7cb871
# first bad commit: [0e401d66c8e5a7e64c667dfa64004cadca7cb871] internal/core/adt: fix performance issue with disjunctions
```

**Comment by extemporalgenome** [comment]
Discussion at https://cuelang.slack.com/archives/CLT3ULF6C/p1638849900162500

I'd like confirmation on whether this is a bug or intended behavior, but Tony Worm brought to my attention in slack that I may have been misinterpreting how disjunctions work in CUE, where I've been thinking of them akin to boolean algebra, in which more than one disjunct in a set may succeed, while it may well be that disjuncts behave more like a boolean xor in this situation, wherein exactly one must succeed.

I'll reread the value lattice and theory docs.

**Comment by mpvl** [comment]
Thanks for the very elaborate report! That is very useful!

**Comment by mpvl** [comment]
Disjunctions are logically akin to boolean algebra, meaning that more than one disjunct may succeed. 

However, a value is not considered concrete unless a disjunction is disambiguated. Currently, if two disjuncts are structurally equal, they are considered to be one and thus unambiguous. In v0.2, redundant disjuncts were eliminated based on subsumption. This was problematic for various reasons, so this logic was removed. We are contemplating a middle ground, though.

Either way, that does not seem to be the problem here, as that would result in a "unresolved disjunction" error.

This very much indeed looks like a bug. My suspicion is that it is related to the other disjunction bugs currently reported.

**Comment by mvdan** [comment]
This appears to be fixed by the new disjunction algorithm in `CUE_EXPERIMENT=evalv3` as of a35caede0d1ecb7f743972b9e9ae18906ae34803 :) I have sent https://review.gerrithub.io/c/cue-lang/cue/+/1194556 to add a slightly simplified version of your example as a regression test.
