### ISSUE TITLE
unable to evaluate reference of quoted hidden field 

### ISSUE THREAD

**Issue by xinau** [cue-lang/cue#1425]
### What version of CUE are you using (`cue version`)?

```console
$ cue version
cue version v0.4.1-beta.6 linux/amd64
```

### Does this issue reproduce with the latest release?

Yes. I build cue from the latest available commit `28b42576ce831209f4dd796d3515f16f784ba570`.

### What did you do?

I tried to reference a "quoted" hidden field of a struct. Cue was unable to evaluate the field even though other cases like quoted visible fields or normal hidden field do work.

```cue
test: {
	_hidden_1: ""
	vissible_1: ""
	"_hidden_2": ""
	"vissible_2": ""
}

works: test.vissible_1
works: test._hidden_1
works: test.vissible_2
fails: test._hidden_2
```

### What did you expect to see?

I expected that the quoted hidden field would be treated equally to a vissible "quoted" field.

### What did you see instead?

```console
$ cue eval test.cue -a 
test: {
    _hidden_1:   ""
    vissible_1:  ""
    "_hidden_2": ""
    vissible_2:  ""
}
works: ""
fails: test._hidden_2
$ cue eval test.cue -ca
fails: undefined field: _hidden_2:
    ./test.cue:13:13
```

**Comment by xinau** [comment]
Additionally, I found out that referencing the quoted hidden field using a index expression, i.e. `["_hidden_2"]` does work.

**Comment by verdverm** [comment]
quoted fields are always regular fields and cannot be hidden or definitions

```cue
"#def": "not a def"
#def: "is a def"

"_hid": "not a hid"
_hid: "is a hid"
```

https://cuelang.org/play/?id=hduKc3GBWus#cue@export@cue

note how the "same" names are not in fact the same label and can have separate values

**Comment by xinau** [comment]
@verdverm thanks for the pointer. I stumbled up on this issue while i wanted trying to "compute" a hidden field. Something like this. I'm going to close this issue as this is clearly the intended behavior and instead will open a feature request to support using "quoted" for hidden fields as well. As in my use case the field name is being computed from another field.
