### ISSUE TITLE
cue import --recursive improperly yaml-izes CRD pattern

### ISSUE THREAD

**Issue by nyarly** [cue-lang/cue#1443]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.4.0 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

I'm `cue import -R`ing the CRDs for ECK (https://download.elastic.co/downloads/eck/1.9.1/crds.yaml),
and in the `beats.beat.k8s.elastic.co` schema, this pair: `pattern: '[a-zA-Z0-9-]+'` is imported as

```
pattern:     yaml656e63.Marshal(_cue_pattern)
let _cue_pattern = ["a-zA-Z0-9-"]
```

which is then marshalled back to YAML as
```
     pattern: |
         - a-zA-Z0-9-
```

which is not the same thing.

### What did you expect to see?

The output YAML should match in the input (i.e. `[a-zA-Z0-9-]+`)

It's possible that the original input might not be properly detectable?

**Comment by rogpeppe** [comment]
Here's a simple reproducer:

```
exec cue import -R x.json
exec cue export --out json x.cue
cmp stdout x.json

-- x.json --
{
	"pattern": "[a]+"
}
```

I see this failure:

```
> exec cue import -R x.json
> exec cue export --out json x.cue
[stdout]
{
    "pattern": "- a\n"
}
> cmp stdout x.json
--- stdout
+++ x.json
@@ -1,3 +1,3 @@
 {
-    "pattern": "- a\n"
+	"pattern": "[a]+"
 }

FAIL: /tmp/testscript646304569/x.txtar/script.txt:3: stdout and x.json differ
error running x.txtar in /tmp/testscript646304569/x.txtar
```


The `x.cue` file looks like this:

```
import yaml656e63 "encoding/yaml"

pattern: yaml656e63.Marshal(_cue_pattern)
let _cue_pattern = ["a"]
```

- it shouldn't be a list
- it's lost the `+` at the end

in general, I suspect that `import -R` should always guarantee to produce exactly the same data that was imported.
That said, that's often not going to be the case where the quoted YAML or JSON isn't in canonical form.
Perhaps some better heuristics could apply (e.g. when the input is sufficiently complex that we're sure that
a false positive is very unlikely)?
