### ISSUE TITLE
cmd/cue: get go generates "time" package that can't be imported properly

### ISSUE THREAD

**Issue by seh** [cue-lang/cue#1453]
### What version of CUE are you using (`cue version`)?

`cue version v0.4.1-beta.6 darwin/amd64`

### Does this issue reproduce with the latest release?

Yes.

### What did you do?

1. Fetch the Go code for a given package.  
```shell
go get -d github.com/jetstack/cert-manager/pkg/apis/certmanager/v1
```
2. Generate CUE definitions for the package.  
```shell
 cue get go github.com/jetstack/cert-manager/pkg/apis/certmanager/v1
```
3. Observe that _cue get go_ generates a "time" CUE package at _cue.mod/gen/time_.  
```shell
% ls -1 cue.mod/gen/time
format_go_gen.cue
time_go_gen.cue
zoneinfo_go_gen.cue
zoneinfo_read_go_gen.cue
```
4. Use a definition from one of the generated files that imports this generated "time" package.  
```cue
import "github.com/jetstack/cert-manager/pkg/apis/certmanager/v1"

cert: v1.#Certificate & {
      spec: issuerRef: name: "my-issuer"
      // NB: This definition unifies with time.#Duration.
      spec: renewBefore: v1.#DefaultRenewBefore
      spec: secretName: "my-secret"
}
```
5. Attempt to export that CUE file.  
```shell
cue export test.cue
```

### What did you expect to see?

```json
{
    "cert": {
        "spec": {
            "renewBefore": 2592000000000000,
            "secretName": "my-secret",
            "issuerRef": {
                "name": "my-issuer"
            }
        },
        "status": {}
    }
}
```

### What did you see instead?

```
cert.spec.renewBefore: 2 errors in empty disjunction:
cert.spec.renewBefore: conflicting values 2592000000000000 and null (mismatched types int and null):
    ./cue.mod/gen/github.com/jetstack/cert-manager/pkg/apis/certmanager/v1/const_go_gen.cue:19:39
    ./cue.mod/gen/github.com/jetstack/cert-manager/pkg/apis/certmanager/v1/types_certificate_go_gen.cue:22:8
    ./cue.mod/gen/github.com/jetstack/cert-manager/pkg/apis/certmanager/v1/types_certificate_go_gen.cue:99:16
    ./test.cue:3:7
cert.spec.renewBefore: undefined field: #Duration:
    ./cue.mod/gen/github.com/jetstack/cert-manager/pkg/apis/certmanager/v1/const_go_gen.cue:19:27
```

Note the complaint near the end:
> undefined field: #Duration

The generated _const_go_gen.cue_ file's content is as follows:
<details>
<summary>const_go_gen.cue</summary>

```cue
// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/jetstack/cert-manager/pkg/apis/certmanager/v1

package v1

import "time"

// minimum permitted certificate duration by cert-manager
#MinimumCertificateDuration: time.#Duration & 3600000000000

// default certificate duration if Issuer.spec.duration is not set
#DefaultCertificateDuration: time.#Duration & 7776000000000000

// minimum certificate duration before certificate expiration
#MinimumRenewBefore: time.#Duration & 300000000000

// Default duration before certificate expiration if  Issuer.spec.renewBefore is not set
#DefaultRenewBefore: time.#Duration & 2592000000000000

// Default index key for the Secret reference for Token authentication
#DefaultVaultTokenAuthSecretKey: "token"

// Default mount path location for Kubernetes ServiceAccount authentication
// (/v1/auth/kubernetes). The endpoint will then be called at `/login`, so
// left as the default, `/v1/auth/kubernetes/login` will be called.
#DefaultVaultKubernetesAuthMountPath: "/v1/auth/kubernetes"
```
</details>

### Additional context

This problem came up for discussion [in the "general" channel of the "CUE" Slack workspace](https://cuelang.slack.com/archives/CLT3ULF6C/p1641327236352900).

Should _cue get go_ generate this "time" package? If it's useful, at minimum it looks like we need to give it a different import path, so as not to conflict with [the built-in "time" package](https://pkg.go.dev/cuelang.org/go@v0.4.0/pkg/time).

**Comment by rogpeppe** [comment]
I agree that it shouldn't be generating packages that mirror the standard library, but for the record, the given example only seems to be a problem because of the use of the `#DefaultRenewBefore` definition.

Maybe packages could be imported under some pseudo name for the Go standard library (e.g. `pkg.go.dev/time`)

**Comment by hooksie1** [comment]
We are seeing a similar issue, but it's with Duration. If the Go struct has a type of `time.Duration`, `cue get go` generates `time.#Duration` and then when generating openapi, cue complains that `openapi: undefined field: #Duration`. Not sure how to tackle this.

**Comment by hooksie1** [comment]
Another note, changing the time directory to `pkg.go.dev/time` does seem to fix the `time.#Duration` issue but it doesn't pull in all of the source from the Go std library, so it fails on some of the types that it can't find because it didn't generate them all.

**Comment by sabedevops** [comment]
I've also encountered the `undefined field: #Duration` issue. Is there any way to fix it currently?

**Comment by verdverm** [comment]
I haven't tried it, but it may be possible to put the following somewhere (maybe `cue.mod/usr/...`). You'd want to structure the directory structure to match where it is expected (given the generated content is not applying a package selector to the `#Duration`. You might even need it multiple times | places.

```
import "time"

#Duration: string & time.Duration
```

**Comment by myitcv** [comment]
I think this is ultimately a duplicate of #648

**Comment by mvdan** [comment]
I agree with @myitcv; let's close this as a duplicate. Both issues have had some useful discussion, but it's best to not duplicate and split the threads.

**Comment by mvdan** [comment]
For what it's worth, this was resolved as part of https://github.com/cue-lang/cue/issues/2969 and https://github.com/cue-lang/cue/issues/2999.
