### ISSUE TITLE
doc: document Go version policy

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#1462]
Per the release notes for `v0.4.1-beta.6`:

> As we near the halfway point to go1.18, go1.15 has been removed from the build matrix. The project's policy for previous versions of Go will be formalized in the near future, but is likely to be that each major Go release is supported until there are two newer major releases, with a 3 month grace period following the release of a new major version (3 months being half a 6-month release cycle) before support for the oldest version is dropped.

**Comment by mpvl** [comment]
Current approach seems okay.

**Comment by mpvl** [comment]
Would be good to know if any of our users are dependent on older Go versions, though.

**Comment by mvdan** [comment]
Closing in favor of https://github.com/cue-lang/cue/discussions/1937, where we're asking our users about our Go support policy.
