### ISSUE TITLE
cue/go: panics and varying behavior on `cue.Value.Subsume` between incompatible values produced from a list iterator

### ISSUE THREAD

**Issue by sdboyer** [cue-lang/cue#1467]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version 0.4.1

</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

OK, this is a doozy. Unfortunately, i haven't been able to precisely isolate the conditions for the panic, but in probing it, i did discover a fair bit of variance in behavior...so, hopefully that's helpful a bit?

The basic issue appears to be around accessing values within lists from the Go API. Here's a broken one:

<details>
<summary>Broken Go program</summary>

```go
package main

import (
	"fmt"

	"cuelang.org/go/cue"
	"cuelang.org/go/cue/cuecontext"
)

const src = `
#def: {
	#seq: { schemas: [_, ..._] }
	seqs: [#seq, ...#seq]
}

#inst: #def
#inst: seqs: [
	{
		schemas: [
			{
				init: string
			},
			{
				init: string
				withDefault?: *"foo" | "bar"
			},
		]
	},
	{
		schemas: [
			{
				init: string
				withDefault?: "foo" | *"bar"
			},
		]
	}
]
`

// func main() {}
func Dotest() {
	ctx := cuecontext.New()
	v := ctx.CompileString(src)

	inst := v.LookupPath(cue.ParsePath("#inst"))
	first := inst.LookupPath(cue.ParsePath("seqs[0].schemas[0]"))
	second := inst.LookupPath(cue.ParsePath("seqs[0].schemas[1]"))
	third := inst.LookupPath(cue.ParsePath("seqs[1].schemas[0]"))
	// fmt.Printf("%+v\n%+v\n%+v\n", first, second, third)

	fmt.Println("Direct 0.1->0.0:", second.Subsume(first, cue.Raw(), cue.Schema()))
	fmt.Println("Direct 1.0->0.1:", third.Subsume(second, cue.Raw(), cue.Schema()))
	inLoop(inst)
}

func inLoop(raw cue.Value) {
	seqiter, _ := raw.LookupPath(cue.MakePath(cue.Str("seqs"))).List()
	var seqv uint
	var predecessor cue.Value
	var prev [2]uint
	for seqiter.Next() {
		var schv uint
		schemas := seqiter.Value().LookupPath(cue.MakePath(cue.Str("schemas")))
		schiter, _ := schemas.List()
		for schiter.Next() {
			sch := schiter.Value()
			if schv == 0 && seqv == 0 {
				continue
			}

			bcompat := sch.Subsume(predecessor, cue.Raw(), cue.Schema())
			fmt.Printf("Iter %v.%v->%v.%v: %s\n", seqv, schv, prev[0], prev[1], bcompat)
			prev = [2]uint{seqv, schv}
			predecessor = sch
			schv++
		}
		seqv++
	}
}
```
</details>

### What did you expect to see?

```
Direct 0.1->0.0: <nil>
Direct 1.0->0.1: field withDefault not present in {init:string} (and 1 more errors)
Iter 0.1->0.0: <nil>
Iter 1.0->0.1: field withDefault not present in {init:string} (and 1 more errors)
```

### What did you see instead?

```
Direct 0.1->0.0: <nil>
Direct 1.0->0.1: field withDefault not present in {init:string} (and 1 more errors)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1263003]

goroutine 1 [running]:
cuelang.org/go/internal/core/subsume.(*subsumer).vertices(0xc00029fae0, 0xc0002a27e0, 0xc0002a30e0)
	/Users/sdboyer/ws/go/pkg/mod/cuelang.org/go@v0.4.1/internal/core/subsume/vertex.go:39 +0x63
cuelang.org/go/internal/core/subsume.(*subsumer).values(0xc00029fae0, {0x15bcbf0, 0xc0002a27e0}, {0x15bcbf0, 0x0})
	/Users/sdboyer/ws/go/pkg/mod/cuelang.org/go@v0.4.1/internal/core/subsume/value.go:48 +0x2e5
cuelang.org/go/internal/core/subsume.(*Profile).Value(0x15b9818, 0xc000207f60, {0x15bcbf0, 0xc0002a27e0}, {0x15bcbf0, 0x0})
	/Users/sdboyer/ws/go/pkg/mod/cuelang.org/go@v0.4.1/internal/core/subsume/subsume.go:81 +0x90
cuelang.org/go/cue.Value.Subsume({0xc000207f60, 0xc0002a27e0, 0xc0002927f0}, {0x0, 0x0, 0x0}, {0xc00029fcc8, 0x2, 0x2})
	/Users/sdboyer/ws/go/pkg/mod/cuelang.org/go@v0.4.1/cue/types.go:1770 +0x178
main.inLoop({0xc000207f60, 0xc000241830, 0x0})
	/Users/sdboyer/ws/thema/tmp/debug.go:72 +0x465
main.main()
	/Users/sdboyer/ws/thema/tmp/debug.go:54 +0x38f
exit status 2
```

FWIW, this is critical for Thema (grafana/thema#14) because these panics preclude us from checking the most foundational backwards compatibility invariants on which the system is built.

Thinking i could get around this, i tried recreating the "Direct" lookup method in the sample program within Thema itself (my [original implementation](https://github.com/grafana/thema/blob/9b9d022dcd1f63a217779ec6bd372f46d92bf257/impl.go#L71-L114) is in the iterator form). Unfortunately, that one panics on the same line, meaning that at a certain point, neither approach works.

Since i can't immediately figure out how to repro the panic in the direct lookup case, the panics there can be observed by:

```bash
git clone https://github.com/grafana/thema --branch panic-validate
cd thema
go test -run TestExemplarValidity github.com/grafana/thema/exemplars
```

The reproducer code above is pretty similar to Thema's actual structure, so it's not immediately obvious to me what's different enough that direct lookup works here, but not in Thema.

**Comment by mpvl** [comment]
The problem is that Subsume is called with an uninitialized value (e.g. predecessor may not be set).

Arguably Subsume shouldn't panic in that case, but rather return an error, but either way, I'm not sure what the desired behavior should be in that case.

**Comment by sdboyer** [comment]
...omg, i think i totally missed a bug in my Go loop, here. Wow, that's embarrassing.

I'll...go see what happens when i fix that.

**Comment by sdboyer** [comment]
Yup! Fixing the dumb bug in the loop solved all my problems. As dumb as the mistake here was on my part, i'm _ecstatic_ that the problem was on my end. This panic had been hanging over my head for some time, feeling like a bad omen for the viability of Thema as a whole.

I do think there's a lesson here, though. Now that i see the bug in my code, i think that panicking within `Subsume()` in the case of an uninitialized value is appropriate - but a more contextualized panic would have made all the difference.

I can't account for why i didn't notice this now-painfully-obvious bug in my code when i first wrote it around three months ago, but i can say that i'm not _surprised_ i missed it. I find working with the `cue.Value` API pretty cognitively taxing: the ambiguity around what any given `cue.Value` may contain makes me constantly uncertain about whether what i'm writing is safe/correct. I never quite feel fully certain of whether i've done all the right validation checks on one or not, given the goals of the particular function i'm in. Given that, especially as i'm prototyping a system as i was in this case, it's not uncommon that i declare mental bankruptcy on checking `cue.Value` in order to reserve enough cognitive bandwidth to focus on the problem i'm actually trying to solve.

FWIW, this has also been the experience of a number of Grafana engineers who've worked with CUE's Go API. Insulating Go authors from that uncertainty was a prime motivator behind the way i designed Thema's Go API. [`BindLineage()`](https://pkg.go.dev/github.com/grafana/thema#BindLineage) is designed to be a logical control point that [confers certainty](https://github.com/grafana/thema/blob/main/docs/go-mapping.md#build-and-verify) about the `Lineage` type itself: send in a `cue.Value`, and if you get a non-nil `Lineage` back, then you can be assured that all promised downstream capabilities of the system are functional. (modulo things we haven't implemented yet, like reverse translation)

Obviously, the same sort of thing isn't possible in the fully general context of `cue.Value`. In this case, having the panic message make clear that the problem is on my end, not CUE's, would have given me exactly the indicator. For the more general case, it seems to me that it's not a problem of the current Go API being insufficient so much as overwhelming. I wonder how feasible it might be to organize the various validation behaviors into some kind of precondition/postcondition checking system.
