### ISSUE TITLE
Unclosed backquote source code causes infinite loop

### ISSUE THREAD

**Issue by Syuparn** [cue-lang/cue#1475]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.4.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```bash
# source code with an unclosed backquote (no break lines at the end)
$ cat backquote.cue
`

# eval this source code
$ cue eval backquote.cue
```

### What did you expect to see?

CUE raises a syntax error.

```bash
$ cue eval backquote.cue
string literal not terminated:
    ./backquote.cue:1:1
```

### What did you see instead?

CUE gets stuck in an infinite loop.

```bash
$ cue eval backquote.cue
```

cf. With an unclosed doublequote, CUE terminated immediately and raises a syntax error (as expected).

```bash
# unclosed doublequote (no break lines at the end)
$ cat doublequote.cue
"
$ cue eval doublequote.cue
string literal not terminated:
    ./doublequote.cue:1:1
```

I tried [fuzzing test](https://go.dev/blog/fuzz-beta) and found this parsing issue.

**Comment by Syuparn** [comment]
I am not sure which error the unclosed backquote should raise.

The reference says backquotes can be used as a string literal, while implementation treats it as a quoted identifier, which is deprecated. 

(reference)

https://cuelang.org/docs/references/spec/#string-and-byte-sequence-literals

```
`日本語`                                 // UTF-8 input text as a raw literal
```

(implementation)

```bash
$ cat b.cue
`abc`
$ cue eval b.cue
use of deprecated quoted identifiers (deprecated as of v0.0.14): try running `cue fix` (possibly with an earlier version, like v0.2.2) to upgrade:
    ./b.cue:1:1
```


While an unclosed backquote with trailing break line raises quoted identifier syntax error, should it raise an identifier error too?

```bash
$ cat backquote_with_break.cue
`
$ cue eval backquote_with_break.cue
quoted identifier not terminated:
    ./backquote_with_break.cue:1:2
```

https://github.com/cue-lang/cue/blob/master/cue/scanner/scanner.go#L824

**Comment by mpvl** [comment]
@Syuparn: backquotes used to be used for identifiers, but have been removed a long time ago.

The example in the spec is thus wrong, and is really a copy-and-paste error left from using Go as a template. So thanks for catching that.

I can reproduce the hang, which should obviously be fixed.

I think it is fair to treat "`" like any other unsupported character. It currently has no meaning at all in CUE. But of course 
I understand leaving references and examples in the spec makes that very confusing. :)

**Comment by Syuparn** [comment]
> I think it is fair to treat "`" like any other unsupported character. It currently has no meaning at all in CUE.

Oh, I see. Thank you for explanation and fixing!
