### ISSUE TITLE
internal/core/adt: undetected structural cycle

### ISSUE THREAD

**Issue by mpvl** [cue-lang/cue#1503]
### What version of CUE are you using (`cue version`)?

Tip and comprehension tip

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
a: #T & {
    a: one: link: a: two: {}
}
#T: {
    a: [string]: link: #T
    a: b: {}
}
```

### What did you expect to see?
Structural cycle error.

### What did you see instead?
Hangs.

**Comment by mpvl** [comment]
A smaller reproducer:
```
a: b: c: {}
a: #T
#T: {
    b: c: {}
    b: [string]: #T
}
```

Analysis: The cycle is only undetected if `a` is evaluated before `#T`.  What is likely going on is that while evaluating `a`, `#T` is not checked for permanent errors, which would have stopped evaluation.

**Comment by antong** [comment]
I bumped into the following with a similar structure:
```
#Basic: number | string | bool
#Sub: {
	X=_maxdepth: >0 | *5 // Hangs without the default
	[string]:    #Basic | #Sub & {
		_maxdepth: X - 1
	}
}

a: #Sub
a: _maxdepth: 5
a: b: c: d: 42
a: x1: x2: x3: x4: x5: "foo"
a: y1: y2: y3: y4: y5: y6: "bar" // -> maxdepth exceeded
```

If I leave out the default value (*5 in the example), then evaluating hangs. Is this the same, or should I file a separate issue?
