### ISSUE TITLE
eval doesn't error on missing package field

### ISSUE THREAD

**Issue by eonpatapon** [cue-lang/cue#1504]
### What version of CUE are you using (`cue version`)?

6bc922c848660781778819a90a343285d0906e2e

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
exec cue eval

cmp stdout stdout.golden
-- cue.mod/module.cue --
module: ""
-- cue.mod/pkg/example.com/x/x.cue --
package x

#B: 1
-- foo.cue --
package foo

import "example.com/x"

a: x.#A
-- stdout.golden --
a: undefined field: #A:
    ./foo.cue:5:6
```

### What did you expect to see?

I expect eval to return an error as `#A` doesn't exist in package `example.com/x`.

When targeting `a`, eval returns an error:

```
cue eval -e a
a: undefined field: #A:
    ./foo.cue:5:6
```

### What did you see instead?

No error

```
> exec cue eval
[stdout]
import "example.com/x"

a: x.#A
> cmp stdout stdout.golden
--- stdout
+++ stdout.golden
@@ -1,3 +0,0 @@
-import "example.com/x"
-
-a: x.#A
@@ -0,0 +1,2 @@
+a: undefined field: #A:
+    ./foo.cue:5:6
```

**Comment by myitcv** [comment]
I believe this is a dup of https://github.com/cue-lang/cue/issues/629, but please shout if you disagree.
