### ISSUE TITLE
DRAFT:  (bug): weird key values in field comp

### ISSUE THREAD

**Issue by verdverm** [cue-lang/cue#1516]
draft, will try to create a minimal reproducer if possible.

### What version of CUE are you using (`cue version`)?

0.4.2

### What did you do?

```cue
  filtered: {
    for i, vid in do.videos.items {
      (i): {
        id: vid.snippet.resourceId.videoId
        title: vid.snippet.title
        description: vid.snippet.description
      }
    }
  }
```

Using `"\(i)"` produces the correct results. `do.video.items` is a list

### What did you expect to see?

`"0", "1" ...` for the keys

### What did you see instead?

identifiers or labels from a different scope... maybe the file, package, or instance scope?

**Comment by mpvl** [comment]
String interpolation converts numbers to strings. Using `()` for fields does no implicit conversion, though. Also number fields are not allowed.

So this should be an error.
