### ISSUE TITLE
How to enable `allowScalar` in evaluation Option

### ISSUE THREAD

**Issue by leejanee** [cue-lang/cue#1517]
I see the `allowScalar` field in  evaluation Option in `cue/types.go` 
![image](https://user-images.githubusercontent.com/74582607/152983936-c2a79ccd-8e7d-410c-8e9b-eb97f45ee2cb.png)

Now, I want to enable `allowScalar`, but I don't know how to?

**Comment by mpvl** [comment]
This doesn't seem to be used at the moment. What is your use case?

**Comment by leejanee** [comment]
For example, I define  workflow by cuelang like as follow. 
```
step1: {}
step2: {prefix: step1.value}
if step2.value > 100 {
   step3: {prefix: step2.value}
}
```
> the workflow will fill `value: number` for every step during execution.

But the cue.Value compiled from the above has an error: 'undefined field: value' . At this time when I use `value.Fields()` to list valid steps(to be executed), an error return.

Expected:
1.  value.Fields() can iterate over all valid fields (when set  option `allowScalar` true)
2.  cueflow(tools/flow) can execute the above cue.Value

**Comment by mpvl** [comment]
Interesting. Note that it is illegal to have "regular" fields (not a definition or hidden field) alongside scalar values. So if I understand correctly what you want, this is not allowed.

It is normal that the above value has errors, btw, as at the start of flow the `value` fields do not exist. That should be fine though. CUE roughly has two kinds of errors: incomplete and final. Incomplete errors can be resolved by making a configuration more complete, which is what a flow execution would usually do.

In the above example, the `value` fields indeed do not exist, but from the sounds of it would be filled by your flow implementation.

So the first thing to solve here is why there is an issue for flow to accept the above value.

**Comment by leejanee** [comment]
Yep, It is exactly what I needed  that the flow could accept the example value.

In our case, We need to determine whether to add a new step according to the execution results of the previous steps.

**Comment by wonderflow** [comment]
hi, @mpvl , Do we have any schedule on this issue? The KubeVela project is still blocking on this issue for upgrading to the new CUE version.

Supporting cueflow can also help if we can't allow setting the value `allowScalar`.  We're going to migrate our own workflow to the cueflow way.

**Comment by verdverm** [comment]
You shod be able to work around this by adding `value: _` to the tasks you expect it to be reference it from. Generally, if you have definitions for your task schemas, it could go there. New tasks should then be generated when the task finishes and the referenced field becomes concrete.

I've been doing this. It would be interesting to see how flow works to create dynamic tasks if undefined fields are acceptable. For example, when dynamically creating a task when a field does not exist.

**Comment by mpvl** [comment]
@wonderflow @leejanee 
I'm still not entirely sure what functionality you are looking for. I think part of my confusion is the name `allowScalar`, which I see in the code doesn't do anything like that.

But if I understand correctly, you want to be able to iterate over any fields known so far, even if there are "incomplete" errors. That is more or less what `allowScalar` seems to do.

Is that correct? I suggest then adding an `IgnoreErrors()` option.

**Comment by mpvl** [comment]
Actually, arguably the API already assumes values can be partial by default. So arguably this is a bug and Fields should iterate over the fields as is.

See https://review.gerrithub.io/c/cue-lang/cue/+/533457. Let me know if this would work for you. We plan to cut 0.4.3 soon and can include it in that.

**Comment by wonderflow** [comment]
ping @leejanee , please help check
