### ISSUE TITLE
internal/eval: keyword should be allowed as field in selector expression

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#1518]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version +37eb22b4 linux/arm64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
exec cue eval in.cue
cmp stdout stdout.golden

-- in.cue --
x: {
	if: "ok"
}
y: x.if
-- stdout.golden --
x: {
    if: "ok"
}
y: "ok"
```

### What did you expect to see?

Passing test

### What did you see instead?

```
> exec cue eval in.cue
[stderr]
expected selector, found 'if':
    ./in.cue:4:6
[exit status 1]
FAIL: /tmp/testscript3635022377/repro.txt/script.txt:1: unexpected command failure
error running repro.txt in /tmp/testscript3635022377/repro.txt
```

**Comment by xinau** [comment]
For others stumbling upon this issue. A workaround for this issue is to quote the field inside the struct and access it using index expression syntax, I.e.

```cue
x: {
	"if": "ok"
}
y: x["if"]
```

Also note that optional fields don't need to be quoted, I.e.

```cue
x: {
  if?: "ok"
}
```
