### ISSUE TITLE
a package which imports itself causes infinite loop

### ISSUE THREAD

**Issue by verdverm** [cue-lang/cue#1519]
### What version of CUE are you using (`cue version`)?

0.4.2

### What did you do?

```
exec cue eval

-- cue.mod/module.cue --
module: "hof.io/repro"
-- data/index.cue --
package data

import "hof.io/repro/data"

Foo: "Bar"
-- index.cue --
package main

import "hof.io/repro/data"

foo: data.Foo
```

### What did you expect to see?

A cycle or other error

### What did you see instead?

nothing and `cue eval` running indefinitely

**Comment by antong** [comment]
Is this the same as #849 ?

**Comment by myitcv** [comment]
Yep, @antong, I believe so.

**Comment by verdverm** [comment]
I would point out that there is a difference in the formulation, not sure about the relation to underlying issue.

- #849 has mutually importing packages
- This issue has a self importing package
