### ISSUE TITLE
pkg/time: Parse is not hermetic for layout with named timezone

### ISSUE THREAD

**Issue by antong** [cue-lang/cue#1522]
time.Parse() in the built-in CUE standard packages should be hermetic. It however directly uses time.Parse from the Go standard library, which works differently based on the external environment. Quoting the Go documentation (https://pkg.go.dev/time#Parse): 

> When parsing a time with a zone abbreviation like MST, if the zone abbreviation has a defined offset in the current location, then that offset is used. The zone abbreviation "UTC" is recognized as UTC regardless of location. If the zone abbreviation is unknown, Parse records the time as being in a fabricated location with the given zone abbreviation and a zero offset.

### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.4.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes, v0.4.2 is the latest release.

### What did you do?

```
exec cue version
env TZ=Europe/London
exec cue eval in.cue
cmp stdout out.cue
env TZ=Europe/Stockholm
exec cue eval in.cue
cmp stdout out.cue

-- in.cue --
import "time"

x: time.Parse(time.RFC822, "01 Jul 21 17:54 CEST")

-- out.cue --
x: "2021-07-01T17:54:00Z"
```

### What did you expect to see?

PASS

... or at least the same result for both environments.

### What did you see instead?

```
> exec cue version
[stdout]
cue version v0.4.2 linux/amd64
> env TZ=Europe/London
> exec cue eval in.cue
[stdout]
x: "2021-07-01T17:54:00Z"
> cmp stdout out.cue
> env TZ=Europe/Stockholm
> exec cue eval in.cue
[stdout]
x: "2021-07-01T15:54:00Z"
> cmp stdout out.cue
--- stdout
+++ out.cue
@@ -1,1 +0,0 @@
-x: "2021-07-01T15:54:00Z"
@@ -0,0 +1,1 @@
+x: "2021-07-01T17:54:00Z"

FAIL: /tmp/testscript1012028401/timezone.txtar/script.txt:7: stdout and out.cue differ
error running timezone.txtar in /tmp/testscript1012028401/timezone.txtar
```

**Comment by antong** [comment]
I noticed this when speculating about #1508 .

**Comment by mpvl** [comment]
Ouch. Good catch. I think the sensible thing to do is to use `ParseInLocation` with the location set to nil, and then allow an argument like `time.Parse(layout, value, location: "Europe/Berlin")`.

**Comment by antong** [comment]
I think ParseInLocation it the only option, but I don't think location can be nil, or it will panic if the layout doesn't have a zone (https://go.dev/play/p/6OkhVrKZu82). Perhaps `ParseInLocation(layout, value, time.UTC)` instead?

Also, I don't know if this now just being too pedantic, but if we allow specifying a location like "Europe/Berlin", then this could be considered non-hermetic as well, as it will cause the time zone rules to be looked up in the external system zoneinfo database. So CUE output would depend on system configuration. As a concrete example, the output of `time.Parse("2006-01-02 15:04", "2030-07-21 17:00", location: "Europe/Berlin")` may well change automatically as part of a system update if/when the EU adopts the proposition to abandon daylight saving time (https://oeil.secure.europarl.europa.eu/oeil/popups/ficheprocedure.do?reference=2018/0332(COD)&l=en). IIRC they actually already voted to do so, but COVID postponed adopting it.

**Comment by mpvl** [comment]
That doesn't crash for me, but seems reasonable to set time.UTC.

Can't wait for getting rid of daylight savings time...

Either way, great point about being careful to allow locations. So if we support it, it should be tied in to the injection mechanism of the tooling layer, which allows injecting non-hermetic values like user name and time.

**Comment by mpvl** [comment]
Ah, it is probably the builtin code that recovers from panics that prevented the crash.

**Comment by antong** [comment]
I think we should add a time.Parse testcase with a layout without any time zone, like "2006-01-02 15:04".

For this issue, for example:
```
env TZ=UTC
exec cue eval timeparse.cue
cmp stdout golden
env TZ=Europe/Berlin
exec cue eval timeparse.cue
cmp stdout golden

-- timeparse.cue --

import "time"

t1: time.Parse(time.RFC822, "01 Jul 21 17:54 CEST")
t1: time.Parse("2006-01-02 15:04", "2021-07-01 17:54")

-- golden --
t1: "2021-07-01T17:54:00Z"
```

For 65ff0f4, it would catch the location=nil error:
```
> env TZ=UTC
> exec cue eval timeparse.cue
[stderr]
error in call to time.Parse: time: missing Location in call to Date:
    ./timeparse.cue:5:5
[exit status 1]
FAIL: /tmp/testscript2299836915/repro.txtar/script.txt:2: unexpected command failure
error running repro.txtar in /tmp/testscript2299836915/repro.txtar
```
