### ISSUE TITLE
`cue.Value().IsClosed()` returns true when a definition has an ellipsis

### ISSUE THREAD

**Issue by tonyhb** [cue-lang/cue#1534]
### What version of CUE are you using (`cue version`)?

0.4.2

### Does this issue reproduce with the latest release?

Yes

### What did you do?

1. Parse a cue definition which has an ellipsis, allowing arbitrary fields
2. Grab the definition as a `cue.Value`
3. Check `IsClosed()`.

### What did you expect to see?

`IsClosed()` should return false as the definition has an ellipsis (https://cuelang.org/play/?id=KdD67R55mhX#cue@export@cue).  I expected this to work as a definition is also
a struct, and its fields can be iterated as a struct.

### What did you see instead?

`IsClosed()` returns true, despite the definition not being closed and allowing arbitrary fields.

**Comment by mpvl** [comment]
Note that IsClosed is deprecated. The semantics of IsClosed is quite shoddy. Better is to use `Value.Allows`.

This was an easy enough fix, but in the future we may default to not fixing bugs in deprecated code.

**Comment by tonyhb** [comment]
Thanks for the heads up with regards to deprecated.  Not quite sure how I missed that :)

Honestly had contemplated using "allows".  The intent is to check for closed structs when converting from Cue to TypeScript - we've written a [(basic) Cue to TypeScript parser](https://github.com/inngest/event-schemas/tree/main/events/marshalling/typescript).

If we were to use `Allows`, it would seem I'd have to create a random field name and check if it can be added to the struct to see if it's open?  Semantically that seemed a little worse than IsClosed on initial impressions, but I'll revisit that decision given your comment.

Thanks again!

**Comment by mpvl** [comment]
> If we were to use `Allows`, it would seem I'd have to create a random field name and check if it can be added to the struct to see if it's open?

You can use the special value `cue.AnyString` to see if it allows any string. I've added a comment in the doc of the upcoming fix to explain that. The fix of IsClosed now uses that itself.
