### ISSUE TITLE
internal/eval: remove any remaining vestiges of '::'

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#1543]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version +a629625c linux/arm64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
! exec cue eval x.cue
stderr "expected operand, found ':'"

-- x.cue --
x :: 2
```

### What did you expect to see?

Test to succeed because we long ago removed support for `::`.

### What did you see instead?

```
> ! exec cue eval x.cue
[stderr]
use of deprecated '::' (deprecated as of v0.2.1): try running `cue fix` (possibly with an earlier version, like v0.2.2) to upgrade:
    ./x.cue:1:3
[exit status 1]
> stderr "expected operand, found ':'"
FAIL: /tmp/testscript4066371334/repro.txt/script.txt:2: usage: stderr [-count=N] 'pattern'
error running repro.txt in /tmp/testscript4066371334/repro.txt
```

**Comment by FogDong** [comment]
I'm quite confused with this issue, can we just remove to code below to fix this issue?

```go
	if p.tok == token.ISA {
		p.assertV0(p.pos, 2, 0, "'::'")
	}
```

**Comment by slewiskelly** [comment]
> I'm quite confused with this issue, can we just remove to code below to fix this issue?
> 
> ```go
> 	if p.tok == token.ISA {
> 		p.assertV0(p.pos, 2, 0, "'::'")
> 	}
> ```

What is confusing? It is quite common to raise an issue to track future work. I believe there is more than just what you have referenced which would be required to remove all traces of it.

**Comment by myitcv** [comment]
@FogDong. @slewiskelly is exactly right here:

> It is quite common to raise an issue to track future work. I believe there is more than just what you have referenced which would be required to remove all traces of it.

Not only are the changes likely broader than just the code change, raising issues like this also helps us to plan future work and releases. Because often things need to happen in a specific order with respect to other changes.

**Comment by mvdan** [comment]
I _think_ this was all done in https://review.gerrithub.io/c/cue-lang/cue/+/546886, we just forgot to reference this issue as fixed. Please let me know if I got that wrong.
