### ISSUE TITLE
Default values behavior is not conforming to the spec

### ISSUE THREAD

**Issue by yujunz** [cue-lang/cue#1550]
### What version of CUE are you using (`cue version`)?

```
❯ cue version
cue version v0.4.2 darwin/amd64
```

### Does this issue reproduce with the latest release?

Yes

### What did you do?

Validate spec with an example

https://github.com/cue-lang/cue/blob/71e9d033c16ee3684f35022890087f9c3a12acb3/doc/ref/spec.md?plain=1#L735

```cue
foo: (string | *"b") & (int | *"a")
```

### What did you expect to see?

According to the spec, it should be evaluated to bottom, i.e.

```cue
foo: (string&int) | *("a"&"b") # _|_ | *_|_
```

### What did you see instead?

```cue
foo: "a"
```
This is logically correct since `"a"` is the only value satisfy both constraints but it seems not conforming to the spec explanation.

**Comment by mpvl** [comment]
What maybe is confusing with the spec representation is that the value CUE syntax `a | b` translates to a tuple `⟨a|b, b⟩` as used in the spec. In other words `v1` in `⟨v1, d1⟩` represents the entire value (the entire disjunction), whereas `d1` represents only those disjuncts marked as default.

**Comment by yujunz** [comment]
> value CUE syntax `a | b` translates to a tuple `⟨a|b, b⟩`

Do you mean `a | *b` => `⟨a|b, b⟩`?

So that `(string | *"b") & (int | *"a")` => `⟨(string | "b") & (int | "a"), "a"&"b"⟩` => `⟨"a", _|_⟩` => `"a"`
