### ISSUE TITLE
Go integration docs rely on deprecated Runtime

### ISSUE THREAD

**Issue by kevinbarbour** [cue-lang/cue#1561]
Most of the examples provided in the documentation for [Go integration](https://cuelang.org/docs/integrations/go/) relies on the use of `cue.Runtime` but it appears this was deprecated last July. These docs could use some updating to make the examples more complete and explain their use with contexts instead.

**Comment by mvdan** [comment]
https://cuelang.org/docs/integration/go/ now says:

> The content on this page has largely been superseded by [“How CUE works with Go”](https://cuelang.org/docs/concept/how-cue-works-with-go/).

and https://cuelang.org/docs/concept/how-cue-works-with-go/ correctly uses the non-deprecated APIs, so I believe this is fixed.

@myitcv @jpluscplusm are there plans to delete the "integrations" section of the new website? The Go entry appears like it should be deleted entirely, and others like JSON or YAML simply redirect into their entries under "concept guides", which is rather confusing.

**Comment by jpluscplusm** [comment]
> @myitcv @jpluscplusm are there plans to delete the "integrations" section of the new website?

> The Go entry appears like it should be deleted entirely, and others like JSON or YAML simply redirect into their entries under "concept guides", which is rather confusing.

Yes, that hierarchy is being revised. The proposed change is at https://cuelang.org/cl/1192707 (https://cl-1192707-3--cue-cls.netlify.app/docs/integration/), with followups as per the CL's commit message.

The aim is outlined in https://github.com/cue-lang/docs-and-content/issues/80.

**Comment by mvdan** [comment]
Ah perfect - given that this is already being tracked and worked on, I think we can close this issue as resolved, given that the new content has fixed this issue :)
