### ISSUE TITLE
...string in struct not working as documented

### ISSUE THREAD

**Issue by huanggze** [cue-lang/cue#1562]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.4.2 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
yes

### What did you do?

I'm following the example below as described in the [doc](https://cuelang.org/docs/references/spec/#structs) , but get errors. Seems `...string` is not supported.

```cue
a: {
    foo:    string    // foo is a string
    [=~"^i"]: int     // all other fields starting with i are integers
    [=~"^b"]: bool    // all other fields starting with b are booleans
    ...string         // all other fields must be a string
}

b: a & {
    i3:    3
    bar:   true
    other: "a string"
}
```

### What did you expect to see?

no error

### What did you see instead?

```bash
$ cue eval test.cue
missing ',' in struct literal:
    ./test.cue:5:8
expected '}', found 'EOF':
    ./test.cue:12:2
```

**Comment by slewiskelly** [comment]
This was [recently updated](https://github.com/cue-lang/cue/commit/1c52d6a7d693133f04810da355f8036848c2c78a) but the change has not yet made it to the website. I expect it might when the next version is release.

See https://github.com/cue-lang/cue/issues/1109 for more information.
