### ISSUE TITLE
Constraints doesn't work for dict/map keys

### ISSUE THREAD

**Issue by NsLib** [cue-lang/cue#1579]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.4.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What did you do?

```
#NonEmptyString: string & >""

map1: [string & >""]: string

map1: {
    "foo": "111"
    "": "abc"
}

map2: [#NonEmptyString]: string

map2: {
    "foo": "111"
    "": "abc"
}
```

```bash
$ cue vet test.cue

$ cue export test.cue
{
    "map1": {
        "foo": "111",
        "": "abc"
    },
    "map2": {
        "foo": "111",
        "": "abc"
    }
}
```

### What did you expect to see?

```
invalid value "" (out of bound >""):
```

### What did you see instead?

* no error is reported
* empty key exists in the exported result

**Comment by jlongtine** [comment]
@NsLib Your code isn't [closing](https://cuelang.org/docs/tutorials/tour/types/closed/) `map1` or `map2`, just setting constraints on non-empty strings.

If you want to constrain the keys of `map1` + `map2`, you'll need to define it as a definition or use the `closed` built-in. 

One of these should work for you:

```cue
#NonEmptyString: string & >""

map1: close({
[string & >""]: string
})

map1: {
    "foo": "111"
    "": "abc"
}

map2: close({
[#NonEmptyString]: string
})

map2: {
    "foo": "111"
    "": "abc"
}

#NonEmptyKeys: [string & >""]: string

map3: #NonEmptyKeys
map3: {
    "foo": "111"
    "": "abc"
}
```

**Comment by mpvl** [comment]
@jlongtine is correct.
