### ISSUE TITLE
ability to pull and push policies written by Cue over OCI Registries

### ISSUE THREAD

**Issue by developer-guy** [cue-lang/cue#1583]
**Is your feature request related to a problem? Please describe.**
No, it is not.

**Describe the solution you'd like**

Cosign can validate attestations based on Rego and Cue policies. Furthermore, the [OCI Artifacts specification](https://github.com/opencontainers/artifacts) allows us to store additional artifacts such as Helm Charts and WASMs, SBOMS, etc. in addition to container images in OCI registries. To learn more about OCI Artifacts, @dlorenc wrote a great blog post about them. You can reach out to the blog post [here](https://dlorenc.medium.com/oci-artifacts-explained-8f4a77945c13).

In cosign, we already have a PR to load Rego policies from OCI registries to validate attestations through these policies. So we tied to the spec that I mentioned below for Rego policies.

[open-policy-agent/conftest@7d0099b/internal/commands/push.go#L48-L50](https://github.com/open-policy-agent/conftest/blob/7d0099b5ed0d8c70a1e4eda9388e4e50bf068218/internal/commands/push.go#L48-L50)

👉 https://github.com/sigstore/cosign/pull/1478

If we specify the same for Cue, we can use it on the cosign side too. 

What I'm proposing is that it'd be nice if we can add two new commands "pull" and "push" to implement distributing Cue policies over OCI registries.

cc: @dentrax @dlorenc

**Describe alternatives you've considered**

**Additional context**

**Comment by mvdan** [comment]
> What I'm proposing is that it'd be nice if we can add two new commands "pull" and "push" to implement distributing Cue policies over OCI registries.

If by policies you mean CUE modules (i.e. groups of packages with a `cue.mod/module.cue`) over OCI registries, this is already being implemented :) Subscribe to https://github.com/cue-lang/cue/issues/2032 for updates, and see https://github.com/cue-lang/cue/discussions/2330 for the design details.

I'm closing as a duplicate for now to join the discussion threads, but please do say if I'm mistaken.
