### ISSUE TITLE
Extracting struct name

### ISSUE THREAD

**Issue by mladedav** [cue-lang/cue#1584]
**Is your feature request related to a problem? Please describe.**
I would like to have an object like this:
```
#Person: {
  name: <nameOfStruct>
}

John: #Person
```

Which should produce
```
John: {
  name: John
}
```
This is obviously just a minimal example, I would like to use the name in some transformations and interpolation.

**Describe the solution you'd like**
Added syntax for a construct like this

**Describe alternatives you've considered**
I can create another string inside the object instead and use that as an identifier that will be expanded. To make it exactly 1-to-1 I would also have to add validation that the identifiers are unique across objects.

**Comment by slewiskelly** [comment]
The example you've given can be accomplished using [templates](https://cuelang.org/docs/tutorials/tour/types/templates/):

```cue
// person.cue
#Person: {
    name: string
}

[Name=string]: #Person & {
    name: Name
}

John: {}
```

```console
$ cue export person.cue
{
    "John": {
        "name": "John"
    }
}
```

**Comment by mladedav** [comment]
Oh, thank you. I have gone through the tutorials in cuelang but I seem to have missed this one.
