### ISSUE TITLE
Value.Decode does not error on mismatched types

### ISSUE THREAD

**Issue by paulhammond** [cue-lang/cue#1592]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.4.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

v0.4.2 is the latest release

### What did you do?

I followed the documentation on how to [Copy CUE values into Go values](https://cuelang.org/docs/integrations/go/#copy-cue-values-into-go-values). Here it is in testscript form:

```
go mod tidy
go run main.go

cmp stdout stdout.golden
-- go.mod --
module cuebug

go 1.16

require cuelang.org/go v0.4.2
-- main.go --
package main

import (
	"fmt"

	"cuelang.org/go/cue"
)

func main() {
	type ab struct{ A, B int }

	var r cue.Runtime

	var x ab

	i, _ := r.Compile("test", `{A: 2, B: 4}`)
	_ = i.Value().Decode(&x)
	fmt.Println(x)

	i, _ = r.Compile("test", `{B: "foo"}`)
	_ = i.Value().Decode(&x)
	fmt.Println(x)
}
-- stdout.golden --
{2 4}
json: cannot unmarshal string into Go struct field ab.B of type int
```

### What did you expect to see?

An error, as documented.

### What did you see instead?

An `ab` is created with `B` set to 0.

It's not clear if this is a documentation bug or a bug in `Value.Decode()`. If the latter can you offer advice on how to ensure that decodes are successful?

**Comment by verdverm** [comment]
A couple of points here:

- you should use `cue.Context` rather than `cue.Runtime` (which is deprecated)
- Decode returns an error which you should check

```
  err := i.Value().Decode(&x)
  if err != nil {
    fmt.Println("error:", err)
  }
```

which would show: `error: B: cannot use value "foo" (type string) as int`

**Comment by paulhammond** [comment]
> Decode returns an error which you should check

Oops! Sorry for missing the obvious answer there. It sounds like the docs just need to be updated here?

**Comment by mpvl** [comment]
> Oops! Sorry for missing the obvious answer there. It sounds like the docs just need to be updated here?

The only thing to add to the docs is something along the lines that it will return an error if an error is encountered during the operation. This is assumed to be the default meaning of an error return value and Go documentation typically omits such statements from the documentation. Just to pick an example from the Go standard documentation: https://pkg.go.dev/net#LookupHost
