### ISSUE TITLE
evaluator: incorrect structural cycle errors in presence of disjunction

### ISSUE THREAD

**Issue by paulrosenzweig** [cue-lang/cue#1608]
I'm not sure whether this is a duplicate of #990. Please close this if it is.

### What version of CUE are you using (`cue version`)?

<pre>
cue version v0.4.3-beta.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
myValue: #type & {fieldName: "some string"}       
#type: fieldName: #subtype                        
#subtype: string | {foo: string} | {bar: #subtype}
```

https://cuelang.org/play/?id=7e5cytWaxLP

Interestingly, changing `#subtype` to `string | {bar: #subtype}` avoids the issues. Inlining `#type` so `myValue` is `{fieldName: #subtype} & {fieldName: "some string"}` avoids the issue as well.

### What did you expect to see?

```
myValue: {
	fieldName: "some string"
}
```

### What did you see instead?

```
#subtype.bar: 1 errors in empty disjunction::
    ./specs/test.cue:2:19
```

**Comment by mpvl** [comment]
This is a problem related to disjunctions. Reordering them fixes it. For instance
```
#subtype: string |  {bar: #subtype} | {foo: string}
```

**Comment by myitcv** [comment]
Confirming this remains a problem with e187f9fe5d45.

```
exec cue export x.cue
cmp stdout stdout.golden

exec cue export y.cue
cmp stdout stdout.golden

-- x.cue --
#Output1: {stdout: {codec: "lines" | "bytes"}} |
	{http: {url: string}}

o: #Output1 & {http: url: "test"}
-- y.cue --
#Output2: {stdout: {codec: "lines" | "bytes"}} |
	{http: {url: string}} |
	{retry: {output: #Output2}}

o: #Output2 & {http: url: "test"}
-- stdout.golden --
{
    "o": {
        "http": {
            "url": "test"
        }
    }
}
```

This test should pass, but fails with:

```
# x.cue (0.012s)
# y.cue (0.012s)
> exec cue export y.cue
[stderr]
#Output2.retry.output: #Output2.retry.output: structural cycle (and 1 more errors)
[exit status 1]
FAIL: /tmp/testscript2521245705/repro.txt/script.txt:6: unexpected command failure
```

Per @mpvl, reordering the disjunction elements fixes things, as does introducing a disjunction on the disjunction element that recursively references `#OutputN`:

```
# f1.cue
exec cue export f1.cue
cmp stdout stdout.golden

# f2.cue
exec cue export f2.cue
cmp stdout stdout.golden

-- f1.cue --
#Output3: {stdout: {codec: "lines" | "bytes"}} |
	{retry: {output: #Output3}} |
	{http: {url: string}}

o: #Output3 & {http: url: "test"}
-- f2.cue --
#Output4: {stdout: {codec: "lines" | "bytes"}} |
	{http: {url: string}} |
	{retry: {output: #Output4 | null}}

o: #Output4 & {http: url: "test"}
-- stdout.golden --
{
    "o": {
        "http": {
            "url": "test"
        }
    }
}
```

This passes, as expected. But neither the reordering nor the `| null` augmentation should be required.
