### ISSUE TITLE
cmd/cue: flag for export string without quotes

### ISSUE THREAD

**Issue by verdverm** [cue-lang/cue#1610]
**Is your feature request related to a problem? Please describe.**

We'd like to replace instances of `jq` with `cue`.

When exporting a string value, it always prints the quotes around it, at the terminal.
This presents issues for downstream consumers, such as piping to another command, where the presence of quotes breaks things.

**Describe the solution you'd like**

A flag to output the raw string value without the quotes, like `jq`

`-r             output raw strings, not JSON texts;`

**Example of issue**

```cue
package foo

import "list"
import "encoding/csv"

abcs: ["a", "b", "c", "d", "e"]

data: [ for i in list.Range(0,5,1) { [i, abcs[i]] }]

out: csv.Encode(data)
```

```sh
$ cue export test.cue -e out
"0,a\n1,b\n2,c\n3,d\n4,e\n"
```

**Comment by myitcv** [comment]
See `cue help filetypes`. I think you are after the `text` filetype:

```
exec cue export -e out --out text x.cue
cmp stdout stdout.golden

-- x.cue --
package foo

import "list"

import "encoding/csv"

abcs: ["a", "b", "c", "d", "e"]

data: [ for i in list.Range(0, 5, 1) {[i, abcs[i]]}]

out: csv.Encode(data)
-- stdout.golden --
0,a
1,b
2,c
3,d
4,e

```

**Comment by verdverm** [comment]
Perfect, thanks @myitcv
