### ISSUE TITLE
tools/flow: No error when using an undefined reference to a sub-field, in a dependency

### ISSUE THREAD

**Issue by helderco** [cue-lang/cue#1611]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.4.3-beta.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

With the following `main_tool.cue`

```cue
package main

import (
	"tool/cli"
)

command: {
	actions: {
		a: cli.Print & {
			$before: [actions.b]
			text: "foobar"
		}
	}
}

```
Run:
```console
$ cue cmd actions
```

### What did you expect to see?

```console
command.actions.a.$before: reference "actions.b" not found:
    ./actions_tool.cue:10:14
```

### What did you see instead?

```console
foobar
```

### Additional Info

I also tried the following with the [overview example](https://pkg.go.dev/cuelang.org/go@v0.4.2/tools/flow#pkg-overview):
```cue
actions: {
    a: input: actions.b
}
```

<details><summary>Full code</summary>
<p>

```go
package main

import (
	"context"
	"fmt"
	"log"

	"cuelang.org/go/cue"
	"cuelang.org/go/tools/flow"
)

func main() {
	var r cue.Runtime
	inst, err := r.Compile("example.cue", `
	actions: {
		a: input: actions.b
	}
	`)
	if err != nil {
		log.Fatal(err)
	}
	controller := flow.New(nil, inst, ioTaskFunc)
	if err := controller.Run(context.Background()); err != nil {
		log.Fatal(err)
	}
}

func ioTaskFunc(v cue.Value) (flow.Runner, error) {
	inputPath := cue.ParsePath("input")

	input := v.LookupPath(inputPath)
	if !input.Exists() {
		return nil, nil
	}

	return flow.RunnerFunc(func(t *flow.Task) error {
		inputVal, err := t.Value().LookupPath(inputPath).String()
		if err != nil {
			return fmt.Errorf("input not of type string")
		}

		outputVal := fmt.Sprintf("hello %s", inputVal)
		fmt.Printf("setting %s.output to %q\n", t.Path(), outputVal)

		return t.Fill(map[string]string{
			"output": inputVal,
		})
	}), nil
}
```

</p>
</details>

Using reference `b` instead of `actions.b` produces expected result.

Detected in https://github.com/dagger/dagger/issues/1885#issuecomment-1081780957.

**Comment by eonpatapon** [comment]
I believe this is related to  #629

Because `actions` is not closed for cue `actions.b` is incomplete and can become concrete at some point.

To demonstrate this, if you close explicitely `actions` then cue will fail:

```cue
package main

import (
	"tool/cli"
)

command: {
	actions: close({
		a: cli.Print & {
			$before: [actions.b]
			text: "foobar"
		}
	})
}
```

```
 cue cmd actions
command.actions.a.$before.0: undefined field: b:
    ./main_tool.cue:10:22
```

**Comment by helderco** [comment]
> I believe this is related to #629

Indeed, it appears so, thanks! Not necessarily a disjunction but the same underlying root cause.
