### ISSUE TITLE
question: min list length of non-concrete data

### ISSUE THREAD

**Issue by mattklein123** [cue-lang/cue#1614]
I would like some way to have a minimum number of list elements that are constrained. This was my first try:
```
-- test.cue --
import "list"

#test: { foo: string }
out: [...#test]
out: list.MinItems(1)
```

Fails with:
```
out: invalid value [] (does not satisfy list.MinItems(1)):
```

This was my next attempt:
```
-- test.cue --
#test: { foo: string }
out: [#test, ...#test]
```

This kind of works, but the error message when exporting is somewhat confusing if the data is not made concrete:
```
mklein@mklein-x1:~/Source/test$ cue export test.cue 
out.0.foo: incomplete value string
```

Is there a better way of thinking about this?

**Comment by tayyab-java** [comment]
WHY TRIAGE LABEL 🗡️

**Comment by slewiskelly** [comment]
https://github.com/cue-lang/cue/issues/1604 was opened for this recently.

**Comment by mattklein123** [comment]
Ah ok, thanks. Feel free to close this as a dup. Sorry for not seeing that.

**Comment by mpvl** [comment]
Dup of #1604
