### ISSUE TITLE
trouble downloading cue modules from a goproxy with go 1.18

### ISSUE THREAD

**Issue by jbcpollak** [cue-lang/cue#1624]
### What version of CUE are you using (`cue version`)?

<pre>
❯ cue version
cue version v0.4.1 linux/amd64
</pre>

### What did you do?

We are using `go get cue-module` to retrieve modules from a goproxy with a command line tool, then run `cue ...` commands against them. Note we are doing this _not_ inside a local module, but instead we just want to install the cue module locally as a repository of schemas to validate local data against. If there is a better way to do this, please let me know.

With go 1.18, this usage of `go get` is removed (you can't use `go get` except in a directory with a .mod file), and the replacement `go install` returns with error conditions:

For a module with the following structure:
```
cuemod/
     go.mod
     cue.mod/
         module.cue
     schema.cue
```

I get this error:

```
❯ GOPATH=/home/user/test go install example.com/cuemod@v0.0.26
go: downloading example.com/cuemod v0.0.26
go: example.com/cuemod@v0.0.26: module example.com/cuemod@v0.0.26 found, but does not contain package example.com/cuemod
```

if I add a `stub.go` file that declares `package example.com/cuemod`

I get this error instead:

```
❯ GOPATH=/home/user/test go install example.com/cuemod@v0.0.26
go: downloading example.com/cuemod v0.0.26
package example.com/cuemod is not a main package
```

I assume this is because it is not an executable go program, so the error makes sense from a go perspective but I'm unsure what to do from a cue perspective.

I tried looking into `cue get go`, but it seems to be specifically for converting go data types to cue, which is not what we need.

**Comment by mvdan** [comment]
> we just want to install the cue module locally as a repository of schemas to validate local data against. If there is a better way to do this, please let me know.

I'd like to better understand what you mean by this. Do you mean that you were using `go get` to effectively `git clone` the repository into your `GOPATH`? `GOPATH` is practically deprecated, so if this is the case, it makes sense to move away from that anyway.

If you were using `go get` to download a mozule zip and place it inside `go env GOMODCACHE`, then you can still do that with `go mod download your-module@your-version`.

**Comment by jbcpollak** [comment]
This is a bit complicated to explain, but in short what we want to do is fetch a cue module (and eventually any dependency modules that it might have) from the GOPROXY, then execute the module against a JSON file. To do that we currently do the following:

* `go get module@version`
* use `load.Config` to set working directory to the local module's directory in the module cache (which as far as I understand is inside $GOPATH/pkg/mod)
* use the config in a call to context.BuildInstance to get a cue Value
* then call `json.Validate(b, cv.Value)` to validate the json file is valid against the cue module.

If there is a better way to do this, I would love to know about it - the goal in short is given a JSON file and a cue module@version, to validate the json. 

As an aside, execing `go get` as a sub-process isn't super elegant, but there doesn't seem to be a way to programmatically do the same thing, with dependency resolution and all that.

I will look into `god mod download` and see if is sufficient.

**Comment by mvdan** [comment]
> fetch a cue module

If you just want to download a Go module (which may contain a CUE module too), then `go mod download` will suffice - just beware that it will place the module inside `go env GOMODCACHE`, and that it's extracted from a module zip, so there will be no VCS/git info.

That seems to be what you want, given your mention of using `load.Config` with `GOPATH/pkg/mod` aka `GOMODCACHE`.

**Comment by jbcpollak** [comment]
I was able to verify on the command line that `go mod download` will do what I want, so I can embed that in my code and that will be an improvement. It seems like go doesn't expose an official api for module downloads, which is frustrating, but this will work in the short term.

Thanks again.

**Comment by mvdan** [comment]
Sounds like you've got a solution, then :) For what it's worth, Go doesn't expose functionality like `go build` or `go mod` as a Go API because those see significant changes in behavior every release, so the tools need to behave like the Go version that is actually installed on the user's system, and not the Go version that happened to build the binary - which is often slightly older or newer.
