### ISSUE TITLE
playground: update when v0.4.3 is out

### ISSUE THREAD

**Issue by antong** [cue-lang/cue#1627]
### What version of CUE are you using (`cue version`)?

Current playground (https://cuelan.org/play), site says v0.4.2 . Tested with latest Firefox and Chrome on Windows.

### Does this issue reproduce with the latest release?

Currently yes.

### What did you do?

Entered a backtick character (`) in the playground editor.

### What did you expect to see?

An error or something.

### What did you see instead?

The page hangs, and is unresponsive. I can't edit the text in the input textbox. Firefox says that "This page is slowing down Firefox. To speed up your browser, stop this page".

**Comment by mvdan** [comment]
I believe this has been fixed via https://github.com/cue-lang/cue/issues/1475; we need to update the playground once 0.4.3 is out. Repurposing this issue to track that.

**Comment by mvdan** [comment]
v0.4.3 is deployed, and I verified that the bug is now fixed.

**Comment by myitcv** [comment]
Thanks for flagging this, @antong!
