### ISSUE TITLE
playground: misleading error message on JSON output

### ISSUE THREAD

**Issue by rogpeppe** [cue-lang/cue#1635]
The error message when JSON output is set can be misleading.
For example: https://cuelang.org/play/?id=ysknQAxbHHO#cue@export@json

The input is: 
```
x: 1
x: string
y: 2
y: string
```

I'd expect the output mention the conflicting fields, as `cue export` does with that input,
but instead the error is:

```
failed to encode: explicit error (_|_ literal) in source (and 1 more errors)
```

which is misleading because there is no `_|_` literal in the source.

**Comment by FogDong** [comment]
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/15977536/168415736-7595c129-9a78-4e30-a5e8-83e67aad7a6a.png">

Is this issue fixed now? We can close this issue probably.

**Comment by slewiskelly** [comment]
Was unable to replicate this against all stable versions since `v0.2.0`. Error message from `cue export` has consistently been the same as mentioned previously:

```
x: conflicting values 1 and string (mismatched types int and string):
    ./test.cue:1:4
    ./test.cue:2:4
y: conflicting values 2 and string (mismatched types int and string):
    ./test.cue:3:4
    ./test.cue:4:4
```

**Comment by myitcv** [comment]
This was most likely fixed by @rogpeppe himself in https://github.com/cue-sh/playground/commit/4c9bd3cf5202a18364d5e5bb1bd14208f4d86c2e!

Thanks for the heads up, @FogDong and @slewiskelly (the issue was specific to the playground). Closing.
