### ISSUE TITLE
Send multiple HTTP requests and print each response

### ISSUE THREAD

**Issue by ghost** [cue-lang/cue#1665]
Hi there,

how can I iterate over a struct of devices and send a HTTP request for each value? Like so:

```
devices: [{"name": "1"}, {"name": "2"}, {"name": "3"}]

command: fetch: {
  for key, value in devices {
    "\( value.name )": http.Do & {
      method: "GET"
      url:    "http://127.0.0.1:8000/config/\( value.name)"
    }
    "\( key )": exec.Run & {
      cmd: ["echo": "\( value.name )".response.status] // <- This does not work
    }
  }
}
``` 

The first part works just fine, CUE is sending a HTTP request for each of the specified devices.
But I am not able to print the response to the CLI because the interpolated string seems to be wrong.

I got the following two error message which in this context I don't understand:

```
invalid operand "\( value.name )" (found string, want list or struct):
conflicting values string and ["echo","\(〈2;value〉.name)".response.status] (mismatched types string and list):
```

Thanks!

**Comment by eonpatapon** [comment]
In this case you need to reference a more top level field which is static and have a selector to target a dynamic field, so in this case it would be: `fetch[value.name]`

```cue
devices: [{"name": "1"}, {"name": "2"}, {"name": "3"}]

command: fetch: {
  for key, value in devices {
    (value.name): http.Do & {
      method: "GET"
      url:    "http://127.0.0.1:8000/config/\(value.name)"
    }
    (key): exec.Run & {
      cmd: ["echo", fetch[value.name].response.status]
    }
  }
}
```

Note that you can also use `cli.Print` to echo stuff on stdout.

```cue
    (key): cli.Print & {
      text: fetch[value.name].response.status]
    }
```

**Comment by ghost** [comment]
Thanks, now everything works as intended.

What is the difference between exec.Run and cli.Print respectively what would be better in this case?

**Comment by eonpatapon** [comment]
If you just need to output text on stdout I would just use `cli.Print` as it's simpler to use. Also it won't spawn any process.

`exec.Run` can run any system command so it's more general.

**Comment by ghost** [comment]
Alright. Thanks again for the explanation.

**Comment by myitcv** [comment]
@snoheta - please can you ask questions as [discussions](https://github.com/cue-lang/cue/discussions)? Issues are for bugs and feature requests. If a discussion turns out to be a bug/feature request, we can of course easily create an issue from that. Thanks very much.

**Comment by ghost** [comment]
Yeah sure, sorry about that.

**Comment by myitcv** [comment]
> Yeah sure, sorry about that.

No problems at all! I think we should probably update the template in the issue to highlight discussions too
