### ISSUE TITLE
CI seems flakey when pulling a master commit through proxy.golang.org

### ISSUE THREAD

**Issue by mvdan** [cue-lang/cue#1667]
https://github.com/cue-lang/cue/runs/6144946455?check_suite_focus=true

```
v=$(git rev-parse HEAD)
  cd $(mktemp -d)
  go mod init mod.com
  GOPROXY=https://proxy.golang.org/ go get -d cuelang.org/go/cmd/cue@$v
  shell: /bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    GOROOT: /opt/hostedtoolcache/go/1.17.8/x64
    CUE_LONG: true
go: creating new go.mod: module mod.com
go get: cuelang.org/go/cmd/cue@33b18be9eddd72ea356a913117bb1327a04242fd: invalid version: reading https://proxy.golang.org/cuelang.org/go/cmd/cue/@v/33b18be9eddd72ea356a913117bb1327a04242fd.info: 410 Gone
	server response: not found: cuelang.org/go/cmd/cue@v0.0.0-20220424062231-33b18be9eddd: invalid version: missing cuelang.org/go/cmd/cue/go.mod at revision 33b18be9eddd
```

It is somewhat expected that the upstreams may return 410 results to basically mean "sorry, try again later". See https://github.com/golang/go/issues/42809 for instance - it applies to sum.golang.org rather than proxy.golang.org, but I assume the cause is practically the same.

We should probably have CI retry a few times over a minute or two if this happens, to reduce flakes.

**Comment by myitcv** [comment]
Two more instances today:

* https://github.com/cue-lang/cue/actions/runs/2677490932/attempts/1
* https://github.com/cue-lang/cue/actions/runs/2678927357/attempts/1

**Comment by myitcv** [comment]
Raised a new issue to track occurrences, per Bryan Mills on Slack:

https://github.com/golang/go/issues/53906

([original Slack exchange](https://gophers.slack.com/archives/C0VPK4Z5E/p1656686571426859))

**Comment by mvdan** [comment]
We removed this "pull master through proxy" step in https://review.gerrithub.io/c/cue-lang/cue/+/551923, thankfully. See the commit message for the reasoning.
