### ISSUE TITLE
cue/load: Loader does not ignore irregular files

### ISSUE THREAD

**Issue by kcburge** [cue-lang/cue#1672]
### What version of CUE are you using (`cue version`)?

<pre>
master , HEAD
</pre>

### Does this issue reproduce with the latest release?

YES

### What did you do?

Using Emacs to edit my cue files, running cue fmt on save, I kept getting a file didn't exist error.  (Emacs saves a symlink in the working directory to a non-existing file, as a locking mechanism).  This was causing cue fmt to fail with "no such file or directory".

It could also be argued that cue should ignore files that are hidden.  This symlink was a hidden file, but cue attempted to read it.

### What did you expect to see?

I expect that the cue loader would:
- ignore symlinks and other irregular files
- ignore hidden files and directories

### What did you see instead?

cue failed loading a symlink to a file that did not exist.

### Test

cat <<EOF | testscript -
exec ln -s not-found .link.cue
exec cue fmt in.cue
-- cue.mod/module.cue --
module: "example.org/test"
-- sub/sub.cue --
package sub
-- in.cue --
import "example.org/test/sub"
EOF

> exec ln -s not-found .link.cue
> exec cue fmt in.cue
[stderr]
import failed: load: open $WORK/.link.cue: no such file or directory:
    ./in.cue:3:8
[exit status 1]
FAIL: /home/kevin/.tmp/testscript3413231860/-/script.txt:2: unexpected command failure
error running <stdin> in /home/kevin/.tmp/testscript3413231860/-

**Comment by verdverm** [comment]
I'm curious if this change would impact those who use symlinks in `cue.mod/pkg/...` to reference other modules while co-developing?

~would it be better to setup emacs to only format the current file being saved?~ (noticed that it is a single file in the repro)

I wonder if the changes to how `cue fmt` operates will solve this (some split so there is less loading, can't find the issue)

**Comment by kcburge** [comment]
In my testing, it appears the package loading behavior for cue.mod/pkg/... is different than the module loading behavior for the current module.  For example, I don't think this symlink issue occurs if I import a package with a non-existing symlink to a file.  I have tried so many variations attempting to find out exactly how to reproduce this error, I've lost track.

My initial solution was to ignore a symlink to a file that did not exist.  How to handle symlinks is certainly a worthy topic of discussion.  But, other irregular files most certainly should be ignored.

**Comment by kcburge** [comment]
I was somewhat surprised the cue fmt caused the entire module to load.  I don't know whether this is justified or not.  I also believe this error will happen for eval as well. So, it's not just a fmt issue. Confirmed. Fails on eval also.

**Comment by kcburge** [comment]
For what it's worth, I know that cue complains about hidden files in some cases. The behavior with this part of the loader however is not consistent.  It will gladly reference hidden files, so, actually ignoring hidden files would also be a proper solution to my problem.  I would agree that a well-behaved *nix application would honor symlinks, even if I wouldn't use them here. So, perhaps the real issue is that hidden files are not ignored here.

cat <<EOF | testscript -
exec cue fmt ./...
-- cue.mod/module.cue --
module: "example.org/test"
-- sub/sub.cue --
package sub
-- in.cue --
import "example.org/test"
-- .invalid.cue --
p
EOF

> exec cue fmt ./...
[stderr]
import failed: build constraints exclude all CUE files in example.org/test:
    .invalid.cue: filename starts with a '.'
    in.cue: no package name:
    ./in.cue:1:8
[exit status 1]
FAIL: /home/kevin/.tmp/testscript774736140/-/script.txt:1: unexpected command failure
error running <stdin> in /home/kevin/.tmp/testscript774736140/-

I believe the above mention of "filename starts with a '.'" is just a warning.

**Comment by kcburge** [comment]
submitted an alternate implementation that preserves symlink capability

**Comment by kcburge** [comment]
I believe the correct behavior is to only consider files and directories and symlinks to files and directories that exist.  If a symlink cannot be stat'd, an error should return, just like directories that cannot be read.  Updated my pull request to do this.

**Comment by myitcv** [comment]
I'm not clear why `.link.cue` is being walked in the first place. Like Go, files and directories that begin with `_` and `.` should be ignored.

**Comment by myitcv** [comment]
@kcburge 

> I expect that the cue loader would:
> 
> * ignore symlinks and other irregular files

Please can you explain why this is your expectation with respect to symlinks?

**Comment by myitcv** [comment]
Crucial edit in my previous reply :)

**Comment by mvdan** [comment]
In https://github.com/cue-lang/cue/issues/3300 we are reaching the conclusion that we should continue to support loading source files which are symlinks as we've done in previous CUE versions due to Bazel. @rogpeppe added regression tests in https://review.gerrithub.io/c/cue-lang/cue/+/1198252 too.

> Please can you explain why this is your expectation with respect to symlinks?

We didn't get a response here, so for now I'm going to close this issue as a duplicate of #3300, as that's the issue we are currently using to finalize our thinking on supporting symlinks when loading CUE packages and source files in general. If you disagree with my reasoning above, or would like to contribute to #3300, please feel free to comment on either issue. Thanks!
