### ISSUE TITLE
evaluator: disallow list concatenation via +

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#1677]
We got rid of this in the spec at the beginning of 2021:

https://cue-review.googlesource.com/c/cue/+/8063

and provided builtins:

https://cue-review.googlesource.com/c/cue/+/8064

Probably time to actually rewrite usages of `+` to use `list.Concat` and then disallow `+` entirely?

cc @mpvl

**Comment by mvdan** [comment]
I must be blind, because I re-filed this as https://github.com/cue-lang/cue/issues/2237 nearly a year later. That one is already milestoned, so I think it's probably easiest to keep it.
