### ISSUE TITLE
Unable to merge two structures on v0.4.3

### ISSUE THREAD

**Issue by akselleirv** [cue-lang/cue#1681]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.4.3 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What did you do?

`cue eval -c`

Will produce error message: 
```
cannot add field cluster: was already used:
    ./example.cue:34:3
```

Example which produces the error:
```
package k8s


cluster: aks: production: {
	sub_domain: "example"
	flavor:     "internal"
	provider:   "aks"
	audience:   "https://example.com"
}

cluster: [ID=_]: [Env=_]: {
	files: {
        (_ingress_nginx_values & {full_name: "\(ID)-\(Env)"}).result
	}
}


_ingress_nginx_values: {
	full_name: string

	result: "../flux/infrastructure/\(full_name)/ingress-nginx/values.yaml": {

		apiVersion: "helm.toolkit.fluxcd.io/v2beta1"
		kind:       "HelmRelease"
		metadata: {
			name:      "ingress-nginx"
			namespace: "ingress-nginx"
		}
	}
}

for c in [cluster] for name, obj1 in cluster for env, obj2 in obj1 for path, content in obj2.files {
	if obj2.provider == "aks" {
		cluster: "\(name)": "\(env)": files: "../flux/infrastructure/\(name)-\(env)/ingress-nginx/values.yaml": spec: values: controller: service: annotations: "service.beta.kubernetes.io/azure-dns-label-name": "\(name)-\(env)-001"
	}
}
```

### What did you expect to see?
I have tested the same code with version 0.4.2 and 0.4.1 and it does not error.

### What did you see instead?
It should not produce an error.

**Comment by rogpeppe** [comment]
Thanks for the report!
Here's a simpler version of the CUE that seems to demonstrate the same issue:

```
x: p: {}

for k, _ in x {
	x: (k): z: true
}
```

**Comment by mpvl** [comment]
I can confirm that this is fixed with the comprehension rework that will land in the near future.

**Comment by mxey** [comment]
Any update on this? Our users run into this bug and the only remedy is to downgrade to v0.4.2 :/

**Comment by myitcv** [comment]
Thanks for your patience. This is a complicated stack of changes, and we are working through it as quickly as we can!

**Comment by myitcv** [comment]
Fixed in https://github.com/cue-lang/cue/commit/748a68589747fed6273d6338eb7e275a4fb116c6
