### ISSUE TITLE
Elide trailing ".0" when exporting numbers to JSON

### ISSUE THREAD

**Issue by brandonbloom** [cue-lang/cue#1693]
Migrating PR to Issue as per https://github.com/cue-lang/cue/pull/1566#issuecomment-1115915190

**Is your feature request related to a problem? Please describe.**

Exporting integers to JSON always print with a trailing `.0`. This is especially not ideal when the exported JSON is intended to be consumed/edited by humans. Moreover, there is often schema/type-knowledge that the number may be an integer and so the `.0` is potentially confusing.

**Describe the solution you'd like**

There are a few possibilities:

One of them is embodied by PR #1566, which simply outputs JSON numbers without a fractional part if they are precisely representable as JSON integers.

**Describe alternatives you've considered**

A richer solution would be to extend the Cue AST to support arbitrary precision numeric literals, preserve type-hints through to printing, etc.

**Comment by brandonbloom** [comment]
Responding to some comments from @mpvl in PR #1566 

> Go doesn't preserve precision when parsing JSON

Go actually does have a type for unmarshaling arbitrary precision numbers (`json.Number`), as well as an option to do this automatically: https://pkg.go.dev/encoding/json#Decoder.UseNumber

> The solution is not to make the representation of CUE to the AST lossy.

That's not what I meant to imply. In fact, quite the opposite. When parsing Cue, an `Int` or `Float` token gets produced, but those tokens are both coercible to any number type. I was proposing to improving the information content of the AST by introducing an explicit untyped `Number` token, freeing up the `Int` and `Float` types to explicitly represent type information. Parsing would return an `Int` only for tokens such as `0700` or `0xdeadbeef`, which are clearly intended to be integers, and `Float` for `123.456` which is clearly intended to be a float. However, `789` would produce a `Number`. Doing this would allow tightening the coercion rules, such as the `Int` and `Float` tokens actually convey type information and cannot be confused with one another. Then the type of token would be usable during printing to ensure sensible formatting. If the printer gets an ambiguous `Number` token, it can use a heuristic (like PR #1566) or user-supplied preference.

The confusion here probably comes because I made a throwaway comment related to runtime value-encoding: I said "converting from any Go type would produce Number", but in retrospect, it should probably produce `Int` or `Float` depending on the source data type, preserving that type info.

Does that clear up the confusion?

**Comment by rogpeppe** [comment]
@brandonbloom

Thanks for the report (and the PR!).

> Exporting integers to JSON always print with a trailing `.0`.

I'm finding it hard to understand the exact problem here without a concrete example to go with,
particularly when the starting point is this statement which isn't actually the case AFAICS.

For example, this CUE:

```
a: 1
b: 1.0
c: 1.00
d: 0 + 1.000
e: 0 + 1
```

produces the following JSON when exported:

```
{
    "a": 1,
    "b": 1.0,
    "c": 1.00,
    "d": 1.000,
    "e": 1
}
```

It's clear that integers exported to JSON do _not_ always include a trailing `.0` in fact.

Perhaps you could come up with a nice self-contained example that demonstrates the behaviour that you find problematic?
Otherwise it's hard to be sure that we're solving the right problem.

Thanks!

**Comment by brandonbloom** [comment]
> Exporting integers to JSON always print with a trailing .0.
> > this statement which isn't actually the case AFAICS.

Apologies. It's been a whole month (with a 10+ day vacation in it) since I looked at this and misremembered the details a bit. I think I now also recall why I said "converting from any Go type would produce Number" (instead of Int or Float).

Re-reading my initial PR's description, I see it says "it is common for data parsed from JSON to contain float64 values when the expected information is an integer" and indeed the problem in my original source code is that I'm doing some generic handling of JSON and trying to convert it to Cue. I could probably introduce this `Int53Representable` heuristic via rewriting at that level. Or I could use `json.Number`, but encoding of `json.Number` doesn't seem to be supported properly by Cue:

```go
package main

import (
	"encoding/json"
	"fmt"

	"cuelang.org/go/cue/cuecontext"
	"cuelang.org/go/cue/format"
)

func main() {
	cc := cuecontext.New()
	v := cc.Encode(struct {
		Int    int
		Float  float64
		Number json.Number
	}{
		Int:    1,
		Float:  2,
		Number: json.Number("3"),
	})
	bs, err := format.Node(v.Syntax())
	if err != nil {
		panic(err)
	}
	fmt.Println(string(bs))
}

/* OUTPUT:

{
	Int:    1
	Float:  2.0
	Number: "3"
}

*/
```

At least until I remember what the heck I was trying to do and why it was a problem and can articulate it more clearly, I'll close the PR and this issue. Apologies for the noise.

Maybe I should open a separate issue about `json.Number` support?

**Comment by myitcv** [comment]
> Maybe I should open a separate issue about `json.Number` support?

This sounds like a good idea, thanks.

**Comment by mvdan** [comment]
> At least until I remember what the heck I was trying to do and why it was a problem and can articulate it more clearly, I'll close the PR and this issue. Apologies for the noise.

The PR was closed, but the issue remained open - I assume by mistake. I'll close it for now, but please feel free to reopen if I got that wrong.
