### ISSUE TITLE
cmd/cue: version information does not include VCS information for devel builds

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#1697]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version +bd9ae537 linux/arm64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
# Set gobin
mkdir gobin
env GOBIN=$WORK/gobin

# Install cue
exec git clone https://github.com/cue-lang/cue
cd cue
exec git checkout bd9ae5371cc23c54cb3cb90c0bd5a1fa4d82bc92
go install ./cmd/cue

# Check version
exec $GOBIN/cue version
stdout 'cue version +bd9ae537 linux/arm64'
```

### What did you expect to see?

A passing test

### What did you see instead?

```
# Check version (0.008s)
> exec $GOBIN/cue version
[stdout]
cue version (devel) linux/arm64
> stdout 'cue version +bd9ae537 linux/arm64'
FAIL: /tmp/testscript321861946/repro.txt/script.txt:13: no match for `cue version +bd9ae537 linux/arm64` found in stdout
```

cc @rogpeppe

**Comment by myitcv** [comment]
The main driver behind this being that in [Go 1.18](https://go.dev/doc/go1.18) `cmd/go` includes version control information in binaries. If `cmd/cue` is built with `>=go1.18` then we can reference that information for dev builds.

**Comment by mvdan** [comment]
I'm actually of the opinion that just a VCS commit hash isn't really enough; at minimum, a timestamp should also be included, similar to how `go version` does it.

In a different tool I've taken the rather simple approach of *always* printing the build information settings:

```
$ git clone https://github.com/burrowers/garble
$ cd garble
$ go install
$ garble version
mvdan.cc/garble (devel) 

Build settings:
       -compiler gc
     CGO_ENABLED 1
          GOARCH amd64
            GOOS linux
         GOAMD64 v3
             vcs git
    vcs.revision 22e3d30216bef48518db2831c14283b13e37bb4a
        vcs.time 2022-05-05T21:07:47Z
    vcs.modified false
$ go install mvdan.cc/garble@master
$ garble version
mvdan.cc/garble v0.6.1-0.20220505210747-22e3d30216be h1:CeeEe24nJ0fulMChMxEsQ7ztH9jKZwrA2GwYjrEHzHc=

Build settings:
       -compiler gc
     CGO_ENABLED 1
          GOARCH amd64
            GOOS linux
         GOAMD64 v3
```

I like this approach because including everything is also helpful for debugging and reproducibility. For example, if a user reports a bug when running cue, we don't have to wonder whether they built with CGO disabled, `-trimpath`, with gccgo rather than the default compiler, etc.

The code is at https://github.com/burrowers/garble/blob/22e3d30216bef48518db2831c14283b13e37bb4a/main.go#L327-L368 and I'm happy to have it be copied over. Just note that we probably don't need `mod.Sum` (not sure why I included it at all), and that the TEST variables were for the sake of a testscript - which may be useful to us as well, for the sake of testing without having to recreate particular git clone scenarios.

@myitcv let me know what you think of the approach above, before the PR is modified. It's certainly more verbose, but for most people the output will be less than ten lines, so I don't think it would be wise to hide it behind something like `cue version --verbose`. Also because then we'd need to tell many bug reporters "please run this other version command that produces more info".

**Comment by mvdan** [comment]
The above has made me realize that I/we can do better now that https://github.com/golang/go/issues/50603 is accepted as a proposal. I've sent https://github.com/burrowers/garble/pull/533, which makes the output nicer:

```
$ go install && garble version
mvdan.cc/garble v0.0.0-20220510090020-89667b2fe081

Build settings:
       -compiler gc
     CGO_ENABLED 1
          GOARCH amd64
            GOOS linux
         GOAMD64 v1
             vcs git
    vcs.revision 89667b2fe081d561ef582eeaab497da58e4a8419
        vcs.time 2022-05-10T09:00:20Z
    vcs.modified false
```

It's up to CUE to decide if its CLI program should print the build settings in their entirety - note that they partially overlap with the constructed module pseudo-version. I'm still of the opinion that they should be included :)

**Comment by myitcv** [comment]
> In a different tool I've taken the rather simple approach of _always_ printing the build information settings:

This seems to make sense to me. I assume there is no potentially sensitive material that would be leaked like file paths? 

I'll defer to @mpvl for a decision, however.

Just a drive-by comment on the implementation and testing (which is hard in this case) we need to ensure we cover at least:

* where `cuelang.org/go` is the main module, with and without a dirty working tree
* where `cuelang.org/go` is not the main module with no replace directives
* where `cuelang.org/go` is not the main module, but is subject to a local directory-based `replace` directive, with and without a dirty working tree
* ...

I'm sure I'm missing cases.

**Comment by mvdan** [comment]
> This seems to make sense to me. I assume there is no potentially sensitive material that would be leaked like file paths?

Not that I'm aware; it's just build options. The user could potentially add their own strings, like `-tags foobar` would then show up in the build settings output, but I can't imagine why something like that would be sensitive.

> Just a drive-by comment on the implementation and testing (which is hard in this case) we need to ensure we cover at least:

We could potentially try to cover all edge cases, but I wonder if that's really necessary - we just really need to cover all the bits of code that print version information. For example, the tree being dirty just changes the printed `vcs.modified` variable, but if it's not used by our code at all, I don't think that needs a specific test.

In the other tool I avoided having to fiddle with `git` in the test code by supplying different kinds of build settings to the version code via JSON. We could go for the same approach, maybe. https://github.com/burrowers/garble/blob/1a3d7868d9a17572de03b1065749a8e8f6835512/testdata/scripts/help.txt#L80-L103

**Comment by myitcv** [comment]
> For example, the tree being dirty just changes the printed `vcs.modified` variable, but if it's not used by our code at all, I don't think that needs a specific test.

Great point. This is hopefully covered in tests elsewhere, probably good to just confirm it behaves as expected.

**Comment by djosephsen** [comment]
Reading through the garble `version` code, I'm unclear whether garble maintains support for an ldflags-based version override.  Does it? I assume we want to maintain that functionality in Cue right?

**Comment by mvdan** [comment]
You're right that in the other tool I don't need the ldflags mechanism. There are only two ways that people should really be obtaining the tool with: a `go install github.com/tool@version`, which will make `mod.Version` contain the real version string, and a `git clone github.com/tool && cd tool && go install`, which will typically make the VCS fallback kick in.

It looks like the ldflags method in CUE is legacy, as it's documented but not used anywhere, so I _imagine_ that we could remove it in favor of the VCS fallback. But I'll leave it to Paul or Marcel to give clarity. It could be that it's still useful for release builds or Docker images that I'm not seeing.

**Comment by djosephsen** [comment]
Thanks.. I committed a compromise that should preserve it.  Just trying to get some tests working with this testscript... thing...

**Comment by mvdan** [comment]
Happy to help tomorrow if you get stuck - I am available on the CUE Slack.

**Comment by djosephsen** [comment]
awesome I will probably take you up on that thanks

**Comment by myitcv** [comment]
> It looks like the ldflags method in CUE is legacy, as it's documented but not used anywhere, so I _imagine_ that we could remove it in favor of the VCS fallback.

Correct. It was previously the means by which the version information would be "injected" into the `cmd/cue` binary at release time by GoReleaser.

**Comment by djosephsen** [comment]
tests working and committed
