### ISSUE TITLE
Gerrit should disallow clicking Submit if either of the two trybot results are red

### ISSUE THREAD

**Issue by mvdan** [cue-lang/cue#1705]
This would have prevented human mistakes like https://review.gerrithub.io/c/cue-lang/cue/+/537569.

We should still allow clicking submit if there are no trybot results, with the assumption that the human knows what they're doing - perhaps the change is to a file that does not get touched by CI at all. We could always restrict this edge case too, if we find that we make mistakes with it as well.

**Comment by mvdan** [comment]
A merge queue bot would also fix this, but the restriction is hopefully a simpler first step.

**Comment by myitcv** [comment]
Looks like a [label function setting of `AnyWithBlock`](https://gerrit-review.googlesource.com/Documentation/config-labels.html#label_function) would work, but given that config field is deprecated perhaps we make the switch to [submit requirements](https://gerrit-review.googlesource.com/Documentation/config-submit-requirements.html) as part of this change?

**Comment by mvdan** [comment]
That sounds good - perhaps we can take a look next time we have a batch of Gerrit config changes to make, since properly reviewing, applying them, and testing them is slightly involved and needs at least two people. This isn't urgent either.

**Comment by mvdan** [comment]
@myitcv interesting, I fixed this in https://review.gerrithub.io/c/cue-lang/cue/+/540885, but the "fixes" line did not work - presumably because we didn't merge into the default branch. Makes sense, I guess, but we need to remind ourselves to close gerrit config issues manually once fixed.
