### ISSUE TITLE
Gerrit should not drop +2 even after changes

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#1707]
Currently, our GerritHub instance is configured to drop a `+2` in case any change is made to a CL, other than a simple SHA difference. i.e. a commit message change, parent commit change, etc... all of these cause a `+2` to be dropped.

We should aim to do what the Go project does here, copying max scores in the case of updates to a CL. We need to consider these three labels in that respect:

* `Code-Review`
* `Trybot-Result`
* `Unity-Result`

The relevant part of the Gerrit config is the [`copyCondition` documentation](https://gerrit-review.googlesource.com/Documentation/config-labels.html#label_copyCondition)

**Comment by mvdan** [comment]
This was done in https://review.gerrithub.io/c/cue-lang/cue/+/540593 via copyCondition.
