### ISSUE TITLE
bad error message in recursive list definition

### ISSUE THREAD

**Issue by vikstrous2** [cue-lang/cue#1717]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
0.4.3
</pre>

### Does this issue reproduce with the latest release?
yes

### What did you do?
```
{
    a: ["1", "2"]
    a: a + ["3"]
}
```

### What did you expect to see?

Some reasonable error such as 
```
cycle error:
    -:3:8
```

### What did you see instead?
```
a: incompatible list lengths (2 and 2)
```

**Comment by mpvl** [comment]
Technically speaking `a: a` is allowed (logically it means that `a` is equal to itself). But `a: a+x` is clearly not. 

In other words, I agree the error message is bad, but it could be `a: incompatible list lengths (2 and 3)`, with lines numbers reported.

**Comment by mxfactorial** [comment]
> But a: a+x is clearly not.

except when open

```
a: [1,...]
a: a + [2]
> a: [1, 2]
```

**Comment by mpvl** [comment]
This has been fixed in the mean time.
