### ISSUE TITLE
cmd/cue: fmt truncates file

### ISSUE THREAD

**Issue by jstewmon** [cue-lang/cue#1744]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.4.3 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What did you do?

I tried to format cue containing a private label with a digit following `_`, (e.g. `_5`).

```cue
_5: 5
five: _5
```

```shell
cue fmt - <<EOF
_5: 5
five: _5
EOF
```

```
invalid identifier "_5":
    -:2:7
```

When `fmt` is used on a file containing such a label, the file is truncated:
```shell
<<EOF > repro.cue
_5: 5
five: _5
EOF
cue fmt repro.cue
ls -lh repro.cue
```
```
invalid identifier "_5":
    ./repro.cue:2:7
-rw-r--r--  1 jstewmon  staff     0B Jun  1 15:46 repro.cue
```

### What did you expect to see?

1. Since this cue evals, fmt should succeed.
2. If fmt encounters an error, it should not truncate the file which produced the error.

### What did you see instead?

1. fmt failed for valid cue
2. fmt truncated the file

**Comment by verdverm** [comment]
I think `_5` is not a valid identifier per the spec: https://cuelang.org/docs/references/spec/#identifiers

Interestingly...

```
$ cat num-ident.cue 
_h: "hidden"
_5: 5
five: _5

$ cue eval -H num-ident.cue 
_h:   "hidden"
"_5": 5
five: 5
```

**Comment by myitcv** [comment]
Thanks both. There appear to be a couple of issues here. Let's leave this issue for the `cue fmt` truncation issue. 

Confirmed with:

```
cue version +9bda2205 linux/arm64
```


# `fmt` truncates file on error

```
# Invalid identifier: cue fmt should do nothing
# with the file, and just report the error
cp x.cue x.cue.golden
! exec cue fmt x.cue
cmp stderr stderr.golden
cmp x.cue x.cue.golden

-- x.cue --
_5
-- stderr.golden --
invalid identifier "_5":
    ./x.cue:1:1
```

### What did you expect to see?

Passing test

### What did you see instead?

```
# Invalid identifier: cue fmt should do nothing
# with the file, and just report the error (0.013s)
> cp x.cue x.cue.golden
> ! exec cue fmt x.cue
[stderr]
invalid identifier "_5":
    ./x.cue:1:1
[exit status 1]
> cmp stderr stderr.golden
> cmp x.cue x.cue.golden
--- x.cue
+++ x.cue.golden
@@ -0,0 +1,1 @@
+_5

```

i.e. `x.cue` is unexpectedly truncated.

**Comment by myitcv** [comment]
Also raised https://github.com/cue-lang/cue/issues/1745 for the issue you flagged, @verdverm

**Comment by marcosnils** [comment]
:wave:  ran into another `fmt` issue that could be relevant here. 

```shell
cue fmt - <<EOF
repo: string

if false == false // foo
{
        repo + "foo"

}, repo + "bar"
EOF
```
produces

```
repo: string

if false == false {
	repo + "foo"
} // foo, repo + "bar"
```

This outputs truncated code given how the comment block is misplaced.

**Comment by NoamTD** [comment]
@myitcv I think this can be closed

**Comment by mvdan** [comment]
Ah yes. I think you would have needed separate "fixes" likes, as GitHub doesn't understand the comma.
