### ISSUE TITLE
sed regexp in kubernetes tutorial not working as intended. 

### ISSUE THREAD

**Issue by LeonardAukea** [cue-lang/cue#1767]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version 
cue version v0.4.3 darwin/amd64

echo $SHELL
/bin/zsh
</pre>

### What did you do?

I was working through the [Kubernetes tutorial](https://github.com/cue-lang/cue/blob/master/doc/tutorial/kubernetes/README.md) 
and noticed what I believe to be a tiny mistake in how the substitution with `sed` was supposed to work

### What did you expect to see?

```bash 
$ ls -d */ | sed 's/.$//' | xargs -I DIR sh -c 'cd DIR; echo "package kube

#Component: \"DIR\"
" > kube.cue; cd ..'
```

### What did you see instead?

```bash 
$ ls -d */ | sed 's/.$//' | xargs -I DIR sh -c 'cd DIR; echo "package kube

#Component: \"DIR\"
" > kube.cue; cd ..'
sh: line 0: cd: fronten: No such file or directory
sh: line 0: cd: infr: No such file or directory
sh: line 0: cd: kitche: No such file or directory
sh: line 0: cd: mo: No such file or directory
sh: line 0: cd: prox: No such file or directory
```

The issue is the slight misplacement in `.`: 

```bash 
$ ls -d */ | sed 's/.$//'                                                   
fronten
infr
kitche
mo
prox
```

What you intended: 

```bash 
$ ls -d */ | sed 's/$.//'                                                 
frontend
infra
kitchen
mon
proxy
```

**Comment by LeonardAukea** [comment]
On a side note, I think the tutorial can be made somewhat more focused by not introducing "bash magic"  in the middle of it. 
Looking forward to more CUE, beautiful design and underpinning idea :pray:

**Comment by rogpeppe** [comment]
@LeonardAukea

What do you see if you type `ls -d */ | cat` in that example (i.e. don't include the `sed` invocation in the pipeline) ?

**Comment by LeonardAukea** [comment]
> @LeonardAukea
> 
> What do you see if you type `ls -d */ | cat` in that example (i.e. don't include the `sed` invocation in the pipeline) ?

@rogpeppe 

```bash
ls -d */ | cat
frontend
infra
kitchen
mon
proxy
```

**Comment by rogpeppe** [comment]
@LeonardAukea That's interesting, because most other shells include a final slash in that case.

I tried this out using `bash` and `zsh` and I get the same result.
Have you got some custom `zsh` settings or otherwise custom shell?

What do you see if you type `echo */` in that example? (I'm wondering if the problem is with your shell or with the version of `ls` that you're using).

Basically, the example in the tutorial does work in most environments, but yours is somehow different.

Perhaps the tutorial should be changed to use this instead, so it's not vulnerable to this difference:

```
ls -d */ | sed -E 's:/?$::'
```

**Comment by LeonardAukea** [comment]
> echo */

```bash 
echo */
frontend/ infra/ kitchen/ mon/ proxy/
```

I'm using zsh and ls command is mapped to [`exa`](https://the.exa.website) which might be the reason I ended up in this scenario 🤷🏻‍♂️ 

```ls
ls --version
exa - list files on the command-line
v0.10.1 [+git]
https://the.exa.website/
```


your suggested command works as expected: 

```bash 
 ls -d */ | sed -E 's:/?$::'
frontend
infra
kitchen
mon
proxy
```

**Comment by mvdan** [comment]
I'm going to close this as "working as intended", since the user had remapped `ls` to a different program with different behavior :) Arguably we could improve the shell line to be a little bit less brittle, but shell will always be a bit platform-dependent in general.
