### ISSUE TITLE
Usage Question - How to compose modules

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#177]
_Originally opened by @robfig in https://github.com/cuelang/cue/issues/177_

CUE is a really exciting development! Intuitively, it seems like an elegant and powerful approach to a tough problem (a rare combination).

I am evaluating it to replace JSON files organized in a directory hierarchy as a way to maintain account configuration across many resources owned by different systems. Each JSON file has a reference to a JSON Schema that validates it.

This seems like a target use case for CUE, but I'm having trouble concretely figuring out how it would work, and I was hoping you could point me in the right direction. 

Here's what I am imagining:

- There are a set of CUE files in a centralized repo that describe the schema of the configuration. It is routinely updated to add new resource types or properties.
- There is a repo per account with that account's configuration. 

Similar to your Kubernetes example, I will make the entire account configuration one large document keyed on system, resource type & name. That means that all CUE files will share the same package. To submit configuration to each system, I will take the document fragment under that system's id. 

However, I wasn't sure how to handle the separation between schema and configuration. Unlike Go, it doesn't seem like putting the schema on github.com/corp/config makes it available to be imported by the account configuration, either automatically or via `cue get`. 

How do you recommend composing multiple CUE modules? Was the idea that I define a cue cmd that fetches the schema, or arrange for the schema to be checked in to the per-account configuration?

Thank you!

**Comment by cueckoo** [comment]
_Original reply by @rudolph9 in https://github.com/cuelang/cue/issues/177#issuecomment-556082284_

[Here]( https://cuelang.slack.com/archives/CLT3ULF6C/p1573866514069000?thread_ts=1573860505.065200&cid=CLT3ULF6C) a thread that dives into this

I can't speak officially for the cuelang team but I would expect `cue get` would be extended to support cue modules but a viable stop gap solution is to use git submodules as described in the thread and demonstrated in the [ipcf/foo repo](https://github.com/ipcf/foo/tree/e7012c57610660190154eca60203ad6140b12af6)

**Comment by cueckoo** [comment]
_Original reply by @robfig in https://github.com/cuelang/cue/issues/177#issuecomment-556858471_

I think I need an invite to log into the Slack workspace, but thanks for the perspective.

**Comment by cueckoo** [comment]
_Original reply by @xinau in https://github.com/cuelang/cue/issues/177#issuecomment-556976509_

@robfig a invite url is in the README.md or use this one https://join.slack.com/t/cuelang/shared_invite/enQtNzQwODc3NzYzNTA0LTAxNWQwZGU2YWFiOWFiOWQ4MjVjNGQ2ZTNlMmIxODc4MDVjMDg5YmIyOTMyMjQ2MTkzMTU5ZjA1OGE0OGE1NmE

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/177#issuecomment-558426278_

Yes, the intention is to support this. Right now you can manually work around this by copying the git repo into `cue.mod/pkg` at the root of your module using the fully qualified package path (essentially manually vendoring it). This will make it available for import in your repo.

I also plan to add (OpenAPI/ JSON schema) -> CUE conversion, which may be of interest here.

**Comment by cueckoo** [comment]
_Original reply by @NicolasRouquette in https://github.com/cuelang/cue/issues/177#issuecomment-584809044_

Thanks @rudolph9 for the git submodule technique!

I've used this w/ v0.0.15 to separate deployment-specific configuration details from shared templates.
However, I've experienced something odd in that `cue cmd <command> ./...` does not seem to look in `cue.mod/pkg/**/*` for related files. Instead, I have to do something like: `cue cmd <command> *.cue cue.mod/pkg/<something>/*.cue`.

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/177#issuecomment-612042116_

There are now various new constructs that aid in slicing and dicing configuration.

Let me know if this is sufficiently addressed. In the meantime I'll remove this from the release tag and morph this in documentation issue.

**Comment by mvdan** [comment]
> How do you recommend composing multiple CUE modules? Was the idea that I define a cue cmd that fetches the schema, or arrange for the schema to be checked in to the per-account configuration?

We now have full support for fetching and publishing CUE modules in the latest alpha release :) See https://cuelang.org/docs/tutorial/working-with-a-custom-module-registry/ for an introduction using a custom registry, for example.

I'm going to close this as resolved for now; please open a new issue if you have any more specific concerns or issues.
