### ISSUE TITLE
Can cue validate number in a string?

### ISSUE THREAD

**Issue by beviz** [cue-lang/cue#1802]
for example:

```YAML
percentages:
  - '10%'
  - '20%'
  - '30%' // sum
```

I want to validate that the third value is the sum of the rest. Does cue support this?
I'm considering using CUE in our project. This is the only validation I've not found.

**Comment by Lyoness** [comment]
Thanks for writing in and sorry we missed this. Hope you found an answer. 

For future reference: The CUE [Github Discussions space](https://github.com/cue-lang/cue/discussions) is the place you can ask these types of questions, for the benefit of all who might have similar questions in future (and also to help improve documenation). 

 You can also chat about what you're trying to do and how CUE might help in the [community slack](https://join.slack.com/t/cuelang/shared_invite/enQtNzQwODc3NzYzNTA0LTAxNWQwZGU2YWFiOWFiOWQ4MjVjNGQ2ZTNlMmIxODc4MDVjMDg5YmIyOTMyMjQ2MTkzMTU5ZjA1OGE0OGE1NmE).
