### ISSUE TITLE
reference: resolve reference can not resolve an optional field

### ISSUE THREAD

**Issue by FogDong** [cue-lang/cue#1816]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
0.4.3
</pre>

### Does this issue reproduce with the latest release?
yes

### What did you do?

Resolve Reference can work fine with required field like:
```
var test = `
#S: string
b: #S`

func main(){
        v := cuecontext.New().CompileString(test)
	node := v.Syntax(cue.ResolveReferences(true))
	formatting, err := format.Node(node)
	if err != nil {
		panic(err)
	}
	fmt.Println(string(formatting))
}
```

And the result is as expected:

```
{
        #S: string
        b:  string
}
```

But if `b` is an optional field like:
```
var test = `
#S: string
b?: #S`
```

The result ends in :
```
{
        #S: string
        b?: #S
}
```

**Comment by mpvl** [comment]
These two results are not the same: in what you _expect_ to see, making `#labelSelector` will not influence `namespaceSelector`, in the actual result it does.

In the new "self-contained" syntax generator you would get something along the lines you expect if you generate the value for `v.LookupPath(cue.ParsePath("namespaceSelector"))`, except that it uses a let expression to get closedness, instead of `close`.

**Comment by FogDong** [comment]
Thanks for the answer, I also find some workarounds by using `cue.Final()` option. Can't wait to use self-contained and thanks you for your help :)

**Comment by FogDong** [comment]
I realize that this is because resolve reference can not resolve optional fields so I update this issue, besides, we can not `lookup` an optional field either.

Can `SelfContain` resolve this problem? 

/cc @mpvl

**Comment by myitcv** [comment]
I think this is covered off by the conversations we've had in https://github.com/cue-lang/cue/issues/1813#issuecomment-1199687724, but please let me know if not.

**Comment by myitcv** [comment]
Per our discussions in various other issues, I think we have identified a better approach via the `cue.Value` API so I will mark this as closed. Please comment if this needs to remain open with details of outstanding issues. Thanks
