### ISSUE TITLE
cmd/cue: support stdin via - for import

### ISSUE THREAD

**Issue by verdverm** [cue-lang/cue#1820]
Many of CUE's commands accept using `-` (hyphen) to specify that the input is from stdin, however `cue import` does not. This would be helpful when piping output from another program or API response to CUE.

**Comment by myitcv** [comment]
This is possible today:

```
stdin x.json
exec cue import -o x.cue json: -
cmp x.cue x.cue.golden

-- x.json --
{
	"x": 5
}
-- x.cue.golden --
x: 5
```

Assuming this covers your use case?

**Comment by christophermaier** [comment]
Yes, this works great @myitcv (this issue was filed on my behalf based on a Slack question). Thanks for the clarification.

(I had missed the bit about the `json:` tag from the `cue filetypes` help text.)

**Comment by mvdan** [comment]
The bug was opened on behalf of @christophermaier's question on Slack, and it appears Paul is right, so I'm going to close this for now :)
