### ISSUE TITLE
Inconsistent behavior for internal and external package definition

### ISSUE THREAD

**Issue by ghost** [cue-lang/cue#1822]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version (devel) linux/amd64
cue version v0.4.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What did you do?

Given:
```
-- cue.mod/module.cue --
module: "example.com"
-- other/other.cue --
package other

#Type: {
    _short?: string
    if _short != _|_ {
        _veryLongLabel: _short
    }
    ...
}
-- root.cue --
package root

import other "example.com/other"

#Type: {
    _short?: string
    if _short != _|_ {
        veryLongLabel: _short
    }
    ...
}

Alice: #Type & {
    _short: "Alice"
}

Bob: other.#Type & {
    _short: "Bob"
}
```

### What did you expect to see?
```
Alice: {
    veryLonglabel: "Alice"
}
Bob: {
    veryLonglabel: "Bob"
}
```

### What did you see instead?
```
Alice: {
    veryLonglabel: "Alice"
}
Bob: {}
```

This issue poped up in the discussion https://github.com/cue-lang/cue/discussions/1804

**Comment by verdverm** [comment]
This is expected, hidden fields are not accessible across package boundaries

**Comment by ghost** [comment]
Is there anyway to make them accessible? Or to achieve similar effect by other means?

**Comment by verdverm** [comment]
You can probably use `#` to have the desired effect

There are differences, in particular openness, but should be able to make it work

**Comment by ghost** [comment]
Thanks. Closing
