### ISSUE TITLE
evaluator: no output or "cycle error" reported while checking existence of non-existing fields

### ISSUE THREAD

**Issue by Somefive** [cue-lang/cue#1837]
### What version of CUE are you using (`cue version`)?

Upgrading from 0.2.2 to 0.4.4.

### Does this issue reproduce with the latest release?

Yes.

### What did you do?

Recently we are upgrade CUE from v0.2.2 to master branch (v0.4.4). We found that the below usage will report "cycle error". I'm not sure if it is a bug that will be fixed in the future (where we only need to upgrade CUE to newer version), or it is a feature that will be kept (where we need to refactor the code style here).
```cue
context: {}
x: context.b
if x == _|_ {
  message: "a"
}
```
The usage here is supported in CUE 0.2.2 but report error in 0.4.4.

**Comment by wonderflow** [comment]
kubevela upgrade related issue, please help mark the label @Somefive

**Comment by myitcv** [comment]
@Somefive sorry, this slipped through the net. 

Please can you confirm what version you are testing with, and complete repro steps? 

I have included a repro below which I believe captures what you are reporting.

### What version of CUE are you using (cue version)?

```
cue version v0.0.0-20220905100514-9e9786e93b63

       -compiler gc
     CGO_ENABLED 1
          GOARCH arm64
            GOOS linux
             vcs git
    vcs.revision 9e9786e93b63af979d9f105a12c8519a6216e56f
        vcs.time 2022-09-05T10:05:14Z
    vcs.modified false
```

### What did you do?

```
exec cue eval x.cue
cmp stdout stdout.golden

-- x.cue --
context: {}
x: context.b
if x == _|_ {
	message: "a"
}
-- stdout.golden --
context: {}
x: context.b
```

### What did you expect to see?

Passing test.

### What did you see instead?

```
> exec cue eval x.cue
> cmp stdout stdout.golden
--- stdout
+++ stdout.golden
@@ -0,0 +1,2 @@
+context: {}
+x: context.b

FAIL: /tmp/testscript442319432/repro.txtar/script.txtar:2: stdout and stdout.golden differ
```

Using v0.4.1 we get different (incorrect) behaviour:

```
> exec cue eval x.cue
[stderr]
cycle error
[exit status 1]
FAIL: /tmp/testscript6714903/repro.txtar/script.txtar:1: unexpected command failure
```

**Comment by Somefive** [comment]
#### Repro
**test.cue**
```cue
context: {}
x: context.b
if x == _|_ {
  message: "a"
}
```
Using cue0.2.2, run `cue eval test.cue`, the result is
```cue
x: context.b
context: {}
message: "a"
```

Using cue-0.4.0, the result is `cycle error`.

### Update

I found that with cue-0.4.3, the result is empty.

The expected result is
```cue
context: {}
x: context.b
```

The behaviour is the same with your reply. Seems the `cycle error` does not exists for v0.4.3 (reported in v0.4.0), but the output is still not as desired.

> FYI, the cue-0.4.0 and cue-0.4.3 above are directly downloaded from the released binary for darwin-arm64. cue-0.2.2 does not have binary for darwin-arm64 so I use the code base of release-0.2.2 and build it.
