### ISSUE TITLE
`os.Environ` is empty

### ISSUE THREAD

**Issue by fmckeogh** [cue-lang/cue#1851]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.4.3 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
cd $(mktemp -d)
cat <<EOF > test.cue 
import (
        "tool/os"
)

os.Environ
EOF
bash -c "cue export test.cue"
```
### What did you expect to see?

```
{
    "$id": "tool/os.Environ"
    "PATH": "/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    "TERM": "xterm"
...etc
}
```

### What did you see instead?

```
{
    "$id": "tool/os.Environ"
}
```

### Debugging Steps Taken

Not a Go developer but using printf debugging I can see that the `pkg/tool/os/env.go:init` function is called, but it does appear that `pkg/tool/os/env.go:newEnvironCmd` or `pkg/tool/os/env.go:Run` are called.

**Comment by slewiskelly** [comment]
The `tools/*` packages are for use in the [scripting layer](https://cuelang.org/docs/usecases/scripting/). For the environment variables to be populated, it must be executed as part of a command (see `cue help commands`).

Consider the following instead:

```cue
// env_tool.cue
package main

import (
	"strings"
	"tool/cli"
	"tool/os"
)

command: env: {
	envs: os.Environ

	print: cli.Print & {
		text: strings.Join([ for k, v in envs {"\(k): \(v)"}], "\n")
	}
}
```

Running `cue env` will then display all environment variables.

**Comment by fmckeogh** [comment]
Ah I see, thank you very much
