### ISSUE TITLE
Definition reference in separate file does not use concrete values

### ISSUE THREAD

**Issue by danielrs** [cue-lang/cue#1853]
I'm trying to define extra constraint for an existing definition in a separate file, however, it seems that the extra constraints only references the original definition and not the concrete values. I'm new to CUE so maybe I'm trying to do something wrong.

### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.4.3 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes it does.

### What did you do?

Created a definition that had a field constraint derived from other field constraints, works OK.

From a different file in the same package, added another field constraint from derived field constraints, did not work OK.

See below:

File `types.cue`:
```
import "math"

#Point: {
  x: int
  y: int
  magnitude: math.Sqrt(x*x + y*y)
}

point: #Point & {
  x: 1
  y: 2
}
```

File `extra.cue`:
```
import "math"

#Point: {
  alsoMagnitude: math.Sqrt(#Point.x * #Point.x + #Point.y * #Point.y)
}
```

### What did you expect to see?

```
$ cue eval types.cue extra.cue
import "math"

#Point: {
    alsoMagnitude: math.Sqrt(#Point.x*#Point.x + #Point.y*#Point.y)
    x:             int
    y:             int
    magnitude:     math.Sqrt(x*x + y*y)
}
point: {
    alsoMagnitude: 2.23606797749979
    x:             1
    y:             2
    magnitude:     2.23606797749979
}
```

### What did you see instead?

```
$ cue eval types.cue extra.cue
import "math"

#Point: {
    alsoMagnitude: math.Sqrt(#Point.x*#Point.x + #Point.y*#Point.y)
    x:             int
    y:             int
    magnitude:     math.Sqrt(x*x + y*y)
}
point: {
    alsoMagnitude: math.Sqrt(#Point.x*#Point.x + #Point.y*#Point.y)
    x:             1
    y:             2
    magnitude:     2.23606797749979
}
```

**Comment by verdverm** [comment]
The way you reference fields in the additional constraint is where this is not working. What you want is

```cue
import "math"

#Point: P={
  alsoMagnitude: math.Sqrt(P.x * P.x + P.y * P.y)
}
```

**Comment by danielrs** [comment]
Thank you that worked perfectly! I wonder if we should put this in the docs somewhere, I did not find anything obvious in:
https://cuelang.org/docs/tutorials/tour/references/
