### ISSUE TITLE
Mutation is being allowed

### ISSUE THREAD

**Issue by kishaningithub** [cue-lang/cue#1874]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.4.3 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

Yes

### Context

The full context of this issue including reproduction steps is present in this discussion thread https://github.com/cue-lang/cue/discussions/1870

**Comment by myitcv** [comment]
Thanks for raising, @kishaningithub. Closing per https://github.com/cue-lang/cue/discussions/1870#discussioncomment-3466217. There is no mutation being allowed here.
