### ISSUE TITLE
evaluator: should RHS builtin call of self be reported as a cycle?

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#1880]
Picking up @verdverm's example in https://github.com/cue-lang/cue/discussions/1870#discussioncomment-3453612

### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.0.0-20220824073610-83d37e79367e

       -compiler gc
     CGO_ENABLED 1
          GOARCH arm64
            GOOS linux
             vcs git
    vcs.revision 83d37e79367ee589d797787b7328ab17a14d39e6
        vcs.time 2022-08-24T07:36:10Z
    vcs.modified false
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
! exec cue eval x.cue
stderr 'cycle'

-- x.cue --
import "strings"

a: "A"
a: strings.ToLower(a)
```

### What did you expect to see?

As written, the test expects a cycle error to be reported. So the expectation is that the test should pass.

### What did you see instead?

Failing test:

```
> ! exec cue eval x.cue
[stderr]
a: conflicting values "a" and "A":
    ./x.cue:3:4
    ./x.cue:4:4
[exit status 1]
> stderr 'cycle'
FAIL: /tmp/testscript2913202972/repro.txtar/script.txt:2: no match for `cycle` found in stderr
```

i.e. no cycle error is reported, and instead a conflicting value error is reported. 

However, it's not clear to me the expectation in the test is correct. Because it's entirely possible that a builtin could be the identity function for a given input. 

Perhaps we need some clarity in the spec on this? 

cc @mpvl for input.

**Comment by mpvl** [comment]
Cycles like `a: a` are explicitly allowed by the spec. 

To me, according to the spec, and the intent of the current implementation
```
a: "a"
a: strings.ToLower(a)
```
is fully valid.

It is akin to
```
a: b+1
b: a-1
```
which is also valid.

**Comment by mpvl** [comment]
Also, builtins like the proposed `must` will rely on being able to refer to the own field.
