### ISSUE TITLE
evaluator: infinite loop with reference to self and valid cyclic definition

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#1882]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.0.0-20220815180007-6b3fd6579004

       -compiler gc
     CGO_ENABLED 1
          GOARCH arm64
            GOOS linux
             vcs git
    vcs.revision 6b3fd657900412db28bc4270aa0bd31d12fa3c48
        vcs.time 2022-08-15T18:00:07Z
    vcs.modified false
</pre>

### Does this issue reproduce with the latest release?

Yes. Bisected to 6b3fd6579004.

### What did you do?

```
exec cue eval x.cue

-- x.cue --
package x

#Output: {
	output?: #Output
}

#Output: #Output

o: #Output
```

### What did you expect to see?

A passing test.

### What did you see instead?

OOM error. The test never completes.

This is a cut down version of a repro from https://github.com/cue-lang/cue/issues/1827, which I was using to test out https://review.gerrithub.io/c/cue-lang/cue/+/542674.

**Comment by mvdan** [comment]
Appears fixed as of master :)

```
$ cue version
cue version v0.6.0-0.dev.0.20230407095412-48207fb5fbfd

go version devel go1.21-231f290e51 Sat Apr 8 05:25:04 2023 +0000
      -buildmode exe
       -compiler gc
        -ldflags -w -s
  DefaultGODEBUG panicnil=1
     CGO_ENABLED 1
          GOARCH amd64
            GOOS linux
         GOAMD64 v3
$ cue eval f.cue
#Output: {}
o: {}
```
