### ISSUE TITLE
internal/core/convert: cue tag can't be parsed when cue contains a comma (using cuego)

### ISSUE THREAD

**Issue by ghostwheel42** [cue-lang/cue#1887]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.4.3 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```go
package main

import (
	"fmt"

	"cuelang.org/go/cuego"
)

type Comma struct {
	Letters string `json:"letters,omitempty" cue:"=~\"^[a-z](,[a-z])*$\",opt"`
}
type Semikolon struct {
	Letters string `json:"letters,omitempty" cue:"=~\"^[a-z](;[a-z])*$\",opt"`
}

func main() {
	s := Semikolon{"a;b;c;d"}
	if err := cuego.Validate(s); err != nil {
		fmt.Println(err)
	} else {
		fmt.Println(s.Letters)
	}
	c := Comma{"a,b,c,d"}
	if err := cuego.Validate(c); err != nil {
		fmt.Println(err)
	} else {
		fmt.Println(c.Letters)
	}
}
```

### What did you expect to see?

```
a;b;c;d
a,b,c,d
```

### What did you see instead?

```
a;b;c;d
invalid tag "=~\"^[a-z](" for field "letters": string literal not terminated (and 1 more errors)
```

The [functions parsing the cue tag](https://github.com/cue-lang/cue/blob/2fea90a631b14946ca0ffac025e64da2d09d3e27/internal/core/convert/go.go#L78) strips everything after the first comma to allow adding options (like "opt" or "req").

I see three possible ways to change the parser:
1. strip "known" options from the end (currently "opt" and "req")
1. find and skip pairs of (not escaped) quotes from the start
1. assume the options can't contain a quote: split at the first comma after the last quote (if any)

I'm in favor of option #3 as it would be relatively simple to implement while still being generic.
I've [implemented a fix](https://github.com/cue-lang/cue/compare/master...ghostwheel42:cue:update_cue_tag_parser) and can prepare a PR if you'd like me to.

**Comment by mvdan** [comment]
Personally, I agree that option 1 isn't great, and option 3 seems reasonable to me. Option 2 also seems reasonable, but I agree that the extra code doesn't seem necessary right away. cc @rogpeppe @4ad to see if they have thoughts.

**Comment by mvdan** [comment]
Agreed with @mpvl that this is a worthwhile improvement.
