### ISSUE TITLE
cmd/cue: mod root not found

### ISSUE THREAD

**Issue by verdverm** [cue-lang/cue#1899]
### What version of CUE are you using (`cue version`)?

`v0.4.3`

### What did you do?

evaluating a file is ok, evaluating a dir reports error

```txt
cd foo
exec cue eval ../bar/bar.cue
exec cue eval ../bar

-- foo/dummy.txt --
-- bar/bar.cue --
package bar

Bar: "Bar"
-- bar/cue.mod/module.cue --
module: "hof.io/repro"
```

### What did you expect to see?

```
Bar: "Bar"
```

### What did you see instead?

```
> cd foo
$WORK/foo
> exec cue eval ../bar/bar.cue
[stdout]
Bar: "Bar"
> exec cue eval ../bar
[stderr]
module root not defined%!(EXTRA string=../bar)
[exit status 1]
FAIL: /tmp/testscript384782878/0/script.txt:2: unexpected command failure
error running modroot.txt in /tmp/testscript384782878/0
```

**Comment by mvdan** [comment]
Just so we're on the same page, why did you expect that to succeed? The "current" or "main" module, i.e. the module used to load and evaluate packages, is found by starting at the directory where you're running `cue` from. In the scenario you describe above, running it inside `/work/foo` will not find the module in `/work/bar`, as it's not in the chain of parent directories.

That said, I can't easily find a piece of docs that properly explains this under `cue help` or https://cuelang.org/docs/concepts/packages/. I am carrying over that knowledge from Go, as CUE's modules work in a very similar way :)

Also, that `%!(EXTRA` output is a bug; the error message should use a formatting verb.

**Comment by verdverm** [comment]
I would expect that evaluating a file and the directory containing that file to have the same behavior. In the example, the behavior is different. In both cases, `cue` is run from outside any module

I would also argue that CUE fills a different role and will have different usage patterns, such that CUE should not (and doesn't already) have 100% alignment with how Go handles modules

**Comment by mvdan** [comment]
To be clear, I'm not saying that the current behavior is right for CUE - I'm simply explaining how the behavior was most likely carried over from Go. My intuition is that we won't want to deviate from its behavior unless necessary, given how Go's system is proven to work.

> would expect that evaluating a file and the directory containing that file to have the same behavior.

The difference (again, carried knowledge from Go) is that specifying a set of files means an "ad-hoc package" which does not belong to any one directory (the files could be in different directories after all), so it does not matter whether the files are inside or outside of a module. Specifying a directory is different, as that is a regular package that should be inside of a module.

**Comment by myitcv** [comment]
> I would expect that evaluating a file and the directory containing that file to have the same behavior. In the example, the behavior is different. In both cases, `cue` is run from outside any module

I'm not clear that the way `cmd/cue` (and `cmd/go`) behaves here is wrong per se. Indeed, if we were to perform dependency resolution within the directory that contains a file, what would happen if multiple files are specified that result in multiple modules with potentially multiple versions of the "same" import? The current logic is simply to explain and reason about. 

FWIW, `cmd/go` is adding the `-C` flag, just like `tar`:

https://go-review.googlesource.com/c/go/+/421436

So this would allow for behaviour akin to setting [`cue/load.Confg.Dir`](https://pkg.go.dev/cuelang.org/go/cue/load#Config). I would suggest we therefore do the same for `cmd/cue`.

**Comment by myitcv** [comment]
I've raised https://github.com/cue-lang/cue/issues/1918 to suggest we add `-C` to `cmd/cue`, linking back to this issue.

I'd suggest we close this issue in favour of that unless anyone has any objections?

**Comment by mvdan** [comment]
I  agree with what Paul wrote above. Closing for now.
