### ISSUE TITLE
ci: pull every commit through the proxy

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#1915]
**Is your feature request related to a problem? Please describe.**

When running `go get cuelang.org/go@$commit` via proxy.golang.org, it generally takes a long time to resolve because the proxy has to resolve from that commit to a pseudo-version. Later requests are cached, so much faster. This makes testing, creating repros etc more painful.

**Describe the solution you'd like**

`go get cuelang.org/go@$commit` to be run as part of CI for each new commit on `master`.

**Describe alternatives you've considered**

Running this myself, but it's better placed in CI as part of the build for each new commit on tip.

**Additional context**

n/a

**Comment by mvdan** [comment]
I'm slightly confused; don't we already do this in https://github.com/cue-lang/cue/blob/9e9786e93b63af979d9f105a12c8519a6216e56f/internal/ci/github/trybot.cue#L89?

**Comment by myitcv** [comment]
Hmm good spot. To be honest I didn't check, and instead assumed we were only doing this for semantic versions.

Because this is the kind of thing I see locally:

```
$ go get -x cuelang.org/go@748a68589747fed6273d6338eb7e275a4fb116c6
# get https://proxy.golang.org/cuelang.org/go/@v/748a68589747fed6273d6338eb7e275a4fb116c6.info
# get https://proxy.golang.org/cuelang.org/@v/748a68589747fed6273d6338eb7e275a4fb116c6.info
# get https://proxy.golang.org/cuelang.org/@v/748a68589747fed6273d6338eb7e275a4fb116c6.info: 404 Not Found (1.453s)
# get https://proxy.golang.org/cuelang.org/go/@v/748a68589747fed6273d6338eb7e275a4fb116c6.info: 200 OK (6.713s)
# get https://proxy.golang.org/cuelang.org/go/@v/list
# get https://proxy.golang.org/cuelang.org/go/@v/list: 200 OK (0.066s)
go: added cuelang.org/go v0.4.4-0.20220622094641-748a68589747
```

6.7s to resolve a commit that has already been pulled through the proxy. 

I'll raise this as a Go issue to see if there's anything up with the proxy.

Thanks for catching this.

**Comment by myitcv** [comment]
The Go issue for completeness https://github.com/golang/go/issues/54977

**Comment by mvdan** [comment]
Just a guess, but that is a fairly old commit. I wouldn't be surprised if their caching mechanism didn't keep every single VCS ref around for quick resolution forever. Perhaps they get kicked out of the cache if unused for a few weeks.

**Comment by mvdan** [comment]
To be clear, by fairly old I mean that https://review.gerrithub.io/c/cue-lang/cue/+/529524 was submitted in late June, meaning that it's been over two months since we last pulled this commit through the proxy in CI.

**Comment by myitcv** [comment]
I did a `go get` with that commit earlier today. I'll be clear on that in the Go issue.
