### ISSUE TITLE
Add function for uuidgen

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#192]
_Originally opened by @epcim in https://github.com/cuelang/cue/issues/192_

1. add UUID library, to be able to define UUID's dynamically.
1. The special use-case is where you want to repeatedly generate output with the constant UUIDs generated.

[2] is quite common pattern, when it comes to configuration flexibility, not just for UUID but for passwords, etc. To solve it you need an external database that will store already generated values by unique keys in an object (like namespace/name etc..)

**Comment by cueckoo** [comment]
_Original reply by @xinau in https://github.com/cuelang/cue/issues/192#issuecomment-558146357_

A problem with uuid's is that they are not relay hermetic if they use a random input. Thus such functions should only be available to `_tool.cue` configurations. 

I'm not sure who mentioned it @mpvl or @rogpeppe or someone else. A possible solution to make the output of this function hermetic would be to use the value lattice or another value generated from the global configuration as input to the uuid function. Thus resulting in the same output for each evaluation.

**Comment by cueckoo** [comment]
_Original reply by @epcim in https://github.com/cuelang/cue/issues/192#issuecomment-558211677_

Yes hermetic output would need a Custom function (not necessary just for uuid) that would have as input an dematerialized reference and storage or general configuration file behind in order to load values that were already defined.This usecase fit for dynamically generated password, encrypted secrets or even integration with 3rs party backends.In the mean time as uuid like IDs are in any configuration is there any workaround that can be used (custom functions etc?)On 25 Nov 2019 14:05, Felix Ehrenpfort <notifications@github.com> wrote:A problem with uuid's is that they are not relay hermetic if they use a random input. Thus such functions should only be available to _tool.cue configurations.
I'm not sure who mentioned it @mpvl or @rogpeppe or someone else. A possible solution to make the output of this function hermetic would be to use the value lattice or another value generated from the global configuration as input to the uuid function. Thus resulting in the same output for each evaluation.

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/192#issuecomment-558414839_

Would it be acceptable to have this available in the tooling layer only? If not, why not?

If it is just a matter of it being tedious, we can think about how to mitigate that.

So far, most of the initial thoughts of computing such values deterministically have their issues.

**Comment by cueckoo** [comment]
_Original reply by @epcim in https://github.com/cuelang/cue/issues/192#issuecomment-569612254_

deterministic calculation of UUID is not use-case for cue 100%!
(MISSING)

if the `tooling layer` is capable to call my binary with attributes (like "denormalized name/key" and my binary will return a cached UUID or NEW UUID) then we can close.

possibly to update doc with some examples

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/192#issuecomment-580836630_

We’re still trying to find a good general data representation for non-hermetic functions. 
But looking at this again, storing values in a database of some sort seems somewhat out the scope of cue. I wonder if there is a way to invoke a tool more generically, without baking it in to cue directly (using exec or http for instance). How do other languages manage this? 

For instance an easy way to do this is cue is to have a tool that generates a cue file that is included.

**Comment by cueckoo** [comment]
_Original reply by @NicolasRouquette in https://github.com/cuelang/cue/issues/192#issuecomment-582953473_

@epcim Which UUID versions are in scope of this issue?

Versions 1,2,4 are non-hermetic; thus as @xinau mentioned, they ought be available only in a `_tool.cue` configuration.

Versions 3 and 5 are hermetic since they are deterministic hashes of an input.

Since Version 3 is defined in terms of MD5 hashing, couldn't it be defined using the [pkg.crypto.md5 package](https://pkg.go.dev/cuelang.org/go@v0.0.15/pkg/crypto/md5?tab=doc)?

Similarly, Version 5 is defined in terms of SHA-1 hashing, couldn't it be defined using the [pkg.crypto.sha1 package](https://pkg.go.dev/cuelang.org/go@v0.0.15/pkg/crypto/sha1?tab=doc)?

**Comment by cueckoo** [comment]
_Original reply by @grantzvolsky in https://github.com/cuelang/cue/issues/192#issuecomment-655429168_

I just stumbled upon this while doing a database schema migration with Cue. Here's an example mapper from `v1.#User` to `v2.#User` with `IsVerified: bool` => `TsEmailVerified: null | #Timestamp` 

```
#UserTransformer: {
  in: v1.#User
  out: v2.#User & {
    ID: in.ID
    Email: in.Email
    TsEmailVerified: *{if in.IsVerified { value: 1594000000 }}.value | null
  }
}
```
The problem is that in another case, a value-object that was previously embedded an entity now has its own identity. This requires giving each instance its own UUID. I'd like to deterministically generate these UUIDs from a seed hardcoded into the transformer and the instance's sequence number. Or even simpler, a UUID sequence starting at some predetermined UUID would suffice.

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/192#issuecomment-829880861_

See https://cue-review.googlesource.com/c/cue/+/9566/4 for an implementation of V3 and V5.

If this isn't sufficient, we could later add the other versions, building on top of the proposed injection mechanisms that allows injection of values in a controlled manner. This would allow all to be used within regular CUE, while still being hermetic.

The `path` package is an example of the direction in which this is heading: it takes an operating system as optional argument. The idea is that the tooling can inject this based on the environment upon request, making it akin to specifying injected values on the command line.

**Comment by myitcv** [comment]
Closing for now on the basis we landed support for v3 and v5 in https://cue-review.googlesource.com/c/cue/+/9566/4. Can easily revisit further support in another issue or by reopening this one.
