### ISSUE TITLE
notify developers when a merge to master breaks CI

### ISSUE THREAD

**Issue by mvdan** [cue-lang/cue#1930]
Because we use GerritHub as the source of truth and GitHub as a git mirror, pushes to GerritHub get mirrored by GerritHub to GitHub.

This has one unintented side effect: when a push to master breaks CI (for example, due to the CL being green before merge, but not being rebased on the latest master, and then its merge on top of master leading to a test failure), we don't get a notification at all.

https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/notifications-for-workflow-runs says:

> If you enable email or web notifications for GitHub Actions, you'll receive a notification when any workflow runs that you've triggered have completed. The notification will include the workflow run's status (including successful, failed, neutral, and canceled runs). You can also choose to receive a notification only when a workflow run has failed.

Note that notifications are sent to the user who _triggered_ a workflow. In our case, this is the user doing a `git push`, which is presumably a GerritHub bot or integration. It's not us, in any case.

So we've broken CI a few times and only noticed hours later, when other CLs start failing after being rebased, or when someone happens to look at our repo on GitHub.

I think we could have one last step for our trybot (test) workflow job, which would only run on failure, and which would notify us. We could do email, but only sending an email to the people involved isn't great. For example, if someone submits a CL and then goes off for lunch, they might not see the email for a while, and others wouldn't get notified. The alert should ideally notify the developers who are online right now.

So, as an alternative to an email, I suggest that we make the "on failure" step post a chat notification, such as on our public Slack. We could consider a mention like @-here or some group/role for the group of people responsible for the repository being green. This shouldn't be too hard - on platforms like Slack or Discord, it's often easy to post a message as a bot via an HTTP POST request with an auth token.

**Comment by myitcv** [comment]
Just came to mind, that we also need to flag `unity` failures too.

**Comment by mvdan** [comment]
We ended up doing this via our workflow and job run github webhooks - when we notice a workflow failure on a default branch on any of our important repos, we post a notification to Discord.
