### ISSUE TITLE
cmd/cue: fmt silently fails to work when there are missing imports

### ISSUE THREAD

**Issue by rogpeppe** [cue-lang/cue#1938]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.0.0-20220915174651-ad253ed099e9

       -compiler gc
     CGO_ENABLED 1
          GOARCH amd64
            GOOS linux
         GOAMD64 v1
             vcs git
    vcs.revision ad253ed099e94ddcffd07e6f73a76735a96cfaf8
        vcs.time 2022-09-15T17:46:51Z
    vcs.modified false

</pre>

### Does this issue reproduce with the latest release?

No, the error isn't silent under v0.4.3.

### What did you do?

I ran this testscript file:

```
exec cue fmt x1/x1.cue x2/x2.cue
cmp x1/x1.cue expectx1.cue
cmp x2/x2.cue expectx2.cue

-- x1/x1.cue --
package x

import _ "github.com/foo/bar"
-- x2/x2.cue --
package y

	needsFormat: int

-- expectx1.cue --
package x

import _ "github.com/foo/bar"
-- expectx2.cue --
package y

needsFormat: int
```

### What did you expect to see?

A passing test.

### What did you see instead?

```
> exec cue fmt x1/x1.cue x2/x2.cue
> cmp x1/x1.cue expectx1.cue
> cmp x2/x2.cue expectx2.cue
--- x2/x2.cue
+++ expectx2.cue
@@ -1,4 +1,3 @@
 package y
 
-	needsFormat: int
-
+needsFormat: int

FAIL: /tmp/testscript1726192439/x.txtar/script.txtar:3: x2/x2.cue and expectx2.cue differ
```

That is, the `cue fmt` command appears to succeed but doesn't actually format all the files.

Under v0.4.3 I see this instead:

```
found packages "x" (x1.cue) and y (x2.cue) in "$WORK"
import failed: cannot find package "github.com/foo/bar":
    ./x1/x1.cue:3:8
```

I would argue that both these failures are spurious. If I give `cue fmt` an explicit list of CUE files, I think it should probably format them independently and regardless of unresolved imports.

**Comment by myitcv** [comment]
See also https://github.com/cue-lang/cue/issues/728

**Comment by myitcv** [comment]
~In the context of modules, this is becoming very painful.~

~cc @mvdan who had an idea on one way of dealing with this.~

Update: https://github.com/cue-lang/cue/issues/728#issuecomment-2009447284
