### ISSUE TITLE
String values don't render correctly in JSON / YAML output

### ISSUE THREAD

**Issue by deleted** [cue-lang/cue#1947]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.4.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
I believe 0.4.3 is the latest release as of this time

### What did you do?

```
# specify a string disjunction, and resolve it to a single element
$ cat test2.cue 
category: 'blue' | 'orange' | 'green'

category: 'green'

# this works as expected when outputting in cue format
$ cue eval test2.cue --out cue
category: 'green'

# but not when outputting to json. is this a hashed value?
$ cue eval test2.cue --out json
{
    "category": "Z3JlZW4="
}

# it also affects the YAML output
$ cue eval test2.cue --out yaml
category: !!binary Z3JlZW4=
```

### What did you expect to see?
I would expect the following JSON output:
```json
{
    "category": "green"
}

```

### What did you see instead?
```json
{
    "category": "Z3JlZW4="
}
```

**Comment by deleted** [comment]
Actually scalar strings don't seem to work either. I will change the name of the issue:

```
$ cat test3.cue 
color: 'green'
category: 'solid'

$ cue eval test3.cue --out cue
color:    'green'
category: 'solid'

$ cue eval test3.cue --out json
{
    "color": "Z3JlZW4=",
    "category": "c29saWQ="
}
```

**Comment by slewiskelly** [comment]
As per the [documentation](https://cuelang.org/docs/tutorials/tour/types/bytes/):

> CUE distinguishes between a string and a bytes type. Bytes are converted to base64 when emitting JSON. Byte literals are defined with single quotes. 

Using double quotes works as expected: 

```cue
category: "blue" | "orange" | "green"

category: "green"
```

```console
$ cue export --out json test2.cue
{
    "category": "green"
}

$ cue export --out yaml test2.cue
category: green
```

**Comment by deleted** [comment]
Thanks @slewiskelly.
Makes sense to me. Closing the issue.
