### ISSUE TITLE
References to let declarations in lists evaluate as a string-typed index (regression)

### ISSUE THREAD

**Issue by seh** [cue-lang/cue#1955]
### What version of CUE are you using (`cue version`)?
<pre>
cue version v0.4.4-0.20220923153140-830b138ebfb6

       -compiler gc
     CGO_ENABLED 1
          GOARCH amd64
            GOOS darwin
         GOAMD64 v1
</pre>

### Does this issue reproduce with the latest release?
No. The latest released version is 0.4.3, and this problem does not occur in that version.

### What did you do?
Feed the following CUE source to _cue export_:
```cue
let x = {
    a: 1
}
[
    x
]
```

### What did you expect to see?
Per [the CUE Playground using version 0.4.3](https://cuelang.org/play/?id=UhDvK97qMO2#cue@export@cue):
```cue
[{
	a: 1
}]
```

### What did you see instead?
Per [the CUE Playground using the "tip" version](https://tip.cuelang.org/play/?id=UhDvK97qMO2#cue@export@cue):
```
0: invalid list index x (type string):
    -:5:5
```
Only by expanding the let declaration's right hand side inline can I get this to evaluate properly, but that transformation is not always practical. Note that [referring to preceding definition rather than a `let` declaration](https://tip.cuelang.org/play/?id=1uQKVeDPzwE#cue@export@cue) works in most cases.

**Comment by myitcv** [comment]
Thanks very much for finding and raising this, @seh. Bisected to 36bd6562f7ba43afbd850abfa565da5576117154:

```
go mod tidy
exec go run cuelang.org/go/cmd/cue eval x.cue
cmp stdout stdout.golden

-- go.mod --
module "mod.com"

require cuelang.org/go v0.4.4-0.20220923153140-830b138ebfb6

-- tools.go --
// +build tools

package tools

import _ "cuelang.org/go/cmd/cue"
-- x.cue --
let x = {
    a: 1
}
[
    x
]
-- stdout.golden --
[{
    a: 1
}]
```

**Comment by seh** [comment]
Thank you for the quick fix, Marcel.
