### ISSUE TITLE
Struct field disjunction does not unify properly (regression)

### ISSUE THREAD

**Issue by seh** [cue-lang/cue#1956]
### What version of CUE are you using (`cue version`)?
<pre>
cue version v0.4.4-0.20220928102958-cad3f2394c59

       -compiler gc
     CGO_ENABLED 1
          GOARCH amd64
            GOOS darwin
         GOAMD64 v1
</pre>

### Does this issue reproduce with the latest release?
No. The latest released version is 0.4.3, and this problem does not occur in that version.

### What did you do?
Feed the following CUE source to cue export:
```cue
#ThingA: {
    kind: "KindA"
    #Details: {
        size: int | *1
    }
    #Details
}

#ThingB: {
    kind: "KindB"
    #Details: {
        name?: string
    }
    #Details
}

#Thing: {
    kind: "KindA" | "KindB"
    if kind == "KindA" {
        #ThingA.#Details
    }
    if kind == "KindB" {
        #ThingB.#Details
    }
}

x: #Thing & #ThingA
```
Admittedly, it's an odd approach, but it resulted from working around other defects back around the version 0.4.2 era.

### What did you expect to see?
Exported as YAML, per [the CUE Playground using version 0.4.3](https://cuelang.org/play/?id=HT4zrA1aUsX#cue@export@yaml):
```yaml
x:
  kind: KindA
  size: 1
```

### What did you see instead?
Per [the CUE Playground using the "tip" version](https://tip.cuelang.org/play/?id=HT4zrA1aUsX#cue@export@yaml):
```
t.kind: 2 errors in empty disjunction:
t.kind: conflicting values "KindB" and "KindA":
    -:2:11
    -:18:21
    -:27:4
    -:27:13
t.kind: field not allowed:
    -:2:5
    -:3:15
    -:6:5
    -:18:5
    -:19:5
    -:19:24
    -:20:9
    -:27:4
    -:27:13
```

Changing the approach to use a disjunction enclosing the `#Thing.kind` field [fixes the problem](https://tip.cuelang.org/play/?id=8_oEfPJipX9#cue@export@yaml), which is nice to see, as I used to find that this approach often didn't work for me.
```cue
#ThingA: {
    kind: "KindA"
    #Details: {
        size: int | *1
    }
    #Details
}

#ThingB: {
    kind: "KindB"
    #Details: {
        name?: string
    }
    #Details
}

#Thing: {
    {
        kind: "KindA"
        #ThingA.#Details
    } | {
        kind: "KindB"
        #ThingB.#Details
    }
}

x: #Thing & #ThingA
```

**Comment by myitcv** [comment]
Thanks for the repro. Bisected to 748a68589747:

Here is a smaller repro:

```
go mod tidy
go run cuelang.org/go/cmd/cue eval -e x x.cue
cmp stdout stdout.golden

-- go.mod --
module mod.com

require cuelang.org/go v0.4.4-0.20220622094641-748a68589747
-- tools.go --
// +build tools
package tools
import _ "cuelang.org/go/cmd/cue"
-- x.cue --
#Details: {
	size: int | *1
}

#Thing: {
	kind: "KindA" | "KindB"
	if kind == "KindA" {
		#Details
	}
}

x: #Thing & {
	kind: "KindA"
}
-- stdout.golden --
kind: "KindA"
size: 1
```

**Comment by mpvl** [comment]
Analyzing old code, it seems like this bug was always there, but was masked by another bug that has now been fixed. Further investigating.
