### ISSUE TITLE
evaluator: structural cycle reported where non existed before

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#1960]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.0.0-20220915144858-36bd6562f7ba

       -compiler gc
     CGO_ENABLED 1
          GOARCH arm64
            GOOS linux
             vcs git
    vcs.revision 36bd6562f7ba43afbd850abfa565da5576117154
        vcs.time 2022-09-15T14:48:58Z
    vcs.modified true
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
exec cue export -e z x.cue
cmp stdout stdout.golden

-- x.cue --
_p: #z: {
	n: string
	e: p: {}
}

#z: {
	n: string
	p: t: "e"
	s: [...string]
	r: (_p.#z & {n: n})[p.t]
	for _, pl in r.p {
		if pl.blah {
		}
	}
}

#i: {
	#z
	t: "i"
	r: e: {}
}

#c: {
	#z
	t: "c"
	n: string
}

z: [N= =~"^b"]: #i & {
	s: [
		for n, z in z
		if z.t == "c"
		if z.n == N {n},
	]
}

z: [N= =~"^h"]: #c & {
	n: string
	let q = z[n]
	p: q.r.e
}

z: {
	"blah": n: ""
	"hello": {
		n: "blah"
	}
}
-- stdout.golden --
{
    "blah": {
        "n": "",
        "t": "i",
        "p": {
            "t": "e"
        },
        "s": [
            "hello"
        ],
        "r": {
            "p": {},
            "e": {}
        }
    },
    "hello": {
        "t": "c",
        "n": "blah",
        "p": {
            "t": "e"
        },
        "s": [],
        "r": {
            "p": {}
        }
    }
}
```

### What did you expect to see?

Passing test

### What did you see instead?

```
> exec cue export -e z x.cue
[stderr]
z.hello.q: structural cycle:
    ./x.cue:40:5
[exit status 1]
FAIL: /tmp/testscript1639836107/repro.txtar/script.txtar:1: unexpected command failure
```

Bisected to 36bd6562f7ba43afbd850abfa565da5576117154

**Comment by mpvl** [comment]
Analysis: the core issue can be reduced to this:
```
	a: {
		b: 1
		let X = a
		c: X.b
	}
```
If `X` were a regular field, this would clearly be a structural cycle. But it is not for a let, as it is not part of the structure. Now `let` is "harmonized" with regular fields, they should be made explicitly exempt from such errors.

**Comment by myitcv** [comment]
For completeness, I updated the original description to use `cue export` instead of `cue eval`.
