### ISSUE TITLE
tools/fix: rewrites `x mod y` with __mod even when there isn't any shadowing

### ISSUE THREAD

**Issue by rogpeppe** [cue-lang/cue#1966]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.0.0-20220915174651-ad253ed099e9

      -buildmode exe
       -compiler gc
     CGO_ENABLED 1
          GOARCH amd64
            GOOS linux
         GOAMD64 v1
             vcs git
    vcs.revision ad253ed099e94ddcffd07e6f73a76735a96cfaf8
        vcs.time 2022-09-15T17:46:51Z
    vcs.modified false

</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
exec cue fmt x.cue
cmp x.cue expect.cue

-- x.cue --
x: y mod 3
y: int

-- expect.cue --
import "math"

x: math.Mod(y, 3)
y: int
```

### What did you expect to see?

A passing test.

### What did you see instead?

```
> exec cue fmt x.cue
> cmp x.cue expect.cue
--- x.cue
+++ expect.cue
@@ -1,2 +1,4 @@
-x: __mod(y, 3)
+import "math"
+
+x: math.Mod(y, 3)
 y: int

FAIL: /tmp/testscript1989248800/x.txtar/script.txtar:2: x.cue and expect.cue differ
error running /tmp/x.txtar in /tmp/testscript1989248800/x.txtar
```

The `x mod 3` expression has been changed to use the built-in `__mod` function, which is non-idiomatic and undocumented AFAICS.
It would be better to rewrite it to use the standard library's `math.Mod` function.

**Comment by rogpeppe** [comment]
After a bit more investigation, `math.Mod` is _not_ a suitable replacement for the `mod` operator because it returns `float` not `int`, so can't be used in all the same operations (e.g. indexing into a list).

**Comment by myitcv** [comment]
> The `x mod 3` expression has been changed to use the built-in `__mod` function, which is non-idiomatic and undocumented AFAICS.

https://tip.cuelang.org/docs/references/spec/#div-mod-quo-and-rem

The fact it rewrite it to `__mod()` instead of `mod()` is the bug here I think.

**Comment by mvdan** [comment]
I don't think this was a bug; it appears to be intentional as of https://cue-review.googlesource.com/c/cue/+/7824.

```
				c.Replace(&ast.CallExpr{
					// Use the __foo version to prevent accidental shadowing.
					Fun:  ast.NewIdent("__" + x.Op.String()),
					Args: []ast.Expr{x.X, x.Y},
				})
```

That said, the code should be clever enough to use `__mod` instead of `mod` if it can tell there isn't any shadowing that can happen.

**Comment by mvdan** [comment]
Also, this is `tools/fix` and not the formatter itself, even if `tools/fix` is used by `cue fmt`. I think the fmt label and milestone should be used for formatting bugs, i.e. those affecting the `cue/format` package.

**Comment by myitcv** [comment]
I believe this is superseded by https://github.com/cue-lang/cue/issues/2932.
