### ISSUE TITLE
evaluator: strconv.Atoi causes inappropriate conversion to float on output

### ISSUE THREAD

**Issue by rogpeppe** [cue-lang/cue#1967]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.0.0-20221001181137-79d80efc2882

      -buildmode exe
       -compiler gc
     CGO_ENABLED 1
          GOARCH amd64
            GOOS linux
         GOAMD64 v1
             vcs git
    vcs.revision 79d80efc288208410f77d47ae9aedd37e106d84b
        vcs.time 2022-10-01T18:11:37Z
    vcs.modified false
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What did you do?

```
exec cue export --out cue x.cue
cmp stdout expect.cue

-- x.cue --
import "strconv"
a: 1_0123456789_0123456789_0123456789
b: strconv.Atoi("0") + a

-- expect.cue --
a: 1012345678901234567890123456789
b: 1012345678901234567890123456789
```

### What did you expect to see?

A passing test.

### What did you see instead?
```
> exec cue export --out cue x.cue
[stdout]
a: 1012345678901234567890123456789
b: 1.01234567890123456789012e+30
> cmp stdout expect.cue
--- stdout
+++ expect.cue
@@ -1,2 +1,2 @@
 a: 1012345678901234567890123456789
-b: 1.01234567890123456789012e+30
+b: 1012345678901234567890123456789

FAIL: /tmp/testscript1438607268/x.txtar/script.txtar:2: stdout and expect.cue differ
```

Precision has been lost on output by using floating point format to print the value.

**Comment by NoamTD** [comment]
@mvdan this test no longer fails on master

**Comment by mvdan** [comment]
Well spotted, thanks!
