### ISSUE TITLE
cuelang.org: doc not updated as cli output

### ISSUE THREAD

**Issue by peter-wangxu** [cue-lang/cue#1971]
url: https://cuelang.org/docs/tutorials/tour/references/emit/

emit.cue
```cue
"Hello \(#who)!"

#who: "world"
```

when execute `$ cue eval emit.cue`

my local got 
```
"Hello world!"
#who: "world"
```
which differs from the doc

**Comment by myitcv** [comment]
Thank you for spotting this, @peter-wangxu. 

This has been fixed at tip, and will be visible as part of the next release of CUE.

For now you can view:

https://tip.cuelang.org/docs/tutorials/tour/references/emit/
