### ISSUE TITLE
evaluator: two level comprehension loses keys

### ISSUE THREAD

**Issue by rogpeppe** [cue-lang/cue#1974]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.0.0-20221001181137-79d80efc2882

      -buildmode exe
       -compiler gc
     CGO_ENABLED 1
          GOARCH amd64
            GOOS linux
         GOAMD64 v1
             vcs git
    vcs.revision 79d80efc288208410f77d47ae9aedd37e106d84b
        vcs.time 2022-10-01T18:11:37Z
    vcs.modified false
</pre>

### Does this issue reproduce with the latest release?

No, it's on tip only.

### What did you do?

```
exec cue export test.cue
cmp stdout expect.json

-- test.cue --
in: {
	foo: {
		bar: ""
		baz: ""
	}
}
out: {
	for k, v in in for vk, vv in v {
		"\(k)": "\(vk)": vv
	}
}
-- expect.json --
{
    "in": {
        "foo": {
            "bar": "",
            "baz": ""
        }
    },
    "out": {
        "foo": {
            "bar": "",
            "baz": ""
        }
    }
}
```

### What did you expect to see?

A passing `testscript` run.

### What did you see instead?

```
> exec cue export test.cue
[stdout]
{
    "in": {
        "foo": {
            "bar": "",
            "baz": ""
        }
    },
    "out": {
        "foo": {
            "bar": ""
        }
    }
}
> cmp stdout expect.json
--- stdout
+++ expect.json
@@ -7,7 +7,8 @@
     },
     "out": {
         "foo": {
-            "bar": ""
+            "bar": "",
+            "baz": ""
         }
     }
 }

FAIL: /tmp/testscript382054878/x.txtar/script.txtar:2: stdout and expect.json differ
```
Thanks to @Fionera on the CUE Slack for reporting this issue.
Bisected to 6b3fd657900412db28bc4270aa0bd31d12fa3c48

**Comment by mpvl** [comment]
This is caused by an overaggressive performance optimization which was a bit overzealous removing duplicates.
