### ISSUE TITLE
cuelang.org: YAML documentation

### ISSUE THREAD

**Issue by retnuh** [cue-lang/cue#1978]
The https://cuelang.org/docs/integrations/yaml/ page, the `Create` and `Parse` subsections show JSON output, not YAML.

**Comment by retnuh** [comment]
Actually, now that I look closer, the data strings are YAML, but embedded in JSON.  It's confusing.  It would probably make more sense to have the examples be YAML-in-YAML, not YAML-in-JSON.

**Comment by myitcv** [comment]
@retnuh - thanks for raising this. We finally got to address this as part of the new site. Please take a look at https://cuelang.org/docs/concept/how-cue-works-with-yaml/ and let us know what you think.
