### ISSUE TITLE
cuelang.org: "view page source" links seem to be broken

### ISSUE THREAD

**Issue by mvdan** [cue-lang/cue#1982]
https://cuelang.org/docs/references/spec/ has a "view page source" link to https://github.com/cue-lang/cuelang.org/tree/master/content/en/docs/references/spec.md, which is a 404.

I imagine that the problem is how the spec actually lives in the main repository, at https://github.com/cue-lang/cue/blob/master/doc/ref/spec.md, and seems to be copied over when the website is generated/built.

cc @myitcv

**Comment by myitcv** [comment]
Yep, this might well be something that can be configured as part of the https://www.docsy.dev/. If not, we should open a feature request. I can't really recall whether this has ever worked or not.

**Comment by myitcv** [comment]
Raised as https://linear.app/usmedia/issue/CUE-291 for now. 

We will be flipping to use the main issue tracker for these sorts of things post the flip from alpha.cuelang.org to cuelang.org
