### ISSUE TITLE
cuelang.org: The Logic of CUE: reversed subsume notation

### ISSUE THREAD

**Issue by mcheshkov** [cue-lang/cue#1983]
In part "The answer to life, the universe and everything" it is said:

> Subsumption: given a set ... F subsumes F', denoted F ⊑ F', if and only if ... 

If I understand correctly, usually notation is reversed - F' is "instance of" F, or "subset of" F, so it is written as F' ⊑ F
This seems especially strange with second part of definition, about types at paths

> 𝓟_F(π) = t implies 𝓟_F'(π) = t'  and t' ⊑ t

Notice how F ⊑ F' implies t' ⊑ t

**Comment by myitcv** [comment]
Revisit this once we republished on the new site.

**Comment by myitcv** [comment]
Raised as https://github.com/cue-lang/docs-and-content/issues/93. That repo is private for now, but will be flipped to be public when we flip alpha.cuelang.org to cuelang.org

**Comment by sh1ng** [comment]
I've also noticed it. You can rephrase the definition to 

```
 F is subsumed by F'...
```

Please reopen it as the existing doc is not correct.
