### ISSUE TITLE
cuelang.org: usecases/datadef.md: thin contrast with CDDL

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#1986]
_Originally opened by @extemporalgenome in https://github.com/cuelang/cuelang.org/issues/131_

> Unlike OpenAPI, CDDL is a domain-specific language (DSL). It needs a specific interpreter. It also has some non-trivial aspects to its evaluation, making it much harder than OpenAPI to implement.

Arguably the same arguments could be made against CUE itself: it's a language, thus needs a language implementation, and the CUE tooling presumably required a non-trivial amount of thought and effort, thus making it harder than OpenAPI to [semantically] implement.

This really feels like it should be a maturity/consistency argument: CUE is a multi-purpose language for which a primary implementation is _provided_, whereas CDDL is a limited-scope language meant to be treated more as a data-interchange format, with the intention that implementations (of inconsistent quality) be developed for use in various host languages or tools.

**Comment by cueckoo** [comment]
_Original reply by @myitcv in https://github.com/cuelang/cuelang.org/issues/131#issuecomment-797565052_

cc @mpvl

**Comment by myitcv** [comment]
Moved this to https://github.com/cue-lang/docs-and-content/issues/92. That repo is private for now, but will be made public when we flip alpha.cuelang.org to cuelang.org.
