### ISSUE TITLE
cuelang.org: usecases/datadef: overly technical content in "On logical not" section

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#1987]
_Originally opened by @extemporalgenome in https://github.com/cuelang/cuelang.org/issues/130_

https://cuelang.org/docs/usecases/datadef/#json-schema--openapi

"On logical not" has content that is perhaps overly technical for a use-cases page. Many readers may not be familiar with the symbols for not and false/bottom, and may get the false impression that CUE is too academic/theoretical for them to learn and start using (or that CUE has important limitations in its integration with OpenAPI, despite "not" being comparatively rare).

The "On logical not" guidance may be more suited for an errata page specific to OpenAPI, and it would be consumable by a wider audience using CUE syntax (or something approximating it) to represent the dilemma and workaround.

**Comment by myitcv** [comment]
Have moved this to https://github.com/cue-lang/docs-and-content/issues/91. That repo is private for now, but will be made public when we go live with the switch from alpha.cuelang.org to cuelang.org.
