### ISSUE TITLE
cuelang.org: Schema Definition: add comparison to SHACL

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#1988]
_Originally opened by @ludovicc in https://github.com/cuelang/cuelang.org/issues/94_

SHACL (https://www.w3.org/TR/shacl/) is a W3C constraint language for RDF and JSON. Its goals are similar to CUE, but restricted to semantic web technologies. It can be used to validate real world data (https://www.semanticarts.com/whats-exciting-about-shacl-rdf-data-shapes/)

Can you provide a comparison between SHACL and CUE?

**Comment by cueckoo** [comment]
_Original reply by @myitcv in https://github.com/cuelang/cuelang.org/issues/94#issuecomment-797606115_

cc @mpvl

**Comment by myitcv** [comment]
Closing this as we have captured the feedback in a repo dedicated to content for https://alpha.cuelang.org. That repo will be made public soon.
