### ISSUE TITLE
cuelang.org: Move away from using git submodules

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#1989]
_Originally opened by @myitcv in https://github.com/cuelang/cuelang.org/issues/75_

Git submodules are currently used to "pin" the version of the docsy theme we are using. That repo itself has submodules for the bootstrap and font-awesome packages. 

Therefore, if one is developing the site locally or deploying via Netlify we need to run:

```
git submodule update -f --init --recursive
```

in order for the site to build properly.

There is, therefore, little benefit to using git submodules because we end up having to retrieve the content in any case (indeed there is a downside that the submodule target repo might not be available...)

We should write a script to "vendor" all the required submodules (noting the commit of docsy we have vendored).

**Comment by myitcv** [comment]
We are doing just this in alpha.cuelang.org so closing.
