### ISSUE TITLE
cuelang.org: all: add instructions for updating documentation to Readme

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#1990]
_Originally opened by @mpvl in https://github.com/cuelang/cuelang.org/issues/52_

For instance:
- how to update the cue repo
- how to add graphs and illustrations
- other guidelines

**Comment by cueckoo** [comment]
_Original reply by @myitcv in https://github.com/cuelang/cuelang.org/issues/52#issuecomment-597730610_

Somewhat addressed by https://github.com/cuelang/cuelang.org/pull/68

**Comment by myitcv** [comment]
Moving this to https://github.com/cue-lang/docs-and-content/issues/88. That is a private repo for now, which will be made public after the flip of alpha.cuelang.org to be the main version.
