### ISSUE TITLE
cuelang.org: content: description of the current project maturity

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#1991]
_Originally opened by @xinau in https://github.com/cuelang/cuelang.org/issues/51_

similar to https://metallb.universe.tf/concepts/maturity/ or https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-stages it could be nice for newcomers and potential adopters to know what the current maturity guarantees are of the project. This might include topics like:

* adoption
* test coverage and thus probability of bugs
* developers (how many people are working on cue)
* expectation of breaking changes

**Comment by cueckoo** [comment]
_Original reply by @myitcv in https://github.com/cuelang/cuelang.org/issues/51#issuecomment-797607826_

As we are getting closer to v1.0.0, @mpvl - might well be worth having something on this?

**Comment by myitcv** [comment]
I'm closing this in favour of a content-related issue in another repository. That repo will be made public when we go live with the new cuelang.org site (hopefully next month).
