### ISSUE TITLE
cuelang.org: theme/docsy: edit page link doesn't work for generated pages

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#1992]
_Originally opened by @xinau in https://github.com/cuelang/cuelang.org/issues/43_

since some pages are being generated/copied from the cuelang/cue repository the edit page button points to missing files on github for cuelang/cuelang.org

affected pages:
* https://cuelang.org/docs/references/spec/
* https://cuelang.org/docs/tutorials/tour/

a possible solution could be to override the href via the metadata in the generated markdown file and a custom template

**Comment by cueckoo** [comment]
_Original reply by @NReilingh in https://github.com/cuelang/cuelang.org/issues/43#issuecomment-792192089_

Related to this, somewhere in contributing or readme it should say where one would go if they would like to submit an edit PR to, say, the tutorial. I wanted to fix some typos but gave up since it doesn't seem to be on GitHub.

**Comment by cueckoo** [comment]
_Original reply by @myitcv in https://github.com/cuelang/cuelang.org/issues/43#issuecomment-797526704_

Thanks for flagging this @xinau and @NReilingh. 

@xinau - we'd happily accept/explore a PR that looked at fixing this "properly" along the lines you suggest. Alternatively in the short term we could simply include a comment in each file stating its source.

@NReilingh thank you for your recent changes, and sorry you couldn't find the spec/tutorial link. The are as follows:

* Spec: https://github.com/cuelang/cue/blob/master/doc/ref/spec.md
* Tour: https://github.com/cuelang/cue/tree/master/doc/tutorial/basics
* Kubernetes: https://github.com/cuelang/cue/tree/master/doc/tutorial/kubernetes

**Comment by myitcv** [comment]
This has been superseded by the new https://cuelang.org site. At the bottom of each page there is a means of reporting an issue for the current page:

![327094336-885b9636-a62e-4878-b893-c199960b67dd](https://github.com/cue-lang/cue/assets/3374574/5cd1340b-5557-41d3-9f17-bc237d734641)
