### ISSUE TITLE
cuelang.org: List of language bindings needed somehwere.

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#1993]
_Originally opened by @paul-hammant in https://github.com/cuelang/cuelang.org/issues/27_

1. Go - available now
2. JavaScript - repo created, but no code yet

Similarly, the prominent 'download' link should indicate what would be downloaded precisely.

**Comment by cueckoo** [comment]
_Original reply by @myitcv in https://github.com/cuelang/cuelang.org/issues/27#issuecomment-797617027_

Apologies for taking so long to get round to this @paul-hammant.

The official list of integrations is here: https://cuelang.org/docs/integrations/

Discussion about other language integrations/etc is happening in the main repo, e.g. https://github.com/cuelang/cue/issues/86, https://github.com/cuelang/cue/issues/162 and https://github.com/cuelang/cue/issues/356

> Similarly, the prominent 'download' link should indicate what would be downloaded precisely.

I assume you're referring to the main download link on https://cuelang.org. I think the "Getting Started" guide provides sufficient distinction? 

https://cuelang.org/docs/install/

Would be interested if you have further suggestions on what could be tweaked there (I'm going to submit a change now to change _The Go APIs can be used as is using Go’s package manager_ to instead be a reference to Go modules)

As ever, docs could always be improved so greatly appreciate the feedback (despite it taking this long to reply)

**Comment by myitcv** [comment]
I'm closing this in favour of a content-related issue in another repository. That repo will be made public when we go live with the new cuelang.org site (hopefully next month).
