### ISSUE TITLE
Report all types of error at the same time (constraints and concreteness)

### ISSUE THREAD

**Issue by edouard-lopez** [cue-lang/cue#1998]
**Is your feature request related to a problem? Please describe.**
When writing a validation schema for a Keycloak config file, I was confused as a rule that check the correctness of my item stop throw error after I added a new item that break another constraint.

**Describe the solution you'd like**
I would like the correctness error to be thrown ASAP, and not have to wait for the whole document to be well-formed.
The YAML document is big, so I progress node by node.

**Describe alternatives you've considered**
fixing issues unrelated to the topic I'm working on to have feedback on my primary goal is a pain and create lots of context switching.

**Additional context**
### Only view constraint error

[One of the `role` is malformed](https://cuelang.org/play/?id=fuKJAZbBbds#cue@export@json), we got the related error, that's fine. But the error related to the `description` field is not visible (field is mandatory).

```cue
#Role: {
	description: string
	realm_name:  string
	name?:       string
}

#Roles: {
    [=~#"^ROLE_\w+"#]: #Role
}


roles: #Roles & {
    ROLE_WORKBENCH_USER: {
        realm_name: "Marketplace"
    }
    ROLE_WORKER: {
        description: "Role to access on all workers of MM."
        realm_name: "Marketplace"
    }
        "/payment/refund/reader": {
        description: "Grants read only access to refund domain."
        realm_name: "Marketplace"
    }
}
```

### Malformed `role` Error 

```
roles: field not allowed: "/payment/refund/reader":
    -:7:9
    -:12:8
    -:20:9
```

### Missing field error
Only when the [malformed role ` "/payment/refund/reader"` is removed do we see the error about the missing `description` field.](https://cuelang.org/play/?id=UPD4TA73ZOn#cue@export@json)

```
roles.ROLE_WORKBENCH_USER.description: incomplete value string:
    -:2:15
```

**Comment by myitcv** [comment]
Thanks @edouard-lopez. 

For others following along, this discussion started on Slack. 

My understanding is that even under changes proposed in the [required fields proposal v2](https://github.com/cue-lang/cue/discussions/1951), a concreteness check would only happen _after_ validation of constraints. Today this necessarily requires that a CUE configuration be valid with respect to constraints _before_ concreteness is checked. However, it struct me that this need not necessarily be the case.

So @edouard-lopez kindly raised this issue as an exploration of whether both could be reported at the same time.

**Comment by myitcv** [comment]
I totally forgot that https://github.com/cue-lang/cue/issues/1319 existed. I'll close this in favour of that issue, linking to this issue from https://github.com/cue-lang/cue/issues/1319.
