### ISSUE TITLE
cuelang.org: documentation and content updates

### ISSUE THREAD

**Issue by Lyoness** [cue-lang/cue#2008]
This is an umbrella placeholder issue all [cue-lang/cuelang.org](github.com/cue-lang/cuelang.org) related updates. 

Please subscribe to this issue if you're interested in following the progress for cuelang.org development.

**Comment by Lyoness** [comment]
Join us for the November Documentation and Content call next **Tuesday, 8 November, 1630 UTC**. 

See #2055 for details.

**Comment by Lyoness** [comment]
Reminder: Today is the CUE Documentation and Content monthly call. Please go to [CUE Community shared calendar](https://calendar.google.com/calendar/u/0?cid=Y19lNzkxMWQ5OWQ4ZGIyMmU2ZTVjMzhkMTVkNjY2ZTVlNjdiNWE5ODNkZWU4N2JmNTU2NDY3NzI1OGIxYjJhMTFhQGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20) for the Google Meet link.

**Comment by myitcv** [comment]
Apologies, this issue got left behind in terms of updates!

To briefly summarise the update from the [last community call](https://github.com/cue-lang/cue/discussions/2441):

* Development and progress on https://alpha.cuelang.org continues
* We are aiming to flip https://alpha.cuelang.org to https://cuelang.org in the first week of September

Further updates to follow on the [next community call](https://github.com/cue-lang/cue/discussions/2515).

Once we flip https://alpha.cuelang.org to https://cuelang.org, we will restart our "Docs and Content" calls for those interested in any aspect of CUE documentation.

**Comment by myitcv** [comment]
This has been superseded by the https://github.com/orgs/cue-lang/projects/19/ project.
