### ISSUE TITLE
Need form generator which supports cuelang

### ISSUE THREAD

**Issue by yuzhichang** [cue-lang/cue#2011]
[json-editor](https://github.com/json-editor/json-editor) takes a JSON Schema and uses it to generate an HTML form and can integrate with several popular CSS frameworks (bootstrap, spectre, tailwind)..
Does such tool exist for cuelang?

**Comment by eadlam** [comment]
Cuelang can export to OpenAPI which is a json-schema.

**Comment by yuzhichang** [comment]
@eadlam Thanks for the answer.
