### ISSUE TITLE
encoding/jsonschema: add coverage of JSON Schema tests

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#2014]
Per @relequestual, JSON Schema has a [test suite](https://github.com/json-schema-org/JSON-Schema-Test-Suite) that is used by implementers of JSON Schema validation libraries to test their validators.

CUE should probably be one such user of this test suite.

This umbrella issue tracks adding coverage of these tests.

@relequestual also pointed out https://github.com/bowtie-json-schema/bowtie:

> Bowtie is a meta-validator of the [JSON Schema specification](https://json-schema.org/), by which we mean it coordinates executing other [validator implementations](https://json-schema.org/implementations.html), collecting and reporting on their results.

**Comment by myitcv** [comment]
cc @jpluscplusm

**Comment by rogpeppe** [comment]
This is arguably fixed by 484dd8e1c20bd978c0dd272d3f20335b5a60b2de and d20e479915c45477965a57d808fb794ead37dc6f. Let's add another more specific issue if we need more.
