### ISSUE TITLE
builtin package "reflect" undefined

### ISSUE THREAD

**Issue by kajogo777** [cue-lang/cue#2016]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.4.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What did you do?

try use "github.com/kyverno/kyverno/api/kyverno/v1"

by importing go structs to cue first
```
go get "github.com/kyverno/kyverno/api/kyverno/v1" 
cue get go "github.com/kyverno/kyverno/api/kyverno/v1" 
```

### What did you expect to see?

I expected to be able to use the definitions
```
import kyvernov1 "github.com/kyverno/kyverno/api/kyverno/v1"

match: kyvernov1.#MatchResources
```

### What did you see instead?
```
builtin package "reflect" undefined:
    ../../../cue.mod/gen/github.com/sigstore/k8s-manifest-sigstore/pkg/util/mapnode/node_go_gen.cue:7:8
```

**Comment by mvdan** [comment]
This appears to be a duplicate of https://github.com/cue-lang/cue/issues/648 :)
