### ISSUE TITLE
decode: Support decoding into cue.Value fields

### ISSUE THREAD

**Issue by asdine** [cue-lang/cue#2029]
**Is your feature request related to a problem? Please describe.**
When decoding a `cue.Value` using [Value.Decode](https://pkg.go.dev/cuelang.org/go@v0.4.3/cue#Value.Decode), it is sometimes necessary to decode configs in multiple steps, and although `TextUnmarshaler` and `json.Unmarshaler` are helpful, there are not always very handy.

**Describe the solution you'd like**

It would be great if we could declare a field to be a `cue.Value` and have the corresponding value be stored in there. Kind of like `json.RawMessage` works for `json.Unmarshal`.

Example:

```cue
name: "omar"
address: {
  city: "kolkata"
}
```

```go
type User struct {
  Name string
  Address *cue.Value // or cue.Value
}

var u User
v.Decode(&u)

vv := u.Address.LookupPath(cue.ParsePath("city"))
```

**Describe alternatives you've considered**
Using json.Unmarshaler and use json to deal with the sub value, but it's not ideal with big structures that need conditional decoding.

**Comment by myitcv** [comment]
@asdine thanks for raising this.

This is pretty close to https://github.com/cue-lang/cue/issues/377

Indeed I think it's close enough to mark as a duplicate, and close in favour of the original issue. Please let us know if you think it's sufficiently different so as to merit a different issues. Thanks

**Comment by asdine** [comment]
I don't think the two issues are similar, not in terms of API at least.
What I had in mind was to simply add support to cue.Value in the [Value.Decode](https://pkg.go.dev/cuelang.org/go@v0.4.3/cue#Value.Decode) method, somewhere around here: https://github.com/cue-lang/cue/blob/256f1f9ee1611636fef85446ff9ea3b7d4f6b7d0/cue/decode.go#L138-L147

In terms of API and effort, it's very different from adding an Encoder / Decoder interface to gocodec.

**Comment by myitcv** [comment]
> In terms of API and effort, it's very different from adding an Encoder / Decoder interface to gocodec.

Good point. Reopened.

**Comment by asdine** [comment]
I'd be happy to submit a PR if you're interested

**Comment by myitcv** [comment]
Thanks, @asdine. Let's first reach some agreement on whether this change makes sense.

cc @mpvl @rogpeppe

**Comment by rogpeppe** [comment]
To me this makes perfect sense. We can already use cue.Value fields when encoding, so the reverse operator should work too.

@asdine Thanks for the report (and hi!) - very happy to review a PR.

**Comment by rogpeppe** [comment]
BTW here's an example that demonstrates that the Encode works with cue.Value but not Decode: https://go.dev/play/p/TbjOqAPBwLt

**Comment by mpvl** [comment]
Pardon for the late reply. I think that makes sense. 

BTW `cue.Value` is basically a wrapper around pointers (not unlike a slice or a `reflect.Value`). So supporting `*cue.Value` may not be needed. Although I see how it can be useful.
