### ISSUE TITLE
CUE package management and modules

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#2032]
This issue is an umbrella issue tracking package management and modules in CUE. Proposals, documents etc will be linked from this issue.

We have not reused #851 as the umbrella issue for package management and modules. That issue captures an early proposal that will very likely be superseded by a v2 proposal. Repurposing that issue would lose history in what is already a long proposal and discussion.

**Comment by rogpeppe** [comment]
~If you'd like to provide use cases and/or feedback on potential module design, please post to the discussion at https://github.com/cue-lang/cue/discussions/2044.~

**Comment by myitcv** [comment]
We have just published a revised package management and modules proposal that entirely replaces [#851](https://cuelang.org/issue/851)

Please see https://github.com/cue-lang/cue/discussions/2330 for a link to that proposal. Feedback and questions very much welcome!

**Comment by myitcv** [comment]
As announced on the [2026-06-20 community call](https://github.com/cue-lang/cue/discussions/2441), the revised module proposal in #2330 has been updated with a number of sub proposals that go into more detail in areas like storage, (supply chain) security etc. Please see #2330 for more details.

**Comment by myitcv** [comment]
As announced on the [2026-06-20 community call](https://github.com/cue-lang/cue/discussions/2441), we are starting fortnightly CUE Modules Feedback Sessions / office hours. For more details please see https://github.com/cue-lang/cue/discussions/2461

**Comment by myitcv** [comment]
The second CUE modules feedback session / office hours is happening in a little under an hour (apologies for the late notice). For more details, please see https://github.com/cue-lang/cue/discussions/2487

**Comment by myitcv** [comment]
Apologies - we failed to update here with recent announcements:

* [2023-09-14 CUE Modules Feedback Session / office hours](https://github.com/cue-lang/cue/discussions/2593)
* [2023-08-03 CUE Modules Feedback Session / office hours](https://github.com/cue-lang/cue/discussions/2514)

**Comment by myitcv** [comment]
Apologies to folks following here: we never really got going with providing updates on this issue, instead switching our focus to https://cuelang.org/issue/2939 and the regular [modules update calls](https://github.com/cue-lang/cue/discussions/categories/community-calls?discussions_q=is%3Aopen+category%3A%22Community+Calls%22+label%3Amodules). 

v3 of the modules proposal has just been accepted in #2939. The implementation of the modules proposal (previously enabled via `CUE_EXPERIMENT=modules`) will be on by default in v0.9.0. https://github.com/cue-lang/cue/releases/tag/v0.9.0-alpha.5 flips the default for some final testing before the v0.9.0 release. 

It seems like an appropriate time to close this issue therefore. From this point onwards, the [modules roadmap](https://github.com/orgs/cue-lang/projects/10) will provide the best overview of our work on modules.
