### ISSUE TITLE
encoding: support for more encodings/adapters

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#2038]
This is an umbrella issue tracking the adding of more (complete) encodings/adapters for CUE.

Existing issues that fall under this umbrella:

* [pkg/encoding/xml support - #330](https://github.com/cue-lang/cue/issues/330)
* ...

Further issues to track specific encodings/adapters to follow.

**Comment by mvdan** [comment]
We are tracking encodings work via a roadmap project at https://github.com/orgs/cue-lang/projects/23, so I'm going to close this in favor of the project. Also a reminder that the `#encodings` channel exists on both Slack and Discord for any questions.
