### ISSUE TITLE
Integrations with other languages (beyond Go)

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#2039]
This is an umbrella issue to track integration CUE with other languages, beyond Go. 

This is intentionally quite a broad and vague statement, as the requirements might well vary by language.

We welcome details of use cases to help shape what these integrations/APIs/etc look like. As with many things in CUE, concrete use cases help us to establish designs back by a clear set of constraints, existing best practice etc.

**Comment by mvdan** [comment]
I believe this is superseded by the work in https://github.com/cue-lang/cue/issues/3104 and https://github.com/orgs/cue-lang/projects/24 now - @myitcv do you agree, or should we keep this issue open for some other purpose?

**Comment by myitcv** [comment]
> I believe this is superseded by the work in #3104 and https://github.com/orgs/cue-lang/projects/24 now

Agreed.
