### ISSUE TITLE
cue/eval: judgment on empty array is weird

### ISSUE THREAD

**Issue by FogDong** [cue-lang/cue#2042]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
v0.4.3
</pre>

### Does this issue reproduce with the latest release?
yes

### What did you do?

CUE Playground link: https://cuelang.org/play/?id=JpAg8kw82n3#cue@export@cue

It looks good when comparing two empty arrays:

```
emptyArr: []

if emptyArr == [] {
  hello: 1
}
```

Output: 

```
emptyArr: []
hello: 1
```

However, become strange when comparing a non-empty array to `[]`:

```
notEmptyArr: [1,2,3,]

if notEmptyArr != [] {
  hello2: 2
}
```

Output:
```
notEmptyArr: [1,2,3,]
```

### What did you expect to see?

```
notEmptyArr: [1,2,3,]
hello2: 2
```

**Comment by antong** [comment]
There is a bug, that makes `list1 != list2` return false if `len(list1) != len(list2)`. It should return true:
https://github.com/cue-lang/cue/blob/dd1169c686c9e45358fa87fcdb9530fe3f6a799f/internal/core/adt/binop.go#L109-L114

I could try to fix this. But, the language specification says that lists aren't comparable: https://cuelang.org/docs/references/spec/#comparison-operators

@mpvl , should lists be comparable?

**Comment by antong** [comment]
Oh, now saw #2024.

**Comment by FogDong** [comment]
This one's priority is **low** since there's a **workaround** to use `if len(arr) == 0`.
This is a **user-facing** issue because in our workflow, users can write an if condition(which will be evaluated as cue value) to decide whether a step should be executed. A detailed explanation of the usage is [here](https://github.com/cue-lang/cue/issues/2232#issuecomment-1423491944).
No **time constraint**.

**Comment by mvdan** [comment]
@antong is right that the implementation currently does not agree with the spec. @rogpeppe filed this as https://github.com/cue-lang/cue/issues/2024 already, thankfully.

Regardless of that discrepancy, I think we can all agree that the current logic has a tiny mistake that should be fixed. https://github.com/cue-lang/cue/pull/2290 already exists as the fix that @antong also spotted, so I'll look at getting that merged.
