### ISSUE TITLE
add go net/url package support to cue

### ISSUE THREAD

**Issue by kghenderson** [cue-lang/cue#2090]
**Is your feature request related to a problem? Please describe.**
we can roll our own functions here (mostly), but again, not very intuitive for future end users

**Describe the solution you'd like**
As simple as it sounds, in Go the [net/url](https://pkg.go.dev/net/url) package provides most importantly for me both the 
[PathEscape](https://pkg.go.dev/net/url#PathEscape)  and  
[QueryEscape](https://pkg.go.dev/net/url#QueryEscape) functions. 

As it happens, I have to work with an OData REST API, which uses PathEscape, even for items in the QueryString, 
specifically, `A%20B` style space escaping instead of `A+B` escaping. This also affects some other punctuation characters as well though. 

If we have net Url I can just use: 

```
MyObject: Name: "Name with Spaces"
MyUrl: BaseUrl + ApiVersion + "?Service(" + MyObject.Name +")"
Request: http.Do & { url: url.PathEscape(MyUrl), ... }

```

**Describe alternatives you've considered**
Just had to roll my own naive replace functions, they'll work for now, but will probably break once i'm long gone from the project :-/

**Additional context**

**Comment by ghostwheel42** [comment]
This should be #1699 and #1695, shouldn't it?

**Comment by mvdan** [comment]
Yes, good point @ghostwheel42 :) Closing as a duplicate.
