### ISSUE TITLE
Maintain field order when rendering templates

### ISSUE THREAD

**Issue by verdverm** [cue-lang/cue#2110]
I suspect this is tied to Decode and maybe Go maps? At some point the fields became lexically ordered.

It would be very helpful if fields maintained their order, like export

Given:

```
import "text/template"

foo: {
	b: "b"
	a: "a"
}

tpl: """
{{ range $k, $v := . }}
{{ $k }}: {{ $v }}
{{ end }}
"""

txt: template.Execute(tpl, foo)
```

Output:

```
$ cue export test.cue -e foo
{
    "b": "b",
    "a": "a"
}
```
note how a & b swap order in this example
```
$ cue eval test.cue 
foo: {
    b: "b"
    a: "a"
}
tpl: """
    {{ range $k, $v := . }}
    {{ $k }}: {{ $v }}
    {{ end }}
    """
txt: """

    a: a

    b: b

    """
```

**Comment by myitcv** [comment]
Thanks for raising this, @verdverm.

If you think this is a bug, please can you update the issue to follow the ["Bug report" template](https://github.com/cue-lang/cue/issues/new/choose)?

Thanks

**Comment by verdverm** [comment]
I'm not sure if it is a bug, or even something CUE can handle easily. It needs more investigation to find the root cause (Decode implementation or Go map iteration)
