### ISSUE TITLE
encoding/yaml.Marshal: assertion failed: no BaseValue: state: finalized; requested: partial

### ISSUE THREAD

**Issue by mxey** [cue-lang/cue#2119]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.5.0-beta.1.0.20221119112418-32bfffd0aa53

       -compiler gc
     CGO_ENABLED 1
          GOARCH arm64
            GOOS darwin
</pre>

### Does this issue reproduce with the latest release?

I initially produced it on the v0.5.0-beta.1 and then reproduced it with the latest commit.
I can reproduce it on the v0.5.0-alpha.1.
I cannot reproduce it on the last stable release v0.4.3

### What did you do?

```
cue export - <<EOF
import (
        "encoding/yaml"
        "regexp"
)

#testableRegexp: R={
        string

        #test: close({
                in:  string
                out: regexp.FindSubmatch("^"+R+"$", in)[1]
        })
}

rule: {
        #patterns: {
                bar: #testableRegexp & {
                        "(.*)"
                        #test: {in: "testcontent", out: "testcontent"}
                }
        }
}
out: yaml.Marshal(rule)
EOF
```

### What did you expect to see?

```
{
    "rule": {},
    "out": "{}\n"
}
```

### What did you see instead?

```
out: error in call to encoding/yaml.Marshal: assertion failed: no BaseValue: state: finalized; requested: partial:
    -:23:6
```

### Notes

If I merely replace `yaml.Marshal` with `json.Marshal`, it works fine.

**Comment by myitcv** [comment]
Thanks @mxey. Confirmed and bisected to ae56267956abf38f79b66fc9809d61abab0a50d1. Marking as v0.5.0. 

### What did you do?

```
exec cue export x.cue
cmp stdout stdout.golden

-- x.cue --
import (
	"encoding/yaml"
	"regexp"
)

#testableRegexp: R={
	string

	#test: close({
		in:  string
		out: regexp.FindSubmatch("^"+R+"$", in)[1]
	})
}

rule: {
	#patterns: {
		bar: #testableRegexp & {
			"(.*)"
			#test: {in: "testcontent", out: "testcontent"}
		}
	}
}
out: yaml.Marshal(rule)
-- stdout.golden --
{
    "rule": {},
    "out": "{}\n"
}
```

### What did you expect to see?

Passing test. Passes with v0.4.3

### What did you see instead?

```
> go run cuelang.org/go/cmd/cue export x.cue
[stderr]
out: error in call to encoding/yaml.Marshal: assertion failed: no BaseValue: state: finalized; requested: partial:
    ./x.cue:23:6
exit status 1

[exit status 1]
FAIL: /tmp/testscript1999356098/repro.txtar/script.txtar:2: unexpected go command failure
```

**Comment by mpvl** [comment]
FTR: a somewhat simplified reproducer:

```
import "encoding/yaml"

x: d: R={
	".*"
	[R+""][0]
}
out: yaml.Marshal(x)
```

This issue is in the export package, used by Syntax and the YAML converter, not the evaluator.
