### ISSUE TITLE
evaluator: incorrect output and no error from comprehension that adds fields

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#2131]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.0.0-20221123190145-e5fb5afcd1a9

       -compiler gc
     CGO_ENABLED 1
          GOARCH arm64
            GOOS linux
             vcs git
    vcs.revision e5fb5afcd1a935f8d2ce662a9267d9660f4771cd
        vcs.time 2022-11-23T19:01:45Z
    vcs.modified false
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
exec cue eval x.cue
cmp stdout stdout.golden

-- x.cue --
import "path"

tests: {
	windows: {
		eg1: in: #"c:\"#
		eg2: in: #"c:\test"#
		eg3: in: #"c:\test\"#
	}

	for os, examples in tests for k, v in examples {
		(os): (k): out: "test"
	}
}
-- stdout.golden --
tests: {
    windows: {
        eg1: {
            in:  "c:\\"
            out: "test"
        }
        eg2: {
            in:  "c:\\test"
            out: "test"
        }
        eg3: {
            in:  "c:\\test\\"
            out: "test"
        }
    }
}
```

### What did you expect to see?

Passing test.

### What did you see instead?

No error, and incorrect output:

```
> exec cue eval x.cue
[stdout]
tests: {
    windows: {
        eg1: {
            in: "c:\\"
        }
        eg2: {
            in: "c:\\test"
        }
        eg3: {
            in: "c:\\test\\"
        }
    }
}
> cmp stdout stdout.golden
--- stdout
+++ stdout.golden
@@ -1,13 +1,17 @@
 tests: {
     windows: {
         eg1: {
-            in: "c:\\"
+            in:  "c:\\"
+            out: "test"
         }
         eg2: {
-            in: "c:\\test"
+            in:  "c:\\test"
+            out: "test"
         }
         eg3: {
-            in: "c:\\test\\"
+            in:  "c:\\test\\"
+            out: "test"
         }
     }
 }
```

This appears to be a variant of a bug that was fixed as part of the comprehension rework. The difference appears to be that in this case we have two chained comprehensions rather than one.

**Comment by mpvl** [comment]
This is related to #2113 and a fix is already in the pipeline. Added a test there to cover that case, which will close this Issue once committed.
