### ISSUE TITLE
evaluator: cycle error reported where non existed in v0.4.3

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#2139]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.0.0-20221124173308-a800e6fadcfd

       -compiler gc
     CGO_ENABLED 1
          GOARCH arm64
            GOOS linux
             vcs git
    vcs.revision a800e6fadcfd2a30bda3f1ef330574c11c292499
        vcs.time 2022-11-24T17:33:08Z
    vcs.modified false
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
exec cue export x.cue
cmp stdout stdout.golden

-- x.cue --
package x

#R: {
	p?: _
	d?: _

	let x = d | p
	if (x == _|_) {
		p: {}
	}
}

#C: {
	r: #R
}

// Removing #C from drops the "cycle error" output
m: #C & {
	r: {
		p: {
		}
	}
}

result: #R & m.r
-- stdout.golden --
{
    "m": {
        "r": {
            "p": {}
        }
    },
    "result": {
        "p": {}
    }
}
```

### What did you expect to see?

Passing test.

### What did you see instead?

```
> exec cue export x.cue
[stderr]
cycle error
m.r: circular dependency in evaluation of conditionals: x changed after evaluation:
    ./x.cue:8:6
[exit status 1]
FAIL: /tmp/testscript154685520/repro.txtar/script.txtar:1: unexpected command failure
```

This passes with v0.4.3.

**Comment by myitcv** [comment]
Bisected to 748a68589747fed6273d6338eb7e275a4fb116c6, where the output is slightly more precise:

```
[stderr]
m.r: circular dependency in evaluation of conditionals: x changed after evaluation:
    ./x.cue:8:6
result: circular dependency in evaluation of conditionals: x changed after evaluation:
    ./x.cue:8:6
exit status 1

[exit status 1]
FAIL: /tmp/testscript1771193351/repro.txtar/script.txtar:2: unexpected go command failure
```

The unhelpful `cycle error` seems to have come later.

**Comment by mpvl** [comment]
This appears to be a legitimate cycle: `d` is an incomplete reference, meaning that `p` is the only valid disjunct (so far), but to evaluate it fully, one needs to evaluate `x` fully, which in turn requires `p` to be evaluated fully.

If one would use `isdefined` (planned) instead of `== _|_`, this could potentially be broken, as long as the `if` clause does not ends up inserting something that changes the outcome of its conditional.

**Comment by myitcv** [comment]
> If one would use `isdefined` (planned) instead of `== _|_`, this could potentially be broken, as long as the `if` clause does not ends up inserting something that changes the outcome of its conditional.

Interesting. I'm not clear though how we could avoid "inserting something that changes the outcome of its conditional" with `isdefined()`, because doesn't the body of the `if` do just that: define something that was previously undefined (according to the conditional)?

As I understand it, this simpler example is a cycle for the same reason:

```cue
#D: {
    x?: int

    if x == _|_ {
        x: 5
    }
}

d: #D
```

If instead of comparison to bottom we used `isdefined()` like this:


```cue
#D: {
    x?: int

    if !isdefined(x) {
        x: 5
    }
}

d: #D
```

would this be legal?

My guess would be yes, because my intuition is that that's equivalent to:

```cue
#D: {
    x: *5 | int
}

d: #D
```

**Comment by myitcv** [comment]
Actually, I'm not sure my assertion above about that use of `isdefined()` being equivalent to defaults is correct. Rather it's `isconcrete()` that is equivalent. So:

```cue
#D: {
    x?: int

    if !isconcrete(x) {
        x: 5
    }
}

d: #D
```

is equivalent to:

```cue
#D: {
    x: *5 | int
}

d: #D
```

Have I got that right, @mpvl?

**Comment by mpvl** [comment]
>  because doesn't the body of the if do just that: define something that was previously undefined

Not necessarily. For instance, in the problem of the OP, `p` was defined in the struct unified with `#R`, so it is defined no matter what the if clause inserts. Note that the inserted value of the if clause is only not allowed to change the result of the condition. It may still change the value itself.

> As I understand it, this simpler example is a cycle for the same reason:

That is not strictly a cycle, but it is indeed a case where the insertion of the if clause changes the value, so that is indeed illegal.

This case is also different from the original: there the purpose of the test is to see if `x` is a valid value. In your example, the intent is more likely to check for concreteness. These are really two different things. In the end we will end up with `isdefined`, `isconcrete` and `isvalid`.

**Comment by mpvl** [comment]
> Have I got that right, @mpvl?

It is different. If you unify `x` with `>6`, for instance, the result would not be concrete.

**Comment by myitcv** [comment]
Summarising our offline discussion.

* This issue highlights an error that should have been caught in earlier CUE versions. The rule to apply in this situation is:

> Note that the inserted value of the if clause is only not allowed to change the result of the condition. It may still change the value itself.

The behaviour in v0.5.0 is therefore _correct_. 

I will create a separate issue to ensure update the spec with some variant of this wording.

* The suggestion in https://github.com/cue-lang/cue/issues/2139#issuecomment-1327083540 that that use of `isconcrete()` is equivalent to defaults is wrong, because of the error semantics associated with disjunctions (amongst other points).
* There is a rather nice pattern that has emerged from this investigation. This "bug" was found in some private CUE code that was attempting default a field in the case that _other_ fields were also not set. Here is a better encoding of that logic:

```cue
#A: {
    x?: int
    y?: int
    z?: int
    
    *{
        x?: _|_
        y?: _|_
        z: 3
    } | _
}

examples: [string]: #A

examples: {
    // No values set
    eg1: {
    }

    // Value for x set
    eg2: {
        x: 1
    }
    
    // Value for x and y set
    eg3: {
        x: 1
        y: 2
    }
    
    // Value for x, y and z set
    eg4: {
        x: 1
        y: 2
        z: 4
    }
    
    // Value for z set
    eg5: {
        z: 4
    }
}
```

[Playground link](https://tip.cuelang.org/play/?id=GmdwIAdpErj#cue@export@cue).

**Comment by myitcv** [comment]
Created https://github.com/cue-lang/cue/issues/2153.
