### ISSUE TITLE
tiny url for cue calendar and/or calendar page

### ISSUE THREAD

**Issue by kghenderson** [cue-lang/cue#2151]
**Is your feature request related to a problem? Please describe.**
currently, the cue calendar url is: 

https://calendar.google.com/calendar/u/0?cid=Y19lNzkxMWQ5OWQ4ZGIyMmU2ZTVjMzhkMTVkNjY2ZTVlNjdiNWE5ODNkZWU4N2JmNTU2NDY3NzI1OGIxYjJhMTFhQGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20

i've taken the liberty of mapping this to:
https://tinyurl.com/cue-calendar

the first one works but is sometimes trimmed, miscopied, or modified by an editor, leading to broken urls.
the tinyurl works but is a little risky, and could be blocked from some networks.

**Describe the solution you'd like**
possibly a DNS redirect from a cue-lang.org or cue.works url, such as cue-lang.org/calendar (or similar).
better would be a simple webpage with some links.

**Describe alternatives you've considered**
^ both options above

**Additional context**

someday this may just be a web-based calendar rather than possibly needing a gmail account,
possibly with multiple formats for different types of calendar systems, but this is just for a simplified url,
that should be very simple to set up as a simple pointer.

**Comment by Lyoness** [comment]
Thank you @kghenderson! Adding the cuelang.org label for now.

**Comment by myitcv** [comment]
I've proposed a solution in https://github.com/cue-lang/cuelang.org/pull/281

**Comment by myitcv** [comment]
As of right now, https://cuelang.org/s/community-calendar works to redirect to the community calendar. Thanks for the suggestion, @kghenderson!
