### ISSUE TITLE
evaluator: using let in field comprehension causes 'invalid interpolation: conflicting values' error

### ISSUE THREAD

**Issue by timspeetjens** [cue-lang/cue#2166]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.5.0-beta.2

       -compiler gc
        -ldflags -s -w
     CGO_ENABLED 0
          GOARCH amd64
            GOOS linux
         GOAMD64 v1

</pre>

### Does this issue reproduce with the latest release?

Yes, this applies to 0.5.0 beta2
Both 0.4.3 and 0.5.0 beta1 work as expected

### What did you do?

```
exec cue eval -c t.cue
cmp stdout stdout.golden

-- t.cue --
_i: {
  a: "d"
  b: "e"
}

for _, v in _i {
    let T = v
    "\(T)": "x"
}
-- stdout.golden --
d: "x"
e: "x"
```

### What did you expect to see?

Passing test.

### What did you see instead?
```
T: invalid interpolation: conflicting values "e" and "d":
    ./t.cue:8:5
    ./t.cue:2:6
    ./t.cue:3:6
    ./t.cue:6:1
    ./t.cue:7:13
```

**Comment by kghenderson** [comment]
i'm getting this too

**Comment by myitcv** [comment]
Thanks for this nice small reproducer.

Marking as v0.5.0.

**Comment by myitcv** [comment]
Bisected to 43fc68115618c5070357dd482530a42ba208e4b1

**Comment by nyarly** [comment]
Also seeing this. I found that moving the `let`s out of the block worked. e.g.

```
for _, v in _i let T = v {
    "\(T)": "x"
}
```

I don't know if that's a onerous "the specs are right" or a hint about the issue, but FWIW

**Comment by mpvl** [comment]
Technical analysis: the current evaluator uses the Vertex in which a comprehension is embedded as a proxy for the comprehension value as the `Environment` lookup Vertex. This generally works, as the fields need to be unified anyway. It works for dynamic fields, as these are evaluated as independent expressions, and have no location within that node. It does not work for let expressions, however. 

The fix would involve evaluating the expression in expression mode, as is done in some other cases.
