### ISSUE TITLE
evaluator: slow evaluation time on cue v0.5.0-beta.2

### ISSUE THREAD

**Issue by august-feng** [cue-lang/cue#2176]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.5.0-beta.2

       -compiler gc
        -ldflags -s -w
     CGO_ENABLED 0
          GOARCH arm64
            GOOS darwin
</pre>

### Does this issue reproduce with the latest release?

Yes. I have just compiled the latest CUE `go install cuelang.org/go/cmd/cue@master` and confirmed it is still an issue.

### What did you do?

CUE did not finish evaluating a configuration for an advent of code (2022) challenge. I used an older version of CUE and it went through. 

I've downsized the input data for the challenge and the evaluation is going through, however, the evaluation is a lot slower:

```shell
$ time ./cue-0.5.0-beta.1 eval code.cue >/dev/null

real	0m0.029s
user	0m0.025s
sys	0m0.007s
$ time ./cue-0.5.0-beta.2 eval code.cue >/dev/null

real	0m0.145s
user	0m0.253s
sys	0m0.019s
```

code: 
```cue
import (
	"strings"
	"strconv"
	"list"
)

#Datastream: {
	message: string
	message: strings.MinRunes(4)

	marker: {
		length: int
		position: {
			let characters = strings.Split(message, "")
			let unique_combinations = {
				// begin computation once we have more than x number of characters.
				for i, _ in characters if i >= length-1 {
					// this line is causing an increased evaluation time between cue versions.
					// vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
					let combination = list.Slice(characters, i-length+1, i+1)

					// last x number of characters are not unique.
					if list.UniqueItems(list.Slice(characters, i-length+1, i+1)) {
						"\(i+1)": combination
					}
				}
			}
			[ for i, _ in unique_combinations {i}][0]
		}
	}
}

input_short: """
	mjqjpqmgbljsphdztnvjfqwrcgsmlb
	"""
input_long: """
	qfmfhmhjmjggwbbvdvwvlvrrtsrsccwsslvlffjrrtprprjjvmmclmmghhddpvddclctcqtccgbgdbgdgsdgghqhtqtvvptvppwrwprpvrrrhpphththvhhrnnhnlnslnlhnhnhgnhnpnqqsmsgsllprlprrlzzqzffmzztctbtnbtthlttqvqcqmcmpcpbbczzbqbgghcghchhvwvllfrfnnbssfzsszpsplpglpprnpnfnbnhbnbtbzzvbvpbbhjjlzzbtbvbppczppbwppqwwnwlwccglgvgrgmmdwmwrmrppnfnhhhhqthqthqqrhrshhhqbhqqjgjvjllzvzbzhbbpttjsszvzqqtzzmbmddpldpdcdnccrmcrmmpwprplrrqssvddmpdmmwfwwlrljrrdsssmhsspnpffjggqllnzlnlhnnmddfrfpfbbvssjsrrznngcghgchcmhmrrrtzztjzzhchssslsmlmvvpwpqpjqjdddmsdmmtgtmgtglttfbbgrrcprrqffmmjnjttcmczzgbzggthhsttpggrmmgwwnpnqnqvnqvqppmlpmlpmpjpljljmmtpptfppfrppfdpfdppddmdttgzgzzdbzdzhzhnnsqssvmvbbpjjzwwvnwvvzmvzmzpmpttvrvccqddpgdppgmmthmthtggsfsbbvfbvfvhfvhvvpwpddqrqgqhghnnfmfbbwrbrgbgbvgbbdttffrddqbqpqzzmttlhhsqhsqhsqhhlplttpnpsstpthhpfhpfplprrgfrgffjppghgppghgdggjmmcgmccjvvsrvsrrwgrgmrrngrgttvbtbltthrthrttmfffjpfpssncnrngrrltrltlggjgcgllrzzllhwwjwrwgrgsrgrhrphrhhqwqsqmqlmqlmqmqrmrnnwnhwnhwhzwzjwwgbghhsjspszsznzfztfzfpzzlczztctsstctqtfqfqcfqqjrjccttmqqfpfdfnfwnffqbfbblpbpfpcfcwfccblbwwmqwqrrgprpccngnhghpppwmpplcppfrfjjgmmbzbhbcbzzgdgsdsvvqllzlppnfnlnlslsljlppcscqqfjjjwzwppfgfjjsvvsggjbjljpjpzjzrzjrzzfnfpnfpnfpnfnsnggmpggdllpmmrhhdqqppttgqqcsqsjsbjsjrsrqrbqqmbmcbmcbmbfmfvfqqdbdppmrprnrggmjjhnhbhdhbbfcbbcjjdhhwjwmjmssjswscswcwzccbgbqqmqgmmsdsjsbsdbsddvttjpppcqpcqcgqqslqsssczszrzvvrtvvjppswwhnnwlwtwhhwwzfwwpfpddlvvnvnnvlnntjtqjqjzzjttvvbqbhqbhbbbwnwhnwnppdbpdpvddrqdqjjlvlqqdfdhdjhdjdcjcrcjjggfmfvvfllvfvgglzllmhmzmdddfwddqjjqjfqfcfrrstrssptsstllrflfwwgswslwlbwbwjjvhvfvhfhffhsslwsllbnbblccbwwjqwqqdllrdrnrnffcbbqqpnqqdmdndtntvvrjvvsvmvgvnnmjlwgnjcwljgwnrwpqlztwrpmpgqtwlhrcwsrrhqhjhznrtpqfdnzbfqrzwslptdbdcnqvcllpjsfdvmzqwvzbpnmfcfcjnbmhtwhttjgtnczwctpdthhwmzvzrrgsnmbflgmszgsbvghbzgcmcmszgsbfmlmpbdspqlftmqrcjtmvgcrzznlfwjcbmddplsqrfflqnqfsldwhnncczdmfrrrsbjjqsdzrsgbdbwjbslfcqglsqfddhdsrcdrgqfqthgmfjvnfdfgdncfzpvqcpscnpmfgvqbfwszwzgmqvmcrdrwplfshdgqrchmccpqfznbmfvlhdpctlqgjslrwhjfjlmqfblgjrdlnzdtwlpwhnrhrcrpfwqpmjlgrdbgpbljntmbqlblqqqpgrnjtmjqvjpzvsqdpgtchmmwbhtmgcjqdplrtptqcvdjjpqdzsrcjhcwvdcghlwrdhtdfctmqfcjcqhcvvbzgsvlggcrdgqbtznwwmnbgsfrjprqgcmlswftlwpqqqvshdprldrsghmhrqvmqmvglbvzpvtrjbhcvhqmvdtcvsllznqzjmhpnlbhmlzthbwwhhvdtcdfdcdzhnbsrnqqjvzzsvfjhbsdlsbdlqjnlpnhfcjtdppzmphghltztzcdvzwbftbvwhvgmrllqfzrpbltptdtjjqtfwjfmczzgdvclqbsbftgtlhnhrrvbpvdltstdnhqvpvtjhmghptvsfnlspslmfsftzdrwljrgblgmcbmlszmhnlfdtmsrnjqwrfmsnfgpcqgzmlwppffrmbvhnlstfpgzw
	"""

input: *input_short | input_long

datastream: #Datastream & {message: input}

output: [string]: string
output: {
	"1": (datastream & {marker: length: 4}).marker.position
	"2": (datastream & {marker: length: 14}).marker.position
}
```

### What did you expect to see?

I expected to see somewhat comparable evaluation times from the latest version of CUE.

### What did you see instead?

I saw a slower evaluation time on the latest version of CUE.

**Comment by mvdan** [comment]
Thanks for the report! If you'd like to dig a little deeper to help investigate the issue, a good next step would be to git bisect what commit caused the slow-down :)

Also worth noting that I'd personally run the "before" and "after" commands at least two or three times to make sure the difference isn't mostly due to noise.

**Comment by august-feng** [comment]
Cool! I've never done a `git bisect` operation before. :) It looks like it comes from this https://github.com/cue-lang/cue/commit/43fc68115618c5070357dd482530a42ba208e4b1.

Given the context of the change, I assume a longer evaluation time is to be expected. It is a bit much though, do you think there'd be a way to mitigate this?

**Comment by august-feng** [comment]
Another potential bug related to this commit. It seems like the x is bound to the upper `{ }` rather than the directly enclosing `{ }`.

```cue
{
	data: [true, false]

	output: {
		for i, d in data {
			let x = data[i]
			if x {
				"\(i)": d
			}
		}
	}
}
```

output: 
````
output.x: conflicting values false and true:
    ./bug.cue:2:1
    ./bug.cue:3:9
    ./bug.cue:3:15
    ./bug.cue:6:3
    ./bug.cue:7:12
```

**Comment by myitcv** [comment]
@augustfengd - thanks for reporting and bisecting.

> Another potential bug related to this commit. It seems like the x is bound to the upper `{ }` rather than the directly enclosing `{ }`.

This particular bug is a dupe of https://github.com/cue-lang/cue/issues/2166 (bisected to 43fc68115618c5070357dd482530a42ba208e4b1).

As you point out, the performance issue is also related.

**Comment by mpvl** [comment]
#2166 is now fixed. 

If I set the key to nil (on tip), I don't see any difference in the number of core operations. So the performance hit was actually incurred by taking the original Conjunct, instead of the pre-expanded expression. Numbers:

Current stats:
```
        Unifications: 3381
        Conjuncts:    7871
        Disjuncts:    3820
```
with `arc` artificially set to `nil`
```
        Unifications: 3381
        Conjuncts:    7871
        Disjuncts:    3820
```
reverting the pre-expanded expression:
```
        Unifications: 44419
        Conjuncts:    113473
        Disjuncts:    51160
```

Will submit a CL that adds this code as a performance test.
