### ISSUE TITLE
ci: release process is not reproducible

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#2177]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
n/a
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

Run the release process repeatedly locally:

```
rm -rf dist
(cd internal/ci/goreleaser/ && GORELEASER_CURRENT_TAG=v0.4.3 GOCACHE=$(mktemp -d) cue cmd release)
mv dist dist1
(command cd internal/ci/goreleaser/ && GORELEASER_CURRENT_TAG=v0.4.3 GOCACHE=$(mktemp -d) cue cmd release)
mv dist dist2
sha256sum dist1/cue_v0.4.3_linux_arm64.tar.gz dist2/cue_v0.4.3_linux_arm64.tar.gz
```

### What did you expect to see?

Identical sums.

### What did you see instead?

Different sums:

```
58e678fa4828965c3211f27a1062e14b2bd4424a17a6b62cd2efe3bfd31ed585  dist1/cue_v0.4.3_linux_arm64.tar.gz
836441f9b8bf190d17ef8f5a211ef7be802b74392cf9bcc9eadf4d0a5dd86a8c  dist2/cue_v0.4.3_linux_arm64.tar.gz
```

What's worse is that the `cue` binaries in any given release artefact are also different:

```
mkdir dist1/out
mkdir dist2/out
cd dist1/out
tar -zxvf ../cue_v0.4.3_linux_arm64.tar.gz
cd ../../dist2/out
tar -zxvf ../cue_v0.4.3_linux_arm64.tar.gz
cd ../../
sha256sum dist1/out/cue dist2/out/cue
```

gives:

```
58e678fa4828965c3211f27a1062e14b2bd4424a17a6b62cd2efe3bfd31ed585  dist1/cue_v0.4.3_linux_arm64.tar.gz
836441f9b8bf190d17ef8f5a211ef7be802b74392cf9bcc9eadf4d0a5dd86a8c  dist2/cue_v0.4.3_linux_arm64.tar.gz
```

cc @seh

**Comment by myitcv** [comment]
This issue was spotted by @seh. The release for v0.5.0-beta.2 did not run properly the first time, and so was re-run. @seh happened to grab the checksums file from the first release. Subsequent downloads started to fail however because the actual release artefacts checksums had changed (following the re-release some time later).

There are two problems here:

1. We are not currently passing the `-trimpath` option to GoReleaser, hence the resulting binaries have temporary build paths included.
2. Even with fixing point 1 (which then gives us identical release contents (`cue` file, docs etc), GoReleaser does not generate identical `.tar.gz` files for the same release contents. This is demonstrated above by the use of `GOCACHE=$(mktemp -d)`.

The first of these problems is under our control. The second is a function of GoReleaser (and how we use it).

**Comment by mvdan** [comment]
Is the goreleaser side https://github.com/goreleaser/goreleaser/issues/3582? That seems to already have a PR ready.
