### ISSUE TITLE
stdlib: semver support

### ISSUE THREAD

**Issue by rogpeppe** [cue-lang/cue#2197]
Semantic versions are commonly used for describing API versions
amongst others. Comparison of these strings isn't easy in native CUE,
if possible at all, and the regular expression to constrain them is
non-trivial. We could provide a standard library package to
implement comparison and semver validity checking.

Something along the lines of this, perhaps:

```
package semver

#Version: =~ "....."
Less: func(#Version, #Version): bool
Compare: func(#Version, #Version): (-1|0|1)
```

**Comment by myitcv** [comment]
Closely related to https://github.com/cue-lang/cue/issues/407. I'd suggest we keep the earlier issue.

**Comment by mvdan** [comment]
I agree - Roger even left a comment there in September. When reviewing the cue.mod changes for modules, I wondered if we had an issue for semver support in std, and neither of us remembered an issue. Failure to search properly :)
