### ISSUE TITLE
cue vet panics if schema has conditional fields

### ISSUE THREAD

**Issue by EeroAirasvirta** [cue-lang/cue#2207]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.5.0-beta.2

       -compiler gc
        -ldflags -s -w
     CGO_ENABLED 0
          GOARCH amd64
            GOOS linux
         GOAMD64 v1
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

Validate configuration against a schema which has a conditional field.

<pre>
exec cue vet item.yml schema.cue -d '#schema'

-- item.yml --
price: 1000
justification: "We need this"
-- schema.cue --
#schema: {
  price: number
  if price > 100 {
    justification: string
  }
}
</pre>

### What did you expect to see?

Validation to pass (no output).

### What did you see instead?
<pre>
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
  panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xaf1b3a]

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0xc0003ede90)
  /home/runner/go/pkg/mod/cuelang.org/go@v0.5.0-beta.2/cmd/cue/cmd/root.go:232 +0x7b
panic({0xb84f20, 0x11d2910})
  /opt/hostedtoolcache/go/1.19.3/x64/src/runtime/panic.go:884 +0x212
cuelang.org/go/cmd/cue/cmd.doVet(0xc000399350, {0xc00036b680, 0x2, 0x4})
  /home/runner/go/pkg/mod/cuelang.org/go@v0.5.0-beta.2/cmd/cue/cmd/vet.go:98 +0xba
cuelang.org/go/cmd/cue/cmd.mkRunE.func1(0xc0003bec80?, {0xc00036b680?, 0x4?, 0x4?})
  /home/runner/go/pkg/mod/cuelang.org/go@v0.5.0-beta.2/cmd/cue/cmd/root.go:48 +0x4d
github.com/spf13/cobra.(*Command).execute(0xc0003bec80, {0xc00036b640, 0x4, 0x4})
  /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0003aa500)
  /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
  /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0xc000399350, {0x5?, 0x5?})
  /home/runner/go/pkg/mod/cuelang.org/go@v0.5.0-beta.2/cmd/cue/cmd/root.go:217 +0x6b
cuelang.org/go/cmd/cue/cmd.mainErr({0xd77df0, 0xc0000380c0}, {0xc000034250?, 0x60?, 0x11f7380?})
  /home/runner/go/pkg/mod/cuelang.org/go@v0.5.0-beta.2/cmd/cue/cmd/root.go:154 +0x55
cuelang.org/go/cmd/cue/cmd.Main()
  /home/runner/go/pkg/mod/cuelang.org/go@v0.5.0-beta.2/cmd/cue/cmd/root.go:136 +0x7c
main.main()
  /home/runner/go/pkg/mod/cuelang.org/go@v0.5.0-beta.2/cmd/cue/main.go:24 +0x19
</pre>

**Comment by mvdan** [comment]
Thanks, I can reproduce with both master and v0.4.3. I think I've spotted a fix.
