### ISSUE TITLE
add cue as native data source for gomplate

### ISSUE THREAD

**Issue by kghenderson** [cue-lang/cue#2212]
**Is your feature request related to a problem? Please describe.**
gomplate is a handy utility to process text/templates at command line without needing to compile to go.
this is very useful for simple client-side template generations. 
https://gomplate.ca/
https://github.com/hairyhenderson/gomplate

gomplate takes a template definition and structured data file (json/yaml) and produces the output,
i'd like to use cue without needing an additional output step.
more importantly, i'd like colleagues to be able to use gomplate+cue in shell scripts without needing a go compiler. 

**Describe the solution you'd like**
CUE as a native source format to gomplate, to avoid a preliminary conversion to json/yaml. 

**Describe alternatives you've considered**
- a pre-compilation step to convert from cue to json/yaml and then be imported

**Additional context**
cue imports and cue tool improvements may help with this, since this could be written as a cue tool, but really this gomplate method is much simpler for people to use.

**Comment by kghenderson** [comment]
fyi, created a mirror ticket on the gomplate site: 
https://github.com/hairyhenderson/gomplate/issues/1601

**Comment by mvdan** [comment]
Just so I understand the whole picture - is there a particular reason why you opened issues both in gomplate and CUE? Are there any changes that would need to happen in CUE itself?

**Comment by mvdan** [comment]
Looks like this happened upstream in https://github.com/hairyhenderson/gomplate/pull/1781. Closing for now.
