### ISSUE TITLE
How to install external libraries in CUE

### ISSUE THREAD

**Issue by debuggerrr** [cue-lang/cue#2223]
How can I install libraries in cue via shell? Suppose I want to install "fmt" for printing purposes but I didn't find a way to install it. In GO it comes by default but how to manage it in CUE?

**Comment by verdverm** [comment]
There is no `fmt` package in CUE. There is a `tool/cli.Print` available in the scripting layer.

The dependency management system is still TBD, but will be very close to Go's. In the meantime, you can install 3rd party modules following one of the methods here: https://cuetorials.com/first-steps/modules-and-packages/

**Comment by debuggerrr** [comment]
@verdverm  I tried importing this `tool/cli.print` but it gave me the below error:  
```
package "tool/cli.Print" imported but not defined in :
    ./mycue.cue:3:2
#Component: reference "Print" not found:
    ./mycue.cue:11:2

```

I used `Print(var)` or is there any other way of using it? or do I need to follow the link you shared for importing this package?

**Comment by mvdan** [comment]
Package management, for tracking dependencies, is under the proposal at https://github.com/cue-lang/cue/issues/851. For any other related questions, like getting help to use `tool/cli`, see https://github.com/cue-lang/cue#contact. Note that the package is `tool/cli`, not `tool/cli.Print`.

**Comment by debuggerrr** [comment]
Cool. Thanks will explore that.
