### ISSUE TITLE
Alternative of tox w.r.t CUE tests

### ISSUE THREAD

**Issue by debuggerrr** [cue-lang/cue#2228]
### Discussed in https://github.com/cue-lang/cue/discussions/2227

<div type='discussions-op-text'>

<sup>Originally posted by **debuggerrr** January 24, 2023</sup>
I was wondering if there could be anything like `tox in python` as standard testing practice. I did research but didn't find anything. Can anyone help me with how can I achieve similar things in CUE?</div>

**Comment by mvdan** [comment]
You already opened this as a discussion, and this seems like a question, so I'd suggest to keep the thread there. It's also best to avoid duplicating the threads :)
