### ISSUE TITLE
evaluator: phase out and deprecate arithmetic on lists

### ISSUE THREAD

**Issue by mvdan** [cue-lang/cue#2237]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.5.0-beta.3

      -buildmode exe
       -compiler gc
        -ldflags -w -s
     CGO_ENABLED 1
          GOARCH amd64
            GOOS linux
         GOAMD64 v3
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What did you do?

```
! exec cue export root.cue

-- root.cue --
import "list"

foo: [1, 2] + [3]
bar: list.Concat([[1, 2], [3]])
```

### What did you expect to see?

`testscript -v repro-cmd.txtar` should succeed; arithmetic on lists hasn't been part of the spec since 2021, per https://cue-review.googlesource.com/c/cue/+/8063. Right now, that feature continues to work, and I didn't even notice that I shouldn't be using it until @myitcv reminded me.

I expect `cue export` to fail on arithmetic on lists, or at least for a command like `cue fmt` to rewrite `+` with `list.Concat` as a transition step. For example, we could make CUE 0.6 apply this `cue fmt` rewrite, and a future version (0.8? 0.9?) reject the old form entirely.

### What did you see instead?

An old and removed spec feature continues to work without hiccups.

**Comment by myitcv** [comment]
Marking this a v0.6.0 pending discussion with @mpvl

**Comment by myitcv** [comment]
Moving forward to v0.6.x to implement a "fix" to rewrite to use `list.Concat`. Later deprecation etc to follow in a later release.

**Comment by 4ad** [comment]
This should also remove multiplication on lists.

**Comment by mvdan** [comment]
We closed this prematurely; the only merged commit does the `cue mod fix` step, but the step to actually remove the feature is https://review.gerrithub.io/c/cue-lang/cue/+/1200221, yet to be merged.
