### ISSUE TITLE
evaluator: regression in use of let field within if comprehension

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#2244]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.0.0-20230203125201-02e19c85e4d9

go version go1.20
      -buildmode exe
       -compiler gc
     CGO_ENABLED 1
          GOARCH arm64
            GOOS linux
             vcs git
    vcs.revision 02e19c85e4d9244bdf721584d626c8ebff287456
        vcs.time 2023-02-03T12:52:01Z
    vcs.modified false
</pre>

### Does this issue reproduce with the latest release?

This fails with the pseudo version listed above, but also with `v0.5.0-beta.5`.

### What did you do?

```
exec cue export x.cue
cmp stdout stdout.golden

-- x.cue --
package x

import (
	"strings"
)

_#matchPattern: {
	#pattern: string
	[
		// can't remove this builtin call
		if strings.HasSuffix(#pattern, "*") {

			// this let is required _within_ the if block
			// i.e. it can't be "inlined" with the if that
			// currently contains it
			let prefix = strings.TrimSuffix(#pattern, "*")

			prefix
		},
		"'\(#pattern)'",
	][0]
}

_#isReleaseTag: _#matchPattern & {#pattern: "refs/tags/v*", _}

#step: {
	if: number | string
}

m: #step & {
	if: _#isReleaseTag
}
-- stdout.golden --
{
    "m": {
        "if": "refs/tags/v"
    }
}
```

### What did you expect to see?

Passing test. It passes with `v0.4.3`.

Bisected to 36bd6562f7ba43afbd850abfa565da5576117154

### What did you see instead?

Failing test with this output:

```
> exec cue export x.cue
[stderr]
m.if: incomplete cause disjunction
[exit status 1]
FAIL: /tmp/testscript836826147/repro.txt/script.txtar:1: unexpected command failure
```

**Comment by mpvl** [comment]
The poor error message can be reproduced with:
```
	if: { [][0] }
	if: number | string
```

**Comment by mpvl** [comment]
The above reproducer can be simplified to:
```
m: {
	if: {
		#str: "refs/tags/v*"
		[
			if [#str][0] != "" {
				let prefix = "refs/tags/v*"
				prefix
			},
			"foo"
		][0]
	}
	if: number | string
}
```

This gives the suspicion that `strings.HasSuffix(#str, "*")` is failing somehow, possibly because `#str` isn't available yet.

A bisection to both simplified cases would be helpful.

**Comment by myitcv** [comment]
Apologies, totally forgot to add the commit bisect from my repro above. I had already performed the bisection, just forgot to include in the issue. I've updated my comment above, but for completeness my repro bisected to 36bd6562f7ba43afbd850abfa565da5576117154. 

I just checked: your repro bisects to exactly the same commit.

**Comment by myitcv** [comment]
This repro:

```
if: { [][0] }
if: number | string
```

has a slightly more interesting story.

With `v0.4.3`, `cue eval` and `cue export` both fail (as expected), with standard error output:

```
​​if: 1 errors in empty disjunction:
if: index out of range [0] with length 0:
    ./x.cue:1:10
```

At a8d68ad05ab615bafacc07d0ccaf12ba0d9f669a, `cue eval` and `cue export` fail (as expected). Error output improved to:

```
if: index out of range [0] with length 0:
    ./x.cue:1:10
```

At 214e11278cbe09e8ae1cbeff83bb7e61cfe1894c, `cue eval` succeeds (NOT expected), with standard output:

```
if: [][0] & (number | string)
```

At that same commit, `cue export` fails (as expected), but the error output WORSENS to just:

```
if: incomplete cause disjunction
```

At current tip (02e19c85e4d9244bdf721584d626c8ebff287456) both `cue eval` and `cue export` behave per 214e11278cbe09e8ae1cbeff83bb7e61cfe1894c (i.e. as above).
