### ISSUE TITLE
evaluator: regression when comparing incomplete structs to bottom

### ISSUE THREAD

**Issue by mvdan** [cue-lang/cue#2245]
### What version of CUE are you using (`cue version`)?

v0.5.0-beta.5:

<pre>
$ cue version
cue version v0.0.0-20230202180031-576d0e461a99

go version devel go1.21-88a36c9e9a Thu Feb 2 20:23:27 2023 +0000
      -buildmode exe
       -compiler gc
     CGO_ENABLED 1
          GOARCH amd64
            GOOS linux
         GOAMD64 v3
             vcs git
    vcs.revision 576d0e461a990ddcdab9da7a10375a1c6d87a865
        vcs.time 2023-02-02T18:00:31Z
    vcs.modified false
</pre>

### Does this issue reproduce with the latest release?

No; getting the expected output with v0.4.3.

### What did you do?

```
exec cue export in.cue
cmp stdout stdout.golden

-- in.cue --
#T: {
	test: [string]: {
		subject: _
		[string & !="subject"]: {
			assert: {
				pass: bool
			}
			assert: {
				invoke:     _
				out:        _
				res:        (subject & {in: invoke}).out
				transform?: _
				pass:       (out & tres) != _|_
				tres:       [
						if transform != _|_ {(transform & {in: res}).out},
						res,
				][0]
			}
		}
	}
	results: {
		for name, suite in test {
			let asserts = {
				for tname, x in suite
				if tname != "subject" {
					(tname): x.assert.pass == true
				}
			}
			let passes = [ for o, v in asserts if v == true {o}]
			if len(passes) > 0 {
				pass: (name): passes
			}
			let fails = [ for o, v in asserts if v == false {o}]
			if len(fails) > 0 {
				fail: (name): fails
			}
		}
	}
}

(#T & {
	test: "complex func": {
		subject: {
			in: int
			out: {
				flag: in < 10
			}
		}
		let t = {
			in: _
			out: in.flag
		}
		"0": assert: {
			invoke: 5
			transform: t
			out: true
		}
		"1": assert: {
			invoke: 60
			transform: t
			out: false
		}
	}
}).results
-- stdout.golden --
{
    "pass": {
        "complex func": [
            "0",
            "1"
        ]
    }
}
```

### What did you expect to see?

A passing test, like with cue v0.4.3.

### What did you see instead?

```
> cmp stdout stdout.golden
--- stdout
+++ stdout.golden
@@ -1,5 +1,5 @@
 {
-    "fail": {
+    "pass": {
         "complex func": [
             "0",
             "1"
```

I have further reduced the difference to:

```
exec cue export in.cue
cmp stdout stdout.golden

-- in.cue --
_fn: {
	in: _
	out: in.f
}
fnExists: _fn != _|_
-- stdout.golden --
{
    "fnExists": true
}
```

v0.4.3 gives the expected output, but v0.5.0-beta.5 gives `{"fnExists": false}`.

**Comment by mvdan** [comment]
Bisected to https://review.gerrithub.io/c/cue-lang/cue/+/545988. That _could_ mean that the change was intentional, but it seems to me like that CL was only meant to surface bugs, not change a value from true to false like the above.

**Comment by mvdan** [comment]
I was investigating another test failure from the same user's codebase, and I found another reproducer. This time, we unify two values and compare the result to bottom. The two values are identical, except that one contains a "let" field.

```
exec cue export in.cue
cmp stdout stdout.golden

-- in.cue --
obj1: f: "foo"
obj2: f: "foo"
obj2: {
	let x = obj1.x
	_use_x: x
}
unified: obj1 & obj2
notBottom: unified != _|_
-- stdout.golden --
{
    "obj1": {
        "f": "foo"
    },
    "obj2": {
        "f": "foo"
    },
    "unified": {
        "f": "foo"
    },
    "notBottom": true
}
```

The script passes with v0.4.3, but v0.5.0 reports `notBottom: false`. It sounds like the same underlying regression, as both involve comparing to bottom, and I also bisected this reproducer to https://review.gerrithub.io/c/cue-lang/cue/+/545988.

**Comment by mvdan** [comment]
On second thought, the two reproducers are quite similar. I further reduced the new one to:

```
_obj1: _
obj2: {
	let x = _obj1.missing
	_use_x: x
}
notBottom: obj2 != _|_
```

Again, the main difference is that I use a `let` inside the struct compared to bottom, rather than a regular field.

**Comment by mvdan** [comment]
@rogpeppe points out that https://cuelang.org/docs/references/spec/#structs says:

> The result of a unification is bottom (`_|_`) if any of its non-optional fields evaluates to bottom, recursively.

Both reproducers use structs with incomplete non-optional fields. There isn't a unification involved, but presumably our structs are bottom even when not unified with anything else, due to the incomplete non-optional field. Will wait to see if @mpvl agrees or disagrees with that. Perhaps the spec should be clarified a bit.

**Comment by mpvl** [comment]
This is indeed an interesting case. There are many possible interpretations for comparing to bottom. We intend to deprecate this feature in favor of more well-defined builtins that capture these differences.

Until then, one could indeed argue that only "incomplete" errors don't count when comparing to bottom. That is not always the case, though, and comparison in CUE typically always takes the concrete value.

Anyway, what is correct or not is not entirely relevant here. Given that we want to replace this construct with more tightly defined builtins, it is best to preserve existing behavior as much as possible. So it will be worth investigating what the impact of special casing incomplete errors is here. Should be relatively simple.

**Comment by rogpeppe** [comment]
> So it will be worth investigating what the impact of special casing incomplete errors is here.

If we special-cased incomplete errors, then would the following code evaluate `y` to `true` ?

```
x: {}
y: x.foo != _|_
```

**Comment by mpvl** [comment]
@rogpeppe, actually, that is different, as the reference itself is incomplete. What matters here is nested incomplete errors. 
Since comparison typically manifests a value, that doesn't seem right. However, comparison against bottom is currently inconsistent anyway and will be replaced by more precise builtins.

So for now we may as well stay as compatible as possible.

The offending code is at the end of expr.go in the bisected change, in `anyerror`. We could compromise there by ignoring incomplete errors, even though I think that is not correct behavior (but indeed how it worked in 0.4).
