### ISSUE TITLE
CI: investigate why the build cache isn't working properly for the tests

### ISSUE THREAD

**Issue by mvdan** [cue-lang/cue#2253]
In our CI with GitHub Actions, we use actions/cache to store GOCACHE and GOMODCACHE. However, sometimes we make trivial changes to our git repository, and yet many of our Go packages re-run their tests from scratch.

For example, I just merged https://github.com/cue-lang/cue/commit/03e8f294fcbeb11e8c4e04f05a6d391535565354, and presumably none of the tests should re-run their tests - they should all show up as `(cached)` in the output of `go test ./...`. However, on ubuntu-20.04 and Go 1.19.x, I see:

```
?   	cuelang.org/go/cmd/cue	[no test files]
ok  	cuelang.org/go/cmd/cue/cmd	33.812s
ok  	cuelang.org/go/cue	(cached)
ok  	cuelang.org/go/cue/ast	(cached)
ok  	cuelang.org/go/cue/ast/astutil	0.019s
?   	cuelang.org/go/cue/build	[no test files]
ok  	cuelang.org/go/cue/cuecontext	(cached)
ok  	cuelang.org/go/cue/errors	(cached)
ok  	cuelang.org/go/cue/format	0.009s
ok  	cuelang.org/go/cue/literal	(cached)
ok  	cuelang.org/go/cue/load	1.449s
ok  	cuelang.org/go/cue/parser	0.008s
ok  	cuelang.org/go/cue/scanner	(cached)
?   	cuelang.org/go/cue/stats	[no test files]
ok  	cuelang.org/go/cue/token	(cached)
ok  	cuelang.org/go/cuego	(cached)
ok  	cuelang.org/go/doc/tutorial/basics	1.107s
ok  	cuelang.org/go/doc/tutorial/kubernetes	61.238s
[...]
```

This makes our CI particularly slow, as some of these packages take tens of seconds to test.

Investigate why this is happening, and fix it. That should make our CI significantly faster.

**Comment by mvdan** [comment]
Investigated this for a bit now, and tracked it down to what I think is an unfortunate test caching behavior in cmd/go; see the link above. FYI @rogpeppe since you filed a few bugs on Go's test caching logic a few years back.

**Comment by myitcv** [comment]
Nice digging. Would one option here be to have a script/similar that sets the `mtime` of each file post checkout to the commit time (of that file)? The could presumably be scripted quite easily?

**Comment by mvdan** [comment]
If we could assume Linux, yes, the scripting is quite easy. And we should probably find a workaround on our own, since at best a fix upstream would take months until Go 1.21 is out.

Unfortunately the scripting becomes a headache on Windows. And I reckon that making use of the test cache on Mac/Windows is more important than on Linux, because those machines tend to be slower.

It could be that scripting this with `shell: bash` makes it work on Mac/Windows well enough to make the test cache happy. I'd have to try and see.

I'll engage with upstream a bit more first to see how that evolves.

**Comment by mvdan** [comment]
Per the brief back and forth with Bryan, we seem to be in agreement that the way the test cache currently works for opened files isn't great, so that will likely get improved upstream.

It's up to us whether we want to have a workaround until upstream's caching is better, which likely wouldn't land until 1.21 or 1.22. I lean towards yes, as it would speed up the trybots by likely a minute or more, and it shouldn't take much time to figure out a portable way to fix up the modified times across linux/macos/windows. I imagine it's only really worthwhile for the main repository, though, as most other repositories of ours don't have nearly as many packages and testscript tests.

**Comment by myitcv** [comment]
> I lean towards yes, as it would speed up the trybots by likely a minute or more, and it shouldn't take much time to figure out a portable way to fix up the modified times across linux/macos/windows. I imagine it's only really worthwhile for the main repository, though, as most other repositories of ours don't have nearly as many packages and testscript tests.

Agreed on all points.

**Comment by myitcv** [comment]
That said, once we have a solution for one repo we presumably have a solution that can be ported everywhere?

**Comment by mvdan** [comment]
Huh, it appears I filed practically the same issue twice in the same week. This is a duplicate of https://github.com/cue-lang/cue/issues/2239, even though I ended up posting about my investigation here. Either way, both were fixed by the same CLs.
