### ISSUE TITLE
cue: attribute parsing should respect nested brackets

### ISSUE THREAD

**Issue by rogpeppe** [cue-lang/cue#2266]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.0.0-20230211165554-7d89acd5c44b

go version devel go1.21-a4d5fbc3a4 Thu Feb 9 21:14:00 2023 +0000
      -buildmode exe
       -compiler gc
     CGO_ENABLED 1
          GOARCH amd64
            GOOS linux
         GOAMD64 v1
             vcs git
    vcs.revision 7d89acd5c44bca0c756f76089436ee9913818b03
        vcs.time 2023-02-11T16:55:54Z
    vcs.modified false
</pre>

### Does this issue reproduce with the latest stable release?

Yes

### What did you do?

```
exec go mod tidy
exec go run main.go
cmp stdout expect-stdout

-- go.mod --
module test

require cuelang.org/go v0.4.3
-- main.go --
package main

import (
	"fmt"

	"cuelang.org/go/cue"
	"cuelang.org/go/cue/cuecontext"
)

func main() {
	ctx := cuecontext.New()
	v := ctx.CompileString(`
x: 1 @A(t=(a, b))
`)
	a := v.Lookup("x").Attributes(cue.FieldAttr)[0]
	fmt.Println(a.Arg(0))
}

-- expect-stdout --
t=(a, b)

```
### What did you expect to see?

A passing test.

### What did you see instead?

```
> exec go mod tidy
> exec go run main.go
[stdout]
t (a
> cmp stdout expect-stdout
--- stdout
+++ expect-stdout
@@ -1,1 +0,0 @@
-t (a
@@ -0,0 +1,1 @@
+t=(a, b)
```

The attribute is split on comma even though there are nested parentheses.
It would be in the spirit of the attribute syntax to allow arbitrarily nested substructure for attributes.

**Comment by myitcv** [comment]
cc @4ad. @mpvl mentioned this may be required/key part of the Wasm work?

**Comment by myitcv** [comment]
Marking as v0.6.0 for now, on the basis there might be a Wasm dependency.
