### ISSUE TITLE
spec: no mention of dynamic fields

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#2267]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.0.0-20230211165554-7d89acd5c44b

go version go1.20
      -buildmode exe
       -compiler gc
     CGO_ENABLED 1
          GOARCH arm64
            GOOS linux
             vcs git
    vcs.revision 7d89acd5c44bca0c756f76089436ee9913818b03
        vcs.time 2023-02-11T16:55:54Z
    vcs.modified false
</pre>

### Does this issue reproduce with the latest stable release?

Yes

### What did you do?

IntelliJ has an excellent CUE plugin (https://github.com/monogon-dev/intellij-cue) that is used by many CUE users. 

In https://github.com/monogon-dev/intellij-cue/issues/53, users are reporting that dynamic fields are not understood by that plugin.

In fixing https://github.com/monogon-dev/intellij-cue/issues/53, @jansorg observed that the spec makes no mention of dynamic fields. Quoting from the relevant part of https://cuelang.org/docs/references/spec/#structs:

```
StructLit       = "{" { Declaration "," } "}" .
Declaration     = Field | Ellipsis | Embedding | LetClause | attribute .
Ellipsis        = "..." [ Expression ] .
Embedding       = Comprehension | AliasExpr .
Field           = Label ":" { Label ":" } AliasExpr { attribute } .
Label           = [ identifier "=" ] LabelExpr .
LabelExpr       = LabelName [ "?" ] | "[" AliasExpr "]" .
LabelName       = identifier | simple_string_lit  .

attribute       = "@" identifier "(" attr_tokens ")" .
attr_tokens     = { attr_token |
                    "(" attr_tokens ")" |
                    "[" attr_tokens "]" |
                    "{" attr_tokens "}" } .
attr_token      = /* any token except '(', ')', '[', ']', '{', or '}' */
```

So it appears the spec needs to be updated with at least the EBNF to make clear for @jansorg and others working with the syntax of CUE what is valid, but also some explanatory text about dynamic fields.

### What did you expect to see?

A mention of dynamic fields in the spec, along with EBNF specification.

### What did you see instead?

No mention of dynamic fields.

cc @mpvl

**Comment by mpvl** [comment]
At least syntactically, shouldn't `AliasExpr` match the dynamic field?
