### ISSUE TITLE
cue-lang/setup-cue: document release versioning & behaviour

### ISSUE THREAD

**Issue by jpluscplusm** [cue-lang/cue#2270]
Hello 👋 

I've been using [cue-lang/setup-cue](https://github.com/cue-lang/setup-cue) for a few weeks, to install CUE inside GitHub Actions (GHA), and I've found that a few things stand out about the current state of that GHA Action:

- The README refers to `v1`, but that version doesn't exist (also addressed in https://github.com/cue-lang/setup-cue/pull/11)
- The 3 tags present are either explicitly marked as alpha, or `v0.0.1`. Whilst of course pre-1.0, `v0.0.1` could be argued to be the most "official", but it's not clear if that's the case 
- Configuring the Action to download the `latest` CUE version results in 0.5.0 **beta** releases being installed, which doesn't feel like a precedent that wants to persist after the Action's v1 (or later) is released. As a consumer, I know that when both Action and CUE are pre-1.0, pretty much "anything goes", but my *expectation* is that `latest` implies a non-beta release - even if it is pre-1.0.

All of the above would seem to be initially-fixable via doc updates, so that if consumers see something that doesn't match their expectations, they have a route to file specific Issues about the behaviours and argue one way or the other... versus the situation right now, where the behaviours aren't well defined, so argument is somewhat less effective!

**Comment by Nemo157** [comment]
Somewhat related, the current versions of setup-cue will likely stop working in ~2 months because they use the `set-output` command: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/. There was a PR merged to fix this a few months ago (https://github.com/cue-lang/setup-cue/pull/10) but it's not yet in a release.
