### ISSUE TITLE
CI: runtrybot fails when triggered a second time on a CL patchset

### ISSUE THREAD

**Issue by mvdan** [cue-lang/cue#2275]
When one wants to test a CUE CL, the following steps happen:

* Developer runs `cueckoo runtrybot HEAD`
* The command above triggers the `trybot_dispatch` workflow on `cue-lang/cue`
* `trybot_dispatch` creates a branch on `cue-lang/cue-trybot` with the change, and opens a PR to run the actual tests (the PR helps with sharing caches between builds)

However, that third step uses a branch name in the form of `trybot/${change_id}/${commit}/${cl}/${patchset}`, like `trybot/Ie11c8cfdc3741927c2aae28bce0d67c214411480/0539d459a8bcc4dc0d424e42f24214271722f0b7/548783/4`. If I run `cueckoo runtrybot` twice on the same CL patchset, which has the same change ID and commit hash, then `trybot_dispatch` pushes to the same branch name and tries to open an identical PR.

And, unfortunately, GitHub doesn't like opening such a PR if an identical one was already opened in the past, even if it was closed by our automation:

> a pull request for branch "trybot/Ie11c8cfdc3741927c2aae28bce0d67c214411480/0539d459a8bcc4dc0d424e42f24214271722f0b7/548783/4" into branch "master" already exists:
> https://github.com/cue-lang/cue-trybot/pull/146

Being able to run the trybots twice on the same commit may seem unnecessary, but there are situations where it's necessary, such as temporarily working around test flakes. In any case, failing with this PR step isn't right.

One potential fix is to always use unique branch names, such as by appending a random string as a last `/${RANDOM}` component. This would avoid conflicts with branch names and PRs, but it would still allow us to easily fetch the variables like the change ID or CL number from the branch name.

cc @mpvl @myitcv

**Comment by mvdan** [comment]
Opened in this repo and not in https://github.com/cue-sh/tools, since the bug is in the workflow contained in this repo, and not in cmd/cueckoo.

**Comment by mvdan** [comment]
@myitcv and I fixed this by no longer using GitHub Pull Requests to trigger Actions for the trybots. We use force-pushes to a single branch now.

**Comment by myitcv** [comment]
Delighted to be able to close this. Thanks for all your helping making and testing those changes.
