### ISSUE TITLE
Wrong release file name about the CPU architecture

### ISSUE THREAD

**Issue by yanghua** [cue-lang/cue#2286]
When I want to download the [released binary file](https://github.com/cue-lang/cue/releases/tag/v0.4.3), I saw the same name as `arm64` (no `x86`).

**Comment by mvdan** [comment]
Sorry, what do you mean exactly? The x86-64 binaries are named `amd64`, because that's what Go calls that architecture.

**Comment by yanghua** [comment]
aha, got it, I thought the `arm64` and `amd64` were the same name. Not an issue sir.
