### ISSUE TITLE
[] != ["x"] evaluates to false

### ISSUE THREAD

**Issue by mmlt** [cue-lang/cue#2289]
### What version of CUE are you using (`cue version`)?
playground v0.4.3

### Does this issue reproduce with the latest stable release?
yes

### What did you do?
a: [] != ["x"]
https://cuelang.org/play/?id=33VAqhnqmrA#cue@export@cue

### What did you expect to see?
a: true

### What did you see instead?
a: false

PS I believe https://github.com/cue-lang/cue/blob/27b6e87efbde0d14b31eeb59943ff79b90fb92ec/internal/core/adt/binop.go line 113 should return c.newBool(true)

**Comment by mvdan** [comment]
Nicely spotted. Duplicate of https://github.com/cue-lang/cue/issues/2042, which was filed first and has a bit more context from other users. I will get your PR merged fixing that issue instead.
