### ISSUE TITLE
cmd/import: Formatting breaks if it contains multibyte characters

### ISSUE THREAD

**Issue by ornew** [cue-lang/cue#2294]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.5.0-beta.2

       -compiler gc
        -ldflags -s -w
     CGO_ENABLED 0
          GOARCH arm64
            GOOS darwin
</pre>

### Does this issue reproduce with the latest stable release?

Yes.
I got the same result with 0.4.3.

### What did you do?

I import and format the following YAML, but the output is dirty.

`cue import test.yaml && cue fmt test.cue && cat test.cue`

test.yaml:

```yaml
x1:
  description: AAAA
  type: string
x2:
  description: AAAA
  type: string
x3:
  description: ああああ
  type: string
x4:
  description: ああああ
  type: string
```

### What did you expect to see?

```cue
x1: {
	description: "AAAA"
	type:        "string"
}
x2: {
	description: "AAAA"
	type:        "string"
}
x3: {
	description: "ああああ"
	type:        "string"
}
x4: {
	description: "ああああ"
	type:        "string"
}
```

### What did you see instead?

```cue
x1: {
	description: "AAAA"
	type:        "string"
}
x2: {
	description: "AAAA"
	type:        "string"
}
x3: {
	description: "ああああ", type:
			"string"
}
x4: {
	description:

		"ああああ", type: "string"
}
```

It works fine as a CUE, but it greatly impairs readability.
For alphabets it works fine and in this case you can see the output is broken after using Japanese.

Also, if you give fmt the files it expects, it won't break the styles.

test2.cue:

```cue
x1: {
	description: "AAAA"
	type:        "string"
}
x2: {
	description: "AAAA"
	type:        "string"
}
x3: {
	description: "ああああ"
	type:        "string"
}
x4: {
	description: "ああああ"
	type:        "string"
}
```

`cue fmt test.cue`:

```cue
x1: {
	description: "AAAA"
	type:        "string"
}
x2: {
	description: "AAAA"
	type:        "string"
}
x3: {
	description: "ああああ"
	type:        "string"
}
x4: {
	description: "ああああ"
	type:        "string"
}
```

It seems that fmt respected the output of the import. The import should output in the clean format.

**Comment by uhthomas** [comment]
Looks like #826?

**Comment by mvdan** [comment]
Indeed a duplicate, thank you @uhthomas for investigating.
