### ISSUE TITLE
cue/fmt: Lists are indented too much

### ISSUE THREAD

**Issue by uhthomas** [cue-lang/cue#2314]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
0.4.3-1
</pre>

### Does this issue reproduce with the latest stable release?

Yes.

### What did you do?

```cue
import "list"

#List: items: list.Concat([
    a,

    b
])
```

### What did you expect to see?

```cue
import "list"

#List: items: list.Concat([
    a,

    b
])
```

### What did you see instead?

```cue
import "list"

#List: items: list.Concat([
        a,

    b
])
```

**Comment by uhthomas** [comment]
FWIW, this is fine:

```cue
import "list"

items: list.Concat([
    a,

    b
])
```

Looks like a problem with shorthand notation and depth calculation. The formatter should understand that just because it's of `depth: 2` does not mean that's how much it should be indented. Clearly the logic for this already exists as successive items are indented correctly.

**Comment by mvdan** [comment]
Thank you, this does look like a formatting bug.

**Comment by uhthomas** [comment]
Looks like it's related to the length of the line.

```cue
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa: list.Concat([
                                                ["a"],

        ["b"],
])
```

**Comment by Nemo157** [comment]
It seems to only trigger when the list is not the top-level value, i.e. this is fine:
```cue
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa: [
        ["a"],

        ["b"],
]
```

but these fail:

```cue
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa: _ | [
                                                ["a"],

        ["b"],
]

aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa: *[
                                                ["a"],

        ["b"],
]
```

if the subsequent lines don't change indentation then it continues using the incorrect indentation for them:

```cue
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa: *[
                                                ["a"],
                                                ["b"],
]
```
