### ISSUE TITLE
cmd/fmt: lists have incorrect whitspace prefix

### ISSUE THREAD

**Issue by uhthomas** [cue-lang/cue#2321]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
0.4.3-1
</pre>

### Does this issue reproduce with the latest stable release?

Yes.

### What did you do?

Pretty sure I already raised this, but I can't find it, sorry. 

```cue
[ "a" ]
```
### What did you expect to see?

```cue
["a"]
```

### What did you see instead?

```cue
[ "a"]
```

**Comment by myitcv** [comment]
This is a dup of #1023. That issue already has the `fmt` label.

**Comment by uhthomas** [comment]
@myitcv I knew I already opened an issue! Thanks for finding it.
