### ISSUE TITLE
alpha.cuelang.org: playground should be served in local development

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#2348]
Currently the playground is not served when running alpha.cuelang.org locally. The loading "spinner" continues to, well, spin:

<img width="1169" alt="Screenshot 2023-04-15 at 16 55 45" src="https://user-images.githubusercontent.com/3374574/232235536-e0096f2e-83fa-4b36-bec1-942097b0678c.png">

Instead it has separate instructions to run independent of the local site:

https://github.com/cue-lang/cuelang.org/tree/039e3a06287f25f35171987e8fa9378b552e5a26/editor

We should fix this to make it run as part of the site being developed locally.

**Comment by myitcv** [comment]
Still an issue with alpha as of https://github.com/cue-lang/cuelang.org/commit/ed2352538858dbed1d505c233f0fdb9578637999

**Comment by mvdan** [comment]
I ran build.bash followed by run.bash and the playground now works locally, as of https://github.com/cue-lang/cuelang.org/commit/c06bde057359494602bc16f3924cdf28fd2b2551 :) I imagine something was fixed in the last few months.

**Comment by mvdan** [comment]
Or it could be that you ran `run.bash` without `build.bash`? That's what I did initially, and the result was broken in a weird way - though different from yours.

**Comment by mvdan** [comment]
> Instead it has separate instructions to run independent of the local site:

I totally misunderstood your report. I am indeed running `run.bash` and `build.bash` inside the playground directory.

**Comment by myitcv** [comment]
This has been fixed for some time. Confirmed working in bcf703c3b2d4cfbbab3d0b5cb779534793d4c223 so closing.
