### ISSUE TITLE
cuelang.org: "Create Documentation Issue" link broken

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#2364]
As of https://github.com/cue-lang/cuelang.org/tree/15f879b2ae82de366f61dbab033179848c8400ec.

For example on page https://cuelang.org/docs/about/#philosophy-and-principles.

Top right hand corner there are a sequence of links:

<img width="361" alt="Screenshot 2023-04-24 at 09 24 09" src="https://user-images.githubusercontent.com/3374574/233940873-5cac1ea4-0eba-40dd-b85c-cce719767346.png">

The "Create Documentation Issue" link is broken. It tries to link to `cue-lang/cuelang.org` to create an issue. But we have intentionally disabled issues in that repo in favour of tracking all issues in this repo, `cue-lang/cue`. 

The fix here should be to link to the main issue tracker with a title prefix of `cuelang.org:` and the `cuelang.org` label (just like this issue). 

Indeed the main repo needs an issue/bug template dedicated to reports from cuelang.org.

**Comment by myitcv** [comment]
Given that we are moving along nicely with https://alpha.cuelang.org, I'm tempted to not fix this on the current (soon to be old) site. See https://github.com/cue-lang/cue/issues/2446

**Comment by evmar** [comment]
I found this bug because I was about to file it myself.  As a person doing a first kind of speculative poke around the cue docs, it is surprising to me to see this unfixed for ~8 months!

**Comment by myitcv** [comment]
This is redundant as of the new https://cuelang.org where there is a link at the bottom of each page that _does_ work:

![327094336-885b9636-a62e-4878-b893-c199960b67dd](https://github.com/cue-lang/cue/assets/3374574/1409f31a-a61a-4472-83a2-c50ecae8690a)
