### ISSUE TITLE
tools/flow: cannot define tasks inside array

### ISSUE THREAD

**Issue by rogpeppe** [cue-lang/cue#2365]
### What version of CUE are you using (`cue version`)?

<pre>
commit 59080b65a5ba539bb3f3cb45d3346f39df67cf01
</pre>

### Does this issue reproduce with the latest stable release?

Yes

### What did you do?

```
exec go mod tidy
exec go run main.go
stdout task1
stdout task2

-- go.mod --
module test
require cuelang.org/go v0.6.0-0.dev.0.20230324092610-eea60b9cd229
-- main.go --

package main

import (
	"context"
	"fmt"
	"log"

	"cuelang.org/go/cue"
	"cuelang.org/go/cue/cuecontext"
	"cuelang.org/go/tools/flow"
)

var cueCode = `
task1: {
	isTask: true
}
task2: [{
	isTask: true
}]
`

func main() {
	ctx := cuecontext.New()
	v := ctx.CompileString(cueCode)
	if err := v.Err(); err != nil {
		log.Fatal("cannot compile: %v", err)
	}
	ctl := flow.New(nil, v, getTask)
	if err := ctl.Run(context.Background()); err != nil {
		log.Fatalf("error running flow: %v", err)
	}
}

func getTask(v cue.Value) (flow.Runner, error) {
	if v := v.LookupPath(cue.MakePath(cue.Str("isTask"))); v.Err() != nil {
		return nil, nil
	}
	fmt.Printf("task %v\n", v.Path())
	return flow.RunnerFunc(func(t *flow.Task) error {
		return nil
	}), nil
}
```

### What did you expect to see?

A passing test.

### What did you see instead?

```
> exec go mod tidy
> exec go run main.go
[stdout]
task task1
> stdout task1
> stdout task2
FAIL: /tmp/testscript1319682935/x.txtar/script.txtar:4: no match for `task2` found in stdout
```

The tools/flow package does not appear to be finding tasks that are defined inside an array.

**Comment by verdverm** [comment]
One thing that would be helpful is for a way to run tasks sequentially, without having to create the dependencies by hand.

I once considered using lists of tasks, but found this gap in the implementation, the tasks not being found, so put it on the back burner. There is an intuitiveness to lists of tasks being sequentially run.

Thoughts?
