### ISSUE TITLE
evaluator: aliasing to a constraint results in invalid output.

### ISSUE THREAD

**Issue by nicuveo** [cue-lang/cue#2374]
### What version of CUE are you using (`cue version`)?

The playground (v0.5.1-0.20230413144408-f681271a38ec and v0.6.0-alpha.1.0.20230428121230-80d6ea032057).

### What did you do?

```cue
r = [string]: {b: r}
a: {r: 0}
```

### What did you expect to see?

Regardless of whether we are to understand `r` as a reference to `a`, the actual field being matched, when evaluating `b`, or as a reference to the body of the constraint, it should result in a **structural cycle**, since it would be equivalent to either `a: {b: a}` or to `cond_1: r = {b: r}`.

### What did you see instead?

This invalid output, which makes a reference to a non-existent field or alias.

```cue
a: {
	r: 0
	b: r_1
}

let r_1 = r
```

### Sidenotes.

- this output also shows an example of _alias renaming_, a behaviour that's not documented in the specification
- i don't think i have been able to come up with an example of an alias to a constraint making sense / being used in a way that didn't result in a structural cycle / evaluation problem; is there any plan to remove this feature / deprecate it?

**Comment by myitcv** [comment]
Marking as triage to bisect. Tentatively scheduling for v0.7.0 so we don't double up on work in v0.6.0 (changes in v0.7.0 make fixing this easier).

**Comment by mpvl** [comment]
@nicuveo: thanks for catching this. This absolutely a bug.

Referencing a parent value can be useful. One example for the definition of recursive types, like linked lists. To break the structural cycle, a reference `r`, for instance, can be used in combination with `null`, as in `r | *null`.

It may be not so obvious to come up with an analogous example using pattern constraints in particular, but it also seems arbitrary to prohibit this particular case.

The alias renaming is not an evaluation thing, but rather an aspect of representing evaluated CUE. As such, it is not defined in the spec.
