### ISSUE TITLE
spec: bug in `len` or incorrect specification

### ISSUE THREAD

**Issue by nicuveo** [cue-lang/cue#2376]
### What version of CUE are you using (`cue version`)?

The playground version (v0.5.1-0.20230413144408-f681271a38ec and v0.6.0-alpha.1.0.20230428121230-80d6ea032057).

### What did you do?

`len([1,2,3,...])`

### What did you expect to see?

As per https://cuelang.org/docs/references/spec/#len, i would expect `>=3`.

### What did you see instead?

`3`. It looks like `len` ignores the fact that the list is open. I don't know if it's a bug in `len`, or if the specification is outdated?

**Comment by uhthomas** [comment]
I don't think there's any bug here, maybe the spec should be clearer. In my mind, the spec is just saying the value of len should be 2 or greater and not the actual value `>=2`.

Logically, `[1,2,3,...]` is actually just `[1,2,3]` and so a length of 3 makes sense. The ellipsis just denotes the list is open and such:

```cue
a: [1, 2, 3, ...]

a: [1, 2, 3, 4]

b: len(a)
```

```cue
a: [1, 2, 3, 4]
b: 4
```

**Comment by myitcv** [comment]
Thanks for flagging, @nicuveo. This is a bug in the spec.

**Comment by mpvl** [comment]
Another spec bug. Thanks for catching this! `len` always returns a concrete integer. It is also no longer supported for strings.
