### ISSUE TITLE
evaluator: alias inlining results in invalid output

### ISSUE THREAD

**Issue by nicuveo** [cue-lang/cue#2378]
### What version of CUE are you using (`cue version`)?

The playground (v0.5.1-0.20230413144408-f681271a38ec and v0.6.0-alpha.1.0.20230428121230-80d6ea032057).

### What did you do?

```cue
a: {
  x = b: 0
  d: {
    b: 1
    c: x & a.z
  }
}
```

### What did you expect to see?

This one is tricky. Due to `a.z` not existing, the expression of `c` cannot be computed yet. I would therefore expect the output to be _exactly the same as the input_:

```cue
a: {
  x = b: 0
  d: {
    b: 1
    c: x & a.z
  }
}
```

### What did you see instead?

```cue
a: {
	b: 0
	d: {
		b: 1
		c: b & a.z
	}
}
```
In this output, the `x` alias got inlined, but then the evaluation of `c` bailed out, resulting in an incorrect equation for `c`, since future processing would use the `b` present in `a.d`. I assume that this is because the evaluation starts with inlining all aliases before proceeding with evaluation (i do the same thing and have the same bug in my hobby implementation ^^).

**Comment by myitcv** [comment]
Thanks for the detailed report here, @nicuveo! 

For the record, with `cue def` here is the test case:

```
exec cue def x.cue
cmp stdout stdout.golden

-- x.cue --
a: {
	x = b: 0
	d: {
		b: 1
		c: x & a.z
	}
}
-- stdout.golden --
a: {
	b: 0
	d: {
		b: 1
		c: x & a.z
	}
}
```

### What did you expect to see?

Passing test

### What did you see instead?

```
$ ts repro.txtar
> exec cue def x.cue
[stdout]
a: {
        b: 0
        d: {
                b: 1
                c: b & a.z
        }
}
> cmp stdout stdout.golden
--- stdout
+++ stdout.golden
@@ -2,6 +2,6 @@
        b: 0
        d: {
                b: 1
-               c: b & a.z
+               c: x & a.z
        }
 }

FAIL: /tmp/testscript518739788/repro.txtar/script.txtar:2: stdout and stdout.golden differ
```
