### ISSUE TITLE
evaluator: unification doesn't propagate to field reference

### ISSUE THREAD

**Issue by grantzvolsky** [cue-lang/cue#2392]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.6.0-alpha.1

go version go1.20.3
      -buildmode exe
       -compiler gc
       -trimpath true
     CGO_ENABLED 0
          GOARCH amd64
            GOOS linux
         GOAMD64 v1
</pre>

### Does this issue reproduce with the latest stable release?

Yes

### What did you do?

<pre>
cd $(mktemp -d)
(
set -e
cat <<EOD > x.cue
#A: {
        v: {
                metadata: labels: {
                        la: string
                }
                spec: {
                        la: v.metadata.labels.la
                }
        }
}

value: #A.v
value: metadata: labels: la: "concrete"
EOD
cue eval -c ./x.cue
)
</pre>

### What did you expect to see?

```
value: {
    metadata: {
        labels: {
            la: "concrete"
        }
    }
    spec: {
        la: "concrete"
    }
}
```

### What did you see instead?

```
value.spec.la: incomplete value (string):
    ./x.cue:4:29
```

**Comment by rogpeppe** [comment]
Thanks for the report, and the minimised example. This is behaving as intended, I believe.

When you do `value: #A.v`, you're copying the value _inside_ `v`, but the `v.metadata.labels.la` expression is referring to something outside that value, namely the reference `v` itself, which has not been copied, hence it still refers to the incomplete value.

If you change the expression to `metadata.labels.la`, it will work as you expect.

Some more tutorial-style documentation in this area could go a long way toward helping to explain this behaviour!
