### ISSUE TITLE
evaluator: comprehension that creates constraint violation silently allowed

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#2403]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.0.0-20230511092117-a670427406af

go version go1.20.2
      -buildmode exe
       -compiler gc
     CGO_ENABLED 1
          GOARCH arm64
            GOOS linux
             vcs git
    vcs.revision a670427406af7451da77cf477c0786d6f1b129c8
        vcs.time 2023-05-11T09:21:17Z
    vcs.modified false
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
! exec cue vet -c x.cue
stderr 'x.age: conflicting values int and "age" (mismatched types int and string)'

-- x.cue --
x: {
	name: string
	age:  int
}

x: {
	for k, _ in x {
		(k): k
	}
}
```

### What did you expect to see?

A passing test.

### What did you see instead?

```
> ! exec cue vet -c x.cue
[stderr]
x.age: incomplete value int:
    ./x.cue:3:8
[exit status 1]
> stderr 'x.age: conflicting values int and "age" (mismatched types int and string)'
FAIL: /tmp/testscript1176224950/repro.txtar/script.txtar:2: no match for `x.age: conflicting values int and "age" (mismatched types int and string)` found in stderr
```

i.e. the mismatch between `int` and `"age"` appears to have been lost, and the error has instead proceeded to a complaint about the `age` field being incomplete (one of the last checks).

Indeed this is somewhat confirmed by the result of `cue eval`:

```
$ cue eval x.cue
x: {
    name: "name"
    age:  int
}
```

**Comment by myitcv** [comment]
Marking this as v0.6.0 because at least v0.4.3 reported an error that this was a cycle. It feels strictly worse that we are reporting this an incomplete error.

**Comment by rogpeppe** [comment]
Perhaps a better test (more befitting the issue title) might be to run `cue vet -c=false`, which succeeds inappropriately.
