### ISSUE TITLE
Usage of imported packages ignores non-concrete values inside string interpolation

### ISSUE THREAD

**Issue by fionera** [cue-lang/cue#2407]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version 0.5.0

go version go1.20.3
      -buildmode exe
       -compiler gc
       -trimpath true
     CGO_ENABLED 1
          GOARCH amd64
            GOOS linux
         GOAMD64 v1
</pre>

### Does this issue reproduce with the latest stable release?
Yep

### What did you do?

```
-- cue.mod/module.cue --
module: "monogon.tech"
-- reprod.cue --
package reprod

import "monogon.tech/sub"

// this should throw an error as there are non concrete values in there
// if value is missing like this it should throw an error
// correct behaviour should be: throw an error
out_invalid: sub.SubStruct.resources

// if value is given like this it has the correct behaviour
out_valid: (sub.SubStruct & { nonConcrete: "concrete" }).resources

-- sub/sub.cue --
package sub

SubStruct: {
        nonConcrete: string

        entry: [string]: string
        entry: "\(nonConcrete)": "foo"

        resources: [string]: bool

        if len(entry) != 0 {
                resources: "entry": true
        }

        resources: "other": true
}
```

### What did you expect to see?
As explained in the comments above an error should be thrown as there are non-concrete values inside the imported and used package

### What did you see instead?

```
$ cue export
{
    "out_invalid": {
        "other": true
    },
    "out_valid": {
        "entry": true,
        "other": true
    }
}
```

**Comment by myitcv** [comment]
Close to https://github.com/cue-lang/cue/issues/2201. @mvdan to investigate.

**Comment by mvdan** [comment]
I confirm that this seems to be a duplicate of #2201. Importing a package is not necessary to reproduce this bug, as this minimized testscript reproduces @fionera's problem in a similar way to Paul's testscript in the other issue thread:

```
exec cue export -e out_valid f.cue

! exec cue export -e out_invalid f.cue
-- f.cue --
out_invalid: #SubStruct.resources

out_valid: (#SubStruct & {nonConcrete: "concrete"}).resources

#SubStruct: {
	nonConcrete: string
	entry: "\(nonConcrete)": "foo"
	resources: "entry": true
}
```

Note that Paul's example used embedding, and this one does not, so I will leave a comment there so that we can have another regression test.
