### ISSUE TITLE
cue fmt flags for checking formatting

### ISSUE THREAD

**Issue by Kilobyte22** [cue-lang/cue#2408]
**Is your feature request related to a problem? Please describe.**
It is currently very painful to verify formatting as part of a CI workflow

**Describe the solution you'd like**
A flag `--check` or similar that would automatically exit with a non-zero exitcode and appropriate error message, if cue fmt would perform any changes on the code. Additionally it should probably print a diff, which the `-d` flag suggested in #1731 would also do

**Describe alternatives you've considered**
This could possibly also become a flag on `cue vet`, like `cue vet --formatting`.
The current solution is to create a copy of the code, format it and diff it against the original. While doable, this is however unnecessary ceremony if you have many repositories with cue code in it

**Additional context**
I've seen this feature in other programming tools: For example: `black` for python has the `--check` flag. `cargo fmt` for rust also has a `--check` flag.

**Comment by verdverm** [comment]
We use `git diff --exit-code` to see if there were any file changes in CI. Works for both formatting and any code gen you may do.

**Comment by mvdan** [comment]
Please see https://github.com/cue-lang/cue/issues/1731. Closing as a duplicate, to avoid splitting the discussion.
