### ISSUE TITLE
cmd/cue: evaluation of multiple imports much slower than a glob of CUE files

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#2413]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.0.0-20230522090210-82f96c5e4073

go version go1.20.4
      -buildmode exe
       -compiler gc
     CGO_ENABLED 1
          GOARCH arm64
            GOOS linux
             vcs git
    vcs.revision 82f96c5e4073ea856efd29cb4153809ac2fb5c1d
        vcs.time 2023-05-22T09:02:10Z
    vcs.modified false
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

For alpha.cuelang.org we are experimenting with two different approaches to maintaining a single graph of configuration.

Approach 1 (https://review.gerrithub.io/c/cue-lang/cuelang.org/+/554244) performs the equivalent of a `cue export **/*.cue`, combining all of the `.cue` files defined in each of the directories that constitutes a page. 

Approach 2 (https://review.gerrithub.io/c/cue-lang/cuelang.org/+/554241) treats each page directory as a separate package, imports each of the page packages, and places the values at the corresponding path. 

(Note: neither is this list of different approaches is exhaustive, nor is this issue about the relative merits of each approach. This issue is specifically about a performance difference noted between two such alternatives, observed in passing and noted here).

The commit message for each CL above shows some rough stats for each. Those stats are reproduced here

Approach 1:

```
$ time CUE_STATS_FILE=- cue export -f --out json -o /dev/null ./content/site.cue content/**/page.cue
{
    "Unifications": 102,
    "Disjuncts": 105,
    "Conjuncts": 397,
    "Freed": 104,
    "Reused": 93,
    "Allocs": 11,
    "Retained": 1
}

real    0m0.038s
user    0m0.013s
sys     0m0.031s
```

Approach 2:

```
$ time CUE_STATS_FILE=- cue export -f --out json -o /dev/null ./content
{
    "Unifications": 185,
    "Disjuncts": 188,
    "Conjuncts": 469,
    "Freed": 101,
    "Reused": 91,
    "Allocs": 96,
    "Retained": 87
}

real    0m3.882s
user    0m4.926s
sys     0m0.241s
```

### What did you expect to see?

Similar wall clock times for both calls to `cue export`, because as can be seen from the stats output, they are performing roughly the same number of evaluations (at least the same order of magnitude). 

### What did you see instead?

Approach 2 taking ~100 times as long as approach 1.

**Comment by myitcv** [comment]
FYI @rogpeppe

**Comment by myitcv** [comment]
Updated the numbers above; my timing was incorrectly taking into account the time to list the files in the glob. Narrowing that glob to the directory in question reduces the wall clock time for approach 1 to a tiny 0.038s, ~100 times less than the import approach.

**Comment by myitcv** [comment]
cc @mvdan for possible dupe.

**Comment by myitcv** [comment]
Dupe of https://github.com/cue-lang/cue/issues/2413

**Comment by myitcv** [comment]
Re-opening, because per @mvdan this is actually a real case where an import _does_ need to be resolved. Whereas in #2413, `cue fmt` does _not_ need to resolve imports, per #728.

**Comment by erkankayaabex** [comment]
Has this been sorted? We observe a few not too big files being parsed around 3m20s. Practically unusable product if you consider this to be ok. An earlier version used to be doing the same job in a few seconds. Using the latest, release or even compiling from the source doesn't fix it.

**Comment by myitcv** [comment]
@erkankayaabex 

> Has this been sorted?

No, this has not yet been fixed. Hence this issue remains open to track that. 

> We observe a few not too big files being parsed around 3m20s.
>
> ...
> 
> An earlier version used to be doing the same job in a few seconds. Using the latest, release or even compiling from the source doesn't fix it.

Are you sure you are suffering from the same problem? Please feel free to open a new issue if you are unsure or would like us to look further. Especially given that you indicate things have changed between releases - this behaviour has not, per se, changed recently.

> Practically unusable product if you consider this to be ok. 

This is an unnecessary statement. There is no indication that the behaviour reported in this issue is "ok". Indeed the very existence of the issue points to quite the opposite stance. 

As I mention above, I'm not entirely clear that you are necessarily running into the same issue. Please feel free to raise a new issue and we can help investigate.

**Comment by mvdan** [comment]
The original numbers are over a year old now, so I thought I'd grab new ones. I had to use the original CLs as you had them, even if they are abandoned, as neither command really does the same sort of benchmark on the master branch of cuelang.org.

Approach 1:

```
$ time CUE_STATS_FILE=- cue export -f --out json -o /dev/null ./content/site.cue content/**/page.cue
{
    "CUE": {
        "Unifications": 170,
        "Disjuncts": 208,
        "Conjuncts": 568,
        "Freed": 197,
        "Reused": 177,
        "Allocs": 21,
        "Retained": 13
    },
    "Go": {
        "AllocBytes": 6833144,
        "AllocObjects": 64590
    }
}

real	0m0.022s
user	0m0.024s
sys	0m0.003s
```

Approach 2:

```
$ time CUE_STATS_FILE=- cue export -f --out json -o /dev/null ./content
{
    "CUE": {
        "Unifications": 253,
        "Disjuncts": 291,
        "Conjuncts": 640,
        "Freed": 194,
        "Reused": 175,
        "Allocs": 106,
        "Retained": 99
    },
    "Go": {
        "AllocBytes": 10887800,
        "AllocObjects": 116444
    }
}

real	0m0.028s
user	0m0.036s
sys	0m0.015s
```

I was curious enough to see what change fixed this between early 2023 and mid 2024, so I did a bisect - and the result is https://review.gerrithub.io/c/cue-lang/cue/+/1193257 :) That filetypes speed-up is the gift that keeps on giving, surprisingly enough. Marking as resolved!
