### ISSUE TITLE
cue get go conflicts with standard packages

### ISSUE THREAD

**Issue by uhthomas** [cue-lang/cue#2422]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
0.5.0
</pre>

### Does this issue reproduce with the latest stable release?

Yes.

### What did you do?

Get a Go package which imports [time](https://pkg.go.dev/time).

```sh
❯ cue get go github.com/rook/rook/pkg/apis/ceph.rook.io/v1
```

### What did you expect to see?

A successful get and build.

### What did you see instead?

First, the generated time package is broke and second, the import of time doesn't work as it conflicts with https://pkg.go.dev/cuelang.org/go/pkg/time.

**Comment by seh** [comment]
See #1453.

**Comment by mvdan** [comment]
... which in turn was a duplicate of https://github.com/cue-lang/cue/issues/648 :) Given that one a slightly better title to make it easier to find. Thanks, @seh.
