### ISSUE TITLE
cuelang.org: add "raise bug" feature to playground

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#2440]
**Is your feature request related to a problem? Please describe.**

The playground is regularly used as a place in which to test out behaviour of CUE, especially when it is considered there might be a bug. 

In https://github.com/cue-lang/cue/issues/1150 we discuss bringing the playground inline with the behaviour, commands etc of `cmd/cue`.

At the moment, copy-paste creation of bug reports is necessary, copying the input to a specific part of the bug report template, as well as the output.

**Describe the solution you'd like**

A link to quickly create a bug report from the current contents of the playground.

**Describe alternatives you've considered**

Copy-paste works, it's just painful. We want to make reporting bugs/issues as easy as possible.

**Additional context**

n/a

cc @mvdan @mpvl

**Comment by mvdan** [comment]
We should also make the playground do something useful, like suggesting that the user report a bug, when the Go code runs into a panic. Right now, it simply freezes and dumps the panic info in the console, meaning that most users are left confused and might not even raise a useful bug report.

**Comment by myitcv** [comment]
> We should also make the playground do something useful, like suggesting that the user report a bug, when the Go code runs into a panic. Right now, it simply freezes and dumps the panic info in the console, meaning that most users are left confused and might not even raise a useful bug report.

This is separate to my mind because it will require work in the Go code space. I will raise a separate issue for that.

**Comment by myitcv** [comment]
Done: https://github.com/cue-lang/cue/issues/2537

**Comment by myitcv** [comment]
This has been working for some time. Per https://github.com/cue-lang/cuelang.org/commit/bcf703c3b2d4cfbbab3d0b5cb779534793d4c223: 

![Screenshot 2024-05-01 at 15 24 42](https://github.com/cue-lang/cue/assets/3374574/e6fa2406-9609-41ff-8a2a-22d1408c9987)
