### ISSUE TITLE
cmd/cue: jsonl validation error incorrectly points to first line

### ISSUE THREAD

**Issue by j0hnsmith** [cue-lang/cue#2444]
**Is your feature request related to a problem? Please describe.**

```
cue vet data.jsonl schema.cue 
-- schema.cue --
id: string
-- data.jsonl --
{"id":"2489651045"}
{"id":2489651064}
```
Gives
```
id: conflicting values 2489651064 and string (mismatched types int and string):
    ./schema.cue:1:5
    ./data.jsonl:1:7
```
The error says line 1 of the jsonl file (because each line is considered in isolation).

**Describe the solution you'd like**
A small nicety but it would be great if the error gave the correct line number, eg 2.

**Comment by mvdan** [comment]
Thanks for reporting, this does seem like a bug. It might not be too difficult to fix, if you want to take a look at a patch :) Though we should likely wait for https://review.gerrithub.io/c/cue-lang/cue/+/555576 to land first, as otherwise this kind of command doesn't work very well.
