### ISSUE TITLE
XOR logic for complex fields

### ISSUE THREAD

**Issue by nieomylnieja** [cue-lang/cue#2464]
I wonder If there's a way to achieve clean XOR logic between two fields with complex types. The https://cuetorials.com/patterns/fields/#oneof pattern shares similar problems to `oneOf` keyword from JSON Schema, it only works for single level of evaluation, once the data is more complex it will fail to match the correct case and report error on the first one. I used to go around this issue with `allOf` and if matching in JSON Schema.

Here's an example I'm currently working at which I based on https://cuetorials.com/deep-dives/comprehension/:

```cue
#thresholdMetric: {
	metricSourceRef: string
	type:            string
}

#ratioMetric: {
	counter: bool | *false
}

spec: {
	description?: string
	if spec.thresholdMetric == _|_ {
		ratioMetric: #ratioMetric
	}
	if spec.ratioMetric == _|_ {
		thresholdMetric: #thresholdMetric
	}
}
```

and a YAML to validate:

```yaml
spec:
  description: This is an amazing description of the best SLI
  ratioMetric:
    counter: true
```

Running `cue vet test.yaml schema.cue` yields `cycle error`, which doesn't really tell me or the user what went wrong. Is this kind of logic possible to achieve with reasonable errors produced in CUE?

**Comment by myitcv** [comment]
@nieomylnieja thank you for raising this issue, and apologies for the lack of any response until now.

I've just raised https://github.com/cue-lang/cue/issues/3165 and suggest we consolidate discussion about this issue (and a number of others) there.
