### ISSUE TITLE
Generate cue definition from openapi

### ISSUE THREAD

**Issue by tamalsaha** [cue-lang/cue#2467]
**Is your feature request related to a problem? Please describe.**
I would like to check if two openapi types are compatible. I think one way to do that will be to generate cue definition for each one of them and check for `subsume` . Is this possible today? Is there any code example that shows how to do this in Golang? Thanks!

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mvdan** [comment]
I believe this is a duplicate of https://github.com/cue-lang/cue/issues/357.
