### ISSUE TITLE
cue cli ignoring leading underscore files

### ISSUE THREAD

**Issue by kghenderson** [cue-lang/cue#2482]
### What version of CUE are you using (`cue version`)?

<pre>
cue version v0.6.0-alpha.2

go version go1.20.5
      -buildmode exe
       -compiler gc
     CGO_ENABLED 1
          GOARCH amd64
            GOOS darwin
         GOAMD64 v1
</pre>

### Does this issue reproduce with the latest stable release?
yes

### What did you do?

```bash
cue export "_filename.cue"
```  

### What did you expect to see?

The file exported as a regular cue file.

### What did you see instead?
command returns:
> no CUE files in command-line-arguments

---
I expect this has to do with golang's treatment of underscore files, but in the case of go embed, they have an `all:` prefix which bypasses this constraint. If this is meant to be the default behavior, please provide a means to accommodate these.

**Comment by jpluscplusm** [comment]
Irrespective of cmd/cue's ignoring of underscore-prefixed files in its normal "cue export <file/package>" mode, the bug/expectation-mismatch here seems to me to be the CLI's unwillingness to examine such files **even when given a cue: type-prefix**. 

Here's a repro for that, which /should/pass but (I believe) currently fails:

```txtar
exec cue export cue: _file.cue --out yaml
cmp stdout out.yml
-- _file.cue --
x: 1
-- out.yml--
x: 1
```

(Typed on mobile hence not tested)

**Comment by kghenderson** [comment]
For completeness, I also have use cases where underscore prefixed files also need to be included with the results of a package. I include what I refer to as 'gather' files which collect all of the other files in the same directory/package and some files to be includes have these leading underscores. These gathered packages are then imported into other packages and the objects from the underscored files need to be included there as well. 

If you consider a relational database, i create a directory/cue package called 'tables' with a cue file per table which is tracked in source control. I don't have any control over these table names because it's a generic tool and the systems and naming conventions vary wildly. These aren't definitions/schemas but rather instances/implementations of those definitions. I then have a separate 'database' package which imports all objects from this tables package. This is so either the whole thing can be evaluated, just tables, or any individual table (cue file) and it works at every level, except of course if the filename begins with an underscore (which happens rather frequently in this case).  What I might need to do is to prefix every file with something, but then that affects the ability to use diffing tools like beyond compare/win merge/kaleidoscope to compare directories where some are prefixed and some are not.

**Comment by myitcv** [comment]
@kghenderson I've fixed the small bug that existed here. I suggest we move discussion about how/when to vary this mode of loading to a separate feature request. For now, rightly or wrongly, we have followed the Go pattern. But we can of course consider alternative loading mechanisms.

**Comment by kghenderson** [comment]
Much obliged, thank you @myitcv  :-)
