### ISSUE TITLE
IntelliJ plugin

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#250]
_Originally opened by @leoluk in https://github.com/cuelang/cue/issues/250_

Is anyone working on an IntelliJ plugin?

With the strong typing of Cue, such a plugin would be highly useful (and probably hard to write). Basic syntax highlighting should be a lot easier.

**Comment by cueckoo** [comment]
_Original reply by @leoluk in https://github.com/cuelang/cue/issues/250#issuecomment-575305973_

Turns out, the native IntelliJ TextMate Bundle support loads https://github.com/betawaffle/vscode-cue just fine. That sorts out basic syntax highlighting!

**Comment by cueckoo** [comment]
_Original reply by @leoluk in https://github.com/cuelang/cue/issues/250#issuecomment-637077305_

Feature request for native support: https://youtrack.jetbrains.com/issue/IDEA-242301

Consider voting for the issue.

**Comment by cueckoo** [comment]
_Original reply by @verdverm in https://github.com/cuelang/cue/issues/250#issuecomment-637087545_

I am unable to vote or comment, but I'm not sure it best fits under tools.Kubernetes (they just added that label over there)

It's a language, and probably belongs where those are.

**Comment by cueckoo** [comment]
_Original reply by @bwplotka in https://github.com/cuelang/cue/issues/250#issuecomment-701294213_

Is there any way we can collaborate together to create one? open source / community driven? (: Anyone up for it?

**Comment by cueckoo** [comment]
_Original reply by @leoluk in https://github.com/cuelang/cue/issues/250#issuecomment-701317745_

Yes, there's a powerful plugin SDK that can be used to implement this.

(In fact, everything in Intellij is a plugin)

**Comment by cueckoo** [comment]
_Original reply by @leoluk in https://github.com/cuelang/cue/issues/250#issuecomment-733840210_

Did anyone start working on a plugin? I'd be happy to contribute.

**Comment by cueckoo** [comment]
_Original reply by @leoluk in https://github.com/cuelang/cue/issues/250#issuecomment-775193877_

Work on this has started, we're over at #intellij on Slack

**Comment by cueckoo** [comment]
_Original reply by @myitcv in https://github.com/cuelang/cue/issues/250#issuecomment-775196663_

Related: https://github.com/cuelang/cue/issues/142

**Comment by cueckoo** [comment]
_Original reply by @jansorg in https://github.com/cuelang/cue/issues/250#issuecomment-783522206_

The plugin on the JetBrains Marketplace: https://plugins.jetbrains.com/plugin/16126-cue

**Comment by myitcv** [comment]
The IntelliJ plugin has long been live meaning we can close this issue.

Per https://github.com/cue-lang/cue/issues/2878, we will be working with @jansorg on defining the interaction model with the LSP server.
