### ISSUE TITLE
pkg/list: Provide a library function to reverse a list value

### ISSUE THREAD

**Issue by seh** [cue-lang/cue#2505]
**Is your feature request related to a problem?**
At present, if one wants to transform a list value into its reversed form, it's possible to use a list comprehension, as [Noam Dolovich demonstrated in a Slack message](https://cuelang.slack.com/archives/CLT4FD7KP/p1690393884654799?thread_ts=1690391964.482999&cid=CLT4FD7KP):
```cue
[
    for i in list.Range(len(original) - 1, -1, -1) {
        original[i]
    }
]
```
We could allow writing this more concisely.

**Describe the solution you'd like**
Provide a new function named "Reverse" in the existing "list" package, available as `list.Reversed`. This function would demand a single value of type `list`, and would return a list of equal length, with the original values present in the reverse order. An empty list supplied as an argument would yield an empty list as a result.

**Describe alternatives you've considered**
Writing the comprehension where it's needed as shown above is possible, as is wrapping it up into a pseduo-CUE "function", but the concision isn't necessarily worth it with that wrapping.

**Additional context**
I have no idea how commonly one would need a reversed value of a list like this, but this is transformation that I'm used to finding in collection-focused programming libraries, alongside existing functions like `Drop` and `Take`.

**Comment by mvdan** [comment]
There's also precedent with https://pkg.go.dev/slices#Reverse, though note that there it's "reverse" and not "reversed" since it modifies the slice (list) in place.

Also, note that we called https://pkg.go.dev/cuelang.org/go/pkg/list#Sort "sort" and not "sorted".

**Comment by seh** [comment]
The latter name choice is unfortunate. If we feel strongly enough about distinguishing transformations from in-place mutations, we could introduce `list.Sorted` and deprecate `list.Sort`, though I expect that it would take a year or two before we could eradicate the latter.

**Comment by mvdan** [comment]
We don't have any list builtin funcs in the passive form today (Summed, Sorted, Repeated, Sliced) so I would say it's fine to continue with the existing trend. If we later decide to rename them, renaming one more is not a significantly bigger amount of churn. But my intuition is that we won't rename them as the benefit is minimal.
