### ISSUE TITLE
Enable developers of go applications to invoke cue cli operations in-process.

### ISSUE THREAD

**Issue by rudifa** [cue-lang/cue#2513]
**Is your feature request related to a problem? Please describe.**
I wish to be able to import the CUE package into my go application and invoke the full range of cue cli operations in-process, thus making my app standalone.

**Describe the solution you'd like**
To achieve above, I wish to propose a simple addition to the CUE package, to enable developers of go applications to invoke the full range of cue cli operations in-process.

**Describe alternatives you've considered**
I have also started to study the CUE GO API and applied these to perform vet and eval from within the application. This approach offers potentially a great flexibility, at the cost of learning the intricacies of the CUE GO API functions and types.

**Additional context**
Details of my proposal follow.

**UPDATE**
Actually, CUE v0.6.0 `package cmd` exports the two functions needed to run `cue` in-process, as I show [below](https://github.com/cue-lang/cue/issues/2513#issuecomment-1829775993).

Nevertheless, I propose that a function similar to `func RunCue(args ...string)` be added to the CUE `package cmd` and its purpose documented.

**Comment by rudifa** [comment]
The proposed change adds to the CUE package a single file, `cmd/cue/cmd/sidekick.go` with a single function
```
// RunSidewise runs the given cue command with the arguments.
func RunSidewise(cmd string, args ...string) error {
    allArgs := append([]string{cmd}, args...)
    return mainErr(context.Background(), allArgs)
}
```
accompanied by the test file `cmd/cue/cmd/sidekick_test.go`.


**EDIT 2023-08-04: above code is compatible with CUE commit `5b2cbe8` of 2023-04-13. See the comment further below for the code compatible with `v0.6.0-rc.1`.**

This enables developers to import the full cue cli capabilities into their go application and invoke the cue cli commands in-process.
```
// main.go --------------------------------------------------------------------
package main

import (
	"log"
	sidekick "cuelang.org/go/cmd/cue/cmd"
)

func main() {
	err := sidekick.RunSidewise("eval", "sample.cue")
	if err != nil {
		log.Println("Error", err)
	}
}
```
```
// go.mod ----------------------------------------------------------------------
module hello-sidekick
go 1.20

replace cuelang.org/go => github.com/rudifa/cue v0.5.0-rudifa
require cuelang.org/go v0.5.0

require (...)
```


**Motivation:**

While working on a go application that fetches geospatial JSON data and validates and transforms it using CUE, I implemented three different solutions

1. invoke the cue cli tool out of process (via go package exec's `func Command(name string, arg ...string) *exec.Cmd`)

2. invoke the cue cli package in-process via sidekick (the current proposal)

3. invoke cue go api functions (CompileString, Unify, LookupPath, ParsePath, ...), see CUE docs, cuetorials, CUE issues, discussions on CUE slack, e.t.c.

Solution 1 is simple to implement and offers the full range of cue cli operations.
It does require the cue cli to be installed on the user's computer.

Solution 2 also offers the full range of cue cli operations, and the application is  standalone as it includes the CUE package in its build.

Both of these solutions require *only* the mastery of CUE language and operations.

Solution 3 offers more flexibility in combining and tailoring the CUE operations to the exact needs of a go application. However, it has a steep learning curve in understanding and applying the cue go api calls, area where advice from members of the cue team is of great help.

**Summary:**

I think that the proposed addition to the CUE package would be useful to a class of developers, while requiring no additionaL testing and maintenance effort from the CUE team.

**Sidekick?!**

sidekick noun
 /ˈsaɪdkɪk/
(informal)
a person who helps another more important or more intelligent person

(Oxford Advanced Learner's Dictionary)

**Comment by NoamTD** [comment]
@rudifa I'm sorry if this isn't relevant (I might have misunderstood your suggestion), but wouldn't it be enough to call [cmd.Main](https://github.com/cue-lang/cue/blob/da3ee7dc7b27de85bbfb0a4104dfb22bcb18ef68/cmd/cue/cmd/root.go#L228) in the `cmd/cue/cmd` package?
I've used this in a few cases to use the cue commands from within go and it has worked great

**Comment by NoamTD** [comment]
> 

Oh nevermind - I've used it for a different use case (tests via the [testscript](https://pkg.go.dev/github.com/rogpeppe/go-internal/testscript) library), and I could use the os args. please ignore

**Comment by rudifa** [comment]
@NoamTD The proposed change lets you run CUE as you would from a terminal, but within your go application's process.

There is a secondary benefit, when running a go test from VSCode: you can run _debug test_ and step from your code into the cue cli code that your app invokes.

**Comment by rudifa** [comment]
I verified that my proposed change (the addition of cmd/cue/cmd/sidekick.go) works with the `v0.6.0-rc.1`, with code updated to match changes in `cmd/cue/cmd/root.go`:
```
// RunSidewise runs the given cue command with the arguments.
func RunSidewise(command string, args ...string) error {
	allArgs := append([]string{command}, args...)
	cmd, _ := New(allArgs)
	return cmd.Run(context.Background())
}
```

**Comment by rudifa** [comment]
Actually, with cue v0.6.0, the user can define `func RunCue` in a local package

```
// inproc/runcue.go

package inproc

import (
	"context"
	"fmt"
	"os"

	"cuelang.org/go/cmd/cue/cmd"
)

// RunCue runs a cue command with its arguments, e.g.
// inproc.RunCue("eval", "testdata/sample.cue")
func RunCue(args ...string) {
	fmt.Fprintln(os.Stderr, args)
	c, _ := cmd.New(args)
	c.Run(context.Background())
}
```
... and call it like so:

```
// main.go

package main

import (
	"fmt"

	"github.com/rudifa/cue-issues-fmt-comments/inproc"
)

func main() {
	fmt.Println("Here we go")

	inproc.RunCue("version")

	inproc.RunCue("fmt", "testdata/sample.cue")

	inproc.RunCue("vet", "testdata/sample.cue")

	inproc.RunCue("def", "testdata/sample.cue")

	inproc.RunCue("eval", "testdata/sample.cue")

	inproc.RunCue("export", "testdata/sample.cue")
}
```

**Comment by mvdan** [comment]
This should work today, and you show it in your last example above. The `cmd` API isn't polished or perfect by any means, but it can be imported and it should be fine for now. I'm going to close this issue for now as this is an existing feature, but please open a new issue if you encounter any bug or missing feature.

**Comment by rudifa** [comment]
```
import (
	"context"
	"cuelang.org/go/cmd/cue/cmd"
)

func RunCue(args ...string) {
	c, _ := cmd.New(args)
	c.Run(context.Background())
}
```
Indeed, this works since `cue v0.6.0`, by calling 2 public functions.

Prior to your commit `59080b6 cmd/cue: refactor our use of cobra` of 18 April 2023 it was necessary to patch the cue source code to achieve the same result, as in my first proposal above, based on `cue v0.5.0`.
