### ISSUE TITLE
preprocessor: in-page steps

### ISSUE THREAD

**Issue by jpluscplusm** [cue-lang/cue#2531]
We need a way to express an ordered list of steps in documentation, with the following properties:

- represents progression along a straight line path of steps
- each step is numbered uniquely on the page
- each step's number can be called back to, by reference, in-page, e.g.

```
{{step "foo"}}
Foo a Bar.

{{step "baz"}}
In step {{step:ref:foo}}, you Foo'd a Bar. Now ....
```
- any step can contain any number of elements (e.g. from the [/examples](https://alpha.cuelang.org/examples/) page)
  - there isn't a 1:1 mapping from "step" to (e.g.) "block" 

The following properties might exist, but aren't required at this stage, if at all:

- step markers are link-to-able anchors
- step markers are clickable anchors
- step markers have custom/visible "names"/etc
- step markers can be referenced across pages (i.e. not just in-page)

**Comment by jpluscplusm** [comment]
I'm currently using the HTML `gg` element as a placeholder for these steps, which will be easily grep-and-replace-able when this issue is fixed. It also gives a nice visual indicator of the step's start point for reviewers.

**Comment by myitcv** [comment]
This was completed in https://review.gerrithub.io/c/cue-lang/cuelang.org/+/1169533
