### ISSUE TITLE
evaluator: structural cycle with optional field regression in v0.6

### ISSUE THREAD

**Issue by heistp** [cue-lang/cue#2545]
### What version of CUE are you using (`cue version`)?

<pre>
# "good" version
$ cue version
cue version v0.5.0

go version go1.21.0
      -buildmode exe
       -compiler gc
  DefaultGODEBUG panicnil=1
     CGO_ENABLED 1
          GOARCH amd64
            GOOS linux
         GOAMD64 v1

# "bad" version
$ cue version
cue version v0.6.0-alpha.1

go version go1.21.0
      -buildmode exe
       -compiler gc
  DefaultGODEBUG panicnil=1
     CGO_ENABLED 1
          GOARCH amd64
            GOOS linux
         GOAMD64 v1
</pre>

### Does this issue reproduce with the latest stable release?

Yes (v0.6.0).

### What did you do?

Minimal CUE to reproduce:
<pre>
package structcycle

#A: {
	B?: #B
}

#B: {
	A: #A
}
</pre>

To reproduce it, run `cue export` with the above saved to structcycle.cue, or similar.

### What did you expect to see?

Result with v0.5.0 ("good"):
<pre>
$ cue export
{}
</pre>

### What did you see instead?

Result with v0.6.0-alpha.1 ("bad"):
<pre>
$ cue export
#B.A: structural cycle
</pre>

### Notes

My [antler](https://github.com/heistp/antler/) project is broken by the new behavior. On line 59 of my CUE schema in [config.cue](https://github.com/heistp/antler/blob/main/config.cue), the Run field in #Schedule refers to #Run, which refers to #Schedule through an optional field. This works in v0.5.0, but broke somewhere between v0.5.0 and v0.6.0-alpha.1. I'm unsure of the correct behavior, or if I need to change something in my schema, but I do know the behavior in v0.5.0 was working fine for me. :)

**Comment by myitcv** [comment]
Thanks for the report, @heistp. This does appear to be a bug to me too, because as you say the use of the optional field in `#A` should terminate the structural cycle. 

This broke in https://cuelang.org/cl/551104, and is to my mind a regression compared to v0.5.0.

It might not be a total fix in your case, but your example can be "fixed" by making the field `#B.A` also optional:

```
package structcycle

#A: {
	B?: #B
}

#B: {
	A?: #A
}
```

https://tip.cuelang.org/play/?id=72kZS2m6oql#cue@export@cue

That said, we need to fix this.

**Comment by heistp** [comment]
Ok, thanks @myitcv. The workaround does allow me to load the config and confirm that that's the only problem, so that's good. I'm likely to stay on v0.5.0 for now though, so the schema can ensure that the Run fields are defined.

The only other thing I noticed with 0.6 is that the time to initialize the config increased from ~200ms to ~1100ms. This may be #803, so I'll rather add a comment over there.

**Comment by heistp** [comment]
I tried this on 0.9.2 with the new evaluator, but it still happens. Just mentioning since I've been stuck on 0.5.0 for about a year now, for this and for poor performance with recursive definitions. I'll check again when the new evaluator is the default.

**Comment by mvdan** [comment]
Thank you for the update and your patience, @heistp. We'll take a look at fixing this in the new evaluator as soon as we're able to. Performance work is only focused on the new evaluator as well, as explained in https://github.com/cue-lang/cue/issues/2850.

**Comment by mvdan** [comment]
Below is a testscript for the original reproducer with the old and new evaluators:

```
env CUE_EXPERIMENT=evalv3=0
exec cue export

env CUE_EXPERIMENT=evalv3=1
exec cue export

-- file.cue --
package p

#A: {
	B?: #B
}

#B: {
	A: #A
}
```

The good news is that, thanks to the new cycle detection algorithm in the new evaluator, this works again with `CUE_EXPERIMENT=evalv3`:

```
> env CUE_EXPERIMENT=evalv3=0
> exec cue export
[stderr]
#B.A: structural cycle
[exit status 1]
FAIL: repro-evalv3.txtar:2: unexpected command failure
> env CUE_EXPERIMENT=evalv3=1
> exec cue export
[stdout]
{}
```

Given how the cycle detection algorithm in the old (default) evaluator is badly designed, we're focusing on the new evaluator for the sake of enabling it by default as soon as possible. It also fixes many closedness and other correctness bugs thanks to its design, as well as unlocking lots of performance improvements. Please try your project with `CUE_EXPERIMENT=evalv3` and let us know if you run into any problems - we will aim to resolve them as quickly as possible.

In the meantime, I'll mark this issue as resolved by adding a regression test for the new evaluator.

**Comment by heistp** [comment]
Sorry for the late reply, I'm just confirming that this does appear to be fixed for me with `evalv3=1`.  Thanks!
