### ISSUE TITLE
preprocessor: allow failing `cue` commands to be demonstrated

### ISSUE THREAD

**Issue by jpluscplusm** [cue-lang/cue#2553]
As I construct different narratives, I often want to show that a certain combination of CUE and `cue` command will fail.

Often this would be useful in a side-by-side context, with CUE on the left and a terminal on the right, showing the failure. This has an affinity with howto content, in my mind.

This issue is a request for side-by-side to be able to process commands which intentionally fail (and are marked as such).

```
In this example, `cue vet` warns us if the elements of `someList` in `data.yml`
sum to greater than 99.5 (because we accidentally typed `100` when we meant `10`):

{{< code-tabs >}}

{{< code-tab name="example.cue" area="top-left" >}}
package example

import (
	"list"
)

someList!: [...number]
_sum_someList: <=99.5 & list.Sum(someList)
{{< /code-tab >}}

{{< code-tab name="data.yml" language="yaml" area="bottom-left" >}}
someList: [ 1, 2, 3, 100 ]
{{< /code-tab >}}

{{< code-tab name="$ cue vet .:example data.yml" type="terminal" area="top-right" >}}
_sum_someList: invalid value 106.5 (out of bound <=99.5):
    ./example.cue:8:16
    ./example.cue:8:25

{{< /code-tab >}}

{{< /code-tabs >}}
```

I'll open a separate issue for the same request in a step-based piece of content, not a stand alone, side-by-side context.

**Comment by verdverm** [comment]
> Sometimes this would be useful in a side-by-side context, with CUE on the left and a terminal on the right, showing the failure.

Something like this: https://cuetorials.com/overview/foundations/#values-cannot-be-changed

You may find https://codehike.org/ interesting, I'm planning to move Cuetorials and all Hof sites over to NextJS with this library for similar possibilities as you outlined

**Comment by jpluscplusm** [comment]
> Something like this: https://cuetorials.com/overview/foundations/#values-cannot-be-changed

Yep, that's one of the kind of narratives I'd like to express 👍

**Comment by myitcv** [comment]
@jpluscplusm - a reminder to please include an example here that shows exactly what you are working with.

**Comment by jpluscplusm** [comment]
> @jpluscplusm - a reminder to please include an example here that shows exactly what you are working with.

Done.

**Comment by verdverm** [comment]
Here's the Hugo shortcode we use for our tabs: https://github.com/hofstadter-io/hof/blob/_dev/docs/layouts/shortcodes/codePane2.html

It's generally pretty easy to implement, just depends on the other web / theme things you have around.

I like CodeHike a lot more, generally, some really awesome extra features, but it's tied pretty well to React

**Comment by jpluscplusm** [comment]
This is currently possible with the following source:

```
{{{with code "en" "example"}}}
#location top-left bottom-left right

! exec cue vet .:example data.yml
cmp stderr out
-- example.cue --
package example

import (
	"list"
)

someList!: [...number]
_sum_someList: <=99.5 & list.Sum(someList)
-- data.yml --
someList: [ 1, 2, 3, 100 ]
-- out --
_sum_someList: invalid value 106 (out of bound <=99.5):
    ./example.cue:8:16
    ./example.cue:8:25
{{{end}}}
```
