### ISSUE TITLE
cmd/cue: `fmt` inserts a leading tab if a comment ends up being the first line of a file

### ISSUE THREAD

**Issue by jpluscplusm** [cue-lang/cue#2556]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.6.0

go version go1.20.6
      -buildmode exe
       -compiler gc
       -trimpath true
     CGO_ENABLED 0
          GOARCH amd64
            GOOS linux
         GOAMD64 v1
</pre>

### Does this issue reproduce with the latest stable release?

Yes, 0.5 and 0.6.

### What did you do?

```
exec cue fmt in.cue
cmp in.cue out.cue
-- in.cue --

// a comment
x: 1
-- out.cue --
// a comment
x: 1
```

### What did you expect to see?

A passing test.

### What did you see instead?

```
$ testscript comment-leading-space.txtar 
> exec cue fmt in.cue
> cmp in.cue out.cue
diff in.cue out.cue
--- in.cue
+++ out.cue
@@ -1,2 +1,2 @@
-       // a comment
+// a comment
 x: 1

FAIL: /tmp/testscript3723497481/comment-leading-space.txtar/script.txtar:2: in.cue and out.cue differ
error running comment-leading-space.txtar in /tmp/testscript3723497481/comment-leading-space.txtar
```

Whilst similar in nature to #1544, the trigger (a comment, not a `let` assignment) and erroneous indentation character (a tab, not a space) prompted me to file this separate issue.

**Comment by myitcv** [comment]
I think this is a dup of https://github.com/cue-lang/cue/issues/722

**Comment by myitcv** [comment]
I think this is a dup of https://github.com/cue-lang/cue/issues/722
