### ISSUE TITLE
Different yaml validation result depending on element order

### ISSUE THREAD

**Issue by cxconj** [cue-lang/cue#2576]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.6.0

go version go1.20.6
      -buildmode exe
       -compiler gc
       -trimpath true
     CGO_ENABLED 0
          GOARCH amd64
            GOOS linux
         GOAMD64 v1
</pre>

### Does this issue reproduce with the latest stable release?

yes

### What did you do?

```
$ cat ex.cue
foos: [#Foo, ...]

#Foo: {
    A: string
    Bs: [#B, ...]
}

#B: {
    C: string
    D: string
}

$ cat ex1.yaml
foos:
  - A: a2
    Bs: []
  - A: a1
    Bs:
      - C: c1
        D: d1
      - C: c2
        D: d2

$ cat ex2.yaml  # change element order
foos:
  - A: a1
    Bs:
      - C: c1
        D: d1
      - C: c2
        D: d2
  - A: a2
    Bs: []

$ cue vet ex1.yaml ex.cue
foos.0.Bs: incompatible list lengths (0 and 2)

$ cue vet ex2.yaml ex.cue
# no output
```

### What did you expect to see?

```
$ cue vet ex2.yaml ex.cue
foos.1.Bs: incompatible list lengths (0 and 2)
```

### What did you see instead?

```
$ cue vet ex2.yaml ex.cue
# no output
```

**Comment by mvdan** [comment]
This is not a bug in CUE, it is working as designed. The spec says:

> A list literal defines a new value of type list. A list may be open or closed. An open list is indicated with a ... at the end of an element list, optionally followed by a value for the remaining elements.

That is, if you end a list with a `...` element, you're not constraining the rest of the elements at all. They can be any value.

Take a look at https://cuelang.org/play/?id=VIGXjm6SJIB#w=function&i=cue&f=eval&o=cue; note how in the examples mimicking your original code, changing the order of the validated values does affect the result, as only the first gets the constraint aplied via `[int, ...]`. However, with `[int, ...int]`, all elements get constrained.

So in your example, don't do `[#Foo, ...]`, but do `[#Foo, ...#Foo]` instead. Or if you prefer not to repeat, use `[...#Foo] & list.MinItems(1)`.
