### ISSUE TITLE
alpha.cuelang.org: "Report an Issue" link passed unhelpful git commit info to new GitHub Issue

### ISSUE THREAD

**Issue by jpluscplusm** [cue-lang/cue#2581]
### What page were you looking at?

https://alpha.cuelang.org/

### What version of the site were you looking at?

https://github.com/cue-lang/cuelang.org/commit/3c511a9686c7289d68b5f64cdaa4649385b9f4fc << this is actually correct (because I edited it!) despite what you'll read in the rest of this issue!

### What did you do?

I selected any random page - let's say it was the home page.

I scrolled to the footer and clicked on "Report an Issue", and the site redirected me to a new GitHub Issue with a pre-populated Issue body. 

The Issue's body correctly captured the page I was looking at, in the 1st section of the report.

But the 2nd section, which asked `What version of the site were you looking at?` was populated with a link to a commit that was merged several days ago. 

### What did you expect?

I expected that the commit that was linked would reflect the "current" version of the site at the moment I clicked on it.

### What did you see instead?

As above, the "wrong" commit was linked to.

### Other info

This appears to be due to the use of Hugo's [`GitInfo.Hash`](https://gohugo.io/variables/git/#the-gitinfo-object) in the footer, that was added in cue-lang/cuelang.org#413. Hugo performs additional work when building each and every page in order to find out which commit last modified that specific page.

I believe we don't want to do this, but instead want to place the commit id into the Issue's body's (via the content of each page's "Report an Issue" link) that reflects the commit that was checked out at the time the site was built.

There are at least 3 contexts in which this needs to be thought about:

- the in-Netlify builds (e.g. for alpha, and for PRs)
- the in-GitHub-Actions builds that are merely pushed to Netlify (e.g. for Gerrit CLs; for tip.cuelang.org)
- local builds, when developing the site

(I suspect that the last of these (local builds) doesn't need to be particularly rigorously thought through. So long as the site **can still build** locally, successfully, the info baked into the "Report an Issue" link can probably ignore the fact that it's local, with a potentially modified working tree. No-one *actively* developing the site is going to use this link, versus the same link on Alpha or a CL/PR, as it's not reproducible for folks on other dev machines.)

**Comment by cedricgc** [comment]
Took a look at the hugo doc and didn't find a Site variable that saved the repo commit that we can use instead of per page git hashes.

One way this can work is using [Data templates](https://gohugo.io/templates/data-templates/) with a build step that writes the commit to a JSON file that can be read at the `.Site.Data` object.

**Comment by myitcv** [comment]
@cedricgc - sounds good. Please feel free to give that a go, and let us know if you run into any issues along the way where we can help out!

**Comment by myitcv** [comment]
Closed via https://review.gerrithub.io/c/cue-lang/cuelang.org/+/1171035. Thanks @cedricgc!
