### ISSUE TITLE
[docs] Dynamic fields example has errors

### ISSUE THREAD

**Issue by SteVwonder** [cue-lang/cue#2592]
### What version of CUE are you using (`cue version`)?

<pre>
❯ cue version
cue version v0.6.0
</pre>

### What did you do?

I copied the dynamic fields example from the docs at https://cuelang.org/docs/references/spec/#dynamic-fields
```
sherbein ~/scratchspace/cue-dynamic-fields
❯ cat test.cue                     
package test

a:   "foo"
b:   "bar"
(a): "baz"

(a+b): "qux"

(a)?: string
(b)!: string
```

### What did you expect to see?

What is listed in the docs :
```
a:   "foo"
b:   "bar"
bar: "baz"

foobar: "qux"

foo?: string
bar!: string
```

### What did you see instead?
```
sherbein ~/scratchspace/cue-dynamic-fields
❯ cue eval                         
a:      "foo"
b:      "bar"
foo:    "baz"

foobar: "qux"

bar!:   string
```

The output from the command is definitely correct and the mistake lies with the docs. Basically the docs should be updated so that the result of `(a): "baz"` is `foo: "baz"` not `bar: "baz"`.  The `a: "foo` in the docs example also needs a closing `"`.

I'm happy to post a PR once I confirm employer sign-off on contributions.

**Comment by mvdan** [comment]
Please do send a patch :) This looks wrong indeed. I also see `a:   "foo` rather than `a:   "foo"`, a closing double quote is missing.
