### ISSUE TITLE
pkg/net: `IPv6` validator function

### ISSUE THREAD

**Issue by jpluscplusm** [cue-lang/cue#2614]
**Is your feature request related to a problem? Please describe.**

I'd like to constrain fields to contain IPv6 addresses. I'm doing this in the context of structured data that represents DNS records, where records of type `AAAA` are only allowed to contain IPv6 addresses.

**Describe the solution you'd like**

I'd like a builtin validator(?) function to parallel https://pkg.go.dev/cuelang.org/go@v0.6.0/pkg/net#IPv4 (probably named `IPv6`), which operates similarly to `IPv4` by only permitting fields to which it's attached to be assigned IPv6 addresses. 

**Describe alternatives you've considered**

I could roll my own regex to validate IPv6 string forms.

**Additional context**

This field being missing seems like a mere oversight, seen in the context of the `net` package - which already has several IPv6-aware functions.

**Comment by mvdan** [comment]
I think adding this API is reasonable, even if just for symmetry. Want to send a CL?

Worth noting that our `net` package is built atop Go's, so `IPv4` is using https://pkg.go.dev/net#IP.To4:

> If ip is not an IPv4 address, To4 returns nil.

However, upstream doesn't seem to have an easy way to check if an IP is IPv6; there is https://pkg.go.dev/net#IP.To16, but it seems to not require the IP to actually be IPv6. Look at the example with an IPv4, which works fine.

The answer might be to switch over to `net/netip` - it is meant to be faster, and it does seem to have a way to check if an address is IPv6: https://pkg.go.dev/net/netip#Addr.Is6

**Comment by mvdan** [comment]
If I'm correct about the switch to `net/netip` being a good idea and perhaps even necessary to implement this, I would suggest to do it in multiple steps: first swap `net` for `net/netip`, and then add new CUE standard library APIs like `IPv6`.
