### ISSUE TITLE
Passing values and context from Java to evaluate during runtime 

### ISSUE THREAD

**Issue by learntoinf** [cue-lang/cue#2635]
We currently have a configuration language which allows to override default value for a given config key based on user passed context. As an example our config looks something like this:
button_color=blue
If (cityId == 5) button_color = red
If (cityId == 10) button_color = green

In the above example, default value for button_color is blue. But based on user context, which is cityId in this case, the value for button_color could be red or green depending on cityId. The user context is passed as input parameter which is determined during runtime in our Java application. How could w achieve the same using cue? I am very new to cue. I have seen this is possible by injecting values or using go apis fill() method. This capability of runtime evaluation based on user input/context to override is heavily used. So I would like to understand what are the options here? Any examples and usage would help. This will determine whether to take dependency on cue or not.thanks for your help in advance.

**Comment by mvdan** [comment]
I see that you asked your question on Slack already, so I'm going to close this one as a duplicate for now. If you prefer to use GitHub for questions instead of Slack, feel free to use the Q&A category in the Discussions tab. Thanks!
