### ISSUE TITLE
cmd/cue: get go: invalid identifier "unsafe.Pointer"

### ISSUE THREAD

**Issue by uhthomas** [cue-lang/cue#2641]
### What version of CUE are you using (`cue version`)?

<pre>
❯ cue version
cue version 0.6.0

go version go1.21.0
      -buildmode pie
       -compiler gc
       -trimpath true
  DefaultGODEBUG panicnil=1
     CGO_ENABLED 1
          GOARCH amd64
            GOOS linux
         GOAMD64 v1
</pre>

### Does this issue reproduce with the latest stable release?

Yes.

### What did you do?

```sh
❯ cue get go github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2
invalid identifier "unsafe.Pointer"
```

### What did you expect to see?

Successful `cue get go`.

### What did you see instead?

`invalid identifier "unsafe.Pointer"`

**Comment by uhthomas** [comment]
In addition, [this struct](https://pkg.go.dev/github.com/cilium/cilium@v1.14.2/pkg/policy/api#Rule) is imported as:

```cue
// Rule is a policy rule which must be applied to all endpoints which match the
// labels contained in the endpointSelector
//
// Each rule is split into an ingress section which contains all rules
// applicable at ingress, and an egress section applicable at egress. For rule
// types such as `L4Rule` and `CIDR` which can be applied at both ingress and
// egress, both ingress and egress side have to either specifically allow the
// connection or one side has to be omitted.
//
// Either ingress, egress, or both can be provided. If both ingress and egress
// are omitted, the rule has no effect.
//
// +deepequal-gen:private-method=true
#Rule: _
```
I guess because it's a [json marshaller](https://pkg.go.dev/github.com/cilium/cilium@v1.14.2/pkg/policy/api#Rule.MarshalJSON)? I really feel this behaviour is unintuitive and wrong.

https://github.com/cue-lang/cue/issues/2466

**Comment by mvdan** [comment]
How do we currently handle `uintptr`? We should probably handle both the same way, since they both represent untyped memory pointers.
