### ISSUE TITLE
cmd/cmd: ignore complex types

### ISSUE THREAD

**Issue by uhthomas** [cue-lang/cue#2661]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
v0.6.0
</pre>

### Does this issue reproduce with the latest stable release?

Yes.

### What did you do?

Import Go code which references [complex types](https://go.dev/ref/spec#Numeric_types) (`complex64` or `complex128`).

```go
type A struct {
	B complex128
}
```

### What did you expect to see?

[Complex numbers](https://en.wikipedia.org/wiki/Complex_number) have no opaque representation in Go. The real and imaginary parts of a complex number are only accessible using the inbuilt functions `real` and `imag`. There is also no agreed upon standard for representing complex numbers in other data formats like JSON or YAML. Most encoders will simply write strings in the form `"1+2i"`. I think the safest thing to do for now is to represent complex numbers with top, and adjust this in future if needed.

```
#A: {
  B: _
}
```

### What did you see instead?

```sh
#A: reference "complex64" not found:
```

**Comment by mvdan** [comment]
Can you expand a bit on why top is the best we can do here? The commit message should also explain it. It might be obvious to you or others, but we should still summarize the reasoning.

**Comment by mvdan** [comment]
Marking as "needs fix" because the current behavior is wrong for sure. We should either refuse to support these types and error, or convert them the best way we can to valid CUE.

**Comment by uhthomas** [comment]
Thanks @mvdan, I've updated the description.
