### ISSUE TITLE
cuelang.org: preprocessor: allow a code block's command pane's title to display the command executed

### ISSUE THREAD

**Issue by jpluscplusm** [cue-lang/cue#2667]
**Is your feature request related to a problem? Please describe.**

In a code block, the explicit command executed is only shown to the reader when:

- we've provided a 3-file in/out input (https://github.com/cue-lang/cuelang.org/blob/3591d715f1e68454f107d1531649cfacf6ac5263/internal/cmd/preprocessor/cmd/code_node.go#L372)
- we've provided a non-in/out, 2-file input, with an explicit command
- we've manually added the command, statically, the output, somehow.

All of these place the command as a `$ command foo bar baz` prefix line in the appropriate code tab's *content* pane. This is often correct, but can bring various problems:

- which content is copied when the copy button is pressed? (cf. #2669)
  - the command?
  - the output?
  - both?
- how do the different content formatters cope with a leading line that's unrelated to the content type they're expecting?
- how is the command visually distinguished from content, apart from a leading `$ `?

**Describe the solution you'd like**

I'd like a way to indicate, via the preprocessor's code block input, that a `TERMINAL` tab's title should contain the command that's executed, instead of the `TERMINAL` string.

It might be useful if the 2-file in/out form (with implicit commands) could also be told to place the command that generated the right hand tab's content in the right hand tab's title - replacing the default `CUE`/`JSON`/`ERR`/etc. (I only mention that here in case it's easier to implement that at the same time). For a situation where this would be useful, see https://review.gerrithub.io/c/cue-lang/cuelang.org/+/1171530.

**Describe alternatives you've considered**

I don't have an alternative. The reader currently either doesn't see the explicit command that's executed, or sees it as a `$ foo bar baz` content prefix line.

**Additional context**

n/a

**Comment by myitcv** [comment]
Per previous conversations, I'm really not clear this is a direction we want to head:

* Doing so causes confusion on what the "title" tab is for; sometimes contains `TERMINAL`, sometimes a command.
* We raise the question of how to copy-paste the command. If it's at all relevant (beyond just displaying `JSON` in the case we render JSON) then we shouldn't bury the command
* I think we can solve the "nicely render output" point via the `preprocessor` being told/aware that certain command output is, say, JSON and should be formatted as such.

We can re-open in case any of the above proves to be poorly founded in terms of reasoning.
