### ISSUE TITLE
CONTRIBUTING.md: Doc references non-existent CONTRIBUTORS file

### ISSUE THREAD

**Issue by cedricgc** [cue-lang/cue#2684]
Hello,

`CONTRIBUTING.md` has the `Copyright headers` section which references a `CONTRIBUTORS` document that does not exist. The section also describes that the `AUTHORS` file will populate commit authors to the file periodically which does not seem to be the case.

https://github.com/cue-lang/cue/blob/4d2ba88849b660e30df921aa1d6f44d4c75ed8d8/CONTRIBUTING.md#copyright-headers

We should clarify what we want to do with these files and update `CONTRIBUTING.md` to reflect this.

**Comment by mvdan** [comment]
Thanks for spotting and reporting! Sending a patch shortly to clean this up. It took us a while as we weren't exactly sure how we wanted to track contributors going forward.
