### ISSUE TITLE
toml support

### ISSUE THREAD

**Issue by uhthomas** [cue-lang/cue#2688]
**Is your feature request related to a problem? Please describe.**

It would be great if toml were supported the same way json and yaml are. This includes exporting/importing as well as an encoding package.

**Describe the solution you'd like**

A new `encoding/toml` package for marshalling/unmarshalling toml. There are some projects which use toml for configuration, and could be represented with cue.

In addition, `cue export -otoml somthing.cue` or `cue import something.toml`.

**Describe alternatives you've considered**

**Additional context**

**Comment by mvdan** [comment]
This seems like a duplicate of https://github.com/cue-lang/cue/issues/68 :)

**Comment by uhthomas** [comment]
Looks like it! I did search for the literal "toml", but this issue didn't show up. Thank you,
