### ISSUE TITLE
Remove Deprecated Istio cue-lang Tool Reference from Documentation

### ISSUE THREAD

**Issue by Amoenus** [cue-lang/cue#2735]
As a user of CueLang's [documentation](https://cuelang.org/docs/integrations/openapi/), 
I propose to remove all references to Istio's `cue-gen` tool from the documentation.
To improve the accuracy of the documentation, 

I've noticed that the documentation mentions Istio's `cue-gen` tool, which seems to be outdated and no longer available or supported. 

Link to the Istio's documentation that led me to believe `cue-gen` is deprecated is [here](https://github.com/istio/tools/blob/master/cmd/protoc-gen-crd/README.md.)

**Comment by mvdan** [comment]
I could not find a single reference to a cue-gen tool in the new website; https://cuelang.org/docs/integration/kubernetes/ does mention Istio briefly, but does not link to any tool. So I think this is done :)
