### ISSUE TITLE
cmd/cue: mod tidy doesn't play along with get go

### ISSUE THREAD

**Issue by richardpeng** [cue-lang/cue#2746]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.7.1-0.20231220122134-3d09a4aafb64

go version go1.21.4
      -buildmode exe
       -compiler gc
  DefaultGODEBUG panicnil=1
     CGO_ENABLED 1
          GOARCH arm64
            GOOS darwin
</pre>

### Does this issue reproduce with the latest stable release?
N/A

### What did you do?

shell:
```
$ rm -r cue.mod
$ cue mod init myfitnesspal.com/config@v0
$ go get k8s.io/api/apps/v1
$ cue get go k8s.io/api/apps/v1
$ cue mod tidy
failed to resolve "k8s.io/api/apps/v1": cannot find module providing package k8s.io/api/apps/v1
```

example.cue
```
import apps "k8s.io/api/apps/v1"
```

**Comment by myitcv** [comment]
@richardpeng thanks for brining this up. The topic of `cue get go` (and the slightly broader use cases that currently require `cue get go`) will be the focus of [the next modules feedback session](https://github.com/cue-lang/cue/discussions/2756). Here's hoping you can join and join the discussion!

**Comment by rogpeppe** [comment]
Fixed (to some degree anyway) by https://review.gerrithub.io/c/cue-lang/cue/+/1176005.
