### ISSUE TITLE
docs: cuelang.org points to a broken issue reporting URL

### ISSUE THREAD

**Issue by MisterSquishy** [cue-lang/cue#2753]
### What did you do?
go to https://cuelang.org/docs/references/spec/ and click the `Create documentation issue` button

![CleanShot 2024-01-02 at 14 44 35@2x](https://github.com/cue-lang/cue/assets/5599894/95026bee-c2d6-407b-941e-2c44df4e03e7)

### What did you expect to see?
a github issue creation page like the one im typing into right now

### What did you see instead?
a github 404 page (https://github.com/cue-lang/cuelang.org/issues/new?title=Language%20Specification)

**Comment by mvdan** [comment]
Thanks for raising this issue! See https://github.com/cue-lang/cue/issues/2364.
