### ISSUE TITLE
cmd/cue: `tool/exec.Run` doesn't handle lists of environment variables

### ISSUE THREAD

**Issue by nickfiggins** [cue-lang/cue#2763]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.7.0

go version go1.21.5
      -buildmode exe
       -compiler gc
       -trimpath true
     CGO_ENABLED 0
          GOARCH amd64
            GOOS darwin
         GOAMD64 v1
</pre>

### Does this issue reproduce with the latest stable release?

yes

### What did you do?

```
exec cue cmd envFromList
stdout FOO=BAR
-- a_tool.cue --
package p

import "tool/exec"

command: envFromList: exec.Run & {
	cmd: "env"
	env: ["FOO=BAR"]
}
```

### What did you expect to see?

A passing test (as a result of FOO=BAR populated in the command output).

### What did you see instead?
```
> exec cue cmd envFromList
            [stderr]
            command.envFromList.env: conflicting values ["FOO=BAR"] and {[string]:(string|[...=~"="])} (mismatched types list and struct):
                ./a_tool.cue:5:23
                ./a_tool.cue:7:7
                tool/exec:6:8
            [exit status 1]
            FAIL: testdata/script/cmd_execenv.txtar:1: unexpected command failure
```

Per the docs (and implementation), it seems like this usage of `env` is meant to be supported. It seems like this just may be due to the order of operations in the [env definition](https://github.com/cue-lang/cue/blob/master/pkg/tool/exec/exec.cue#L32) which leads to [this schema](https://github.com/cue-lang/cue/blob/master/pkg/tool/exec/pkg.go#L66) being generated

**Comment by mvdan** [comment]
Thanks - this looks like a mistake in the schema. I think `env: [string]: string | [...=~"="]` should be `env: {[string]: string} | [...=~"="]` so that the disjunction applies to the entire `[string]: string`, otherwise it applies to just `string` on the left side. See: https://tip.cuelang.org/play/?id=Q2sENh20fvy#cue@export@cue
