### ISSUE TITLE
install instructions don't appear to actually install it

### ISSUE THREAD

**Issue by JoeStrout** [cue-lang/cue#2767]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
Command 'cue' not found
</pre>

### Does this issue reproduce with the latest stable release?

Yes.

### What did you do?

1. Go to the install instructions at https://cuelang.org/docs/install/ , and scroll down to "To install the cue command line tool:"
2. Verify that we have an appropriate version of Go already installed: <pre>
$ go version
go version go1.21.6 linux/amd64</pre>
3. Try the given command:
<pre>$ go install cuelang.org/go/cmd/cue@latest
go: downloading cuelang.org/go v0.7.0
go: downloading cuelabs.dev/go/oci/ociregistry v0.0.0-20231103182354-93e78c079a13
go: downloading github.com/spf13/cobra v1.7.0
go: downloading github.com/spf13/pflag v1.0.5
go: downloading golang.org/x/mod v0.13.0
go: downloading golang.org/x/text v0.13.0
go: downloading golang.org/x/tools v0.14.0
go: downloading github.com/opencontainers/go-digest v1.0.0
go: downloading github.com/opencontainers/image-spec v1.1.0-rc4
go: downloading golang.org/x/exp v0.0.0-20231006140011-7918f672742d
go: downloading github.com/cockroachdb/apd/v3 v3.2.1
go: downloading github.com/mpvl/unique v0.0.0-20150818121801-cbe035fff7de
go: downloading github.com/tetratelabs/wazero v1.0.2
go: downloading github.com/emicklei/proto v1.10.0
go: downloading golang.org/x/sys v0.13.0
go: downloading github.com/protocolbuffers/txtpbfmt v0.0.0-20230328191034-3462fbc510c0
go: downloading golang.org/x/net v0.16.0
go: downloading github.com/google/uuid v1.2.0
go: downloading github.com/mitchellh/go-wordwrap v1.0.1
go: downloading gopkg.in/yaml.v3 v3.0.1</pre>
4. Try to verify that `cue` was installed:
<pre>$ which cue
$ cue
Command 'cue' not found, did you mean:
...
$ ls /usr/local/bin
(bin, cuda, games, go, etc., but no sign of cue)
</pre>

(These negative results persist even after logging out and back in.)

### What did you expect to see?

Some indication that `cue` was installed.

### What did you see instead?

No sign of it.  I do have a new "go" directory in my home folder, but nothing new in my path.  If a manual addition to the path is required, that should be pointed out.  As written it sounds like this one go command should "install the cue command line tool", but it does not appear to have done that.

**Comment by bueti** [comment]
`go install` will install binaries into `$GOPATH/bin`[1]. If this is not set up in your shell (for example, by adding `$GOPATH/bin` to your `$PATH`) , you wont be able to run `cue` like that.  

[1] https://pkg.go.dev/cmd/go#hdr-GOPATH_environment_variable

**Comment by mvdan** [comment]
What @bueti said - this sounds like an issue with your Go setup.
