### ISSUE TITLE
cmd/cue: trim: format an empty struct without an extra line

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#278]
_Originally opened by @rogpeppe in https://github.com/cuelang/cue/issues/278_

When all fields in a struct are redundant, it's common for `cue trim` to produce the empty struct (`{}`), but this is always formatted on two lines, for example:

```
z: a: {
}
```
rather than:
```
z: a: {}
```

This means that even though data has been removed, structs that go from having a single field to having none will actually increase the total number of lines.

Consider formatting the empty struct without an intervening newline to make this case nicer.

**Comment by cueckoo** [comment]
_Original reply by @rogpeppe in https://github.com/cuelang/cue/issues/278#issuecomment-582485287_

It could be argued that `cue fmt` should always remove whitespace in an empty struct.

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/278#issuecomment-583729059_

The easiest fix seems to be formatting `{}` on a single line. I'll be down for that if there are no objections.

**Comment by mvdan** [comment]
I have no objections to always formatting empty structs to single lines, as long as there aren't any comments inside the struct, like:

```
foo: {
    // Some commented out code.
    // bar: "baz"
}
```

We should also behave the same with lists, i.e. `foo: []` never formatting as multiple lines.

 @NoamTD does your fix above deal with these properly? Could you please make sure that we have test coverage for inner comments as well as empty lists with and without inner comments?

**Comment by NoamTD** [comment]
@mvdan yup that's the first thing I checked - there's pretty good coverage for cases like this:

- [empty struct with comment](https://github.com/cue-lang/cue/blob/797d6f4b8fe2e371d538583f13cfbb9c8c2c4b44/cue/format/testdata/comments.golden#L42)
- [empty list with comment](https://github.com/cue-lang/cue/blob/797d6f4b8fe2e371d538583f13cfbb9c8c2c4b44/cue/format/testdata/comments.golden#L83)

I've update [the CL](https://review.gerrithub.io/c/cue-lang/cue/+/1193759) accordingly to support both lists and structs

**Comment by NoamTD** [comment]
This change would also reformat this:

```cue
a: {

} // a comment

b: [

] // a comment
```

To this:

```cue
a: {} // a comment

b: [] // a comment
```

I /think/ that makes sense, but want to put it out there

**Comment by NoamTD** [comment]
This change would also reformat this:

```cue
a: {

} // a comment

b: [

] // a comment
```

To this:

```cue
a: {} // a comment

b: [] // a comment
```

I /think/ that makes sense, but want to put it out there

**Comment by mvdan** [comment]
Ah perfect, thanks. And yup, those trailing comment changes look right.
