### ISSUE TITLE
cmd/cue: cue mod init should allow versioned module paths

### ISSUE THREAD

**Issue by rogpeppe** [cue-lang/cue#2780]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.7.0
</pre>

### What did you do?

```
cue mod init example.com@v0
```

### What did you expect to see?

Success.

### What did you see instead?

```
invalid host name v0
```

The `cue mod init` code does not yet grok major-versioned module paths.

**Comment by rogpeppe** [comment]
Fixed by https://review.gerrithub.io/c/cue-lang/cue/+/1176076

**Comment by mvdan** [comment]
Please get in the habit of doing "fixes" lines in commit messages :) Otherwise there's no link from the commit/CL back to the issue.

**Comment by rogpeppe** [comment]
> Please get in the habit of doing "fixes" lines in commit messages :) Otherwise there's no link from the commit/CL back to the issue.

Yeah, I do prefer to do that, but I only realised this issue existed after I landed the CL :)
