### ISSUE TITLE
evaluator: defaults override values inside string interpolation

### ISSUE THREAD

**Issue by nickfiggins** [cue-lang/cue#2787]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.7.0

go version go1.21.5
      -buildmode exe
       -compiler gc
       -trimpath true
     CGO_ENABLED 0
          GOARCH amd64
            GOOS darwin
         GOAMD64 v1
</pre>

### Does this issue reproduce with the latest stable release?
yes

### What did you do?

```
exec cue cmd print
cmp stdout expect-stdout

-- expect-stdout --
hello
2
-- task_tool.cue --
package home

import (
	"tool/cli"
)

a: "hello"
b: 2

command: print: {
	print: cli.Print & {
		text: """
                 \(*"no message" | a)
                 \(*"no message" | b)
                 """
	}
}

-- task.cue --
package home
-- cue.mod --

```

### What did you expect to see?
A passing test.

### What did you see instead?
```
> exec cue cmd print
            [stdout]
            no message
            no message
            > cmp stdout expect-stdout
            diff stdout expect-stdout
            --- stdout
            +++ expect-stdout
            @@ -1,2 +1,2 @@
            -no message
            -no message
            +hello
            +2
            
```

**Comment by mvdan** [comment]
Perhaps I'm missing something here. With `a: "hello"`, the expression `*"no message" | a` should be evaluating to `"no message"`, because that is the default in the disjunction. This is working as intended, as far as I can tell.

**Comment by mvdan** [comment]
If you want `"no message"` to only be used as a fallback, then your default is backwards - you should use `*a | "no message"`.

**Comment by nickfiggins** [comment]
Oops. Thanks @mvdan - apologies for the false positive 🙂. I double-checked the spec before opening but realizing now I was misunderstanding. Closing this issue.
