### ISSUE TITLE
Cue packages

### ISSUE THREAD

**Issue by lakshy-amagi** [cue-lang/cue#2797]
I saw we can use "strings", "math" packages in cue files.
My question can we use the "time" package as well? If yes, what functions we can use?

What other packages are supported by the cuelang?

Can we please get documentation on it?

**Comment by slewiskelly** [comment]
The standard library is documented on GoDoc: https://pkg.go.dev/cuelang.org/go/pkg.

**Comment by lakshy-amagi** [comment]
> The standard library is documented on GoDoc: https://pkg.go.dev/cuelang.org/go/pkg.

Thanks @slewiskelly . Closing this issue.

**Comment by lakshy-amagi** [comment]
https://pkg.go.dev/cuelang.org/go@v0.7.0/pkg/
Standard packages in cuelang
