### ISSUE TITLE
cue: mod tidy is hidden (but is mentioned in the modules tutorial)

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#2804]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.0.0-20240209203336-3d1c0cb3f5e0

go version go1.21.4
      -buildmode exe
       -compiler gc
     CGO_ENABLED 1
          GOARCH arm64
            GOOS linux
             vcs git
    vcs.revision 3d1c0cb3f5e0abef4e6638d6775c2672968d2863
        vcs.time 2024-02-09T20:33:36Z
    vcs.modified false
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
cue help mod
```

Surfaced via https://cl-1176651-7--cue-cls.netlify.app/docs/reference/cli/cue-mod/

### What did you expect to see?

```
$ cue help mod


Usage:
  cue mod <cmd> [arguments] [flags]
  cue mod [command]

Available Commands:
  init        initialize new module in current directory
  tidy        download and tidy module dependencie

Global Flags:
...
```

### What did you see instead?

```
$ cue help mod


Usage:
  cue mod <cmd> [arguments] [flags]
  cue mod [command]

Available Commands:
  init        initialize new module in current directory

Global Flags:
...
```

i.e. tidy is not listed.

**Comment by mvdan** [comment]
Yeah, I think we should stop hiding it now that we intend to release it in experimental form. Should be OK as long as we keep the experimental notice in place.

**Comment by myitcv** [comment]
Noting that the same applies to `cue mod publish`:

https://github.com/cue-lang/cuelang.org/blob/d56ff105a657241b0b6674dbc855d931cc7d6080/content/docs/tutorial/working-with-a-custom-module-registry/en.md?plain=1#L183

I've assigned this issue to myself and will fix that instance too.
