### ISSUE TITLE
alpha.cuelang.org: modules tutorial should make clear the version of cmd/cue being used

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#2813]
### What page were you looking at?

https://alpha.cuelang.org/docs/tutorial/working-with-a-custom-module-registry/

### What version of the site were you looking at?

https://github.com/cue-lang/cuelang.org/commit/205a27149521530c85faa4927ed8c47fd78eb144

### What did you do?

Viewed the above page.

### What did you expect?

Confirmation of the `cmd/cue` version that was being used.

### What did you see instead?

Nothing.

**Comment by mvdan** [comment]
This is fixed; the GitHub automation for "Fixes" didn't kick in since the cuelang.org repo's default branch is `master`, not `alpha`. Closing manually.
