### ISSUE TITLE
cmd/cue: debug logging for modules

### ISSUE THREAD

**Issue by rogpeppe** [cue-lang/cue#2815]
**Is your feature request related to a problem? Please describe.**

When debugging registry-related issues, it's useful to be able to see what's going on under the hood.

**Describe the solution you'd like**

All commands that talk to the registry should be able to have logging enabled, probably by using the `-v` flag.

**Additional context**

To be decided: do we want to enable multiple levels of debug info (for example, higher level operations, OCI level operations, low level HTTP requests, auth requests) ?

**Comment by myitcv** [comment]
Perhaps following Go here it should be `-x` but I hold that lightly.
