### ISSUE TITLE
alpha.cuelang.org: add support for sudo commands in multi-step scripts

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#2818]
### What page were you looking at?

https://alpha.cuelang.org/docs/

### What version of the site were you looking at?

https://github.com/cue-lang/cuelang.org/commit/eb2ecd699e4451e0284f62764d145abdd14040e2

### What did you do?

I tried to write a bit of documentation that modified `/etc/hosts` to fake a couple of hostnames for a multi-value `CUE_REGISTRY` demonstration of how to "route" modules to/from different registries.

### What did you expect?

For `sudo` to be available in the default site image.

### What did you see instead?

```
$ sudo
bash: sudo: command not found
```

cc @rogpeppe because the hypothesised `cmd/cue mod` command we discussed earlier that would print out where a module resolves from a registry perspective would be helpful for such a guide too.

**Comment by jpluscplusm** [comment]
Please could you clarify: would this merely place the `sudo` binary in the container, or would it actually grant code running in the container the ability to escalate to root on the host machine (irrespective of if the use case proposed in this issue would modify files on the host machine or not)?

**Comment by myitcv** [comment]
Closing as we don't have a current need for this.
