### ISSUE TITLE
cmd/cue: fmt doesn't align definitions very well

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#283]
_Originally opened by @mvdan in https://github.com/cuelang/cue/issues/283_

For example:

```
$ cat test.cue
Fooo  :: string
Bar   :: string
Baaaz :: string
$ cue fmt test.cue
$ cat test.cue
Fooo ::  string
Bar ::   string
Baaaz :: string
```

I think the original version is more readable. I don't think this kind of alignment needs to happen for any other space-spearated token, as `::` seems like the only one that's useful when laying many definitions/values at the top level.

I think there is some precedent in Go - for example, this is valid `gofmt`:

```
package p

var (
	Fooo  string      = "x"
	Bar   int         = 3
	Baaaz interface{} = nil
)
```

The way we currently format definitions makes the code ugly to me, almost as if the Go snippet above formatted as:

```
package p

var (
	Fooo  string =      "x"
	Bar   int =         3
	Baaaz interface{} = nil
)
```

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/283#issuecomment-584833879_

That seems reasonable. The alternative is to not have a space between the field name and the double colon.

**Comment by cueckoo** [comment]
_Original reply by @mvdan in https://github.com/cuelang/cue/issues/283#issuecomment-584835231_

I think I like the current spaced form better. It also helps differentiate `Foo::` from `Foo:`.

If this change sounds like a good idea, I might give it a try later this week.

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/283#issuecomment-584848999_

Yeah. Another thing to consider is to space
```
a: bbb:  int
ccc: dd: 5 
```
as
```
a:   bbb: in
ccc: dd:  5
```
This may not work well if the fields are too different in size, but the latter seems to be better in general.

At some point the formatter should be completely rewritten. The current one is a fork from the Go one, but CUE underwent some changes that should make formatting much simpler: it has relative positioning, there is no need to use absolute positions, there are no more block comments, etc.

**Comment by cueckoo** [comment]
_Original reply by @mvdan in https://github.com/cuelang/cue/issues/283#issuecomment-584851079_

I think this second suggestion is a good idea, but it would also need a heuristic like Go's, to work around the problem of too much whitespace - like you said.

> At some point the formatter should be completely rewritten.

I know Robert has plans to rewrite gofmt, so I think you should pick his brains a bit there :)

**Comment by mvdan** [comment]
Definitions changed from `Foo :: bar` to `#Foo: bar` a long time ago now, so I think this feature request is now moot. It's possible that we can still improve the way we align some tokens, like in https://github.com/cue-lang/cue/issues/2458, but this issue on its own appears no longer relevant to me.
