### ISSUE TITLE
cuelang.org: frontend: content-type-specific search boxes' live-search displays results from all content types

### ISSUE THREAD

**Issue by jpluscplusm** [cue-lang/cue#2841]
### What page were you looking at?

https://alpha.cuelang.org/docs/concept/find-a-guide/

### What version of the site were you looking at?

https://github.com/cue-lang/cuelang.org/commit/a1865093a899fdf8f8aabfbcebf77b80f49da8dd

### What did you do?

I wanted to find a concept guide on the topic of "unification". I clicked in the on-page (**not** top right) `Search in Concept Guides` text entry box, and started typing.

### What did you expect?

I expected to see results limited to "Concept Guides", given the page's source: https://github.com/cue-lang/cuelang.org/blob/alpha/hugo/content/en/docs/concept/find-a-guide/index.md?plain=1

### What did you see instead?

A live "search results" overlay appeared on top of the static, "current query" results list.

Its results were sub-string constrained as I typed more of the word "unification", but the results were taken from across the site. They weren't limited to just concept guides.

After hitting enter, the live results overlay disappeared, and the on-page static results list was finally updated, containing only concept guide results.

The live results overlay **is**, for all intents and purposes, the "search results" list, as it obscures the list on the page. It seems wrong to expect the user to know they have to hit enter to populate the on-page list with content-type-constrained results.

**Comment by myitcv** [comment]
@jpluscplusm please can you do a quick check to ensure this issue is still current?

**Comment by jpluscplusm** [comment]
> @jpluscplusm please can you do a quick check to ensure this issue is still current?

Yes, the issue still strikes.

**Comment by myitcv** [comment]
Removing @JorindeUsMedia as assignee for now until we have planning/scheduling sorted.
