### ISSUE TITLE
cuelang.org: frontend: search doesn't work on mobile

### ISSUE THREAD

**Issue by jpluscplusm** [cue-lang/cue#2848]
### What page were you looking at?

https://cuelang.org/

### What version of the site were you looking at?

https://github.com/cue-lang/cuelang.org/commit/916ac4fbcfa93f3f40da57ac325e61a9a506d741

### What did you do?

I tried to use the search interface to find documents related to "testing". I was using mobile Safari on an iPhone 14 running iOS version 17.2.1. A video of the process is shared here: https://share.icloud.com/photos/046O91wx0ppHT2lLhvBOkU0Fw. (NB iCloud automatically unshares the video on March 22, 2024) 

### What did you expect?

I expected to see a results page containing (far) fewer than the site's current corpus of 217 pages.

#### Problem 1

As shown in the video above, I:

- opened the floating search box via the hamburger menu
- clicked in the search UI
- typed the word "testing"
- hit the on-screen keyboard's "search" action button. 

A results page was returned with a list of all the documents on the site, and definitely not the set of documents matching my search string. Not shown in the video, the page URL had no search term in the `q=` query string parameter.

#### Problem 2

Shown in the same video, **on the results page** I:

- clicked in the on-page search UI's text box in the body of the page (*not* using the hamburger menu, this time)
- observed that the yellow-tinted search UI was displayed
- clicked in the yellow-tinted UI's text box
- observed that the yellow-tinted search UI disappeared, leaving me with the previous results list.

An on-screen keyboard was never presented, leaving me unable to enter a new search term.

**Comment by jpluscplusm** [comment]
Problem 2 also strikes on pages such as https://alpha.cuelang.org/docs/howto/find-a-guide/ that use the search shortcode.

**Comment by myitcv** [comment]
@jpluscplusm please can you do a quick check to ensure this issue is still current?

**Comment by jpluscplusm** [comment]
> @jpluscplusm please can you do a quick check to ensure this issue is still current?

Yes: on the same iPhone as the issue mentions, now running iOS 17.4.1, both the problems still strike as described.

**Comment by myitcv** [comment]
Note this also affects the desktop version when working in a smaller viewport (perhaps unsurprising, but noting here for completeness)

**Comment by jpluscplusm** [comment]
> Note this also affects the desktop version when working in a smaller viewport (perhaps unsurprising, but noting here for completeness)

Problem #<wbr>1 strikes on desktop with a narrow viewport. I can't get problem #<wbr>2 to strike in the same context, as it's on-screen-keyboard related.

**Comment by anne-usmedia** [comment]
I created an issue for algolia since we couldn't find a fix for this: https://github.com/algolia/autocomplete/issues/1259

**Comment by jpluscplusm** [comment]
Problem 2 *appears* to have been resolved by NPM upgrades or site/UI changes. Problem 1 still strikes.

@anne-usmedia Does the idea linked to by the comment on your upstream issue look like it'll resolve problem 1?

**Comment by JorindeUsMedia** [comment]
@jpluscplusm The comment on the algolia issue wasn't very helpful for us.. But I've possibly found the problem in our code. I managed to get more insights by using android remote debug in chrome and I think I found the issue. Will do some more tests and hopefully provide a pr with the solution this week.
