### ISSUE TITLE
alpha.cuelang.org: definitions are highlighted as errors in CUE code

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#2872]
### What page were you looking at?

https://alpha.cuelang.org/docs/integration/json/

### What version of the site were you looking at?

https://github.com/cue-lang/cuelang.org/commit/3d3c62a8898b86d857ca8a850a0d5f6e2ae3c21f

### What did you do?

Visited the above page.

### What did you expect?

Nicely rendered CUE code.

### What did you see instead?

The `#` in a definition rendered as if it is an error:

![Screenshot 2024-02-26 at 16 53 49](https://github.com/cue-lang/cue/assets/3374574/cf9a5319-45fd-4d06-92e2-b60ac87a1cb2)

**Comment by myitcv** [comment]
This will be fixed via https://github.com/alecthomas/chroma/pull/935. It will need a new chroma release, which can then be picked up by hugo, then we need to upgrade to the latest hugo version.

**Comment by jpluscplusm** [comment]
Closed via https://github.com/cue-lang/cuelang.org/commit/2cf998ec6863a626b7e5a1e7e3cc9d92db8a8c37
