### ISSUE TITLE
modules: make final decision on major version defaults

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#2881]
As of v0.8.0-alpha.3, we support the concept of [major version defaults](https://alpha.cuelang.org/docs/reference/modules/#major-version-defaults):

> When a package import path does not contain a major version, the  `module.cue`  file is consulted to determine which major version of the module to use. In a canonical  `module.cue`  file, all imports without major versions will have an explicit  `default: true`  present in the corresponding dependency entry, but  `cue mod tidy`  will add those if not present and there is no ambiguity in the build list.
> 
> That is, given only a single major version of a module in the build list, the major version need not be specified in any of the package imports.

On the face of things, this is convenient and user friendly.

Consider, however, the following code:

```cue
package p

import "mycompany.com/module/example"

x: example.Thing
```

It is now impossible (without additional reference to the `cue.mod/module.cue` file) to know what major version `mycompany.com/module/example` refers to. As such, the ability to copy-paste CUE is harmed by this change, because potentially two copy-pastes are required. 

This issue is designed to capture discussion around the pros and cons of adding major version defaults (the above list is not exhaustive), to help a final decision by we make a decision on the modules proposal.

**Comment by mvdan** [comment]
I seem to recall that @rogpeppe was always in favor of this default mechanism for the sake of large codebases and upgrades being less painful when a shared dependency is only ever used at a single major version. Even if tooling could in theory solve the git conflicts, in practice there still are git conflicts to deal with, and even when resolved, a significant deal of git diff/log noise.

I agree with Paul that standalone CUE files or examples without explicit major versions in imports become less useful, though, as they lack context. Perhaps we could mitigate this by enforcing that CUE examples and tutorials always include major versions. Once we eventually have rendered documentation with runnable examples like pkg.go.dev, we could enforce this for all CUE modules, for example.

One counter-argument is that some context is always missing - even with a major version like `@v1`, you can't know if the example was written with `v1.1.0` or `v1.20.5`. In theory, v1+ is backwards compatible so picking the latest version should be OK. In practice, APIs are deprecated, functionality is changed, and examples break in subtle ways given enough time. This is all of course much more common with v0.

**Comment by mvdan** [comment]
One more thought: if we want to keep this default major version feature in, but we want to make it more self-explanatory and less prone for users to "run into" without realising, we could always spell it out explicitly, like one of:

* `import "mycompany.com/module/example@cue.mod"`
* `import "mycompany.com/module/example@mod"`
* `import "mycompany.com/module/example@single"`

**Comment by rogpeppe** [comment]
> One more thought: if we want to keep this default major version feature in, but we want to make it more self-explanatory and less prone for users to "run into" without realising, we could always spell it out explicitly, like one of:
> 
> * `import "mycompany.com/module/example@cue.mod"`
> * `import "mycompany.com/module/example@mod"`
> * `import "mycompany.com/module/example@single"`

I think I understand what the first of those might mean (take the major version from the version specified in cue.mod/module.cue), but what are the second and third meant to mean?

**Comment by mvdan** [comment]
I'm not sure, I was only throwing ideas out there. I agree the top suggestion is the only one that seems self-explanatory.

**Comment by rogpeppe** [comment]
FWIW I'm still in favour of having major version defaults. @mvdan recalls correctly above.
A few other points:
- it has been said that it's more common for configuration schemas to be change in a backwardly incompatible way than language APIs. Having major version defaults makes it easier for people to upgrade a major version, thus making it easier for people to use semver correctly, something that might actually be mandated by some registry compatibility checks.
- this decision doesn't necessarily paint us into a corner we can't escape from: as the chosen major version is entirely determined from local information, if we decided _not_ to support major version defaults in the future, we could easily provide a `cue fix` that would add the explicit major version in every import path.
- having major version defaults can make the transition from old semantics to new module semantics more straightforward, as an import path can work both for the old style imports from `cue.mod/pkg` etc _and_ for imports from modules.

**Comment by mpvl** [comment]
@rogpeppe I think these are good arguments. I also think the benefits of keeping it as is (allowing major version defaults) outweighs the disadvantages. If it turns out to be a quagmire, we can change it later.

**Comment by rogpeppe** [comment]
Based on the discussion above it seems that keeping major version defaults, at least for now, is a good idea.
As such, I'm closing the issue.

**Comment by mvdan** [comment]
For the sake of clarity, we are comfortable with keeping the design as-is because we can later move away from it (by either making the default selection explicit with `import/path@cue.mod`, or removing the default selection entirely) with a `cue fix` rewrite step. We don't think we will need to do this, as we think the current design and implementation are sound, but if it turns out we made a mistake it won't be hard to recover from.

**Comment by myitcv** [comment]
Also noting that via tooling (especially LSP) we can surface the actual version (which implicitly includes the major version) via things like hover text etc. So it's not like this information is hidden/buried with such a decision.
