### ISSUE TITLE
general: cuelang.org/go@v0.5.0 not available via GOPROXY=direct

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#2895]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.0.0-20240229185933-77936ec16926

go version go1.22.0
      -buildmode exe
       -compiler gc
  DefaultGODEBUG httplaxcontentlength=1,httpmuxgo121=1,tls10server=1,tlsrsakex=1,tlsunsafeekm=1
     CGO_ENABLED 1
          GOARCH arm64
            GOOS linux
             vcs git
    vcs.revision 77936ec16926012597aeb9ba99e7844c7910a883
        vcs.time 2024-02-29T18:59:33Z
    vcs.modified false
</pre>

### Does this issue reproduce with the latest release?

n/a

### What did you do?

```
env GOPATH=$WORK/_gopath
env GOPROXY=direct
go mod init mod.example
go get -x cuelang.org/go@v0.5.0
```

### What did you expect to see?

Passing test.

### What did you see instead?

```
> env GOPATH=$WORK/_gopath
> env GOPROXY=direct
> go mod init mod.example
[stderr]
go: creating new go.mod: module mod.example

> go get -x cuelang.org/go@v0.5.0
[stderr]
# get https://cuelang.org/?go-get=1
# get https://cuelang.org/go?go-get=1
# get https://cuelang.org/?go-get=1: 200 OK (0.120s)
# get https://cuelang.org/go?go-get=1: 200 OK (0.212s)
mkdir -p $WORK/_gopath/pkg/mod/cache/vcs # git3 https://review.gerrithub.io/cue-lang/cue
# lock $WORK/_gopath/pkg/mod/cache/vcs/d82383d43199d57840995f1c0a94e81eee5ed02e43dbba4468223292497673e2.lock
mkdir -p $WORK/_gopath/pkg/mod/cache/vcs/d82383d43199d57840995f1c0a94e81eee5ed02e43dbba4468223292497673e2 # git3 https://review.gerrithub.io/cue-lang/cue
cd $WORK/_gopath/pkg/mod/cache/vcs/d82383d43199d57840995f1c0a94e81eee5ed02e43dbba4468223292497673e2; git init --bare
0.010s # cd $WORK/_gopath/pkg/mod/cache/vcs/d82383d43199d57840995f1c0a94e81eee5ed02e43dbba4468223292497673e2; git init --bare
cd $WORK/_gopath/pkg/mod/cache/vcs/d82383d43199d57840995f1c0a94e81eee5ed02e43dbba4468223292497673e2; git remote add origin -- https://review.gerrithub.io/cue-lang/cue
0.005s # cd $WORK/_gopath/pkg/mod/cache/vcs/d82383d43199d57840995f1c0a94e81eee5ed02e43dbba4468223292497673e2; git remote add origin -- https://review.gerrithub.io/cue-lang/cue
cd $WORK/_gopath/pkg/mod/cache/vcs/d82383d43199d57840995f1c0a94e81eee5ed02e43dbba4468223292497673e2; git tag -l
0.004s # cd $WORK/_gopath/pkg/mod/cache/vcs/d82383d43199d57840995f1c0a94e81eee5ed02e43dbba4468223292497673e2; git tag -l
cd $WORK/_gopath/pkg/mod/cache/vcs/d82383d43199d57840995f1c0a94e81eee5ed02e43dbba4468223292497673e2; git ls-remote -q origin
1.297s # cd $WORK/_gopath/pkg/mod/cache/vcs/d82383d43199d57840995f1c0a94e81eee5ed02e43dbba4468223292497673e2; git ls-remote -q origin
go: cuelang.org/go@v0.5.0: invalid version: unknown revision v0.5.0

[exit status 1]
FAIL: /tmp/testscript1588843347/repro.txtar/script.txtar:4: unexpected go command failure
error running repro.txtar in /tmp/testscript1588843347/repro.txtar
```

The issue appears to be down to different behaviours between CUE's main remote https://review.gerrithub.io/cue-lang/cue and the mirror at https://github.com/cue-lang/cue:

```
exec bash script.bash https://review.gerrithub.io/cue-lang/cue
cmp stdout gerrit.golden

exec bash script.bash https://github.com/cue-lang/cue
cmp stdout github.golden

# These results should be the same
cmp gerrit.golden github.golden

-- script.bash --
cd $(mktemp -d)
git init -q --bare
git remote add origin -- $1
git ls-remote -q origin | grep refs/tags | awk '{print $2}' | sort | uniq
-- gerrit.golden --
refs/tags/v0.0.0-goreleaser.202211181000
refs/tags/v0.0.10
refs/tags/v0.0.11
refs/tags/v0.0.12
refs/tags/v0.0.13
refs/tags/v0.0.14
refs/tags/v0.0.15
refs/tags/v0.0.2
refs/tags/v0.0.3
refs/tags/v0.0.4
refs/tags/v0.0.4-rc1
refs/tags/v0.0.5
refs/tags/v0.0.6
refs/tags/v0.0.7
refs/tags/v0.0.8
refs/tags/v0.0.9
refs/tags/v0.1.0
refs/tags/v0.1.1
refs/tags/v0.1.2
refs/tags/v0.2.0
refs/tags/v0.2.1
refs/tags/v0.2.2
refs/tags/v0.3.0
refs/tags/v0.3.0-alpha1
refs/tags/v0.3.0-alpha2
refs/tags/v0.3.0-alpha3
refs/tags/v0.3.0-alpha4
refs/tags/v0.3.0-alpha5
refs/tags/v0.3.0-alpha6
refs/tags/v0.3.0-beta.1
refs/tags/v0.3.0-beta.2
refs/tags/v0.3.0-beta.3
refs/tags/v0.3.0-beta.4
refs/tags/v0.3.0-beta.5
refs/tags/v0.3.0-beta.6
refs/tags/v0.3.0-beta.7
refs/tags/v0.3.0-beta.8
refs/tags/v0.3.1
refs/tags/v0.3.2
refs/tags/v0.4.0
refs/tags/v0.4.0-alpha.1
refs/tags/v0.4.0-alpha.2
refs/tags/v0.4.0-beta.1
refs/tags/v0.4.0-beta.2
refs/tags/v0.4.0-rc.1
refs/tags/v0.4.1
refs/tags/v0.4.1-beta.1
refs/tags/v0.4.1-beta.2
refs/tags/v0.4.1-beta.3
refs/tags/v0.4.1-beta.4
refs/tags/v0.4.1-beta.5
refs/tags/v0.4.1-beta.6
refs/tags/v0.4.1-rc.1
refs/tags/v0.4.1-rc.2
refs/tags/v0.4.2
refs/tags/v0.4.2-rc.1
refs/tags/v0.4.3
refs/tags/v0.4.3-beta.1
refs/tags/v0.4.3-beta.2
refs/tags/v0.5.0-alpha.1
refs/tags/v0.5.0-beta.1
refs/tags/v0.5.0-beta.2
refs/tags/v0.5.0-beta.3
refs/tags/v0.6.0
refs/tags/v0.6.0-0.dev
refs/tags/v0.6.0-alpha.1
refs/tags/v0.6.0-alpha.2
refs/tags/v0.6.0-beta.1
refs/tags/v0.6.0-rc.1
refs/tags/v0.7.0
refs/tags/v0.7.0-rc.1
refs/tags/v0.7.1
refs/tags/v0.8.0-0.dev
refs/tags/v0.8.0-alpha.1
refs/tags/v0.8.0-alpha.2
refs/tags/v0.8.0-alpha.3
refs/tags/v0.8.0-alpha.4
-- github.golden --
refs/tags/v0.0.0-goreleaser.202211181000
refs/tags/v0.0.10
refs/tags/v0.0.11
refs/tags/v0.0.12
refs/tags/v0.0.13
refs/tags/v0.0.14
refs/tags/v0.0.15
refs/tags/v0.0.2
refs/tags/v0.0.3
refs/tags/v0.0.4
refs/tags/v0.0.4-rc1
refs/tags/v0.0.5
refs/tags/v0.0.6
refs/tags/v0.0.7
refs/tags/v0.0.8
refs/tags/v0.0.9
refs/tags/v0.1.0
refs/tags/v0.1.1
refs/tags/v0.1.2
refs/tags/v0.2.0
refs/tags/v0.2.1
refs/tags/v0.2.2
refs/tags/v0.3.0
refs/tags/v0.3.0-alpha1
refs/tags/v0.3.0-alpha2
refs/tags/v0.3.0-alpha3
refs/tags/v0.3.0-alpha4
refs/tags/v0.3.0-alpha5
refs/tags/v0.3.0-alpha6
refs/tags/v0.3.0-beta.1
refs/tags/v0.3.0-beta.2
refs/tags/v0.3.0-beta.3
refs/tags/v0.3.0-beta.4
refs/tags/v0.3.0-beta.5
refs/tags/v0.3.0-beta.6
refs/tags/v0.3.0-beta.7
refs/tags/v0.3.0-beta.8
refs/tags/v0.3.1
refs/tags/v0.3.2
refs/tags/v0.4.0
refs/tags/v0.4.0-alpha.1
refs/tags/v0.4.0-alpha.2
refs/tags/v0.4.0-beta.1
refs/tags/v0.4.0-beta.2
refs/tags/v0.4.0-rc.1
refs/tags/v0.4.1
refs/tags/v0.4.1-beta.1
refs/tags/v0.4.1-beta.2
refs/tags/v0.4.1-beta.3
refs/tags/v0.4.1-beta.4
refs/tags/v0.4.1-beta.5
refs/tags/v0.4.1-beta.6
refs/tags/v0.4.1-rc.1
refs/tags/v0.4.1-rc.2
refs/tags/v0.4.2
refs/tags/v0.4.2-rc.1
refs/tags/v0.4.3
refs/tags/v0.4.3-beta.1
refs/tags/v0.4.3-beta.2
refs/tags/v0.5.0
refs/tags/v0.5.0-alpha.1
refs/tags/v0.5.0-beta.1
refs/tags/v0.5.0-beta.2
refs/tags/v0.5.0-beta.3
refs/tags/v0.5.0-beta.4
refs/tags/v0.5.0-beta.5
refs/tags/v0.5.0-rc.1
refs/tags/v0.6.0
refs/tags/v0.6.0-0.dev
refs/tags/v0.6.0-alpha.1
refs/tags/v0.6.0-alpha.2
refs/tags/v0.6.0-beta.1
refs/tags/v0.6.0-rc.1
refs/tags/v0.7.0
refs/tags/v0.7.0-rc.1
refs/tags/v0.7.1
refs/tags/v0.8.0-0.dev
refs/tags/v0.8.0-alpha.1
refs/tags/v0.8.0-alpha.2
refs/tags/v0.8.0-alpha.3
refs/tags/v0.8.0-alpha.4
```

To my understanding, that test should also pass but it fails with:

```
# These results should be the same (0.000s)
> cmp gerrit.golden github.golden
--- gerrit.golden
+++ github.golden
@@ -57,10 +57,14 @@
 refs/tags/v0.4.3
 refs/tags/v0.4.3-beta.1
 refs/tags/v0.4.3-beta.2
+refs/tags/v0.5.0
 refs/tags/v0.5.0-alpha.1
 refs/tags/v0.5.0-beta.1
 refs/tags/v0.5.0-beta.2
 refs/tags/v0.5.0-beta.3
+refs/tags/v0.5.0-beta.4
+refs/tags/v0.5.0-beta.5
+refs/tags/v0.5.0-rc.1
 refs/tags/v0.6.0
 refs/tags/v0.6.0-0.dev
 refs/tags/v0.6.0-alpha.1

FAIL: /tmp/testscript2426096314/repro.txtar/script.txtar:8: gerrit.golden and github.golden differ
```

Looking at the output of `go get -x` this at least explains why `cmd/go` thinks that `v0.5.0` does not exist on GerritHub.

Possibilities:

* A GerritHub issue; unlikely because GerritHub still knows about this tag and the commit: https://review.gerrithub.io/plugins/gitiles/cue-lang/cue/+/refs/tags/v0.5.0
* A `cmd/go` issue

### Context

Some important context here for those investigating:

The `v0.5.0` tag references a commit that is not part of the default (`master`) branch. That release happened from a release branch, `release-branch.v0.5`. That branch no longer exists on GerritHub or GitHub. This is confirmed by GitHub: https://github.com/cue-lang/cue/tree/v0.5.0. But per that GitHub link and https://review.gerrithub.io/plugins/gitiles/cue-lang/cue/+/refs/tags/v0.5.0, both know about the tag and commit.

**Comment by myitcv** [comment]
@mvdan - any thoughts here? My temptation is to raise first as a `cmd/go` issue. Because it's `cmd/go` that has an expectation on these `git` commands. There is a difference in behaviour here between Gerrit and GitHub - I don't know which is correct, but I'm assuming that Bryan et at will know more because of their experience with `cmd/go` and `git`.

**Comment by myitcv** [comment]
Per an exchange in `#tools` on Gophers slack, this is actually smelling more like a GerritHub bug.

**Comment by myitcv** [comment]
Raised as a GerritHub issue.

**Comment by mvdan** [comment]
GerritHub responded, and our suspicion that this was related to the release branch being deleted is correct:

> Gerrit does not allow access to detached heads, even if a tag points them, unless the user has complete visibility of the repository (ALLOW READ ON refs/*), which is not the case for the 'cue-lang/cue' repository.
> 
> The behavior is different than GitHub because of the higher security standards adopted by Gerrit, compared to GitHub.
> See the full discussion on the mailing list at [1].
> 
> You have two ways to make the v0.5.0 tag visible to all users:
> 
> Option-1: Allow all users to access all refs, granting ALLOW READ on 'refs/*'
> Option-2: Re-create the ‘release-branch.v0.5’ pointing to the tag v0.5.0
> 
> Option 2 is the safest because it does not expose your repository's configuration (refs/meta/*) to all users.
> 
> References:
> [1] https://groups.google.com/g/repo-discuss/c/f0nArdvuFCw/m/lB_xc2AQAgAJ?utm_medium=email&utm_source=footer

I've asked them if there's any way to make all tags always readable without opening access to `refs/meta/*`. If that's not easy, we can always keep release branches around forever, although that's not ideal as they will pile up in the long term.

Keeping release branches around forever also has the current unintended consequence that our "evict caches" daily job triggers daily TryBot runs on all present release branches, e.g. https://github.com/cue-lang/cue/actions/runs/8165887118 ran today for release-branch.v0.7 even though v0.7.1 happened many weeks ago. If the only solution is to keep release branches around forever, we should at least tweak our "evict caches" daily job so that it doesn't cause as much CI churn and noise, by e.g. only doing this for the last one or two release branches.

**Comment by mvdan** [comment]
I tried creating `refs/attic/release-branch.v0.5` as chief cueckoo, and it didn't work:

> Error 403: not permitted: create on refs/attic/release-branch.v0.5

So I'm sending a config change to try to give super admins explicit "create" access, and then I'll try again: https://review.gerrithub.io/c/cue-lang/cue/+/1183763

**Comment by mvdan** [comment]
OK, with the CL above merged, the same action as Chief Cueckoo (creating the "branch" from https://review.gerrithub.io/admin/repos/cue-lang/cue,branches) worked. The testscript at the top went from failing to succeeding, and the "branch" is available from both github and gerrit, even though neither lists the name in the branch list:

```
$ git fetch github refs/attic/release-branch.v0.5
From https://github.com/cue-lang/cue
 * branch              refs/attic/release-branch.v0.5 -> FETCH_HEAD
$ git fetch origin refs/attic/release-branch.v0.5
From https://review.gerrithub.io/a/cue-lang/cue
 * branch              refs/attic/release-branch.v0.5 -> FETCH_HEAD
 ```

I think we can mark this as resolved. I've added another note to https://github.com/cue-lang/cue/wiki/Notes-for-project-maintainers#releases about the "release branch attic".

**Comment by mvdan** [comment]
This should not happen again, at least not for long: I've added an automated CI check at https://review.gerrithub.io/c/cue-lang/cue/+/1201173.
