### ISSUE TITLE
alpha.cuelang.org: old CUE_MODCACHE described

### ISSUE THREAD

**Issue by kharf** [cue-lang/cue#2903]
What page were you looking at?
https://alpha.cuelang.org/

What version of the site were you looking at?
cue-lang/cuelang.org@3168163

What did you do?
Was reading about module references (https://alpha.cuelang.org/docs/reference/modules/#module-cache) and wanted to adjust the module cache directory. 

What did you expect?
`$CUE_CACHE_DIR` being described.

What did you see instead?
Old `$CUE_MODCACHE` still stated.

**Comment by myitcv** [comment]
@kharf - nice find, thank you. We absolutely should have caught this prior to release. 

cc @mvdan and @rogpeppe - with us doing releases so regularly now, as part of composing the change log I think we need to reflect and actively check if there is content on https://alpha.cuelang.org that needs to change. 

@kharf - just to check that you're aware of the "Report an issue" link at the bottom of each page?

![Screenshot 2024-03-02 at 20 00 04](https://github.com/cue-lang/cue/assets/3374574/76067298-5724-47f1-9f37-c8590e924617)

This issue looks similar to the result from clicking on that link, but the page link is not quite right, the formatting slightly off, and the labels not per the template. So wondering if perhaps created the template by hand? If so thank you for going to such effort - hopefully the link will make that easier for future issues.

**Comment by mvdan** [comment]
My bad, when I replaced the env var I grepped through our main repo, but forgot about the website entirely. I'll keep it in mind to check the site repo next time.

**Comment by myitcv** [comment]
Fixed by https://github.com/cue-lang/cuelang.org/commit/a6c0ff562901379bbe91bb60595468e3c01c7a6a

**Comment by kharf** [comment]
> @kharf - nice find, thank you. We absolutely should have caught this prior to release.
> 
> cc @mvdan and @rogpeppe - with us doing releases so regularly now, as part of composing the change log I think we need to reflect and actively check if there is content on https://alpha.cuelang.org that needs to change.
> 
> @kharf - just to check that you're aware of the "Report an issue" link at the bottom of each page?
> 
> ![Screenshot 2024-03-02 at 20 00 04](https://private-user-images.githubusercontent.com/3374574/309497741-76067298-5724-47f1-9f37-c8590e924617.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0NTEyMTIsIm5iZiI6MTcwOTQ1MDkxMiwicGF0aCI6Ii8zMzc0NTc0LzMwOTQ5Nzc0MS03NjA2NzI5OC01NzI0LTQ3ZjEtOWYzNy1jODU5MGU5MjQ2MTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDNUMDcyODMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODFlYjMyNzcwNjQ3YjVhOTQxN2QwN2U0MjhmM2Q0OWQ4OWI2NmVjZGI3YTdkMDg1NjU4ODc0NGY0ZDM0NDVjMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CxxfGag2Dy6ct_gyEpV4ffnwIc0OLH8enpO0zb4lnqE)
> 
> This issue looks similar to the result from clicking on that link, but the page link is not quite right, the formatting slightly off, and the labels not per the template. So wondering if perhaps created the template by hand? If so thank you for going to such effort - hopefully the link will make that easier for future issues.

Oh you're completely right. It was handcrafted. 😅  Will remember next time, thanks!
