### ISSUE TITLE
cmd/cue: help environment does not explain what lives under CUE_CACHE_DIR

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#2904]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.0.0-20240229185933-77936ec16926

go version go1.22.0
      -buildmode exe
       -compiler gc
  DefaultGODEBUG httplaxcontentlength=1,httpmuxgo121=1,tls10server=1,tlsrsakex=1,tlsunsafeekm=1
     CGO_ENABLED 1
          GOARCH arm64
            GOOS linux
             vcs git
    vcs.revision 77936ec16926012597aeb9ba99e7844c7910a883
        vcs.time 2024-02-29T18:59:33Z
    vcs.modified false
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
$ cue help environment
The cue command consults environment variables for configuration.
If an environment variable is unset or empty, it uses a sensible default
setting.

        CUE_CONFIG_DIR
                The directory where the cue command keeps configuration and
                state files. This defaults to a directory for user-specific
                configuration data, such as:

                        "$XDG_CONFIG_HOME/cue" or "$HOME/.config/cue" on Linux
                        "$HOME/Library/Application Support/cue" on MacOS
                        "%AppData%/cue" on Windows

        CUE_CACHE_DIR
                The directory where the cue command keeps a cache of files to be
                reused. This defaults to a directory for user-specific temporary
                cache data, such as:

                        "$XDG_CACHE_HOME/cue" or "$HOME/.cache/cue" on Linux
                        "$HOME/Library/Caches/cue" on MacOS
                        "%LocalAppData%/cue" on Windows

        CUE_REGISTRY

                This variable specifies which registry or registries to use for
                downloading and publishing modules. See "cue help registryconfig"
                for details.

        CUE_EXPERIMENT
                Comma-separated list of experiments to enable or disable. The
                list of available experiments may change arbitrarily over time.
                See exp.go in package cuelang.org/go/internal/cueexperiment for
                currently valid values.

                Warning: This variable is provided for the development and
                testing of the cue commands itself. Use beyond that purpose is
                unsupported.
```

### What did you expect to see?

Some explanation of what can live under `$CUE_CACHE_DIR`, e.g. `$CUE_CACHE_DIR/mod` and what's inside that directory. etc.

### What did you see instead?

The generic docs for `$CUE_CACHE_DIR`.

**Comment by mvdan** [comment]
I thought about this when writing the docs, but I worried that the help text would get too long. Maybe OK if we keep it to one line per file/directory.

This also applies to CUE_CONFIG_DIR, which currently only holds logins.json.

One though: I would keep the help text relatively vague, because the actual layout and format of the files is an implementation detail that end users shouldn't rely on.

**Comment by myitcv** [comment]
> One though: I would keep the help text relatively vague, because the actual layout and format of the files is an implementation detail that end users shouldn't rely on.

Agreed.
