### ISSUE TITLE
evaluator: export as YAML vs JSON emits different templated data

### ISSUE THREAD

**Issue by jpluscplusm** [cue-lang/cue#2916]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.8.0-alpha.5

go version go1.22.0
      -buildmode exe
       -compiler gc
       -trimpath true
     CGO_ENABLED 0
          GOARCH amd64
            GOOS linux
         GOAMD64 v1

</pre>

### Does this issue reproduce with the latest stable release?

Yes, 0.7.0.

### What did you do?

I tried to export the same data as YAML and JSON:

```
exec cue export file.cue --out json
! stdout 1
exec cue export file.cue --out yaml
! stdout 1
-- file.cue --
a: {
	b: _
	[_]: c:      uint | *1
	[string]: c: >=3 | *3
}
```

### What did you expect to see?

The same data emitted as both JSON and YAML.

### What did you see instead?

```
> exec cue export file.cue --out json
[stdout]
{
    "a": {
        "b": {
            "c": 3
        }
    }
}
> ! stdout 1
> exec cue export file.cue --out yaml
[stdout]
a:
  b:
    c: 1
> ! stdout 1
FAIL: /tmp/testscript136453955/cue.export.yamlVsJsonDifferentData.txtar/script.txtar:4: unexpected match for `1` found in stdout: 1
```

**Comment by myitcv** [comment]
I've marked this as an evaluator issue for now. It we can be sure the evaluator has the "right" value here, then we can look at whether/why the encoders handle that differently.

**Comment by myitcv** [comment]
As discussed, neither are valid i.e. the evaluator should have reported an unresolved disjunction in this situation:

Rewriting your example according to the notation used [in the spec](https://tip.cuelang.org/docs/references/spec/#default-values):

```
x: *1 | uint  // ⟨1 | uint, 1⟩
x: *3 | >=3   // ⟨3 | >=3, 3⟩
```

Applying rule U2, you can see that you end up with:

```
⟨(1 | uint)&(3 | >=3), 1&3⟩
```

`1&3` is bottom, so we "lose" any default in this situation and we end up with:


```
⟨3&uint | >=3&uint⟩
```

which means we should be left with an unresolved disjunction.

What I think you were hinting at here is effectively achieved by:

```
job: {
	nginx: replicas:  2
	manager: command: "monit -I"
	etcd:     _
	boltdb:   _
	postgres: _
}

job: [Name=_]: {
	name:     Name
	command:  string | *"exec \(Name)"
}

#DB: =~"db$" | "etcd" | "postgres" | "mysql"
#NotDB: !~"db$" & !="etcd" & != "postgres" & != "mysql"

job: [#DB]:    replicas: >=3 | *3
job: [#NotDB]: replicas: uint | *1
```

where `#NotDB` could be written as `not(#DB)` under #943.

**Comment by myitcv** [comment]
Noting that the new evaluator gets things right here:

```
env CUE_EXPERIMENT=evalv3

! exec cue export file.cue --out json
cmp stderr stderr.golden
! exec cue export file.cue --out yaml
cmp stderr stderr.golden
-- file.cue --
a: {
	b: _
	[_]: c:      uint | *1
	[string]: c: >=3 | *3
}
-- stderr.golden --
a.b.c: incomplete value >=3 & int | 3
```

i.e. this passes.
