### ISSUE TITLE
cmd/cue: help $blah does not error for non-existent $blah

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#2918]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.0.0-20240304165426-7d4d90de3798

go version go1.22.0
      -buildmode exe
       -compiler gc
  DefaultGODEBUG httplaxcontentlength=1,httpmuxgo121=1,tls10server=1,tlsrsakex=1,tlsunsafeekm=1
     CGO_ENABLED 1
          GOARCH arm64
            GOOS linux
             vcs git
    vcs.revision 7d4d90de3798a00807f50373466322771bd0a10a
        vcs.time 2024-03-04T16:54:26Z
    vcs.modified false
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
! exec cue help mod rubbish
stderr 'unknown command "mod rubbish"'
```

### What did you expect to see?

Passing test (for some variation of the `stderr` expectation)

### What did you see instead?

```
$ ts repro.txtar
> ! exec cue help mod rubbish
[stdout]


Usage:
  cue mod <cmd> [arguments] [flags]
  cue mod [command]

Available Commands:
  get         add and upgrade module dependencies
  init        initialize new module in current directory
  publish     publish the current module to a registry
  tidy        download and tidy module dependencies

Global Flags:
  -E, --all-errors   print all available errors
  -i, --ignore       proceed in the presence of errors
  -s, --simplify     simplify output
      --strict       report errors for lossy mappings
      --trace        trace computation
  -v, --verbose      print information about progress

Use "cue mod [command] --help" for more information about a command.
FAIL: /tmp/testscript1456235653/repro.txtar/script.txtar:1: unexpected command success
```

i.e. `cue help mod rubbish` exists with a 0 exit code for an unknown command `mod rubbish`

**Comment by mvdan** [comment]
Similar to https://github.com/cue-lang/cue/issues/2560, but likely not the same fix as `cue cmd` needs to load a CUE package to figure out what commands are available.
