### ISSUE TITLE
pkg/math: MultipleOf can't be used as a validator

### ISSUE THREAD

**Issue by jpluscplusm** [cue-lang/cue#2927]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.8.0-alpha.5

go version go1.22.0
      -buildmode exe
       -compiler gc
       -trimpath true
     CGO_ENABLED 0
          GOARCH amd64
            GOOS linux
         GOAMD64 v1

</pre>

### Does this issue reproduce with the latest stable release?

Yes, 0.7.0

### What did you do?

```
exec cue vet file.cue
-- file.cue --
import "math"

x: 10
x: math.MultipleOf(2)
```

I tried to use `math.MultipleOf` as a validator, which I believe should work given

1. its `(bool, error)` return type
2. other multi-parameter functions work as validators, e.g. https://alpha.cuelang.org/docs/howto/use-list-contains-as-a-field-validator/

### What did you expect to see?

A passing test. Note that the values chosen, 10 and 2, are *not* affected by #2926.

### What did you see instead?

```
> exec cue vet file.cue
[stderr]
x: invalid value 10 (does not satisfy math.MultipleOf(2)): error in call to math.MultipleOf: interface conversion: adt.Value is *adt.Vertex, not *adt.Num:
    ./file.cue:4:4
    ./file.cue:3:4
    ./file.cue:4:20
[exit status 1]
FAIL: /tmp/testscript1312268940/math.MultipleOf.doesntWorkAsValidator.txtar/script.txtar:1: unexpected command failure
```

**Comment by mogsie** [comment]
In addition, the following relatively natural construct:

```
import "math"

foo: 3
bar: 9 & math.MultipleOf(foo)
```

fails with:

```
bar: invalid value 9 (does not satisfy math.MultipleOf(3)): error in call to math.MultipleOf: interface conversion: adt.Value is *adt.Vertex, not *adt.Num:
```

I guess it's the same error, but might be worth to include in a test case.
