### ISSUE TITLE
cmd/cue: Docker auth integration should not give up on config.json errors

### ISSUE THREAD

**Issue by mvdan** [cue-lang/cue#2934]
```
$ cat repro-cmd.txtar
env CUE_EXPERIMENT=modules
env DOCKER_CONFIG=$WORK/docker-config

exec cue mod tidy

-- cue.mod/module.cue --
module: "foo.com/bar@v0"
-- foo.cue --
package bar

import "foo.com/baz@v0"

out: baz.Baz
-- docker-config/config.json --
{
  "credsStore": "no-such-helper",
  "auths": {}
}
$ testscript -v repro-cmd.txtar 
[...]
> exec cue mod tidy
[stderr]
failed to resolve "foo.com/baz@v0": cannot do HTTP request: Get "https://registry.cue.works/v2/foo.com/tags/list?n=1000": cannot acquire auth info for registry "registry.cue.works": cannot run auth helper: exec: "docker-credential-no-such-helper": executable file not found in $PATH
[exit status 1]
FAIL: /tmp/testscript3829924505/repro-cmd.txtar/script.txtar:4: unexpected command failure
error running repro-cmd.txtar in /tmp/testscript3829924505/repro-cmd.txtar
```

The setup above is broken - Docker is configured with a credential helper which isn't installed. Marcel had an issue like this one, which caused cue/load test failures until the test fix at https://review.gerrithub.io/c/cue-lang/cue/+/1178161.

There are other forms of broken Docker setups too, for example the docker/config.json file might have JSON syntax errors, or duplicate/ambiguous registry entries.

cmd/cue tries to be compatible with the Docker auth setup, but Docker isn't a requirement, so I think we should gracefully recover from these "broken Docker setup" cases rather than erroring and refusing to continue. My personal take is that we should print a warning to stderr and continue, because silently ignoring the Docker auth setup could lead to user confusion if they expected it to work but they made a mistake in the setup.

Not a high priority issue either way, but a sharp UX edge that we should polish at some point.

**Comment by rogpeppe** [comment]
This is an interesting case. It seems that in some cases, `.docker/config.json` is set up with a default credential helper that may not actually exist. It could be argued that this should behave differently to having a credential helper explicitly configured for a particular registry. Perhaps it's reasonable to treat a non-existent registry helper as equivalent to having no registry configuration, for the purposes of getting config information anyway (for credential _storage_, I suspect that's not a good idea).

One data point is to look at how Docker itself behaves when confronted with an invalid helper. It seems that it just ignores the bad helper without printing any warning (in fact it seems to ignore _any_ error from the helper, including bad JSON and a non-zero exit code, which is not necessarily a good example to follow), so perhaps it's reasonable for us to do that too.

This does not necessarily require any changes to the `ociregistry` module, as I believe it includes all the necessary flexibility to do this by customizing from outside the `ociauth` package, but perhaps it would be good to change the default behavior anyway.

**Comment by mvdan** [comment]
> One data point is to look at how Docker itself behaves when confronted with an invalid helper. It seems that it just ignores the bad helper without printing any warning (in fact it seems to ignore _any_ error from the helper, including bad JSON and a non-zero exit code, which is not necessarily a good example to follow), so perhaps it's reasonable for us to do that too.

This might be why Marcel had a broken Docker config and never noticed. At any rate, if Docker doesn't care about a configured default credential helper which isn't installed, we probably shouldn't either - especially if it's a relatively common scenario, which it seems to be.

**Comment by mvdan** [comment]
I'm fine with continuing to treat other errors as fatal, such as syntax errors or non-default credential helper errors, for what it's worth. We can re-evaluate those cases if users raise concerns about them. For now, Marcel only ran into the default credential helper not being installed.
