### ISSUE TITLE
cuelang.org: frontend: code examples' filenames should be made easy to select-and-copy

### ISSUE THREAD

**Issue by jpluscplusm** [cue-lang/cue#2935]
### What page were you looking at?

https://alpha.cuelang.org/docs/tutorial/working-with-a-custom-module-registry/

### What version of the site were you looking at?

https://github.com/cue-lang/cuelang.org/commit/4ccad6b8377da7e68b45103fb92ab2d7c7610f22

### What did you do?

As I scanned down the page, the filenames presented in each code/upload block (e.g. https://alpha.cuelang.org/docs/tutorial/working-with-a-custom-module-registry/#step-3) didn't pop off the page. I had to look for them, knowing that they were there, and were filenames.

They seemed somewhat lost against the background, **especially** when the filename importantly contains a directory name. 

### What did you expect?

I expected to be more firmly guided towards the fact that the filename element **was** a filename, whose contents I was about to see; perhaps differentiated by colour, perhaps font size, perhaps background contrast, perhaps an icon.

I believe the presence of the filename shouldn't be (as it currently is) /smaller/ than the code in the block, along with the same text and background colour as the code.

### What did you see instead?

![image](https://github.com/cue-lang/cue/assets/224508/165da667-496d-47bc-80dd-9686e848d495)

**Comment by JorindeUsMedia** [comment]
@jpluscplusm We can make the tab title a bit bigger. Maybe something like this? (14px instead of 12px)

![Screenshot from 2024-07-19 12-05-15](https://github.com/user-attachments/assets/fa8289fa-ad7a-45a1-98af-20e0a74ee15d)

**Comment by jpluscplusm** [comment]
@JorindeUsMedia That does feel /better/ but not (to my glasses-wearing eyes!) sufficient :-)

I know I mustn't fall into the trap of thinking that everyone has my specific problems, but I think there are two main issues captured here:

1. We need to making the text differentiate itself enough from the code that inevitably follows, so that it jumps out at the reader as "this is a **filename**, not just the start of some fixed-width code content". I think we should definitely do that with larger text, as you've demo'd, but could also add:
   - a small icon prefix that breaks up the flow of the text and stands out by indenting the filename's text with something that /can't/ be confused for text. In [CUE by example](https://github.com/cue-labs/cue-by-example/blob/main/000_template/README.md#files) I started by using the `:floppy:` emoji, but that was because we're limited by the emoji supported by GitHub's Markdown, and it definitely felt anachronistic!
   - filenames in a different colour from the text (e.g. the syntax highlighting will almost never include red, and very rarely include yellow). I lack the a11y awareness to know what acceptable options are in the colour-blindness spectrum.
   - a different font - perhaps a /wider/ font, given that horizontal space is rarely at a premium in the specific context of filename tabs.
2. I believe the reader will want to select the filename, before copying it and pasting it into their terminal, more often than not. I'm /not/ suggesting a copy button for the filename (unless there's an obvious precedent in this space), but that we should ensure that the filename area has an *affordance* of click-and-ctrl-C-copy'ability. I don't quite know what that /means/, merely that I suspect a majority of readers (who are attempting to follow a specific guide carefully, and not just paging through it) will prefer the copy/paste method of grabbing the filename, rather than typing it. Whatever we can do to give them an easier time will, I believe, be worth it.

**Comment by JorindeUsMedia** [comment]
@jpluscplusm something like this perhaps? 

![Screenshot from 2024-07-22 09-58-01](https://github.com/user-attachments/assets/039d088d-bd71-4a35-90a8-fe382c5101f1)

Edit: Just noticed I put an upload file icon there: this should be a regular file icon

Not all code-tabs have a filename right? So we should also add something to the shortcode where you can set if it's a file or not.

**Comment by developer-usmedia** [comment]
@jpluscplusm Did you have time to look at the comment above? If this is what you want we can started with the implementation.

**Comment by JorindeUsMedia** [comment]
@jpluscplusm Did you have time to look at the comment above? If this is what you want we can start with the implementation.

**Comment by jpluscplusm** [comment]
@JorindeUsMedia I'd totally missed your earlier comment - apologies!

> something like this perhaps?

Yes, that's the kind of thing that I was imagining. If it were possible to make the icon clickable, such that the filename were either copied to the clipboard *or* it were highlighted, ready for a ctrl-c, that would be fantastic. That's not a blocker, however - please don't go down a JS rabbit hole in order to achieve that!

> This should be a regular file icon

Do you have an example of what that might look like at the text sizes we're using?

> Not all code-tabs have a filename right?

Correct, but the significant majority of them do have one. Given that it'll be the preprocessor generating the `code-tab` source, I don't think we need to have a convenient default - feel free to make it a required parameter, if that's easiest. Otherwise, it should default to showing a file icon whilst allowing it to be disabled on a code-tab-by-tab basis.
