### ISSUE TITLE
cmd/cue: mod init should only add major version if modules is enabled

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#2940]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.8.0-rc.1

go version go1.22.1
      -buildmode exe
       -compiler gc
  DefaultGODEBUG httplaxcontentlength=1,httpmuxgo121=1,tls10server=1,tlsrsakex=1,tlsunsafeekm=1
     CGO_ENABLED 1
          GOARCH arm64
            GOOS linux
             vcs git
    vcs.revision d48dcbecbc82edacd50c26ce5f88ab02b3df8e27
        vcs.time 2024-03-13T12:28:08Z
    vcs.modified false
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
env CUE_EXPERIMENT=modules
cd $WORK/modules-enabled
exec cue mod init mod.com
cmp cue.mod/module.cue cue.mod_module.cue.golden

env CUE_EXPERIMENT=
cd $WORK/modules-not-enabled
exec cue mod init mod.com
cmp cue.mod/module.cue cue.mod_module.cue.golden

-- modules-enabled/cue.mod_module.cue.golden --
module: "mod.com@v0"
language: {
	version: "v0.8.0-rc.1"
}
-- modules-not-enabled/cue.mod_module.cue.golden --
module: "mod.com"
language: {
	version: "v0.8.0-rc.1"
}
```

### What did you expect to see?

Passing test.

### What did you see instead?

```
> env CUE_EXPERIMENT=modules
> cd $WORK/modules-enabled
$WORK/modules-enabled
> exec cue mod init mod.com
> cmp cue.mod/module.cue cue.mod_module.cue.golden
> env CUE_EXPERIMENT=
> cd $WORK/modules-not-enabled
$WORK/modules-not-enabled
> exec cue mod init mod.com
> cmp cue.mod/module.cue cue.mod_module.cue.golden
--- cue.mod/module.cue
+++ cue.mod_module.cue.golden
@@ -1,4 +1,4 @@
-module: "mod.com@v0"
+module: "mod.com"
 language: {
        version: "v0.8.0-rc.1"
 }

FAIL: /tmp/testscript199697189/repro.txtar/script.txtar:9: cue.mod/module.cue and cue.mod_module.cue.golden differ
```

**Comment by mvdan** [comment]
🤦‍♂️ I missed the "Fixes" in https://review.gerrithub.io/c/cue-lang/cue/+/1183394, totally my bad.
