### ISSUE TITLE
cuelang.org: index of pages to ease content creation during local development

### ISSUE THREAD

**Issue by jpluscplusm** [cue-lang/cue#2946]
### What page were you looking at?

https://alpha.cuelang.org/

### What version of the site were you looking at?

https://github.com/cue-lang/cuelang.org/commit/a1fd3fbd65583183fbd604199b8a6c02a6c62165

### What did you do?

In https://cuelang.org/cl/1178814 we plan to move the howto, tutorial and concept guide section pages to be search-based, removing the unwieldy index from the end of their respective section pages.

We would still like that index in local development mode, as it's useful when creating content, but I couldn't achieve that easily in the above CL.  

### What did you expect?

A page, e.g. `/docs/{howto,tutorial,concept}/-dev-index/` that serves an index of that content type's docs.

### What did you see instead?

n/a.

**Comment by myitcv** [comment]
Can we not leverage the existing drafts mechanism for this?

**Comment by jpluscplusm** [comment]
> Can we not leverage the existing drafts mechanism for this?

Not as far as I can see. The index-capable page **exists** (it's `/docs/howto/`, or equivalent), so it can't be a draft. But it only gets the auto-generated index of sub-pages by dint of being those sub-pages' parent - a characteristic I can't assign to another page, at least with my current Hugo skills.
