### ISSUE TITLE
mod: ignore files with "ignore" tags

### ISSUE THREAD

**Issue by rogpeppe** [cue-lang/cue#2962]
Currently there is no way of excluding a file from consideration from
the dependency analysis run by `cue mod tidy` other than by placing
inside an excluded directory such as `.foo`.

It might be good for `cue mod tidy` to check file-level build tags and
exclude files with an "ignore" tag, mirroring Go's behavior in this
respect.

**Comment by myitcv** [comment]
I think you're referring to the `@if` attribute in `cue help injection` here. That is not a tag. Please can you sketch what a solution would look like?

**Comment by rogpeppe** [comment]
> I think you're referring to the `@if` attribute in `cue help injection` here. That is not a tag. Please can you sketch what a solution would look like?

The `@if` attribute selects files based on the values of tags. To quote the `@if` help from `cue help injection`:

> The expression is a subset of CUE consisting only of identifiers
> and the operators &&, ||, !, where identifiers refer to tags
> defined by the user on the command line.

The logic in `cue mod tidy` that evaluates all dependencies does not currently look at `@if` attributes
or tags at all. It should probably do so (and exclude files that have `@if` attributes that require the `ignore` tag).

**Comment by myitcv** [comment]
So the proposal here is that to ignore a file we use the `@if` build attribute with the ignore tag? 

```
@if(ignore)

x: 5
```

**Comment by rogpeppe** [comment]
Yes. Actually, not quite, because I believe file-level attributes only apply when there's a package clause, so the correct phrasing would be:

```
@if(ignore)

package foo

x: 5
```

**Comment by rogpeppe** [comment]
One interesting question here is whether CUE files without a package directive _should_ have their dependencies considered by `cue mod tidy`. Should they really be considered as "part" of the module in that sense?

**Comment by myitcv** [comment]
> Should they really be considered as "part" of the module in that sense?

When evaluating such a file, is `cue.mod/module.cue` used to resolve the dependencies? I believe the answer is yes, and thus I think the answer to your question should also be yes.

**Comment by myitcv** [comment]
@rogpeppe - has the change to ignore `@if(ignore)` files been made already along with the recent changes to fix consideration of `@if` and `_test.cue` files in dependencies?

**Comment by rogpeppe** [comment]
> @rogpeppe - has the change to ignore `@if(ignore)` files been made already along with the recent changes to fix consideration of `@if` and `_test.cue` files in dependencies?

No, it had not.

But after online discussion, we've gone with a separate `@ignore()` attribute for this functionality. See https://cuelang.org/cl/1198249
