### ISSUE TITLE
`cue get go` renders time.Duration with invalid CUE

### ISSUE THREAD

**Issue by gdvalle** [cue-lang/cue#2969]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.8.0

go version go1.22.1
      -buildmode exe
       -compiler gc
        -ldflags -extldflags -static
  DefaultGODEBUG httplaxcontentlength=1,httpmuxgo121=1,tls10server=1,tlsrsakex=1,tlsunsafeekm=1
     CGO_ENABLED 0
          GOARCH amd64
            GOOS linux
         GOAMD64 v1
             vcs git
    vcs.revision 7d757419377e66b0aa7bc7a6d68b6b6801214bd3
        vcs.time 2024-03-15T12:04:18Z
    vcs.modified false

</pre>

### Does this issue reproduce with the latest stable release?
Yes

### What did you do?
Here's a txtar with a failing test, with what I believe to be the correct output.
```
# Test for go get issue with time.Duration returning invalid numerics.
#
# cue get go
exec cue get go --local ./...
cmp ./pkg1/file1_go_gen.cue ./pkg1/file1_go_gen.cue.golden

# Verify dependencies did not change
cmp go.mod go.mod.golden

-- go.mod --
module mod.test

go 1.21
-- go.mod.golden --
module mod.test

go 1.21
-- cue.mod/module.cue --
module: "mod.test"
-- pkg1/file1.go --
package pkg1

import "time"

const (
	Time1Second = time.Duration(time.Second)
)
-- pkg1/file1_go_gen.cue.golden --
// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go mod.test/pkg1

package pkg1

import "time"

Time1Second: time.Duration & "1000000000ns"
```

### What did you expect to see?
The `time.#Duration` to be properly referenced as `time.Duration`.
The duration represented as a valid string, not an invalid numeric.
Also the proper unit suffixed (ns).

### What did you see instead?
A numeric for the time, and an invalid `time.#Duration` reference.

```
❯ diff pkg1/file1_go_gen.cue pkg1/file1_go_gen.cue.golden 
9c9
< #Time1Second: time.#Duration & 1000000000
---
> Time1Second: time.Duration & "1000000000ns"
```

**Comment by mvdan** [comment]
Thank you for filing this issue. There is some logic that tries to parse the expression and turn it into a CUE value, but it's rather basic, and it clearly does not deal with duration values properly - as they are nanosecond integers on the Go side, but they need to be strings with a unit on the CUE side, as you point out.

**Comment by seh** [comment]
Related precedent:
- #1453
- #648

**Comment by rogpeppe** [comment]
A related question is: if one wishes to specify durations as strings (corresponding to CUE's `time.Duration` constraint), what would be a good way to describe that in the Go from which the CUE is generated? Ideally the Go code would have direct access to the Go `time.Duration` value.
