### ISSUE TITLE
cuelang.org: not enough distinction between terminal and code blocks

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#2975]
### What page were you looking at?

https://cuelang.org/docs/tutorial/working-with-a-custom-module-registry/

### What version of the site were you looking at?

https://github.com/cue-lang/cuelang.org/commit/389843e899185f5765828377aec36a2c2c827e89

### What did you do?

Visited the above page

### What did you expect?

A clear distinction between terminal and code blocks

### What did you see instead?

A terminal block:

![Screenshot 2024-03-21 at 08 49 11](https://github.com/cue-lang/cue/assets/3374574/b36da6ee-5173-47d6-afca-9da638f11e80)

A code block:

![Screenshot 2024-03-21 at 08 49 20](https://github.com/cue-lang/cue/assets/3374574/965b11c6-65e4-427d-b5f0-5c2c1421047d)

"At a glance" the headers of these two blocks look very similar. Such that a `TERMINAL` block could easily be confused as being a file, or vice-versa. 

Perhaps we can use a subtle emoji as the prefix to both to help with the distinction?

cc @mvdan

**Comment by mvdan** [comment]
For some more context, as I looked at one of Paul's new tutorials, my brain was learning to ignore the "terminal" headers as they were repetitive. Once we got to a file, I couldn't even see the filename, because I was still ignoring the headers - given that they look so similar.

**Comment by jpluscplusm** [comment]
Related: https://github.com/cue-lang/cue/issues/2935

**Comment by JorindeUsMedia** [comment]
@jpluscplusm By adding type=terminal to the codeblock it should show a lightblue background. See https://cuelang.org/examples/basic/code-block/

**Comment by jpluscplusm** [comment]
We already use `type=terminal` for our `code` blocks; I've now added this to the `script` blocks' output: https://cl-1197693-4--cue-cls.netlify.app/docs/concept/how-cue-works-with-go/#converting-go-types-to-cue

I'm not sure that it distinguishes them /enough/, but now we've got it in both script and code blocks perhaps we could look at changing the background & foreground colours for terminals, and differentiating them more starkly. Light text on dark background, maybe?

**Comment by JorindeUsMedia** [comment]
Maybe something like this @jpluscplusm ? 

![Screenshot from 2024-07-19 12-11-51](https://github.com/user-attachments/assets/7dbe16c6-69b9-406f-a0a0-043d5262047e)

or

![Screenshot from 2024-07-19 12-14-55](https://github.com/user-attachments/assets/6fd0ad3d-15c2-4cb8-9acd-8a07351342bd)

**Comment by jpluscplusm** [comment]
@JorindeUsMedia I /think/ there's a loss of contrast with both of those, such that a11y would be negatively affected. I am definitely no expert in that area, but I do notice when lowered contrast makes things harder for me to read!

I wonder how a pitch black background would look against the same font colour as the dark example, but where the font were bold(er).

**Comment by JorindeUsMedia** [comment]
@jpluscplusm See image: I tried the darkest blue we have. We're using shades of blue and grey-blue everywhere so using black would not fit in the color scheme / branding of the site.
![Screenshot from 2024-07-22 10-01-57](https://github.com/user-attachments/assets/5ce937a1-a910-4bc6-bfcf-e2ccd562f683)

**Comment by myitcv** [comment]
Is there anything further to do here now, given that we've made a change to https://cuelang.org/docs/tutorial/publishing-modules-to-the-central-registry/? The terminal blocks are grey-ish. That's not perfect, but perhaps good enough for now.

**Comment by mvdan** [comment]
I'd like slightly more contrast/difference with file blocks, but otherwise I'm fine with that page as-is. Between the white background and the line numbers, it's much clearer now that file blocks are different than terminal blocks.

**Comment by jpluscplusm** [comment]
@myitcv Whilst I'd like to see the site rendered with the darkest blue terminal background (@JorindeUsMedia's most recent comment), I won't ask them to spend any time on that change.

**Comment by myitcv** [comment]
> @myitcv Whilst I'd like to see the site rendered with the darkest blue terminal background (@JorindeUsMedia's most recent comment), I won't ask them to spend any time on that change.

To my mind that shifts us more towards a dark mode; which I would like to leave for now.

**Comment by mvdan** [comment]
Yeah I had a similar thought. I avoid "dark modes" on my laptop these days as they make it harder for me to read text without my glasses. So I'd definitely prefer black text on light background in the light mode.

**Comment by jpluscplusm** [comment]
Closed following https://cuelang.org/cl/1197693.

We can re-open later if the blocks still need to be differentiated further.
