### ISSUE TITLE
List comprehensions cannot begin with a let declaration

### ISSUE THREAD

**Issue by jpluscplusm** [cue-lang/cue#2986]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.8.0

go version go1.22.1
      -buildmode exe
       -compiler gc
       -trimpath true
     CGO_ENABLED 0
          GOARCH amd64
            GOOS linux
         GOAMD64 v1

</pre>

### Does this issue reproduce with the latest stable release?

Yes, 0.8.0

### What did you do?

I tried to start a list comprehension with a `let` declaration, which failed.
Both other elements of a comprehension (`for` & `if`) can begin a list comprehension.

```
exec cue fmt startsWithFor.cue
exec cue fmt startsWithIf.cue
exec cue fmt startsWithLet.cue
-- startsWithFor.cue --
[
	for i in [1, 2, 3]
	let x = 1
	if 6 > 5 {
		x
	},
]
-- startsWithIf.cue --
[
	if 6 > 5
	for i in [1, 2, 3]
	let x = 1 {
		x
	},
]
-- startsWithLet.cue --
[
	let x = 1
	if 6 > 5
	for i in [1, 2, 3] {
		x
	},
]
``` 

I couldn't find any issues mentioning this, either as an issue or as a feature request. I can see from the spec that **aliases** inside a list aren't yet supported, but this felt distinct.

### What did you expect to see?

A passing test.

### What did you see instead?

```
> exec cue fmt startsWithFor.cue
> exec cue fmt startsWithIf.cue
> exec cue fmt startsWithLet.cue
[stderr]
missing ',' in list literal:
    ./startsWithLet.cue:2:6
missing ',' in list literal:
    ./startsWithLet.cue:7:3
[exit status 1]
FAIL: /tmp/testscript1085439904/listComprehensions.txtar/script.txtar:3: unexpected command failure
```

**Comment by rogpeppe** [comment]
One awkwardness with allowing this is that ACAICS it would change the meaning of some existing code, because a `let` statement is valid in itself and creates a scope that covers the enclosing statements, whereas the scope of a `let` statement within a comprehension is only within the subexpression.

Here are few examples to demonstrate the issue:

```
// succeeds with:
//	example0: {
//		b: 5
//		a: 5
//	}
// The meaning of this would change if let counted as a comprehension.
example0: {
	let x = 5
	{
		a: x
	}
	b: x
}

// succeeds with:
//example2: {
//	p: [5, 5]
// }
// This illustrates the fact that the scope of a regular let
// statement encompasses all the fields in that struct literal.
example2: {
	let x = y
	let y = 5
	p: [x, y]
}

// fails with:
// example3: reference "y" not found
// Here we can see that it's different for let
// statements inside comprehensions.
example3: {
	if 5 > 3
	let x = y
	let y = 5
	{
		p: [x, y]
	}
}

```

**Comment by jpluscplusm** [comment]
This is explicitly outlined in the spec, at https://cuelang.org/docs/reference/spec/#comprehensions

> Comprehensions [...] must start with a for or if clause.

My confusion arose from the fact that this is a valid form inside a struct but not a list:

```CUE
x: [1, 2, 3]
y: {
	let X = [for i in x {i * i}]
	for i in X
	if i >= 2 {
		"\(i)": i
	}
}
```

The root of my confusion was from the fact that (I believe!) the `let` doesn't bind solely to the comprehension's scope, but is available throughout the surrounding `y` struct. In other words, the fact that this *looks* like a 3-clause comprehension is a red herring, and it's actually a 2-clause comprehension where there also happens to be a let declaration in scope.

I recall that there was an underlying use case which I didn't articulate in the original comment, but I don't have it to hand at the moment. It was related to doing a non-trivial amount of work once, and then iterating over the result of the work in a list comprehension. I.e. as with my example above, but where `X` needed to be calculated inside `y` which was a list. I'll open a different issue when I come across the concrete use case again.

**Comment by myitcv** [comment]
Noting in passing that the existence of let declarations and let clauses (to give them their name from the spec) creates the following "niceness":

```
example3: {
    let x = 5
	if 5 > 3
	let y = 5
	{
		p: [x, y]
	}
}
```

**Comment by myitcv** [comment]
I've picked up on my last comment in https://github.com/cue-lang/cue/issues/3537
