### ISSUE TITLE
cuelang.org: preprocessor: upload block should handle multiple files, with an optional #location tag

### ISSUE THREAD

**Issue by jpluscplusm** [cue-lang/cue#2991]
### What page were you looking at?

https://cuelang.org/

### What version of the site were you looking at?

https://github.com/cue-lang/cuelang.org/commit/3953c5f0db191ef4bde57d5851d3ce67ac7ef45f

### What did you do?

I'm writing a guide that needs to upload several files before using them in a multi-step script. For Reasons, I need to perform the upload several times with slightly modified files each time (but will switch to an assertion-based mechanism proposed in #2798 when it's available). 

### What did you expect?

I would like an `upload` block to support the upload of multiple files, and to support a `#location` tag which works as the `code` block `#location` tag currently does.

One possible source form would be this:

```
{{{with upload "en" "multiple files"}}}
#location left left right
-- file1.cue --
x: 1
-- file2.cue --
y: 2
-- file3.cue --
z: 3
{{{end}}}
```

IMHO their default rendering, if a `#location` tag isn't given, should be as follows:
- 1 file: current `upload` rendering
- 2 files: render the same as this `code` block:
   ```
   {{{with code "en" "test"}}}
   #location left right
   exec true
   -- file.cue --
   x: 1
   -- file2.cue --
   y: 2
   {{{end}}}
   ```
   ![image](https://github.com/cue-lang/cue/assets/224508/55575ec1-323a-4aa2-8e09-274d60e3c21b)
- 3+ files: place all files on the left hand side, as per this `code` block:
   ```
   {{{with code "en" "test"}}}
   #location left left left
   exec true
   -- file.cue --
   x: 1
   -- file2.cue --
   y: 2
   -- file3.cue --
   z: 3
   {{{end}}}
   ```
   ![image](https://github.com/cue-lang/cue/assets/224508/9e5dbcb7-c756-4219-bad6-2660b3655a00)

### What did you see instead?

I currently have to use multiple `upload` blocks in an n-wide `columns` setup, which wastes horizontal space with their inter-block spacing, and doesn't allow for placing files in the same code-tab position.

As mentioned above, it would be useful if this feature were compatible with anything that comes out of #2798.

**Comment by myitcv** [comment]
@jpluscplusm it's helpful in these situations if you can sketch out what the `upload` block (in this case) would look like. e.g.

```
{{{with upload "en" "upload"}}}
#location left left left
exec true
-- file.cue --
x: 1
-- file2.cue --
y: 2
-- file3.cue --
z: 3
{{{end}}}
```

It's perhaps obvious in this case, but worth doing so for the avoidance of doubt/possible misinterpretation/etc.

**Comment by jpluscplusm** [comment]
> it's helpful in these situations if you can sketch out what the `upload` block (in this case) would look like.

👍 Added.

**Comment by myitcv** [comment]
This is blocked on https://github.com/cue-lang/cue/issues/3005

**Comment by jpluscplusm** [comment]
Multiple upload files (with location blocks) are a soft requirement for the correct form of the "How CUE enables boilerplate removal" guide to land: https://cuelang.org/cl/1183487. The page currently uses `code` blocks, which don't allow cross-step consistency to be assured, but do render a reasonably concise page. Using `upload` and `script` blocks before multi-file uploads are implemented will either require fiddly, manual column-based layouts to be maintained at each step (cf. the page's initial 3x "app" CUE files), or will elongate the page.

**Comment by jpluscplusm** [comment]
@myitcv This feels close-able to me. Is there anything left in "multiple file uploads" that means it should stay open?

**Comment by myitcv** [comment]
Agreed. I think we're done here.
