### ISSUE TITLE
cuelang.org: frontend: playground id parameter not dropped when example selected

### ISSUE THREAD

**Issue by jpluscplusm** [cue-lang/cue#2994]
### What page were you looking at?

https://cuelang.org/play/?id=eVdbhSP1QnG&example=test-example#w=function&i=cue&f=eval&o=cue
### What version of the site were you looking at?

https://github.com/cue-lang/cuelang.org/commit/3953c5f0db191ef4bde57d5851d3ce67ac7ef45f

### What did you do?

I simulated a new user:
- clicking some link to a shared CUE snippet in the playground
- wanting to learn more
- using the Examples menu to select an enticing example

### What did you expect?

Selecting an example from the examples menu should load the example, no matter how the user arrived at the page.

### What did you see instead?

The page reloaded, but the saved CUE snippet remained in the editor.

**Comment by myitcv** [comment]
I've updated the title to reflect my understanding of the problem: specifically, that when selecting an example, the `id` parameter should be dropped from the URL.

**Comment by JorindeUsMedia** [comment]
When clicking on example the ID should be dropped from the url.  This should be changed in `playground/src/components/examples-menu.tsx` in the updateUrl function.
estimate: 15-30 min

When for some reason both are still present in the url after this fix (an already shared url in the community channels for instance?)  ID wins from the Example parameter. @myitcv Is this correct? or should example win from id ?

**Comment by JorindeUsMedia** [comment]
Discussed previous comment: ID wins in that case but we do need to remove the example param from the url
