### ISSUE TITLE
cuelang.org: frontend: info, warning and caution blocks cannot be placed inside steps

### ISSUE THREAD

**Issue by jpluscplusm** [cue-lang/cue#3002]
### What page were you looking at?

https://cuelang.org/

### What version of the site were you looking at?

https://github.com/cue-lang/cuelang.org/commit/46b75884c677fdc1c2e974bed2017d15ca20362c

### What did you do?

I tried to place a `caution` block inside a `step` block:

```
{{{with step}}}
Initialize the directory as a module.
{{< caution >}}
foo
{{< /caution >}}
{{{end}}}
```

The preprocessor transforms this into:

```
{{< step stepNumber="3" >}}
Initialize the directory as a module.
{{< caution >}}
foo
{{< /caution >}}
{{< /step >}}
```

### What did you expect?

That a caution (or warning or info) block would be rendered as an element inside the step block.

### What did you see instead?

The warning text was exposed as HTML

![image](https://github.com/cue-lang/cue/assets/224508/0cc3447b-5731-40fa-823e-1815af194d9b)

**Comment by myitcv** [comment]
See also https://github.com/cue-lang/cue/issues/3005

**Comment by myitcv** [comment]
Confirmed working (by hand) as of https://review.gerrithub.io/c/cue-lang/cuelang.org/+/1195633

**Comment by myitcv** [comment]
Fixed via https://review.gerrithub.io/c/cue-lang/cuelang.org/+/1195633
