### ISSUE TITLE
cuelang.org: CUE version that defines the spec is not linked to the site's CUE version

### ISSUE THREAD

**Issue by jpluscplusm** [cue-lang/cue#3013]
### What page were you looking at?

https://cuelang.org/docs/reference/spec/

### What version of the site were you looking at?

https://github.com/cue-lang/cuelang.org/commit/0f80600d1d2083d1e94276c13b532b71171ae12f

### What did you do?

I tried to document where and what versions of CUE are encoded  in the `cue-lang/cuelang.org` repo; and what effects their upgrades have. In doing so I was reminded that:

- The version of CUE that the site uses is constrained by `site.cue`.
- The version of the spec that is published at https://cuelang.org/docs/reference/spec/ is constrained by the version of CUE selected by `go.mod`, which is upgraded manually through running `go get cuelang.org/go@latest` (or similar) whilst inside `cue-lang/cuelang.org`.

### What did you expect?

That upgrading the version of CUE that the site uses should automatically pull in the spec from the upgraded version of CUE.

### What did you see instead?

The published spec (*harmlessly*) doesn't include the trivial changes merged in 7ed1bcaa253fc9111fd61ee3713da11b1f2e464a.

**Comment by myitcv** [comment]
This should follow an approach similar to https://review.gerrithub.io/c/cue-lang/cuelang.org/+/1194099. `genspec` could be updated to create a temporary module from which the spec details are copied. We don't need a separate module for this dependency.
