### ISSUE TITLE
CUE should not calculate indentation from nested objects

### ISSUE THREAD

**Issue by uhthomas** [cue-lang/cue#3015]
### What version of CUE are you using (`cue version`)?

<pre>
❯ cue version
cue version 0.7.0

go version go1.21.5
      -buildmode pie
       -compiler gc
       -trimpath true
  DefaultGODEBUG panicnil=1
     CGO_ENABLED 1
          GOARCH amd64
            GOOS linux
         GOAMD64 v1
</pre>

### Does this issue reproduce with the latest stable release?

Yes

### What did you do?

```cue
let probe = {
    httpGet: {
        path: "/status"
        port: "http"
    }
}

livenessProbe:  probe
readinessProbe: probe & {failureThreshold: 12}
```

### What did you expect to see?

![image](https://github.com/cue-lang/cue/assets/9749173/dc817435-a6fa-4a2d-8a0d-6a16e35d9463)

### What did you see instead?

![image](https://github.com/cue-lang/cue/assets/9749173/ec6cbd5f-2fc5-4b92-9e0b-62750a5e182a)

**Comment by NoamTD** [comment]
To simplify the reproduction steps a bit, we can use:

```
exec cue fmt input.cue
cmp input.cue expected-output.cue

-- input.cue --
first: probe
second: a & {field: 1}
-- expected-output.cue --
first: probe
second: a & {field: 1}
```

Expect: passing test
Got: failing test

```shell
╰─❯ ts repr.txtar                                                                                                                                                       ─╯
> exec cue fmt input.cue
> cmp input.cue expected-output.cue
diff input.cue expected-output.cue
--- input.cue
+++ expected-output.cue
@@ -1,2 +1,2 @@
-first:              probe
+first: probe
 second: a & {field: 1}

FAIL: /var/folders/xj/q6k0bchn5414yzgryc_m1hgw0000gn/T/testscript4032321700/repr.txtar/script.txtar:2: input.cue and expected-output.cue differ
error running repr.txtar in /var/folders/xj/q6k0bchn5414yzgryc_m1hgw0000gn/T/testscript4032321700/repr.txtar
```

**Comment by NoamTD** [comment]
I only managed to reproduce this in the case of a binary expression, where the second element is a struct, and the entire struct is defined on the same line
