### ISSUE TITLE
cmd/cue: mod init does not permit paths that contain capital letters

### ISSUE THREAD

**Issue by jpluscplusm** [cue-lang/cue#3021]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.8.1

go version go1.22.1
      -buildmode exe
       -compiler gc
       -trimpath true
     CGO_ENABLED 0
          GOARCH amd64
            GOOS linux
         GOAMD64 v1

</pre>

### Does this issue reproduce with the latest stable release?

Yes, 0.8.1.

### What did you do?

```
exec cue mod init github.com/SomeUsername
```

### What did you expect to see?

Nothing, indicating a successfully initialised CUE module. Note that `CUE_EXPERIMENT=modules` is **not** set, and therefore the requirement mentioned in https://cuelang.org/docs/reference/modules/ *feels* like it shouldn't apply:

> No characters are allowed in the path except lower case ASCII letters, ASCII digits, and limited ASCII punctuation

### What did you see instead?

```
> exec cue mod init github.com/SomeUsername
[stderr]
invalid module name "github.com/SomeUsername": non-conforming path "github.com/SomeUsername"
[exit status 1]
FAIL: /tmp/testscript3664076240/cue.mod.init.DislikesCapitalLetters.txtar/script.txtar:1: unexpected command failure
```

**Comment by mvdan** [comment]
Is this a significant issue or blocker for you or for a project that you know? It does seem like a minor breakage of existing modules users who haven't opted into the experiment, but given that we are about to start enabling the experiment by default soon, I'm not sure that it's worth spending the time to resolve this edge case. cc @myitcv

**Comment by myitcv** [comment]
> but given that we are about to start enabling the experiment by default soon, I'm not sure that it's worth spending the time to resolve this edge case. cc @myitcv

Agreed. On that basis I think we can close this issue.
