### ISSUE TITLE
cuelang.org: wrong value in example

### ISSUE THREAD

**Issue by davidgamba-au** [cue-lang/cue#3023]
### What page were you looking at?

https://cuelang.org/docs/concept/how-cue-enables-configuration/

### What version of the site were you looking at?

https://github.com/cue-lang/cuelang.org/commit/742eb9333a39b4a54626494656a9ce1db6321515

### What did you do?

The docs say the `values.yaml` should have a value of 768, the example values.yaml file has 3072.

### What did you see instead?

![image](https://github.com/cue-lang/cue/assets/112971423/a80e004f-366f-4b80-9222-71981fdd32a4)

**Comment by jpluscplusm** [comment]
Thanks for raising this, @davidgamba-au.

I believe the *values* are technically correct, but we can do a better job of clarifying that the "developer" updated a value (`replicas`) which caused a policy violation in a *derived* field (`replicaMem`).

I've opened https://cuelang.org/cl/1193139 to address this, and I'd be grateful for your feedback as to if you think this *would* have made it clear enough on first reading! The rendered form of the page is at https://cl-1193139-1--cue-cls.netlify.app/docs/concept/how-cue-enables-configuration/.

**Comment by DavidGamba** [comment]
Much clearer, during my first read I didn't even really noticed that the `replicaMem` was a calculated/derived value.
