### ISSUE TITLE
cmd/cue: add mod edit to support tooling-based updates of module.cue file

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#3028]
**Is your feature request related to a problem? Please describe.**

As part of implementing a solution to https://github.com/cue-lang/cue/issues/2992, we now require the presence of a `source` field when running `cue mod publish`. Whilst later versions of CUE might add heuristics/default behaviour, this field is required. Therefore we should add some means of setting a value for this field in such a way that does not require reverting to `cat <<EOD > module.cue` or similar.

**Describe the solution you'd like**

As above, a tooling-oriented way of making changes to `cue.mod/module.cue`, in the style perhaps of `go mod edit`.

**Describe alternatives you've considered**

Nothing good. Per above `cat <<EOD > module.cue` and friends, or "make this change by hand". None of which are really in the spirit of CUE.

**Additional context**

n/a

**Comment by mvdan** [comment]
This was implemented in https://review.gerrithub.io/c/cue-lang/cue/+/1193116, and is indeed being released as part of v0.9.0-alpha.3.
