### ISSUE TITLE
modules: parse module.cue according to language version

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#3035]
(Edit by @rogpeppe)

In order to accommodate future schema changes in the module.cue file,
and to allow the use of a closed schema to catch spelling errors, when
parsing a module.cue file, we should first inspect the `language.version`
field, then use that to decide what schema and semantics to use.

This allows arbitrary schema changes in the future, although we will
maintain backward compatibility when possible.

**Comment by rogpeppe** [comment]
Closed by https://cuelang.org/cl/1193275

**Comment by myitcv** [comment]
Given the previous message I suspect you meant to close this issue.
