### ISSUE TITLE
cuelang.org: CUE syntax highlighting fails on attributes

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#3040]
### What page were you looking at?

https://cuelang.org/docs/integration/protobuf/

### What version of the site were you looking at?

https://github.com/cue-lang/cuelang.org/commit/11094806ff902554f50fd7928d64e5a3039711d8

### What did you do?

Visited the above page.

### What did you expect?

CUE code to be well-formatted

### What did you see instead?

The `@` in an attribute is rendered as an error:

![Screenshot 2024-04-17 at 16 58 20](https://github.com/cue-lang/cue/assets/3374574/cc9ff9c8-9efc-4345-80b2-434cc3261f5b)

**Comment by myitcv** [comment]
This is addressed in https://github.com/alecthomas/chroma/pull/961

**Comment by jpluscplusm** [comment]
https://github.com/alecthomas/chroma/pull/961 is present in Hugo versions from `v0.128.0` onwards. The site currently uses `v0.128.2`, therefore I'm closing this issue as resolved. (Also demonstrated by reviewing https://cuelang.org/docs/concept/how-cue-works-with-protocol-buffers/ and seeing the attributes highlighted correctly).
