### ISSUE TITLE
evaluator: validation not working for arrays in nested structs?

### ISSUE THREAD

**Issue by richardpeng** [cue-lang/cue#3042]
### What version of CUE are you using (`cue version`)?

Web version v0.8.0: https://cuelang.org/play/?id=mY9l8fX1ZXQ#w=function&i=cue&f=eval&o=cue

### What did you do?

```
#foo: =~"^foo"
#nesting: string | {name?: #foo, [string]: #nesting} | [...#nesting]

data: #nesting & {
    secret: {
        infra: [
            {
                name: "bar1"
            }
        ]
    }
    infra2: [
        {
            name: "bar1"
        }
    ]
}
```

Trying to validate the `name` field in a deeply nested struct: `data.secret.infra[0].name`. Validation works for `data.infra2[0].name`

### What did you expect to see?

This type of error for `data.secret.infra[0].name`:
```
data: 2 errors in empty disjunction:
data: conflicting values [...#nesting] and {secret:{infra:[{name:"bar1"}]},infra2:[{name:"bar1"}]} (mismatched types list and struct):
    -:2:56
    -:4:18
data: conflicting values string and {secret:{infra:[{name:"bar1"}]},infra2:[{name:"bar1"}]} (mismatched types string and struct):
    -:2:11
    -:4:18
```

### What did you see instead?

No validation errors

**Comment by myitcv** [comment]
I suspect the "right" thing is happening here, just that we are not surfacing the (right) error (at all). 

Paging @mpvl because my usual means of inspecting the internal form of the errors has changed with the landing of work for the new evaluator. 

My suspicion is that something along the following lines is happening:

* The field `name` constraint is violated can "caught" as an error
* This in turn causes the `{...}` element of the `#nesting` disjunction to be eliminated
* This in turn causes the mismatch in type error that we see reported

**Comment by richardpeng** [comment]
Sorry, my example is confusing. I'm expecting an error for this, but not getting one:
```
#foo: =~"^foo"
#nesting: string | {name?: #foo, [string]: #nesting} | [...#nesting]

data: #nesting & {
    secret: {
        infra: [
            {
                name: "bar1"
            }
        ]
    }
}
```

In fact, I'm even getting a concrete value:

```
❯ cue export test.cue 
{
    "data": {
        "secret": {
            "infra": [
                {
                    "name": "bar1"
                }
            ]
        }
    }
}
```

**Comment by myitcv** [comment]
Interesting. That does indeed just look like a straight bug. Again, paging @mpvl

**Comment by mvdan** [comment]
Thanks for raising this - reduced from a Slack thread. Once the new evaluator experiment is all in master we should check whether it still has the same bug, and if not, add a regression test.

**Comment by richardpeng** [comment]
This seems to be fixed in the latest version using the new evaluator!

```
cue version v0.9.0-alpha.3

go version go1.21.4
      -buildmode exe
       -compiler gc
     CGO_ENABLED 1
          GOARCH arm64
            GOOS darwin
```

**Comment by mvdan** [comment]
Excellent, thanks @richardpeng! Please keep this issue open because I want to track adding a regression test to the repository, to ensure it stays fixed.
