### ISSUE TITLE
cuelang.org: search treats underscores differently from other characters

### ISSUE THREAD

**Issue by jpluscplusm** [cue-lang/cue#3051]
### What page were you looking at?

https://cuelang.org/search/?q=CUE_DEBUG_TOOLS_FLOW

### What version of the site were you looking at?

https://github.com/cue-lang/cuelang.org/commit/d77b7dcdfe387dba98ea36c9005a5f33ca09cdba

### What did you do?

I searched for a environment variable that contains internal underscores.

### What did you expect?

That the search page would return pages referencing that environment variable; or no pages at all. 

### What did you see instead?

The search tokenisation seems to treat underscores as *actual* word separators. Or, at the very least, it does something to match against the `CUE_` that's present on both the pages it finds.

I suspect we want to teach search to treat underscores as just another character.

![image](https://github.com/cue-lang/cue/assets/224508/68bff045-7302-438d-9d93-9dcc1df008d3)

**Comment by myitcv** [comment]
This feels like an Algolia configuration issue.
