### ISSUE TITLE
cuelang.org: visiting an anchor/section should hide the floating header

### ISSUE THREAD

**Issue by mvdan** [cue-lang/cue#3058]
### What page were you looking at?

https://cuelang.org/docs/concept/modules-packages-instances/#instances

### What version of the site were you looking at?

https://github.com/cue-lang/cuelang.org/commit/47796448e1dfc31c188db061f7d785ee94df4fa8

### What did you do?

Navigate to the "instances" section with the link above via a new browser tab.

### What did you expect?

To be able to read the section, for example:
![image](https://github.com/cue-lang/cue/assets/3576549/57ec0367-c232-4e33-a8ac-8359faf9edd5)

### What did you see instead?

Not much!
![image](https://github.com/cue-lang/cue/assets/3576549/d351d5dd-b044-403e-a837-a32c545c450b)

**Comment by mvdan** [comment]
I realise that the header disappears and reappears as I scroll, but it should definitely default to being hidden if I navigate to any part of the page that isn't the very top.

The very same issue happens if I navigate to the page without an anchor, scroll halfway down the page (hiding the header), and refresh with Ctrl+R. The header reappears, hiding a good chunk of the visible text.

**Comment by mvdan** [comment]
One more thought: right now the header reappears as soon as I scroll up by a single pixel. I reckon it should take a little bit more than that, because otherwise it reappears extremely easily - for example, when I scroll down with my fingers, sometimes I'm not perfect and I scroll up by a few pixels at the start or end, due to the nature of how my fingers move. This can make the header re-appear when I don't want it to, causing a bit of frustration as it eats into my reading space.

**Comment by jpluscplusm** [comment]
@mvdan Please could you check if this issue's headline problem still strikes and, if so, using which browser?

Either way, I think we should use this issue to track the later point:

> One more thought: right now the header reappears as soon as I scroll up by a single pixel. I reckon it should take a little bit more than that

... as that's definitely still a problem.

**Comment by JorindeUsMedia** [comment]
It seems the scrolling to anchor has not been picked up by the listener that should hide the header on scroll down. 
In #2971 I also fixed an issue related to anchor links so it could be this is related and maybe fixed by this.

> One more thought: right now the header reappears as soon as I scroll up by a single pixel. I reckon it should take a little bit more than that, because otherwise it reappears extremely easily - for example, when I scroll down with my fingers, sometimes I'm not perfect and I scroll up by a few pixels at the start or end, due to the nature of how my fingers move. This can make the header re-appear when I don't want it to, causing a bit of frustration as it eats into my reading space.

We can add some logic that will show the header on scroll up after x pixels are scrolled (100 or so?) Let's create a separate issue for that.  @mvdan @jpluscplusm
