### ISSUE TITLE
cuelang.org: preprocessor: allow non-prose blocks (script/upload/code) to be indented

### ISSUE THREAD

**Issue by jpluscplusm** [cue-lang/cue#3059]
### What page were you looking at?

https://cl-1190655-8--cue-cls.netlify.app/docs/concept/how-cue-works-with-go/

### What version of the site were you looking at?

https://github.com/cue-lang/cuelang.org/commit/714c395ca605475d32adbbd5ccd9d0d23438e8a0

### What did you do?

In https://review.gerrithub.io/c/cue-lang/cuelang.org/+/1190655/comment/05705208_f74fe0d1/ @mvdan identified that their review was slightly hampered by the co-mingling of prose and non-prose, and that one way to distinguish them might be to indent the preprocessor's blocks. I tried doing this, but wasn't able to for a variety of reasons.

### What did you expect?

That this would render successfully, as if the indentation weren't present:

```markdown
## Some heading

This is some prose

   {{{with upload "en" "file"}}}
   -- some.cue --
   x: 1
   y: 2
   {{{end}}}

   {{{with script "en" "export"}}}
   cue export some.cue
   {{{end}}}

This is some more prose.
```

### What did you see instead?

Indents of 4 or more spaces were interpreted as markdown code blocks.
Indents of 3 or fewer spaces (e.g. the example above) failed due to:
- the script block was reformatted, unindenting the `{{{end}}}` and adding a blank line at the end of the script 
- the upload block's files weren't recognised as such, as the `--` filename marker prefix wasn't discovered at the start of a line

**Comment by myitcv** [comment]
This would involve a non-trivial amount of work. 

FWIW, I tend to review the rendered version (reminder of the `Preview-Path` trailer which results in a "special" TryBot result with hyperlinks to the previews), and then only comment in the source file.

**Comment by jpluscplusm** [comment]
@myitcv's point that primary review can be via the rendered site preview, only falling back to source when needed, makes this issue moot, mostly. Closing it for now; we can re-open as needed.
