### ISSUE TITLE
evaluator: enable use of new evaluator via the Go API

### ISSUE THREAD

**Issue by mvdan** [cue-lang/cue#3060]
This is a placeholder issue for providing a means of enabling the new evaluator via the Go API.

It is a follow-up to https://github.com/cue-lang/cue/issues/2884, as well as https://github.com/cue-lang/cue/issues/2886, which already exposes the experiment to cmd/cue via $CUE_EXPERIMENT.

The new evaluator is not be enabled by default: an uncontrolled flip from one evaluator to another would be an incredibly risky and unnecessary move. Just like some users are already enabling the experiment via e.g. `CUE_EXPERIMENT=evalv3 cue export`, we should expose a way for Go API users to opt into it as well.

My intuition is that we would add something to pass to https://pkg.go.dev/cuelang.org/go/cue/cuecontext#New, for example a `cuecontext.Option` to select a particular evaluator version, so that we can also reuse it for future versions we might need. When the option isn't given, we would continue with the current default.

**Comment by mvdan** [comment]
Spoke briefly with @mpvl about this today. This task is not as simple as I thought, as it is more than just threading an option through between the cuecontext and internal evaluator packages. A number of the public APIs that use internal APIs, such as in the `cue` package, may need tweaking so that they continue to work as intended with the new evaluator, as it works quite differently due to structure sharing.

We still intend to get to this soon. With Marcel we agreed that he would get to this after finishing the current batch of fixes already in progress, as he's working on bits of code relating to structure sharing.

**Comment by jeffmccune** [comment]
Since this is one of the top Google search results and linked from the bottom of #2886, at your convenience could you drop a summary or link to how to enable the new evaluator in the Go API?  I've been poking around for awhile but haven't figured it out yet.

**Comment by mvdan** [comment]
Of course; you can swap

    ctx := cuecontext.New()

with

    ctx := cuecontext.New(cuecontext.EvaluatorVersion(cuecontext.EvalV3))
