### ISSUE TITLE
using list concatenate operator causes non-concrete value error

### ISSUE THREAD

**Issue by networkhermit** [cue-lang/cue#3112]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version 0.8.1

go version go1.22.2
      -buildmode pie
       -compiler gc
       -trimpath true
  DefaultGODEBUG httplaxcontentlength=1,httpmuxgo121=1,tls10server=1,tlsrsakex=1,tlsunsafeekm=1
     CGO_ENABLED 1
          GOARCH amd64
            GOOS linux
         GOAMD64 v1
</pre>

### Does this issue reproduce with the latest stable release?

Yes.

### What did you do?

1. copy the following code to test_tool.cue

```cue
package main

import (
	"list"
	"tool/cli"
	"tool/exec"
)

ask: cli.Ask & {
	prompt:   "What's your name?"
	response: string
}

command: test1: exec.Run & {
	{cmd: ["echo"] + [ask.response]}
}

command: test2: exec.Run & {
	{cmd: list.Concat([["echo"], [ask.response]])}// works
}

command: test3: exec.Run & {
	{cmd: "echo " + ask.response}// works
}
```

2. run `cue cmd test1`

### What did you expect to see?

```text
What's your name?
```

### What did you see instead?

```text
command.test1.cmd.1: non-concrete value string:
    ./test_tool.cue:11:12
```

**Comment by mvdan** [comment]
Given that we plan to phase out list arithmetic in favor of `list.Concat` soon (https://github.com/cue-lang/cue/issues/2237), and seeing how `list.Concat` works well in your example, I suspect this might not be worth attempting to fix.

**Comment by mvdan** [comment]
I'm going to close this issue per my reasoning above. We plan to remove arithmetic on lists in v0.11.
