### ISSUE TITLE
cmd/cue: evaluation commands (excluding import) drop Yaml comments

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#3115]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.0.0-20240501134849-612f1aed155f

go version go1.22.1
      -buildmode exe
       -compiler gc
  DefaultGODEBUG httplaxcontentlength=1,httpmuxgo121=1,tls10server=1,tlsrsakex=1,tlsunsafeekm=1
     CGO_ENABLED 1
          GOARCH arm64
            GOOS linux
             vcs git
    vcs.revision 612f1aed155f8198f58a068d6286dcf31d339b21
        vcs.time 2024-05-01T13:48:49Z
    vcs.modified false
cue.lang.version v0.9.0
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
# Import
exec cue import x.yml

# Let's just ignore the fmt bug
cmp x.cue x.cue.golden

# Export
exec cue export --out cue x.yml
cmp stdout x.cue.golden

-- x.yml --
# this is a test
x: 5
-- x.cue.golden --
	// this is a test
x: 5
```

### What did you expect to see?

Passing test (just look past the `fmt`-related issue)

### What did you see instead?

```
# Import (0.013s)
# Let's just ignore the fmt bug (0.000s)
# Export (0.011s)
> exec cue export --out cue x.yml
[stdout]
x: 5
> cmp stdout x.cue.golden
--- stdout
+++ x.cue.golden
@@ -1,1 +1,2 @@
+       // this is a test
 x: 5

FAIL: /tmp/testscript911939675/repro.txtar/script.txtar:9: stdout and x.cue.golden differ
```

i.e. the `cue export` does not match the behaviour of `cue import`: Yaml comments are dropped via `cue export`.

**Comment by mvdan** [comment]
This testscript passes today as of c683420c0797090a1445b453e3318a4570fc4742:

```
# Import
exec cue import x.yml

# Let's just ignore the fmt bug
cmp x.cue x.cue.golden

# Export
exec cue export --out cue x.yml
cmp stdout x.cue.golden

-- x.yml --
# this is a test
x: 5
-- x.cue.golden --
// this is a test
x: 5
```

The fmt bug aside, it seems like the YAML bug was fixed by https://review.gerrithub.io/c/cue-lang/cue/+/1196291, so https://github.com/cue-lang/cue/issues/3214 was filed as a near duplicate. I'm satisfied with the added test case in that commit, so I think we can close this as resolved as well.
