### ISSUE TITLE
cmd/cue: mod edit should support setting language.version

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#3136]
Currently, as of `v0.9.0-alpha.4`, `cue mod edit` provides functionality for editing requirements, the source field and the module field, but not the language version.

It should do so. Strawman interface:

```
cue mod edit --language.version=v0.9.0
```

We could also support upgrading the version to the current version language version with:

```
cue mod edit --language.version=current
```

This would fail like other `cue mod edit` commands if there is no language version already present,
as the syntax of the file is predicated on that.

**Comment by rogpeppe** [comment]
Duplicate of #2920
