### ISSUE TITLE
cmd/cue: the directory tree structure of the modules cache is inconsistent

### ISSUE THREAD

**Issue by mvdan** [cue-lang/cue#3139]
After cleaning my entire `~/.cache/cue` and running `cue mod tidy` on a module which depends on another module, I see:

```
$ find .cache/cue -type f
.cache/cue/cache/download/github.com/mvdan/test-repo/@v/v0.0.11.lock
.cache/cue/cache/download/github.com/mvdan/test-repo/@v/v0.0.11.zip
.cache/cue/cache/download/github.com/mvdan/test-repo/@v/v0.0.11.mod
.cache/cue/github.com/mvdan/test-repo@v0.0.11/cue.mod/module.cue
.cache/cue/github.com/mvdan/test-repo@v0.0.11/foo.cue
```

* `~/.cache/cue/cache/download` is unnecessarily repetitive; we should not insert a "cache" directory inside... CUE's cache directory.
* The unzipped modules are extracted straight inside CUE's cache directory, causing namespace issues for future kinds of caches we might want to use.

My thinking is that we should use `${CUE_CACHE_DIR}/mod/download/${modpath}` for downloaded artifacts (e.g. zip files), and `${CUE_CACHE_DIR}/mod/extract/${modpath}` for the contents of extracted archives. This way they are nicely grouped together, and there is some hierarchy that describes their contents as well.

**Comment by myitcv** [comment]
> My thinking is that we should use `${CUE_CACHE_DIR}/mod/download/${modpath}` for downloaded artifacts (e.g. zip files), and `${CUE_CACHE_DIR}/mod/extract/${modpath}` for the contents of extracted archives. This way they are nicely grouped together, and there is some hierarchy that describes their contents as well.

This sounds good to me.
