### ISSUE TITLE
cuelang.org: preprocessor: scripts/serve.bash usually fails to serve updated content

### ISSUE THREAD

**Issue by jpluscplusm** [cue-lang/cue#3166]
### What page were you looking at?

https://cuelang.org/

### What version of the site were you looking at?

https://github.com/cue-lang/cuelang.org/commit/9adb346c4051adcbb933db4ba9bcf5a31c1acc8b

### What did you do?

I ran `_scripts/serve.bash`, and waited for the site to be served at http://localhost:1313.

I updated some prose source (i.e. not code-related) inside the `content/` hierarchy. 

### What did you expect?

I expected that, when the locally served page refreshed itself, its rendered form would always reflect the updated source.

### What did you see instead?

At least half the time I follow this process, the on-page content doesn't reflect the updated source in `content/`. The `hugo` process emits debug output that says "Change detected, rebuilding site", and the rendered page refreshes itself automatically (as expected), but the rendered content matches what was present when `scripts/serve.bash` was initially invoked. 

To fix this, I have to rerun `_scripts/serve.bash` until the behaviour changes.

For each run (and rerun), the behaviour is internally consistent: if the changes aren't reflected on-page, they never will be. If the changes **are** reflected, then the process is in a good working state until the next time I stop it for some reason.

The "wrong" behaviour kicks in somewhat more than 50% of the time. I'm unable to find a consistent trigger, but it's easy to observe happening, several times each editing session.

I've recorded a screen capture video of the problem striking. (Note that the wall clock timings experienced in the video are over an order of magnitude slower than when I'm **not** performing a screen capture - my machine doesn't seem to enjoy recording video!). The video is a split screen of a terminal on the left, and http://localhost:1313 on the right, to demonstrate the problem in action.

Video timings:

- 00:00 - context (current tip of master; script recording of `script/serve.bash` output (attached to this issue)).
- 00:25 - running `script/serve.bash` for the first time; the problem **does** strike this invocation.
- 01:00 - the site is being served.
- 01:08 - making a change to `content/docs/_en.md`.
- 01:23 - the favicon on the browser window flickers, indicating that Hugo has prompted a page reload after a content update. The rendered page **doesn't** reflect the amended content.
- 01:27 - making a second change to the same source page.
- 01:37 - the page reloads again.
- 01:42 - restarting the script.
- 02:18 - the site is being served; the page is reloaded manually.
- (to the end) - changes in the markdown source are reflected in reloads of the site, though due to the slow site render speed they get out of "sync". This is *not* the issue being reported here, and isn't in effect in normal (non-screen-captured) operation.

**Comment by myitcv** [comment]
Per offline chat, this feels like a hugo issue. And perhaps upgrading Hugo will fix the issue.

**Comment by jpluscplusm** [comment]
I've upgraded from Hugo 0.124.0 to 0.126.1, which appears on first glance to have resolved the issue. I'll close this if the problem doesn't strike again over the next few hours.

**Comment by myitcv** [comment]
I think you can close this issue regardless, because the updated file was (per your offline comment) being written to the `hugo` directory structure. As such, if there is an issue here, it's almost certainly a Hugo issue.
