### ISSUE TITLE
cue/load: special '_' package name incorrectly allowed in import path

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#3167]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.0.0-20240522152506-a6a7002b7bc6

go version go1.22.3
      -buildmode exe
       -compiler gc
  DefaultGODEBUG httplaxcontentlength=1,httpmuxgo121=1,tls10server=1,tlsrsakex=1,tlsunsafeekm=1
     CGO_ENABLED 1
          GOARCH arm64
            GOOS linux
             vcs git
    vcs.revision a6a7002b7bc688fd6d4f37b9273cd88a605085db
        vcs.time 2024-05-22T15:25:06Z
    vcs.modified false
cue.lang.version v0.9.0
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
! exec cue export .
stderr 'invalid import path'

-- cue.mod/module.cue --
module: "mod.example@v0"
language: {
	version: "v0.9.0"
}
-- p/p.cue --
5
-- x.cue --
package x

import something "mod.example/p:_"

x: something
```

### What did you expect to see?

Passing test.

### What did you see instead?

```
> ! exec cue export .
[stdout]
{
    "x": 5
}
FAIL: /tmp/testscript4046662259/repro.txtar/script.txtar:1: unexpected command success
```

i.e. the import `"mod.example/p:_"` is valid.

Firstly it's not clear to me we should support this. It unnecessarily creates another edge case when it comes to loading CUE. Adding CUE files to a package should not be problematic, and if it is we need to know why.

Related (give that this "trick" can be used to import JSON) is #2031. Again, a more explicit (and flexible) approach is a better approach, hence dropping support for `:_` in favour of #2031 is a side effect we should be happy to accept.

Although phrases as a bug report, this issue is in effect a proposal to drop support for `:_` from import paths.

**Comment by myitcv** [comment]
Noting that the documentation for [`cue/load.Config`](https://pkg.go.dev/cuelang.org/go/cue/load#Config) says the following:

```
	// Package defines the name of the package to be loaded. If this is not set,
	// the package must be uniquely defined from its context. Special values:
	//    _    load files without a package
	//    *    load all packages. Files without packages are loaded
	//         in the _ package.
	Package string
```

Note that this issue does not propose making any changes to `cue/load`. So `_` would continue to work as a special value for the `Package` field. That's because `cue/load` is a much more general purpose CUE loader. This issue is limited to dropping the support for `:_` appearing in an import path.

**Comment by mvdan** [comment]
I think this could be a case where we transition away from having this accidental feature via CUE_EXPERIMENT, e.g. to give users one or two release cycles where they can opt back into the old behavior.
