### ISSUE TITLE
The cue struct tag isn't registered on the Go "well-known struct tags" wiki page

### ISSUE THREAD

**Issue by jpluscplusm** [cue-lang/cue#3169]
**Is your feature request related to a problem? Please describe.**

I noticed that https://go.dev/wiki/Well-known-struct-tags exists, but the `cue` tag used by [cuego](https://pkg.go.dev/cuelang.org/go/cuego#section-documentation) isn't mentioned on that page.

**Describe the solution you'd like**

Someone CUE-related who meets the requirements listed on that wiki page could propose a change to the page that adds an entry reserving/registering the `cue` tag. The requirements are:

> List entries can be added by anyone who creates a public package where a new tag is used. 

**Describe alternatives you've considered**

n/a

**Additional context**

n/a

**Comment by myitcv** [comment]
@mvdan - seems reasonable to me, thoughts?

**Comment by mvdan** [comment]
Sure - I don't think there is a need to track this here, you can just send a patch directly to that wiki page. Or if you prefer not to, I can.

**Comment by jpluscplusm** [comment]
> you can just send a patch directly to that wiki page

If that "you" means me, I don't think I meet the requirement of being a package creator.

**Comment by mvdan** [comment]
Ah, I hadn't noticed that was a requirement. Sure, I'll send a patch, I guess I sort of qualify :)

**Comment by mvdan** [comment]
https://go-review.googlesource.com/c/wiki/+/587895

**Comment by mvdan** [comment]
Merged.
