### ISSUE TITLE
encoding/jsonschema: decode of oneof with non-trivial constraints results in incorrect schema

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#3176]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.0.0-20240524053519-927c5037cebc

go version go1.22.3
      -buildmode exe
       -compiler gc
  DefaultGODEBUG httplaxcontentlength=1,httpmuxgo121=1,tls10server=1,tlsrsakex=1,tlsunsafeekm=1
     CGO_ENABLED 1
          GOARCH arm64
            GOOS linux
             vcs git
    vcs.revision 927c5037cebc0d89fae9397f033c4f197262dca1
        vcs.time 2024-05-24T05:35:19Z
    vcs.modified true
cue.lang.version v0.9.0
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
# type-only oneof
exec cue import -p example -f -l '#schema:' jsonschema: schema_1.json
cmp schema_1.cue schema_1.cue.golden
exec cue vet vals.cue schema_1.cue

# non-trivial oneof including pattern constraint (which applies to string)
exec cue import -p example -f -l '#schema:' jsonschema: schema_2.json
cmp schema_2.cue schema_2.cue.golden
exec cue vet vals.cue schema_2.cue

-- schema_1.json --
{
	"properties": {
		"matrix": {
			"oneOf": [
				{
					"type": "object"
				},
				{
					"type": "string"
				}
			],
			"patternProperties": {
				"^(in|ex)clude$": {
					"type": "string"
				}
			}
		}
	},
	"type": "object"
}
-- schema_1.cue.golden --
package example

#schema: {
	matrix?: string | {
		{[=~"^(in|ex)clude$" & !~"^()$"]: string}
		...
	}
	...
}
-- schema_2.json --
{
	"properties": {
		"matrix": {
			"oneOf": [
				{
					"type": "object"
				},
				{
					"maxLength": 3,
					"type": "string"
				}
			],
			"patternProperties": {
				"^(in|ex)clude$": {
					"type": "string"
				}
			}
		}
	},
	"type": "object"
}
-- schema_2.cue.golden --
package example

import "strings"

#schema: {
	matrix?: ({
		...
	} | strings.MaxRunes(3)) & {
		{[=~"^(in|ex)clude$" & !~"^()$"]: string}
		...
	}
	...
}
-- vals.cue --
package example

examples?: [string]: #schema

examples: "string": matrix: "ok"
examples: "object": matrix: {
	include: "value"
}
```

### What did you expect to see?

Passing test.

### What did you see instead?

```
# type-only oneof (0.024s)
# non-trivial oneof including pattern constraint (which applies to string) (0.019s)
> exec cue import -p example -f -l '#schema:' jsonschema: schema_2.json
> cmp schema_2.cue schema_2.cue.golden
> exec cue vet vals.cue schema_2.cue
[stderr]
examples.string.matrix: 2 errors in empty disjunction:
examples.string.matrix: conflicting values "ok" and {...} (mismatched types string and struct):
    ./schema_2.cue:6:12
    ./vals.cue:3:22
    ./vals.cue:5:29
examples.string.matrix: conflicting values "ok" and {[(=~"^(in|ex)clude$" & !~"^()$")]:string} (mismatched types string and struct):
    ./schema_2.cue:9:3
    ./vals.cue:3:22
    ./vals.cue:5:29
[exit status 1]
FAIL: /tmp/testscript2082541543/repro.txtar/script.txtar:9: unexpected command failure
error running repro.txtar in /tmp/testscript2082541543/repro.txtar
```

The key here is the diff between the resulting CUE schemas:

```diff
--- schema_1.cue        2024-05-24 15:08:57.663273018 +0100
+++ schema_2.cue        2024-05-24 15:08:57.683272963 +0100
@@ -1,7 +1,11 @@
 package example

+import "strings"
+
 #schema: {
-       matrix?: string | {
+       matrix?: ({
+               ...
+       } | strings.MaxRunes(3)) & {
                {[=~"^(in|ex)clude$" & !~"^()$"]: string}
                ...
        }
```

In the case of schema 1, the constraint implied by the `patternProperties` applies only to the second elements of the disjunction, that is where the `matrix` field is an object.

In the case of schema 2, the `patternProperties` constraint applies to _both_ elements of the disjunction. This immediately eliminates the `string` type disjunct because those two constraints are not compatible. Hence the error message reported.

The relevant part of the JSON Schema spec here is https://json-schema.org/draft/2020-12/json-schema-core#name-assertions-and-instance-pri:

> Most assertions only constrain values within a certain primitive type. When the type of the instance is not of the type targeted by the keyword, the instance is considered to conform to the assertion.
>
> For example, the "maxLength" keyword from the companion [validation vocabulary](https://json-schema.org/draft/2020-12/json-schema-core#json-schema-validation) [[json-schema-validation](https://json-schema.org/draft/2020-12/json-schema-core#json-schema-validation)]: will only restrict certain strings (that are too long) from being valid. If the instance is a number, boolean, null, array, or object, then it is valid against this assertion.

(it goes on to give an important reason why this behaviour is specified in case multiple types are possible, which is equivalent to a simple type-based oneof as far as I can tell).

Hence, what CUE is doing in the case of schema 2 is wrong: it should only be applying the `patternProperties` constraints to the elements of the oneof (disjunction) which are type-appropriate. In this case the object type.

**Comment by rogpeppe** [comment]
The relevant part of the specification seems to be [here](https://json-schema.org/draft/2020-12/json-schema-core#section-7.6.1):
> Most assertions only constrain values within a certain primitive type. When the type of the instance is not of the type targeted by the keyword, the instance is considered to conform to the assertion.

This means that the logic currently in `encoding/jsonschema` is not correct, because it interprets a type-specific assertion as asserting the type of the instance, not just applying when the instance happens to be that type.
