### ISSUE TITLE
modules: move away from the term "main module"

### ISSUE THREAD

**Issue by mvdan** [cue-lang/cue#3181]
Go, where we derive much of our packages and modules design from, has historically used the term "main module" to refer to the module where one is running a Go command or build from. It is helpful to then refer to that main module's properties or dependencies, and to separate it from any other modules such as dependencies.

However, "main module" is problematic as it is quite similar to "main package", which is a very different concept, and unrelated to the current directory. That's why https://github.com/golang/go/issues/58830 was raised. I agree with "main module" being confusing as well.

They are moving to "work module", and I asked a question in that thread about the reasoning why. I'd also find "current module" to be a valid choice.

This mainly affects documentation (`cue help`, Go API docs, code comments, cuelang.org content) and error messages.

**Comment by rogpeppe** [comment]
Perhaps the confusion with "main package" is less of an issue for CUE, because CUE doesn't have the concept of a main package?

**Comment by mvdan** [comment]
That's a good point. Intuitively I still find "main module" to be easier to grasp than "work module", so I'm fine with keeping our naming as is, deciding against following Go's change here.

Closing for now but feel free to say if you disagree. I never had a strong opinion about this switch in the first place.
