### ISSUE TITLE
cuelang.org: deployments break when changes containing new pages aren't rebased on top of newer infra-related commits 

### ISSUE THREAD

**Issue by jpluscplusm** [cue-lang/cue#3188]
### What page were you looking at?

https://cuelang.org/

### What version of the site were you looking at?

https://github.com/cue-lang/cuelang.org/commit/721d221e53d9ff8aec0b78f348e330c2607ee094

### What did you do?

I submitted https://cuelang.org/cl/1195043 (which had green CI and no merge conflicts) and it failed to deploy cleanly. 

### What did you expect?

I expect that CLs that pass CI and have no merge conflicts can be submitted and will be deployed successfully.

### What did you see instead?

A deployment failure.

Gerrit gave me the all-clear because (a) CI passed and (b) Gerrit didn't believe there was a merge conflict. Whilst there wasn't a true merge conflict, the `gen_cache.cue` file generated on my machine matched the one in CI but *didn't* match the one that CI-on-master generated, mid-deployment.

This happened because I didn't rebase the CL on top of master, pre-submission; and master contained commits that updated infra-related components of the site's build process that form part of the `gen_cache.cue` cache key.

### What would you like to be done?

I'm not sure. I'm mostly opening this to track that it happened, and to give us something to explicitly close if the problem isn't deemed to be fixable.

**Comment by myitcv** [comment]
Given the current implementation of caching (where the cache is committed along with the pages) there is not a solution per se. We will always need to rebase before and after a change that changes the cache key. I'm going to close this issue on the basis we at least fail safe in both situations. 

A better solution would be to have a read only append remote cache that clients/users can share and contribute to. But that is another issue very much for another day.

**Comment by jpluscplusm** [comment]
@myitcv A potential fix for the specific "new `gen_cache.cue` file built with old infra components" problem popped into my head. I won't spend any time on it, but I thought I'd write it down for posterity ...

Each time the preprocessor is invoked:
- take the known set of infra components that, if modified, would result in every `gen_cache.cue` file being updated
- write them out, as both plain text and as a hash combining all their data, in a single, well-known location such as `content/gen_infra.cue`.

This way, there's a single file guaranteed to exist whose merge conflict *will* be caught by Gerrit, in the scenario that prompted me to open this issue.

The "both plain text and hashed" idea is so that the file contains useful, diff-able, info for the operator, whilst also containing an opaque hash that will conflict in a way that git can't attempt to automatically resolve.
