### ISSUE TITLE
cmd/cue: fmt -s removes quotes in keys when it shouldn't

### ISSUE THREAD

**Issue by vikstrous2** [cue-lang/cue#3189]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.9.0-rc.1

go version go1.22.1
      -buildmode exe
       -compiler gc
  DefaultGODEBUG httplaxcontentlength=1,httpmuxgo121=1,tls10server=1,tlsrsakex=1,tlsunsafeekm=1
     CGO_ENABLED 1
          GOARCH amd64
            GOOS linux
         GOAMD64 v1
cue.lang.version v0.9.0
</pre>

### Does this issue reproduce with the latest stable release?
no, but it's in the 0.9 RC

### What did you do?
I have the following code:
```cue
key: a: "value"
other: "key": k: key["a"]
```
Running `cue fmt -s` removed the quotes from `key` and changed it to:

```cue
key: a: "value"
other: key: k: key["a"]
```

### What did you expect to see?
No change from `go fmt -s`. Expected eval output:

```cue
key: {
    a: "value"
}
other: {
    key: {
        k: "value"
    }
}
```

### What did you see instead?
After evaling it, the behaviour changed and broke the config:
```
$ cue eval -c repro.cue 
other.key.k: undefined field: a:
    ./repro.cue:2:20
```

### Workaround

There's a workaround:

```
key: a: "value"
let alias = key
other: key: k: alias["a"]
```

**Comment by myitcv** [comment]
Tentatively marked as a release blocker for now until we can prove otherwise.
