### ISSUE TITLE
modules: create an FAQ for the common "upgrade problems"

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#3196]
Breaking this out from https://github.com/cue-lang/cue/issues/3127

There are a number of points to cover here:

* What is a major version suffix?
* What version of `language.version` should I set?
* When do I require a `source` field?
* ...

**Comment by mvdan** [comment]
Published at https://github.com/cue-lang/cue/wiki/FAQ:-Modules-and-v0.9.0, thank you @myitcv. I published your original draft as one revision (commit), then my tweaks as extra revisions afterwards. This way you can later review my changes and shout if you disagree with any of them.
