### ISSUE TITLE
cue/load: downcast cue.mod/module.cue so we can add more fields without breaking existing consumers

### ISSUE THREAD

**Issue by mvdan** [cue-lang/cue#3197]
Right now there are two types of scenarios where we read `cue.mod/module.cue` files:

1) When we need to consume packages, such as `cue/load.Instances` or `cue export .` - in this scenario, we only need to extract the information needed for the package loading and dependency resolution.

2) When we are doing some operation to develop, modify, or publish the current module, such as `cue mod tidy`, `cue mod edit`, or `cue mod publish` - in this scenario, we need to fully understand the entire contents of `module.cue`, as editing or publishing unknown module information is unsafe.

We do number 2 above correctly right now; trying to `cue mod tidy` or `cue mod publish` a module with an unknown field (such as a field that would be added by a future CUE version) results in an error.

However, in scenario 1 above, we still parse `module.cue` files requiring validation with a module file schema following `language.version`, which means that we are stricter than we really should be.

Take for example the matrix testscript below:

```
# Downstream user 1: on v0.8.2 with modules disabled by default.
# Failure A: cannot resolve any imports for the current module due to the major version suffix,
# which is okay, because a user on v0.8 can enable the modules experiment as shown below.
cd ${WORK}/v0.8.0-nomajor
exec cue-v0.8.2 export
stdout '"hello from v0.8.0-nomajor"'
cd ${WORK}/v0.9.0
! exec cue-v0.8.2 export
stderr 'cannot find package "mod.example/subpkg"'
cd ${WORK}/v0.9.0-source
! exec cue-v0.8.2 export
stderr 'cannot find package "mod.example/subpkg"'
cd ${WORK}/v0.10.0
! exec cue-v0.8.2 export
stderr 'cannot find package "mod.example/subpkg"'

# Downstream user 2: on v0.8.2 with modules enabled.
# Failure B: cannot load the unknown "source" field due to the closed schema,
# which appears wrong, because the source field does not change package loading in any way.
env CUE_EXPERIMENT=modules
cd ${WORK}/v0.8.0-nomajor
exec cue-v0.8.2 export
stdout '"hello from v0.8.0-nomajor"'
cd ${WORK}/v0.9.0
exec cue-v0.8.2 export
stdout '"hello from v0.9.0"'
cd ${WORK}/v0.9.0-source
! exec cue-v0.8.2 export
stderr 'source: field not allowed'
cd ${WORK}/v0.10.0
exec cue-v0.8.2 export
stdout '"hello from v0.10.0"'

# Downstream user 3: on v0.9.0 with modules enabled by default.
# Failure C: cannot load a language version v0.10.0 due to not having a schema for it,
# which we should not do with a schema version once it's split up from the language version.
cd ${WORK}/v0.8.0-nomajor
exec cue-v0.9.0-rc.1 export
stdout '"hello from v0.8.0-nomajor"'
cd ${WORK}/v0.9.0
exec cue-v0.9.0-rc.1 export
stdout '"hello from v0.9.0"'
cd ${WORK}/v0.9.0-source
exec cue-v0.9.0-rc.1 export
stdout '"hello from v0.9.0-source"'
cd ${WORK}/v0.10.0
! exec cue-v0.9.0-rc.1 export
stderr 'language version "v0.10.0" declared in module.cue is too new for current language version "v0.9.0"'

-- v0.8.0-nomajor/cue.mod/module.cue --
module: "mod.example"
language: version: "v0.8.0"
-- v0.8.0-nomajor/main.cue --
package main
import "mod.example/subpkg"
subpkg
-- v0.8.0-nomajor/subpkg/main.cue --
package subpkg
"hello from v0.8.0-nomajor"

-- v0.9.0/cue.mod/module.cue --
module: "mod.example@v0"
language: version: "v0.9.0"
-- v0.9.0/main.cue --
package main
import "mod.example/subpkg"
subpkg
-- v0.9.0/subpkg/main.cue --
package subpkg
"hello from v0.9.0"

-- v0.9.0-source/cue.mod/module.cue --
module: "mod.example@v0"
language: version: "v0.9.0"
source: kind: "git"
-- v0.9.0-source/main.cue --
package main
import "mod.example/subpkg"
subpkg
-- v0.9.0-source/subpkg/main.cue --
package subpkg
"hello from v0.9.0-source"

-- v0.10.0/cue.mod/module.cue --
module: "mod.example@v0"
language: version: "v0.10.0"
-- v0.10.0/main.cue --
package main
import "mod.example/subpkg"
subpkg
-- v0.10.0/subpkg/main.cue --
package subpkg
"hello from v0.10.0"
```

There are three "hard breaks" that are happened with the transition to modules:

Failure A - anyone wishing to publish a CUE module must add a major version suffix like `@v0` to `module`, which breaks CUE consumers on v0.7 or earlier, as well as v0.8 unless they set `CUE_EXPERIMENT=modules`.
Failure B - anyone wishing to publish a CUE module with `language.version` v0.9 or later must set `source.kind`, which breaks any CUE consumers on v0.8, as this field is disallowed in the closed schema introduced by v0.8.
Failure C - anyone publishing a CUE module with a newer schema version (currently the same thing as the language version, unfortunately) will break any consumers on CUE v0.9, as it cannot find a schema for that version.

Failure A is hard to resolve, because it would require us backporting some form of support for major version suffixes on paths when resolving imports.

Failure B is relatively easy to resolve, as we can "downcast" `module.cue` values to only extract the fields needed for import resolution, such as `module` and `deps`.

Failure C we should be able to resolve with the downcasting above, plus splitting of `language.version` into a schema version, so that one can use newer `module.cue` schemas without also requiring a new `language.version`. See https://github.com/cue-lang/cue/issues/3145.

**Comment by rogpeppe** [comment]
ISTM that this proposed "downcasting" approach is similar to the approach that Go historically took with regard
to interpreting modules with newer language versions. Go would optimistically try to interpret the newer
code, and fail with a "language version is too new" error only if the compilation failed.

Go moved away from that approach and I'm not entirely sure that it's appropriate for CUE either.

To quote the issue description above:

> we can "downcast" `module.cue` values to only extract the fields needed for import resolution, such as `module` and `deps`.

This seems to assume that in the future, `module` and `deps` will remain the only fields that are relevant to import resolution.
For one, this assumes that we will not wish to rename those fields or change their meaning.
For another, it assumes that we won't add more fields inside `deps`, for example, that influence dependency resolution.

My opinion is that I think we should reserve the right to make changes that break the above assumptions.
One specific feature that has been talked about is the ability to specify "dependency islands". At least
some of the proposed designs involve changing the meaning of the deps field to allow different forms of dependency
to be specified. For example, there's the possibility of specifying dependencies with a non-numeric major
version, something that would likely result in hard-to understand errors if using an old version of the parser
to interpret the file.

In other words, at least for now, I think we should have a hard requirement that an old version of CUE cannot
interpret modules marked with a newer version of CUE. This does not preclude moving towards a more
lax stance in the future, but leaves our options open.

That said, this does lead to thoughts about whether it would be useful to be able to [specify the language version
independently of the module schema version](https://github.com/cue-lang/cue/issues/3145#issuecomment-2114378021).
Might that help matters? I suspect not, as in practice the current evaluator ties together both module schema
and language versions into a single executable, so the actual acceptable version is limited to that version,
regardless of whether module schema version and language version can be specified independently of one another.

One argument _for_ splitting language version and schema version is if it's important to be able to specify an older
language or schema version when using a newer evaluator. That may well turn out to be an important requirement,
but hopefully that need can be mitigated by providing ways to automatically "fix" code to migrate it to a newer version.
If such fixes are provided and the older functionality is still available in the newer version, albeit in different form,
then the user should always have the capability to update both versions at the same time.

**Comment by mvdan** [comment]
As discussed recently with you and Paul, we only reached the conclusion of downcasting because we forgot that Go stopped doing it recently. And with your point about dependency islands likely needing to change how dependencies are declared and loaded soon, dropping that option seems fine to me.

Can you please refer back to the failure scenarios A, B, and C I listed above and share what you think the behavior should be? Because those are the three scenarios that I believe broke as part of the transition to the new modules behavior, and I want to be on the same page in terms of what we think are acceptable breakages or limitations of the new system.

For example, from what you said, here is my understanding:
* Failure A - we still require a major version suffix to publish new modules, so this is still a break for old CUE loaders. I think we're OK with this as we want to fully move away from published modules without a major version suffix.
* Failure B - we now assume `language.version` to be a hard minimum, like Go's `go` directive, so this breaks by design.
* Failure C - publishing a module with a newer schema version (either as `language.version` or as a separate field like `schemaVersion`) will also act as a hard minimum, given that the loader expects to fully understand the schema version.

C is what worries me most here - if v0.10 were to add a new schema field which is optional for loading, such as `source.metadata`, I would have to bump the schema version to v0.10 to declare it for publishing to the registry. But that would necessarily break any CUE loaders or users on v0.9. So I effectively cannot use the new field until I'm happy to bump the minimum version required to load the CUE module.

So if my understanding above is right, yes, decoupling the schema version from the language version does not make sense if bumping either of them has the same effect - bumping the hard minimum version required to load or evaluate the module. But that in itself seems rather unfortunate to me - if we add new schema fields that don't affect loading, such as my example above, most module publishers won't start making use of them for multiple months until they can be confident enough that all of their users have upgraded.

**Comment by rogpeppe** [comment]
> C is what worries me most here - if v0.10 were to add a new schema field which is optional for loading, such as `source.metadata`, I would have to bump the schema version to v0.10 to declare it for publishing to the registry. But that would necessarily break any CUE loaders or users on v0.9. So I effectively cannot use the new field until I'm happy to bump the minimum version required to load the CUE module.

Yup.  I can't think of any way to distinguish "new field that doesn't influence semantics at all" from "new field that _does_ influence semantics", unless we just preemptively add support for metadata (or other name for "informational-only field").

So my take is that this is unfortunate but just a fact of life, for now at least.

So I'll close this as "not planned".
