### ISSUE TITLE
NaN.0 showing up as evaluation of math.Acos(1.1)

### ISSUE THREAD

**Issue by gisle** [cue-lang/cue#3199]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.8.2

go version go1.22.2
      -buildmode exe
       -compiler gc
       -trimpath true
     CGO_ENABLED 0
          GOARCH arm64
            GOOS darwin

</pre>

### Does this issue reproduce with the latest stable release?

I belive that's the version I have.

### What did you do?

I ran `cue eval -e "math.Acos(1.1)" - </dev/null` and saw that the output was:

> NaN.0

### What did you expect to see?

From reading the spec it appears that Cue the language does not have the concept of `NaN` and `Infinity` values for floats.  It means that it need to handle expressions that generate `NaN` or `Infinity` in some other way, like signaling an error.

Other other expressions that generate such values that I tried seems to give me an error, for instance:

```
$ cue eval -e "0.0 / 0.0" - </dev/null
failed arithmetic: division undefined:
    --expression:1:1
```

### What did you see instead?

> NaN.0

Which is not valid cue code at all.

**Comment by mvdan** [comment]
See https://github.com/cue-lang/cue/issues/3168; I'm going to close this as a duplicate but please feel free to add more cases or examples as comments under that issue.
