### ISSUE TITLE
cue/load: regression on `load.Instances()` with unrelated error message

### ISSUE THREAD

**Issue by AntoineThebaud** [cue-lang/cue#3213]
### What version of CUE are you using (`cue version`)?

cuelang.org/go v0.9.0

### Does this issue reproduce with the latest stable release?

It appeared with it. The issue didn't exist in the [v0.9.0-alpha.5](https://github.com/cue-lang/cue/releases/tag/v0.9.0-alpha.5) we were using before.

### What did you do?

I have the two following files under the same folder:

**gauge.cue**
```cue
package model

import (
	"github.com/perses/perses/cue/schemas/common"
)

kind: "GaugeChart"
spec: close({
	calculation: common.#calculation
	format?:     common.#format
	thresholds?: common.#thresholds
	max?:        number
})
```

**migrate.cue**
```cue
if #panel.type != _|_ if #panel.type == "gauge" {
	kind: "GaugeChart"
	spec: {
		// transformation logic
	}
},
```

Then, at some point in my program, I'm using the Go API of Cue to process the content of the **model** package only:
```golang
buildInstances := load.Instances([]string{}, &load.Config{Dir: schemaPath, Package: "model"})
```
(just in case, full code available [here](https://github.com/perses/perses/blob/main/internal/api/schemas/loader.go#L76))

### What did you expect to see?

I expect the load.Instances() call to work, just like it was in v0.9.0-alpha.5 & prior.

### What did you see instead?

The first (& only as expected) build instance returned by load.Instances() reports an error:
```
import failed: [...]\\perses\\cue\\schemas\\panels\\gauge\\gauge.cue:17:2: no dependency found for package \"github.com/perses/perses/cue/schemas/common\"
```

The error message seems totally unrelated to the root cause here because if ever I delete the file migrate.cue that has no package clause (so that I expect to be ignored thanks to the provided load.Config), then the load.Instances() call works. Before latest release it was properly ignored.

**Comment by rogpeppe** [comment]
Thanks for the report! I've got a fix in the pipeline for this. If you need a workaround in the meantime, the following code should work and be equivalent to your current code:

```
buildInstances := load.Instances([]string{".:model"}, &load.Config{Dir: schemaPath})
```
