### ISSUE TITLE
Playground should support evaluating cue files with different releases and flags

### ISSUE THREAD

**Issue by infogulch** [cue-lang/cue#3216]
We should be able to evaluate a cue expression in the playground against different versions of cue. This would be especially useful for developing and sharing bug reports or test cases where the evaluation may have changed between versions, and it would prevent new releases from breaking old playground share links.

I would like to see:

1. Add a dropdown to the cue playground to select the release of cue to evaluate the expression. The list should include: the current stable release, some past major and minor releases, recent prereleases, and the most recent build of the master branch. The default should remain the current stable release.
2. New share links should include the cue version in the share link, and existing share links without a version should default to the current release as of the resolution of this feature.

The Go playground has this feature which makes it much more useful for sharing bug reproductions and comparing releases: https://go.dev/play/

**Comment by myitcv** [comment]
Completely agree. I think this request is fully covered by https://github.com/cue-lang/cue/issues/2538. Please shout if not.
