### ISSUE TITLE
mod/modfile: support missing major version suffix even in strict mode

### ISSUE THREAD

**Issue by rogpeppe** [cue-lang/cue#3217]
Currently `cue mod tidy` and `cue mod fix` always add a major version suffix to
the `module` field in `module.cue`. If there is not one already present, `@v0` is assumed.

This means that even if a module does not use any new language or module-related
features, it will still be incompatible with older CUE versions that will reject a module
path of this form, which isn't the case currently.

This enhancement should make migration to the new tooling smoother: simple
CUE code with no dependencies (or dependencies solely resident inside the `cue.mod` directory)
will be consumable by both old and new CUE versions.

This would be coupled with a change to `cue mod fix` and `cue mod tidy` to avoid
adding the `@v0` suffix unless it is already present. A possible variant of that
would be to avoid adding the suffix only if it's clear that no new module features
are being used (for example if the `module` field is the only one present in the `module.cue`
file), because that's arguably the only time that this forward-compatibility feature is actually useful.

**Comment by myitcv** [comment]
> This would be coupled with a change to `cue mod fix` and `cue mod tidy` to avoid
> adding the `@v0` suffix unless it is already present.

I'm struggling to parse this sentence :) If it's already present, there's nothing to add?
