### ISSUE TITLE
cmd/cue: mod fix and AcceptLegacyModules should use fixed language version

### ISSUE THREAD

**Issue by rogpeppe** [cue-lang/cue#3222]
As of commit 475f692480d697861fcaa4a608c29b5122d8a2f9, `cue mod fix`
uses the latest known language version when fixing legacy module files.

This is probably incorrect, at least in the future, because the CUE version used by such legacy
modules is likely to be an older version and so use older language features that
might be deprecated or altered by a newer language version.

To fix that, so we can always use some specific version (such as v0.9.0) when fixing such files.

**Comment by myitcv** [comment]
Marking as v0.10.0. Arguably we don't need to make this change until the first language change that would require a new `language.version`, but making the change to `cue mod fix` and the new `cue/load.Config` field

https://github.com/cue-lang/cue/blob/d8742c13dce6f5f02ff67740da2efe1f94a2ed0e/cue/load/config.go#L143

could happen sooner than that.
