### ISSUE TITLE
cuelang.org: playground: selected text isn't highlighted 

### ISSUE THREAD

**Issue by jpluscplusm** [cue-lang/cue#3239]
### What page were you looking at?

https://cuelang.org/play/

### What version of the site were you looking at?

https://github.com/cue-lang/cuelang.org/commit/202963fe570864693785d659fffec99373840600

### What did you do?

I selected some text inside a single line in the playground's editor.

### What did you expect?

I expected to be able to tell which characters I had selected. 

### What did you see instead?

In this example, I have selected some (but not all) of line 3:

![image](https://github.com/cue-lang/cue/assets/224508/ebefd2e0-fd88-4120-a2fb-b522dcdfb3c5)

**Comment by mvdan** [comment]
I can see the same - selecting text via Ctrl-A works, and selecting manually works but doesn't show in the UI.

**Comment by JorindeUsMedia** [comment]
Related issue: https://github.com/uiwjs/react-codemirror/issues/609
