### ISSUE TITLE
Type-checking values with disjunct defaults produces incorrect output

### ISSUE THREAD

**Issue by stouset** [cue-lang/cue#3250]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.9.1

go version go1.22.4
      -buildmode exe
       -compiler gc
       -trimpath true
  DefaultGODEBUG httplaxcontentlength=1,httpmuxgo121=1,tls10server=1,tlsrsakex=1,tlsunsafeekm=1
     CGO_ENABLED 1
          GOARCH arm64
            GOOS darwin
cue.lang.version v0.9.0
</pre>

### Does this issue reproduce with the latest stable release?

I haven't yet tested with cue v0.9.2, but nothing in the CHANGELOG indicates that this would be affected.

### What did you do?

```cue
foo: {
  a: false | *{}
  b: false | *{}
  c: false | *{}
}

foo: a: {}
foo: b: false

a_enabled: (foo.a & false) == _|_
b_enabled: (foo.b & false) == _|_
c_enabled: (foo.c & false) == _|_
```

### What did you expect to see?

```
foo: {
	a: {}
	b: false
	c: {}
}
a_enabled: true
b_enabled: false
c_enabled: true

```

### What did you see instead?

```
foo: {
	a: {}
	b: false
	c: {}
}
a_enabled: true
b_enabled: false
c_enabled: false # `foo.c & {}` should not be equal to `_|_`
```

**Comment by myitcv** [comment]
@stouset - my apologies, for some reason I totally missed this. Thanks for raising. If it's ok with you, I will close this in favour of https://github.com/cue-lang/cue/issues/3292, because I think that issue covers the positive and negative comparisons with `_|_`.

**Comment by mpvl** [comment]
A default is not "picked" by the `&` operator. So this behavior is according to the spec.
