### ISSUE TITLE
cuelang.org: an on-page search widget's most prominent/clickable real-time "auto-complete" links redirect to the general search page

### ISSUE THREAD

**Issue by jpluscplusm** [cue-lang/cue#3257]
### What page were you looking at?

https://cuelang.org/docs/concept/find-a-guide/

### What version of the site were you looking at?

https://github.com/cue-lang/cuelang.org/commit/fcdc044c24832b430ce066ba418dbe4d8e17d839

### What did you do?

Whilst testing if #2841 still strikes, I used the search widget on https://cuelang.org/docs/concept/find-a-guide/. I started typing "unification". When I was halfway through the word, the page looked like this:

![image](https://github.com/cue-lang/cue/assets/224508/989214dc-0583-4c61-afe6-789e5d5bc1de)

Notice the link at the top of the real-time, pop-up search results that purports to complete the word "unification" for me. 

### What did you expect?

I expected that if I clicked the finish-typing-the-word-for-me "unification" search link, then that would result in the same search view as if I finished typing "unification" myself, and hit enter. In other words, I expected that the URLs linked to by these finish-the-typing links would respect the page that I was already on, and would merely reload the current page with an additional `q` query string parameter.

### What did you see instead?

Clicking the "unification" link took me to https://cuelang.org/search/?q=unification, which not only removes the implicit content-type restrictions from my search query, but also navigates away from the page/hierarchy that I was reading.

**Comment by JorindeUsMedia** [comment]
This is probably also fixed with the same fix as  
https://github.com/cue-lang/cue/issues/2841
https://github.com/cue-lang/cuelang.org/pull/467

@jpluscplusm @myitcv Can you verify?

**Comment by jpluscplusm** [comment]
Confirmed as fixed by https://github.com/cue-lang/cuelang.org/pull/467
