### ISSUE TITLE
cue/interpreter/embed: decide how to treat imports in CUE files

### ISSUE THREAD

**Issue by rogpeppe** [cue-lang/cue#3258]
### What version of CUE are you using (`cue version`)?

<pre>
71eb3be5be97a916d1256a1e89107ffe1589cf39
</pre>

### Does this issue reproduce with the latest stable release?

N/A

### What did you do?

```
env CUE_EXPERIMENT=embed
exec cue eval
cmp stdout want-stdout
-- cue.mod/module.cue --
module: "module.example"
language: {
	version: "v0.10.0"
}
-- want-stdout --
x: {
    hello: 21345
}
-- main.cue --
@extern(embed)

package main

x: _ @embed(file=foo.cue)

-- foo.cue --
import "module.example/bar"

hello: bar.something

-- bar/bar.cue --
package bar

something: 21345
```

### What did you expect to see?

A passing test... maybe?

### What did you see instead?

```
> env CUE_EXPERIMENT=embed
> exec cue eval
[stderr]
@embed: package "module.example/bar" imported but not defined in :
    ./main.cue:5:6
```

In general embedded files are treated as if they were decoded by the regular CUE decoder.
In this case, the regular CUE decoder would interpret import directives as if they were situated
in the main module, so we might expect the `import "module.example/bar"` import to work.

On the other hand, perhaps embedded files should not ever participate in the main module's
dependency graph.

**Comment by myitcv** [comment]
My feeling/sense is that we disallow this day 1, only allowing CUE to be embedded as `text` or `bytes`.

**Comment by rogpeppe** [comment]
> My feeling/sense is that we disallow this day 1.

Yup, I tend to agree. Note: that will require a special case in the explanation/docs and in the code.

**Comment by mpvl** [comment]
I think we should importing cue file that are not part of a package.
