### ISSUE TITLE
cmd/cue: `cue mod init` should not create module.cue file with empty module path

### ISSUE THREAD

**Issue by rogpeppe** [cue-lang/cue#3260]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
v0.9.2
</pre>

### Does this issue reproduce with the latest stable release?

Yes

### What did you do?

```
! exec cue mod init
```

### What did you expect to see?

A passing test. Modules cannot have an empty module path, so either `cue mod init` should fail,
or it should choose an arbitrary path for the module (`test.example` ?).

### What did you see instead?

```
> ! exec cue mod init
FAIL: /tmp/x.txtar:1: unexpected command success
```

**Comment by jpluscplusm** [comment]
> or it should choose an arbitrary path for the module (`test.example` ?).

\<bikeshed>
`cue.example`
\</bikeshed>
