### ISSUE TITLE
cuelang.org: LHS input and RHS output do not allow horizontal scroll for long lines

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#3266]
### What page were you looking at?

https://cuelang.org/play/

### What version of the site were you looking at?

https://github.com/cue-lang/cuelang.org/commit/c151815c80d0686e318a724870f5a6ab9b831678

### What did you do?

* Visit https://cuelang.org/play/?id=sJAM4FCiz6n#w=function&i=cue&f=eval&o=cue
* Observe that line 1 is very long and needs horizontal scrolling to see the full contents on the LHS

### What did you expect?

The ability to scroll horizontally scroll in the LHS to see the full text of the line. The same should be possible in the RHS because this field outputs as a single line.

### What did you see instead?

No such ability. Instead I can only horizontally scroll the entire window.

**Comment by jpluscplusm** [comment]
Reproduced on Chrome(OS) v126.
