### ISSUE TITLE
cue/interpreter/embed: glob incorrectly handles directories

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#3267]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.0.0-20240703133932-f1f0963cb0f9

go version go1.22.3
      -buildmode exe
       -compiler gc
  DefaultGODEBUG httplaxcontentlength=1,httpmuxgo121=1,tls10server=1,tlsrsakex=1,tlsunsafeekm=1
     CGO_ENABLED 1
          GOARCH arm64
            GOOS linux
             vcs git
    vcs.revision f1f0963cb0f978020fc895202c50f40452da31b9
        vcs.time 2024-07-03T13:39:32Z
    vcs.modified false
cue.lang.version v0.10.0
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
env CUE_EXPERIMENT=embed

exec cue export x.cue
cmp stdout stdout.golden

-- dir/a.txt --
a.txt contents
-- dir/subdir/b.txt --
b.txt contents
-- x.cue --
@extern(embed)

package x

x: _ @embed(glob=dir/*, type=text)

-- stdout.golden --
{
    "x": {
        "dir/a.txt": "a.txt contents\n"
    }
}
```

### What did you expect to see?

Passing test.

### What did you see instead?

```
> env CUE_EXPERIMENT=embed
> exec cue export x.cue
[stderr]
@embed: cannot embed directories:
    ./x.cue:5:6
[exit status 1]
FAIL: /tmp/testscript557990626/repro.txtar/script.txtar:3: unexpected command failure
```

**Comment by mvdan** [comment]
I'm confused. Regular globbing is not meant to be recursive, so `dir/*` should match `dir/a.txt` and `dir/subdir` from your list of files above, and then possibly fail as it already does via "cannot embed directories". It would only be recursive or "globstar" globbing like `dir/**` which would also match `dir/subdir/b.txt`. Although note that it would still match `dir/subdir`, so perhaps you would want something like `dir/**/*.txt` or embedding the whole `dir` directory without globbing.

**Comment by myitcv** [comment]
Goodness, apologies. The expectation here is spectacularly wrong somehow. Adjusted in the original description. Thanks for spotting. There was in any case some overlap/muddling with https://github.com/cue-lang/cue/issues/3274 which I've also resolved.
