### ISSUE TITLE
cmd/cue: expand `cue help embed`

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#3268]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.0.0-20240703133932-f1f0963cb0f9

go version go1.22.3
      -buildmode exe
       -compiler gc
  DefaultGODEBUG httplaxcontentlength=1,httpmuxgo121=1,tls10server=1,tlsrsakex=1,tlsunsafeekm=1
     CGO_ENABLED 1
          GOARCH arm64
            GOOS linux
             vcs git
    vcs.revision f1f0963cb0f978020fc895202c50f40452da31b9
        vcs.time 2024-07-03T13:39:32Z
    vcs.modified false
cue.lang.version v0.10.0
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
cue help embed
```

### What did you expect to see?

Some help text about embedding.

### What did you see instead?

```
$ cue help embed
Unknown help topic: embed
```

**Comment by myitcv** [comment]
FYI @jpluscplusm

**Comment by mvdan** [comment]
Note that https://review.gerrithub.io/c/cue-lang/cue/+/1197335 added the skeleton here, so the page is no longer missing.
