### ISSUE TITLE
cue/interpreter/embed: glob with unspecified extension accepted as valid

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#3274]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.0.0-20240703133932-f1f0963cb0f9

go version go1.22.3
      -buildmode exe
       -compiler gc
  DefaultGODEBUG httplaxcontentlength=1,httpmuxgo121=1,tls10server=1,tlsrsakex=1,tlsunsafeekm=1
     CGO_ENABLED 1
          GOARCH arm64
            GOOS linux
             vcs git
    vcs.revision f1f0963cb0f978020fc895202c50f40452da31b9
        vcs.time 2024-07-03T13:39:32Z
    vcs.modified false
cue.lang.version v0.10.0
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
env CUE_EXPERIMENT=embed
! exec cue export x.cue
stderr 'extension not specified'

-- dir/a.txt --
This is a file
-- dir/b.json --
{
   "field" : "name"
}
-- x.cue --
@extern(embed)

package x

x: _ @embed(glob=dir/*.*)
```

### What did you expect to see?

Passing test (for some variation of the error message)

### What did you see instead?

```
> env CUE_EXPERIMENT=embed
> ! exec cue export x.cue
[stdout]
{
    "x": {
        "dir/a.txt": "This is a file\n",
        "dir/b.json": {
            "field": "name"
        }
    }
}
FAIL: /tmp/testscript3739177402/repro.txtar/script.txtar:2: unexpected command success
```

**Comment by mvdan** [comment]
Can you explain the reasoning behind an error? From a first look, the behavior on master seems reasonable.

**Comment by myitcv** [comment]
> Can you explain the reasoning behind an error? From a first look, the behavior on master seems reasonable.

Consistency with the initial design which says:

> All files must be of the same type, as identified by the extension. In case the extension is not fully specified (for example `@embed(glob=file.json*)`), the type needs to be explicitly specified.

An alternative (which we could relax to) is if all files identified by a glob pattern result in known file types then the type is not required.
