### ISSUE TITLE
cuelang.org: yellow pill on installation page appears to be a bit lost

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#3278]
### What page were you looking at?

https://cuelang.org/docs/introduction/installation/

### What version of the site were you looking at?

https://github.com/cue-lang/cuelang.org/commit/c465fca5c23f2b0a7d4a905dc80b646e761d3fcc

### What did you do?

Visited the above page.

### What did you expect?

A "clean" look to the top of the page.

### What did you see instead?

![Screenshot 2024-07-11 at 16 56 29](https://github.com/cue-lang/cue/assets/3374574/ba05426e-f7d5-43e4-aaa5-bde3f6ab3698)

That yellow pill on the RHS looks out of place to my eye. The alignment is off relative to the text on the LHS.

Perhaps we are after some sort of image here? If so, we can speak to Peter for some ideas on how to spice up this page (he had a number of ideas on the download page before)

For now at least I think we need to fix the slightly wonky appearance.

**Comment by jpluscplusm** [comment]
The intention was to use the [sidenote](https://cuelang.org/examples/shortcodes/sidenote/) UI element to highlight the installation-free nature of the playground, and to act as a small CTA, but it has a vertical offset that we can't modify in prose (currently).

If the element's offset doesn't seem right then we should probably consider deprecating the element entirely, or putting it through a design pass to find out how it could be made acceptable.

In this context, I've replaced the CTA with a cuelang.org-colour-aligned info block (incidentally using the `warning` block, for the colour match): https://cuelang.org/cl/1197643
