### ISSUE TITLE
docs: publish modules FAQ wiki to cuelang.org

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#3305]
We started https://github.com/cue-lang/cue/wiki/FAQ:-Modules-and-v0.9 as a quick and easy place to add, refine etc FAQs at the time of the v0.9.0 release. However the FAQ is not specific to v0.9.0, not least because we have since released v0.10.0-alpha.1. Instead, the focus of the FAQ is modules questions, especially those that contrast "old" style modules (the default prior to v0.9.0) and "new" (the default as of v0.9.0).

**Comment by myitcv** [comment]
FYI @jpluscplusm

**Comment by mvdan** [comment]
I think it's fine to keep the format similar to the FAQ page we already have, but it's worth keeping in mind that with further CUE versions that change how modules work, we might need something a bit more structured so that users can understand what they need to do when updating past one, two, or even three CUE versions at a time.

For example, with Go, I would look at each of the changelogs and skim for any announcements or warnings that might affect me.

**Comment by myitcv** [comment]
> but it's worth keeping in mind that with further CUE versions that change how modules work, we might need something a bit more structured so that users can understand what they need to do when updating past one, two, or even three CUE versions at a time.

Agreed. But at least to get started we can port the FAQ and take it from there.

> For example, with Go, I would look at each of the changelogs and skim for any announcements or warnings that might affect me.

This chimes with thoughts @jpluscplusm has had elsewhere.

Ok, per agreement offline too, this is a decision: move the wiki to cuelang.org.

@jpluscplusm - please can you pick this up?

**Comment by jpluscplusm** [comment]
> this is a decision: move the wiki to cuelang.org.

The whole wiki, or just the page referenced in this issue?

"Move", as in deduplicate (I.e ensure that the process ends up with the moved pages being updated to be pointers to their cuelang.org equivalents); or just copy the contents over (appropriately) and leave the wiki pages intact?

**Comment by myitcv** [comment]
> The whole wiki, or just the page referenced in this issue?

Just the referenced wiki, thanks.

> "Move", as in deduplicate (I.e ensure that the process ends up with the moved pages being updated to be pointers to their cuelang.org equivalents)

Yes please.

**Comment by jpluscplusm** [comment]
Page imported by https://cuelang.org/cl/1198148. A later update to the wiki page, pointing it to the new cuelang.org page, will close this issue.

**Comment by jpluscplusm** [comment]
Wiki page updated with pointer to cuelang.org.
