### ISSUE TITLE
cuelang.org: live-search doesn't permit Algolia's advanced syntax

### ISSUE THREAD

**Issue by jpluscplusm** [cue-lang/cue#3308]
### What page were you looking at?

https://cuelang.org/docs/howto/find-a-guide/

### What version of the site were you looking at?

https://github.com/cue-lang/cuelang.org/commit/e93b6b5c5e99274f336e821bcbf99bff74604d96

### What did you do?

I typed `"json schema"` into the on-page search box.

### What did you expect?

I expected the live-search overlay box, showing me results as I typed, in real time, to display some subset of the results returned by the site search, https://cuelang.org/search/?q=%22json%20schema%22%20contentType:%22How-to%20Guides%22: 

![image](https://github.com/user-attachments/assets/da5438de-b12d-49af-b82e-154c69feef47)

### What did you see instead?

The live-search results included pages which only match when advanced syntax is /disabled/ - in other words, ignoring the grouping of word phrases inside quotation marks, and interpreting each word in isolation.

![image](https://github.com/user-attachments/assets/9c53e37e-e02c-46e3-bab5-2fe2a219c93e)

cf. https://www.algolia.com/doc/api-reference/api-parameters/advancedSyntax/#how-to-use, which was added to the site search in https://github.com/cue-lang/cuelang.org/commit/11f8a8c8e01716e111fe790b8a9df96dfd8e4fcd.

**Comment by JorindeUsMedia** [comment]
I think it has something to do with the regex we use to pull apart the entered query. 
Todo: Figure out the difference between the typescript for the query on search results & search-autocomplete widgets
estimate: 1 - 1.5 h.

**Comment by JuanUsMedia** [comment]
Hi @jpluscplusm, 
Thanks for the details! I tried to replicate the issue, but I’m seeing the same results in both the live search and site search when entering "json schema." To investigate further, I have a few questions:

- Are you still able to reproduce the issue?
- Are there any other specific search terms where the issue appears? This would help determine if it’s related to particular keywords.

**Comment by jpluscplusm** [comment]
Hey @JuanUsMedia.

> Hi @jpluscplusm, Thanks for the details! I tried to replicate the issue, but I’m seeing the same results in both the live search and site search when entering "json schema." To investigate further, I have a few questions:
> 
> * Are you still able to reproduce the issue?

Yes.

> * Are there any other specific search terms where the issue appears?

Here's how to replicate it with an arbitrary pair of words:

- Open any random page
  - I've chosen https://cuelang.org/docs/howto/log-statistics-from-the-cue-evaluator
- Find a non-trivial word that appears on the page
  - I've selected `statistics`
- Find another non-trivial word on the page that **doesn't** appear near to the first word
  - `interpreted`
- Open https://cuelang.org/search/
- Type quotation-mark word-1 word-2 quotation-mark. **DO NOT HIT ENTER**
  - `"statistics interpreted"`
- Observe your initial choice of page appears in the live-results list
  - ![image](https://github.com/user-attachments/assets/ee78e98b-741b-4aa9-8c9f-1f4058a3caf7)
- Hit enter
- Observe your initial choice of page does **not** appear in the site-search results lists
  - ![image](https://github.com/user-attachments/assets/94534b81-9b0e-4d9b-b53d-3b9ef9a61a82)
