### ISSUE TITLE
cmd/cue: cue def is very slow on recursive jsonschema file

### ISSUE THREAD

**Issue by rogpeppe** [cue-lang/cue#3321]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
v0.9.2
</pre>

### Does this issue reproduce with the latest stable release?

Yes

### What did you do?

```
exec timeout 5s cue def schema.json

-- schema.json --
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "$id": "https://www.sourcemeta.com/schemas/vendor/json-e@1.json",
  "$comment": "https://json-e.js.org",
  "$defs": {
    "jsone-value": {
      "oneOf": [
        {
          "$ref": "#"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#"
          }
        },
        {
          "type": ["null", "boolean", "number", "string", "integer"]
        }
      ]
    },
    "jsone-array": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/jsone-value"
      }
    },
    "jsone-object-array": {
      "type": "array",
      "items": {
        "$ref": "#"
      }
    }
  },
  "additionalProperties": {
    "$ref": "#/$defs/jsone-value"
  },
  "properties": {
      "$if": {
      "type": "string"
    },
    "$json": {
      "$ref": "#/$defs/jsone-value"
    },
    "$let": {
      "type": "object",
      "additionalProperties": {
        "additionalProperties": {
          "$ref": "#"
        }
      }
    },
    "$map": {
      "$ref": "#/$defs/jsone-array"
    },
    "$match": {
      "$ref": "#"
    },
    "$merge": {
      "$ref": "#/$defs/jsone-object-array"
    },
    "$mergeDeep": {
      "$ref": "#/$defs/jsone-object-array"
    },
    "$reverse": {
      "$ref": "#"
    },
    "$then": {
      "$ref": "#/$defs/jsone-value"
    }
  },
  "title": "JSON-e templates",
  "type": "object"
}
```

### What did you expect to see?

A passing test. Conversion of JSON Schema to CUE should not take more than 5s.

### What did you see instead?

```
> exec timeout 5s cue def schema.json
[exit status 124]
FAIL: /tmp/testscript1916985807/x.txtar/script.txtar:1: unexpected command failure
```

On my machine, when I let it run to completion, I get the following timings:

```
82.62user 0.43system 0:46.49elapsed 178%CPU (0avgtext+0avgdata 76356maxresident)k
```

In the [original schema](https://github.com/SchemaStore/schemastore/blob/9f36b9cca86745a19ed5a74f4b660af5b6684fd6/src/schemas/json/jsone.json), I thought it had gone into an infinite loop: I don't know how
long it would take to run to completion.

**Comment by cuematthew** [comment]
With eval v3 this `cue def` completes for me in < 2s and gives identical output as v2.

**Comment by mvdan** [comment]
I think this means we can resolve this issue as fixed by evalv3; under 2s is still not particularly fast, but it finishes in reasonable time, and there's still plenty of optimization to be had in evalv3. @rogpeppe do you disagree?

**Comment by mvdan** [comment]
Closing per the above, as the performance is already reasonable on master with `CUE_EXPERIMENT=evalv3`. We are aiming to switch evalv3 to be on by default as soon as possible, so we are not spending the extra time to keep issues resolved by evalv3 open until the flip happens.
