### ISSUE TITLE
cuelang.org: search term "FAQ" returns no results

### ISSUE THREAD

**Issue by jpluscplusm** [cue-lang/cue#3322]
### What page were you looking at?

https://cuelang.org/search/?q=FAQ

### What version of the site were you looking at?

https://github.com/cue-lang/cuelang.org/commit/9bfb04b479b3fdd037c52f1bca7bf5dd65b98259

### What did you do?

Searched for the term `FAQ`, to find the just-published page https://cuelang.org/docs/concept/faq/new-modules-vs-old-modules/.

### What did you expect?

The page should return at least one result: https://cuelang.org/docs/concept/faq/new-modules-vs-old-modules/.

### What did you see instead?

Zero results.

**Comment by myitcv** [comment]
I think you were perhaps too quick:

![Screenshot 2024-07-24 at 16 09 00](https://github.com/user-attachments/assets/e723d384-d94b-45e5-9c28-5c83b23d0cae)

The updating of the Algolia indexes happens as part of the default branch build:

https://github.com/cue-lang/cuelang.org/blob/9bfb04b479b3fdd037c52f1bca7bf5dd65b98259/.github/workflows/trybot.yml#L258

And after that step runs, it's not inconceivable that there is some delay on their side before things update.

Perhaps you tried just a bit too soon?

**Comment by jpluscplusm** [comment]
> I think you were perhaps too quick
> Perhaps you tried just a bit too soon?

Agreed. I /thought/ that I'd left it a good 10 minutes after the page became available, waiting for the index to update, but clearly I needed to give it a bit longer!
