### ISSUE TITLE
evalv3: field not allowed

### ISSUE THREAD

**Issue by uhthomas** [cue-lang/cue#3331]
### What version of CUE are you using (`cue version`)?

<pre>
$ go run cuelang.org/go/cmd/cue@v0.10.0-alpha.2.0.20240726102249-5de5b42c834f version
cue version v0.10.0-alpha.2.0.20240726102249-5de5b42c834f

go version go1.22.5
      -buildmode exe
       -compiler gc
     CGO_ENABLED 1
          GOARCH amd64
            GOOS linux
         GOAMD64 v1
cue.lang.version v0.10.0
</pre>

### What did you do?

```cue
import "list"

#A: {
	let b = {}

	c: b & {
		d: 1
	}
}

list.Concat([[#A]])
```

### What did you expect to see?

```sh
$ go run cuelang.org/go/cmd/cue@v0.10.0-alpha.2.0.20240726102249-5de5b42c834f export ./a.cue
[
    {
        "c": {
            "d": 1
        }
    }
]
```

### What did you see instead?

```sh
$ CUE_EXPERIMENT=evalv3 go run cuelang.org/go/cmd/cue@v0.10.0-alpha.2.0.20240726102249-5de5b42c834f
0.0.c.d: field not allowed:
    ./a.cue:6:5
    ./a.cue:7:3
exit status 1
```

**Comment by uhthomas** [comment]
Really bizarre. This fails:

```cue
import "list"

#A: {
	let b = {}

	c: #B & b & {
		d: 1
	}
}

#B: d: int

list.Concat([[#A]])

```

This doesn't:

```cue
import "list"

#A: {
	c: #B & {
		d: 1
	}
}

#B: d: int

list.Concat([[#A]])
```

This is also okay:

```cue
import "list"

#A: {
	c: #B & {} & {
		d: 1
	}
}

#B: d: int

list.Concat([[#A]])
```

**Comment by uhthomas** [comment]
_this_ is okay though.

```cue
import "list"

#A: {
	let b = #B & {}

	c: b & {
		d: 1
	}
}

#B: d: int

list.Concat([[#A]])
```

**Comment by uhthomas** [comment]
Funnily enough, the reproduction is also fixed if I change

```cue
let probe = {exec: command: ["mc-health"]}
```

to

```cue
let probe = v1.#Probe & {exec: command: ["mc-health"]}
```

**Comment by mpvl** [comment]
Analysis: Similar to #3330. Normally referencing a struct within a definition does not affect closeness. In other words, this is allowed according to the spec:
```
#A: {
   b: c: int
   d: b
   d: e: int
}
```
Referencing in `#A` seems to trigger a different behavior in some cases, so that a reference like `b` treats it as closed.
