### ISSUE TITLE
cmd/cue: jsonschema interpretation is loose by default (and cannot be made strict)

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#3338]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.0.0-20240729152131-f7b7aaf1592f

go version go1.22.3
      -buildmode exe
       -compiler gc
     CGO_ENABLED 1
          GOARCH arm64
            GOOS linux
             vcs git
    vcs.revision f7b7aaf1592f9d324ee2e7db95fe50acd45bf09c
        vcs.time 2024-07-29T15:21:31Z
    vcs.modified false
cue.lang.version v0.10.0
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
! exec cue def jsonschema: x.json
stderr 'unsupported constraint "not"'

-- x.json --
{ "not": { "type": "string" } }
```

### What did you expect to see?

Passing test.

### What did you see instead?

```
> ! exec cue def jsonschema: x.json
[stdout]
_
FAIL: /tmp/testscript3427084930/repro.txtar/script.txtar:1: unexpected command success
```

At the time of writing, CUE does not understand how to interpret the JSON Schema `not` constraint. This is confirmed by the following:

```
go mod tidy
! go run .
stderr 'unsupported constraint "not"'

-- go.mod --
module mod.example

go 1.22.3

require cuelang.org/go v0.10.0-alpha.2.0.20240729152131-f7b7aaf1592f

-- main.go --
package main

import (
	"fmt"
	"log"

	"cuelang.org/go/cue/cuecontext"
	"cuelang.org/go/encoding/jsonschema"
)

func main() {
	ctx := cuecontext.New()
	v := ctx.CompileString(`{ "not": {"type": "string"} }`)
	sast, err := jsonschema.Extract(v, &jsonschema.Config{
		Strict: true,
	})
	if err != nil {
		log.Fatal(err)
	}
	s := ctx.BuildFile(sast)
	fmt.Printf("%v\n", s)
}
```

Clearly the default `jsonschema` interpretation of `cmd/cue` does not use strict mode. 

Arguably it should, with a `jsonschema+tag`-based approach to varying that default.

**Comment by rogpeppe** [comment]
This issue is under the misapprehension that it's not possible to enable
strict mode, but it actually is: the `--strict` flag does exactly that,
so closing this issue as
