### ISSUE TITLE
pkg/encoding/toml: add package to expose TOML encoder as a CUE package

### ISSUE THREAD

**Issue by mvdan** [cue-lang/cue#3344]
So that one may `import "encoding/toml"` and use APIs like `toml.Marshal` from CUE, just like https://pkg.go.dev/cuelang.org/go/pkg/encoding/json and other encodings.

**Comment by grihabor** [comment]
@mvdan Hey, what's the status of this? I'm thinking about starting working on it

I'm looking at [`pkg/encoding/json.Marshal`](https://github.com/cue-lang/cue/blob/f4f38bf03ac716a362f644ba75afc359a956e8ed/pkg/encoding/json/manual.go#L74-L78) as an example which uses [`internal/encoding/json.Encode`](https://github.com/cue-lang/cue/blob/f4f38bf03ac716a362f644ba75afc359a956e8ed/internal/encoding/json/encode.go#L32-L43) to serialize `cue.Value` to json. I guess I have to create two similar packages `pkg/encoding/toml` and `internal/encoding/toml`, right?

**Comment by mvdan** [comment]
Please don't work on it, as I'm currently working on it alongside other TOML work. That's why I assigned it to myself, to avoid duplication.

**Comment by grihabor** [comment]
Ok, thank you, excited to use it when it's done!
