### ISSUE TITLE
encoding/json: NewDecoder takes uses deprecated cue.Runtime type

### ISSUE THREAD

**Issue by rogpeppe** [cue-lang/cue#3353]
### What version of CUE are you using (`cue version`)?

<pre>
187fb1a3b08d4bcbf14be755a1981352fcac0b19
</pre>

### Does this issue reproduce with the latest stable release?

Yes

### What did you do?

The [API for `cuelang.org/go/encoding/json`](https://pkg.go.dev/cuelang.org/go/encoding/json#NewDecoder) uses the deprecated `*cue.Runtime` type. It should take `*cue.Context` instead, although changing the signature of `NewDecoder` directly would be a backwards incompatible change, so perhaps we should introduce a new function (`NewDecoderWithContext` ?) and deprecate the old one.

**Comment by mvdan** [comment]
We have been using generics to work around this like so:

```
package gocodec
func New[Ctx *cue.Runtime | *cue.Context](ctx Ctx, c *Config) *Codec {
```

I suggest we continue with the same approach. This is not perfectly backwards compatible, but we are v0 and this is still very unlikely to actually break any users - and if they are broken, the fix is relatively simple.

**Comment by mvdan** [comment]
Per the above, let's track this in https://github.com/cue-lang/cue/issues/2480, which already covers the dozens of deprecated API uses, including cue.Runtime. I don't think we should use one issue per API or package - that's far too noisy.
