### ISSUE TITLE
Improve Cue documentation for users and provide examples

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#336]
_Originally opened by @alexruf in https://github.com/cuelang/cue/issues/336_

I really like the idea behind Cue and would love to use Cue within some of my projects.
The problem is that for somebody who is completely new to Cue, the documentation just doesn't provide enough guidance to get started. On a conceptual level the documentation gives good information to grasp the idea behind it, but when it comes to apply those concepts you are more or less on your own.
It would be great to have a step by step tutorial going through some typical real world use cases, showing all the code, command line tools and how to use them. Also and some good examples on GitHub could also help users a lot.

Currently I'm a bit clueless how Cue is supposed to work. Digging through the code just isn't effective, given the fact that there are similar tools with extensive documentation.

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/336#issuecomment-611437062_

Agreed. 
Three major pieces missing are:
1) A language guide. This would sit in between the tutorial (too loose) and the language spec (too terse).
2) A best practices/ patterns doc: CUE uses a concept that is alien to many and it will not be obvious how to structure a configuration, even if one is familiar with the language itself.
3) A tooling guide: explaining from a higher level how to use the CUE tool.

Let me know if you think there is anything missing from this list.

**Comment by cueckoo** [comment]
_Original reply by @alexruf in https://github.com/cuelang/cue/issues/336#issuecomment-612045219_

Having those three points added to the documentation would be great. I am pretty sure this would help allot of people to get started with CUE.

**Comment by mvdan** [comment]
The new website has a number of [tutorials](https://cuelang.org/docs/tutorial/), [how-to guides](https://cuelang.org/docs/howto/), and [concept guides](https://cuelang.org/docs/concept/) - that should be much more helpful than the content on the old site :) If you find any particular gap or issue with those, please file a new issue with a specific request and we'll take a look. Thanks!
