### ISSUE TITLE
cuelang.org: trybot runs involve duplicated CI steps 

### ISSUE THREAD

**Issue by jpluscplusm** [cue-lang/cue#3366]
### What page were you looking at?

https://github.com/cue-lang/cuelang.org-trybot/actions/runs/10351636146/job/28650571026

### What version of the site were you looking at?

https://github.com/cue-lang/cuelang.org/commit/b8027323a96807781daf452e32fd9cf6610de9eb

### What did you do?

I triggered the trybot for `cue-lang/cuelang.org`

### What did you expect?

That the GHA run would be as quick and simple as possible.

### What did you see instead?

As demonstrated by this screenshot, some steps are duplicated in the CI job:

![image](https://github.com/user-attachments/assets/37c61244-b591-48a2-b04d-72007e79d927)

At minimum, these steps are invoked twice:

- Regenerate
- Test
- staticcheck
- Check module is tidy

Because of caching and temporal/spatial locality, the second invocation of each step does not appear to take long to run - if it takes any time at all. They are invoked, however, and are *not* skipped by GHA.

The duplication appears to be an indication that something in the workflow YAML file generation isn't working as intended.

**Comment by mvdan** [comment]
The job step names are confusing in that they seem like duplicates, but the steps themselves are not duplicates:

![image](https://github.com/user-attachments/assets/dbe0b418-b20f-410b-96e0-debee25064e5)

We basically test and check the two modules in the repository, `.` and `./playground`. Do you want to send a PR to give the "matrix" of per-module steps better names? Aside from a tweak like that, I don't see anything to be done here.

**Comment by jpluscplusm** [comment]
> the steps themselves are not duplicates:

How embarrassing! 🤦 

I'd noticed the "duplicates" a fair while back, but the trivial amount of time they "lost" never rose to the level of bothering to raise an issue - until I decided to open this one. By then, I'd simply internalised them as "duplicates", and didn't think to check the underlying workflows.

Sorry for the noise!

**Comment by mvdan** [comment]
All good! I think the clarification in the titles was needed.
