### ISSUE TITLE
inversion of list.Contains() function's return doesn't work

### ISSUE THREAD

**Issue by gulnarrra** [cue-lang/cue#3374]
I need validate list elements: list must contain required elements and must not contain forbidden elements.
Cue function list.Contains() works perfectly for checking required elements. I'm trying to use this function to check denied elements. 
My json to be validated - all_confs.json: 
```
{
  "/tmp/europe.yml": {
    "raw": "conf:\n  iscontinent: true\n  cities: [\"Dehli\", \"Paris\"]\n\n",
    "structure": {
      "conf": {
        "iscontinent": true,
        "cities": [
          "Dehli",
          "Paris"
        ]
      }
    }
  },
  "/tmp/africa.yml": {
    "raw": "conf:\n  iscontinent: true\n  cities: [\"Addis-Abeba\", \"Nairobi\", \"Paris\"]\n  ",
    "structure": {
      "conf": {
        "iscontinent": true,
        "cities": [
          "Addis-Abeba",
          "Nairobi",
          "Paris"
        ]
      }
    }
  }
}
```
Rules file static_conf.cue:
```
package verifylist

import "list"

[=~"/tmp/africa.yml"]: structure!: conf!: {
  ...
// check for required elements - this works perfectly
//  "cities"!: list.Contains("Nairobi")
  "cities"!: !list.Contains("Paris")
}
```
In this example denied value is "Paris" - it must not be in list. If it is, I must get validation error. So I'm trying to add some rule like this:
```
  "cities"!: !list.Contains("Paris")
```
"!" must invert true to false and false to true. 
list.Contains() return true or false: https://github.com/cue-lang/cue/blob/67f508f9935be0f639bebfa98a2588e411be6ea9/pkg/list/list.go#L279 
So I could be able to invert function result. 
But I get error:
```
$ cue vet *.cue *.json
"/tmp/africa.yml".structure.conf.cities: invalid operation !list.Contains("Paris") (! list):
    ./static_conf.cue:9:14

```
So the question is: how can I invert list.Contains() function result true to false? Or may be I should use another way to check lists for denied elements?

**Comment by haoqixu** [comment]
We can't use `!` to invert the result when using `list.Contains` as a field validator.

You can try this:
```cue
package verifylist

import "list"

[=~"/tmp/africa.yml"]: structure!: conf!: {
	...

	// check for required elements - this works perfectly
	// cities!:             list.Contains("Nairobi")
	cities!: [...]
	#contains_forbidden: list.Contains(cities, "Paris") & false
}

```
Run `CUE_EXPERIMENT=evalv3 cue vet static_conf.cue all_confs.json` and get:
```
"/tmp/africa.yml".structure.conf.#contains_forbidden: conflicting values true and false:
    ./static_conf.cue:11:23
    ./static_conf.cue:11:56
```

After `list.MatchN`  (#3370) is added, I think we can use `list.MatchN` to get a better error message for this case:
```
package verifylist

import "list"

[=~"/tmp/africa.yml"]: structure!: conf!: {
	...

	// check for required elements - this works perfectly
	// cities!:             list.Contains("Nairobi")
	cities!: list.MatchN(0, "Paris")
}
```
and get something like:
```
"/tmp/africa.yml".structure.conf.cities: invalid value ["Addis-Abeba","Nairobi","Paris"] (does not satisfy list.MatchN(0, "Paris")): number of matched elements is 1: does not satisfy 0:
...
```

**Comment by myitcv** [comment]
Thanks for responding here, @haoqixu.

Now that we have `matchN` as a builtin validator (https://github.com/cue-lang/cue/commit/1c2b1052d088e272a6dd766f047d106256d63a1d), it is also be possible to do this:

```
import "list"

tests: [string]: matchN(0, [list.Contains("Paris")])

tests: good: ["test"]
tests: bad: ["test", "Paris"]
```

And if we implement https://github.com/cue-lang/cue/issues/3382 then this could be written more succinctly as:

```
import "list"

tests: [string]: not(list.Contains("Paris"))

tests: good: ["test"]
tests: bad: ["test", "Paris"]
```
