### ISSUE TITLE
encoding/jsonschema: OpenAPI schema versions

### ISSUE THREAD

**Issue by rogpeppe** [cue-lang/cue#3375]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
v0.10.0
</pre>

### Does this issue reproduce with the latest stable release?

Yes

### What did you do?

```
! exec cue def cue+openapi: openapi.cue
stderr 'constraint "oneOf" is not supported'

! exec cue def cue+jsonschema: jsonschema.cue
stderr 'constraint "nullable" is not supported'

-- openapi.cue --
openapi: "3.0.0"
info: {
	version:     "1.0.0"
	title:       "Sample API"
	description: "Some description"
}
components: schemas: Example: {
	type: "object"
	properties: {
		foo: {
			type:        "string"
			nullable:    true
		}
		bar: {
			oneOf: [{
				type: "string"
			}, {
				const: null
			}]
		}
	}
}

-- jsonschema.cue --
$schema: "http://json-schema.org/draft-07/schema#"
type: "object"
properties: {
	foo: {
		type:        "string"
		nullable:    true
	}
	bar: {
		oneOf: [{
			type: "string"
		}, {
			const: null
		}]
	}
}
```

### What did you expect to see?

A passing test.

### What did you see instead?

```
> ! exec cue def cue+openapi: openapi.cue
[stdout]
info: {
	version:     *"1.0.0" | string
	title:       *"Sample API" | string
	description: "Some description"
}
#Example: {
	foo?: null | string
	bar?: string | null
	...
}
FAIL: /tmp/testscript662380999/x.txtar/script.txtar:1: unexpected command success
```

This schema should not be valid as OpenAPI 3.0 (`oneOf` is not supported) or JSON Schema (`nullable` is not supported).

We should have version-specific behaviour for OpenAPI.

**Comment by myitcv** [comment]
> We should have version-specific behaviour for OpenAPI.

And accordingly a means of choosing that version via `cmd/cue` or the Go API.

**Comment by rogpeppe** [comment]
I think we can treat this as closed by https://cuelang.org/cl/1200578. Further work will be required to implement the OpenAPI variations correctly, but that can be tracked in individual issues.
