### ISSUE TITLE
encoding/jsonschema: implement not, oneof and anyof in terms of matchN

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#3380]
Following the landing of https://review.gerrithub.io/c/cue-lang/cue/+/1198922, we should adapt the JSON Schema encoding to use `matchN` for the correct semantics. 

See https://github.com/cue-lang/cue/issues/3165 for related discussion.

**Comment by rogpeppe** [comment]
Fixed by https://cuelang.org/cl/1200526.
