### ISSUE TITLE
cmd/cue: "help mod edit" references Go elements that seem out of place

### ISSUE THREAD

**Issue by jpluscplusm** [cue-lang/cue#3401]
### What page were you looking at?

https://cuelang.org/docs/reference/command/cue-help-mod-edit/

### What version of the site were you looking at?

https://github.com/cue-lang/cuelang.org/commit/2b2c37ea473e6aab0d23472b057b00212f96818d

### What did you do?

I read the help text for `cue help mod edit`

### What did you expect?

I expected that the help text would be CUE-specific, and would point to relevant `cue` commands.

### What did you see instead?

> Users should prefer
'cue get path@version' which makes other go.mod adjustments as needed
to satisfy constraints imposed by other modules.

1. `go.mod` seems like a missed find/replace;
2. `cue get` isn't related to *CUE* modules hence feels incorrect in this context.

**Comment by mvdan** [comment]
Indeed this seems to be a copy paste mistake; do you want to send a patch?
