### ISSUE TITLE
"CUE_EXPERIMENT=modules=0" doesn't permit the current module to be referenced by import path 

### ISSUE THREAD

**Issue by jpluscplusm** [cue-lang/cue#3402]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.10.0

go version go1.23.0
      -buildmode exe
       -compiler gc
       -trimpath true
     CGO_ENABLED 0
          GOARCH amd64
            GOOS linux
         GOAMD64 v1
cue.lang.version v0.10.0

</pre>

### Does this issue reproduce with the latest stable release?

v0.10.0 is latest.

### What did you do?

```
exec cue mod init cue.example

exec cue export ./foo
cmp stdout output

exec cue export cue.example/foo
cmp stdout output

env CUE_EXPERIMENT=modules=0
exec cue export cue.example/foo
cmp stdout output
-- foo/main.cue --
package foo
source: "foo/main.cue": true
-- output --
{
    "source": {
        "foo/main.cue": true
    }
}

```

### What did you expect to see?

A passing test.

### What did you see instead?

```
> exec cue mod init cue.example
> exec cue export ./foo
[stdout]
{
    "source": {
        "foo/main.cue": true
    }
}
> cmp stdout output
> exec cue export cue.example/foo
[stdout]
{
    "source": {
        "foo/main.cue": true
    }
}
> cmp stdout output
> env CUE_EXPERIMENT=modules=0
> exec cue export cue.example/foo
[stderr]
cannot find package "cue.example/foo"
[exit status 1]
FAIL: /tmp/testscript3560661586/x.txtar/script.txtar:10: unexpected command failure
```

**Comment by mvdan** [comment]
With the upcoming v0.10.0-alpha.1 release [removing the option to set `CUE_EXPERIMENT=modules=0`](https://review.gerrithub.io/c/cue-lang/cue/+/1200580), as enough time has passed and we are not aware of any more regressions, I think we can close this issue as resolved. Please say if I got that wrong.
