### ISSUE TITLE
eval: invalid structural cycle error with `matchN`

### ISSUE THREAD

**Issue by rogpeppe** [cue-lang/cue#3410]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
e48fb9db492048b213b6a56fdce5c3660e69a189
</pre>

### Does this issue reproduce with the latest stable release?

N/A

### What did you do?

```
env CUE_EXPERIMENT=evalv3
exec cue export x.cue

-- x.cue --
_s
_s: {
    #x: matchN(1, [_s, [..._s]])
}
```

### What did you expect to see?

Passing test.

### What did you see instead?

```
> env CUE_EXPERIMENT=evalv3
> exec cue export x.cue
[stderr]
0: structural cycle:
    ./x.cue:3:19
_s.0: structural cycle:
    ./x.cue:3:19
[exit status 1]
FAIL: /tmp/testscript4122338254/x.txtar/script.txtar:2: unexpected command failure
```

**Comment by mpvl** [comment]
FTR: this also happens with `or`: 
```
s: or([s, []])
```
