### ISSUE TITLE
cmd/cue: fix should be able to process CUE from stdin

### ISSUE THREAD

**Issue by jpluscplusm** [cue-lang/cue#3417]
**Is your feature request related to a problem? Please describe.**

I have processes that need to operate inside an isolated container, consuming stdin and communicating via stdout.
One of the processes I'd like to run in this way is `cue fix` - but I can't, as it only consumes named packages (or files?) it can find via the filesytem.

**Describe the solution you'd like**

I'd like `cue fix` to accept CUE that needs fixing on stdin, and emit the fixed result to stdout.
I'd like this test to pass:

```
cp orig.cue unfixed.cue
exec cue fix unfixed.cue
cmp unfixed.cue fixed.cue

stdin orig.cue
exec cue fix -
cmp stdout fixed.cue
-- orig.cue --
x: 5 mod 3
-- fixed.cue --
x: __mod(5, 3)
```

**Describe alternatives you've considered**

n/a.

**Additional context**

n/a

**Comment by mvdan** [comment]
Here is a version of your testscript without needing a shell:

```
cp orig.cue unfixed.cue
exec cue fix unfixed.cue
cmp unfixed.cue fixed.cue

stdin orig.cue
exec cue fix -
cmp stdout fixed.cue
-- orig.cue --
x: 5 mod 3
-- fixed.cue --
x: __mod(5, 3)
```

`cue fix -` indeed seems to be a no-op:

```
> stdin orig.cue
> exec cue fix -
> cmp stdout fixed.cue
diff stdout fixed.cue
--- stdout
+++ fixed.cue
@@ -0,0 +1,1 @@
+x: __mod(5, 3)
```

This could be related to https://github.com/cue-lang/cue/issues/3405.

**Comment by jpluscplusm** [comment]
> Here is a version of your testscript without needing a shell:

Thanks - I didn't know `stdin` could work like that! I've edited my original comment to include your updated example.
