### ISSUE TITLE
evalv3: unexpected failure with explicit `_|_` in `matchN` arguments

### ISSUE THREAD

**Issue by rogpeppe** [cue-lang/cue#3420]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
1440b9eae7fa9ea40133418df0e5bacdcca29cb4
</pre>

### Does this issue reproduce with the latest stable release?

N/A

### What did you do?

```
env CUE_EXPERIMENT=evalv3
exec cue vet schema.cue

-- schema.cue --
matchN(1, [_, _|_])
```

### What did you expect to see?

Passing test (and under evalv2, this does indeed pass).

### What did you see instead?

```
> env CUE_EXPERIMENT=evalv3
> exec cue vet schema.cue
[stderr]
explicit error (_|_ literal) in source:
    ./schema.cue:1:15
[exit status 1]
FAIL: /tmp/x.txtar:2: unexpected command failure
```

**Comment by mvdan** [comment]
Why are you writing a bottom like that in your CUE? How did this come about from jsonschema?

**Comment by rogpeppe** [comment]
> Why are you writing a bottom like that in your CUE? How did this come about from jsonschema?

In JSON Schema, the value `false` is valid as a schema that never validates. The most natural translation of that into CUE is as bottom.
