### ISSUE TITLE
general: cuelang.org/go@v0.9.2 not available via GOPROXY=direct

### ISSUE THREAD

**Issue by pendo324** [cue-lang/cue#3447]
### What version of CUE are you using (`cue version`)?

I'm not running cue locally, this is a build time error/bug.

### Does this issue reproduce with the latest stable release?
No.

### What did you do?

```
export GOPATH=$WORK/_gopath
export GOPROXY=direct
go mod init mod.example
go get -x cuelang.org/go@v0.9.2
```

### What did you expect to see?

cuelang.org/go @ version 0.9.2 to be added to my go.mod/go.sum files.

### What did you see instead?
```
go: creating new go.mod: module mod.example
# get https://cuelang.org/?go-get=1
# get https://cuelang.org/go?go-get=1
# get https://cuelang.org/go?go-get=1: 200 OK (0.133s)
mkdir -p _gopath/pkg/mod/cache/vcs # git3 https://review.gerrithub.io/cue-lang/cue
# lock _gopath/pkg/mod/cache/vcs/d82383d43199d57840995f1c0a94e81eee5ed02e43dbba4468223292497673e2.lock
# _gopath/pkg/mod/cache/vcs/d82383d43199d57840995f1c0a94e81eee5ed02e43dbba4468223292497673e2 for git3 https://review.gerrithub.io/cue-lang/cue
cd _gopath/pkg/mod/cache/vcs/d82383d43199d57840995f1c0a94e81eee5ed02e43dbba4468223292497673e2; git tag -l
# get https://cuelang.org/?go-get=1: 200 OK (0.134s)
0.002s # cd _gopath/pkg/mod/cache/vcs/d82383d43199d57840995f1c0a94e81eee5ed02e43dbba4468223292497673e2; git tag -l
cd _gopath/pkg/mod/cache/vcs/d82383d43199d57840995f1c0a94e81eee5ed02e43dbba4468223292497673e2; git ls-remote -q origin
2.348s # cd _gopath/pkg/mod/cache/vcs/d82383d43199d57840995f1c0a94e81eee5ed02e43dbba4468223292497673e2; git ls-remote -q origin
go: cuelang.org/go@v0.9.2: invalid version: unknown revision v0.9.2
```

I noticed this issue while trying to build a project (cosign) which takes cue as a dependency. Their latest stable release ([v2.4.0](https://github.com/sigstore/cosign/releases/tag/v2.4.0) at the time of writing) [uses v0.9.2](https://github.com/sigstore/cosign/blob/v2.4.0/go.mod#L6).

I also noticed that v0.9.1 does not exist on gerrit (I haven't checked if all GitHub tags have gerrit tags, just happened to notice v0.9.1 as well)

This type of issue was previously reported in #2895, for an older version. Just like in that issue, [v0.9.2 _does_ exist on GitHub](https://github.com/cue-lang/cue/releases/tag/v0.9.2), but not gerrit.

I'm no gerrit expert, but It seems like if v0.9.2 were to be present on gerrit, [this link](https://review.gerrithub.io/plugins/gitiles/cue-lang/cue/+/refs/tags/v0.9.2) would work, and v0.9.2 would show up on [this list of tags](https://review.gerrithub.io/plugins/gitiles/cue-lang/cue/+refs)

**Comment by mvdan** [comment]
Thanks for reporting this, and you're absolutely correct. Due to how Gerrit works (or how we have configured it), tags are only publicly available if they are reachable from a branch. And we recently deleted the release-branch.v0.9 branch, thus hiding some of the v0.9.x tags. We know how to work around this, and even documented it (https://github.com/cue-lang/cue/wiki/Notes-for-project-maintainers#release-branches), but we failed to follow this process.

Maybe we should add some sort of automated checks for it, given that we messed up twice already.

**Comment by mvdan** [comment]
I created refs/attic/release-branch.v0.9 on Gerrit, and v0.9.2 is now reachable. Apologies again for the trouble.

**Comment by mvdan** [comment]
This should not happen again, at least not for long: I've added an automated CI check at https://review.gerrithub.io/c/cue-lang/cue/+/1201173.

**Comment by pendo324** [comment]
Thanks for the quick response @mvdan! The new automation looks good 👍
