### ISSUE TITLE
Trailing whitespace in encoding/jsonschema /constraints_string.go causes issues with date-time format

### ISSUE THREAD

**Issue by paulmayer** [cue-lang/cue#3454]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
v0.11.0-alpha.1.0.20240912172423-67f9dfa9015d
</pre>

### Does this issue reproduce with the latest stable release?

no, works fine on 0.10.0

### What did you do?

`cue import -p api foo.yaml`  with properties of type `string` with `date-time` format.

### What did you expect to see?

Import to work fine.

### What did you see instead?

```
cue import -p api openapi/ml.yaml -o schema/ml.cue
unknown format "date-time":
    ./openapi/ml.yaml:994:11
```

This appears to be due to a simple trailing whitespace in https://github.com/cue-lang/cue/blob/67f9dfa9015d8c484a8c43869919220d02b189a0/encoding/jsonschema/constraints_string.go#L70

**Comment by mvdan** [comment]
cc @rogpeppe
