### ISSUE TITLE
cmd/cue: "help cmd namedCommand ./some/path" no longer displays help text for named command

### ISSUE THREAD

**Issue by jpluscplusm** [cue-lang/cue#3462]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.11.0-alpha.1.0.20240912132401-a558a4b46cdb

go version go1.23.0
      -buildmode exe
       -compiler gc
  DefaultGODEBUG asynctimerchan=1,gotypesalias=0,httpservecontentkeepheaders=1,tls3des=1,tlskyber=0,x509keypairleaf=0,x509negativeserial=1
     CGO_ENABLED 1
          GOARCH amd64
            GOOS linux
         GOAMD64 v1
cue.lang.version v0.11.0

</pre>

### Does this issue reproduce with the latest stable release?

Yes, 0.10.0.

This definitely used to work, as we relied on it when writing https://github.com/cue-labs/cue-by-example/blob/main/001_github_actions_importing_workflows/README.md#arrow_right-test-the-cue-workflow-command, which was pre-0.10.0.

If this regression was intended, then we should recognise that (I believe) it's now not possible to ascertain the availability of a named command without attempting to invoke it. `cue help cmd ./some path` doesn't display a list of available commands and, as this issue tracks, individually named commands can't be referenced outside the current working directory either - leaving no neat options allowing documentation to confirm "is command X correctly set up in CUE code?". 

### What did you do?

```
cd foo
exec cue help cmd bar
stdout bar
stdout baz

cd ..
exec cue help cmd bar ./foo
stdout bar
stdout baz

-- foo/foo_tool.cue --
package foo

import "tool/exec"

// Say "baz".
command: bar: {
	print: exec.Run & { cmd: "echo baz" }
}
```

### What did you expect to see?

A passing test, indicating that the named command's name and help text had been displayed.

### What did you see instead?

```
> cd foo
$WORK/foo
> exec cue help cmd bar
[stdout]
Say "baz".

Usage:
  cue cmd bar [flags]

Global Flags:
  -E, --all-errors   print all available errors
  -i, --ignore       proceed in the presence of errors
  -s, --simplify     simplify output
      --strict       report errors for lossy mappings (deprecated: use "jsonschema+strict:" filetype instead; see cue help filetypes)
      --trace        trace computation
  -v, --verbose      print information about progress
> stdout bar
> stdout baz
> cd ..
$WORK
> exec cue help cmd bar ./foo
[stderr]
Unknown cmd command: bar
Usage:
  cue cmd bar [flags]

Global Flags:
  -E, --all-errors   print all available errors
  -i, --ignore       proceed in the presence of errors
  -s, --simplify     simplify output
      --strict       report errors for lossy mappings (deprecated: use "jsonschema+strict:" filetype instead; see cue help filetypes)
      --trace        trace computation
  -v, --verbose      print information about progress
[exit status 1]
FAIL: /tmp/testscript174030437/cue.help.cmd.doesNotShowAvailableCommands.txtar/script.txtar:7: unexpected command failure
> stdout bar
FAIL: /tmp/testscript174030437/cue.help.cmd.doesNotShowAvailableCommands.txtar/script.txtar:8: no match for `bar` found in stdout
> stdout baz
FAIL: /tmp/testscript174030437/cue.help.cmd.doesNotShowAvailableCommands.txtar/script.txtar:9: no match for `baz` found in stdout
```

**Comment by mvdan** [comment]
Thank you for the report. This broke at some point between v0.8.0 and v0.9.0; we never had tests for it, and technically it's not a documented feature. But it still seems useful and reasonable, and the breakage was unintentional.
