### ISSUE TITLE
pkg/struct: MinFields fails when combined with a conditional

### ISSUE THREAD

**Issue by jpluscplusm** [cue-lang/cue#3474]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.11.0-alpha.2

go version go1.23.0
      -buildmode exe
       -compiler gc
       -trimpath true
     CGO_ENABLED 0
          GOARCH amd64
            GOOS linux
         GOAMD64 v1
cue.lang.version v0.11.0

</pre>

### Does this issue reproduce with the latest stable release?

Yes, I've tested it and found it to fail with v0.10.0, v0.9.2, **but it passes with v0.8.2**. I've not tested v0.9.0.

### What did you do?

```
exec cue vet -c file.cue
env CUE_EXPERIMENT=evalv3
exec cue vet -c file.cue
-- file.cue --
import "struct"

A: struct.MinFields(1)
A: {
	if true {B: true}
}
```

### What did you expect to see?

A passing test.

### What did you see instead?

```
> exec cue-0.11.0-alpha.2 vet -c file.cue
[stderr]
A: incomplete value struct.MinFields(1):
    ./file.cue:3:4
[exit status 1]
FAIL: /tmp/testscript2904768139/minFields.conditional.disagree.txtar/script.txtar:1: unexpected command failure
> env CUE_EXPERIMENT=evalv3
> exec cue-0.11.0-alpha.2 vet -c file.cue
[stderr]
A: incomplete value struct.MinFields(1):
    ./file.cue:3:4
[exit status 1]
FAIL: /tmp/testscript2904768139/minFields.conditional.disagree.txtar/script.txtar:3: unexpected command failure
```

This feels adjacent to #3450 but, unlike that issue, *this* issue strikes with both the current and new evaluator.

**Comment by rogpeppe** [comment]
After bisecting, it looks like the culprit is https://review.gerrithub.io/c/cue-lang/cue/+/1200328
