### ISSUE TITLE
"field not allowed" error when embedding a definition inside an if comprehension

### ISSUE THREAD

**Issue by coding-yogi** [cue-lang/cue#3486]
### What version of CUE are you using (`cue version`)?
<pre>
$ cue version
v0.10.0
</pre>

### Does this issue reproduce with the latest stable release?
Yes

### What did you do?

Trying to eval below cue config
```
#cluster: {
    karpenter: {
      enable: bool | *true
    }
}

_cluster: #cluster

#service_account_annotations: {
  [Name=string]: {
    service_account: {
      annotations: {
        "test": "test"
      }
    }
  }
}

if _cluster.karpenter.enable {
  #service_account_annotations:karpenter: {}

  karpenter: {
    replicas: int | *2
    #service_account_annotations.karpenter
  }
}
```

### What did you expect to see?
I except the `if` condition to evaluate and generate the required `karpenter` struct, but it fails. If the `if` statement is commented, then code works fine.

I understand that  `#service_account_annotations:karpenter: {}` is a closed struct , and making it open works. 
But I am not sure why it complains about the fields of `karpenter`

### What did you see instead?
```
karpenter.replicas: field not allowed:
```

**Comment by mvdan** [comment]
Nicely spotted, this appears to be a bug in both the old and new evaluator. Simplified below:

```
env CUE_EXPERIMENT=evalv3=0
exec cue export input.cue

env CUE_EXPERIMENT=evalv3=1
exec cue export input.cue

-- input.cue --
#schema: {}

if true {
	out: {
		#schema
		extra: "foo"
	}
}
```

Which results in the following testscript output:

```
> env CUE_EXPERIMENT=evalv3=0
> exec cue export input.cue
[stderr]
out.extra: field not allowed:
    ./input.cue:1:10
    ./input.cue:3:1
    ./input.cue:5:3
    ./input.cue:6:3
[exit status 1]
FAIL: test.cue:2: unexpected command failure
> env CUE_EXPERIMENT=evalv3=1
> exec cue export input.cue
[stderr]
out.extra: field not allowed:
    ./input.cue:6:10
    ./input.cue:6:3
[exit status 1]
FAIL: test.cue:5: unexpected command failure
failed run
```

I know this is a bug because removing the `if true` conditional results in JSON output. This bug seems to be pretty similar to https://github.com/cue-lang/cue/issues/3483, except that it affects the old evaluator too.

**Comment by mvdan** [comment]
Note that the commit above only fixes the issue for the new evaluator, enabled via `CUE_EXPERIMENT=evalv3`.
