### ISSUE TITLE
evalv3: "field not allowed" regression with definition fields

### ISSUE THREAD

**Issue by mvdan** [cue-lang/cue#3491]
```
env CUE_EXPERIMENT=evalv3=0
exec cue export

env CUE_EXPERIMENT=evalv3=1
exec cue export

-- file.cue --
package p

#Schema: {
	schemaField?: {}
}

config: #Schema & {
	schemaField: {}
}

config: config2

config2: {
	#Extra: {}
}
```

As of 44cceca806909f9e24292770ee8381b5138ea2bf:

```
> env CUE_EXPERIMENT=evalv3=0
> exec cue export
[stdout]
{
    "config": {
        "schemaField": {}
    },
    "config2": {}
}
> env CUE_EXPERIMENT=evalv3=1
> exec cue export
[stderr]
config.#Extra: field not allowed:
    ./file.cue:11:9
[exit status 1]
FAIL: repro-evalv3.txtar:5: unexpected command failure
```

As far as I can tell, evalv2 is right in accepting this configuration. In fact, the error `config.#Extra: field not allowed` feels like it should be impossible; as far as my understanding of the spec goes, definitions and hidden fields should not be affected by closedness at all.

**Comment by mpvl** [comment]
This is related to this: https://github.com/cue-lang/cue/issues/543

This behavior was proposed, but it should not be implemented by v3 yet or at all.

**Comment by mvdan** [comment]
Agreed. Even if we did want to do this soon, it should be as a separate experiment. We want to make the transition from v2 to v3 as smooth as possible first.
