### ISSUE TITLE
cuelang.org: list of files presented in a code tabs element can't be scrolled 

### ISSUE THREAD

**Issue by jpluscplusm** [cue-lang/cue#3502]
### What page were you looking at?

https://cuelang.org/docs/concept/using-the-cue-export-command/inputs/#cue-package-file-inputs

### What version of the site were you looking at?

https://github.com/cue-lang/cuelang.org/commit/b5ad2337b8206c753e57e85ba4a6ce80e6222a6c

### What did you do?

I tried to scroll inside a code-tabs element, along the bar where the filenames are presented.

### What did you expect?

That I'd be able to scroll the filename list to view the right-most filenames.

### What did you see instead?

I couldn't scroll to the right either on desktop (ChromeOS v129.0.6668.80) or mobile (mobile Safari, iOS v17.7)

![image](https://github.com/user-attachments/assets/36554d07-0f6a-4148-a79c-023da500ebad)

**Comment by JorindeUsMedia** [comment]
This is a bug: scroll functionality for this was added but seems broken. I guess something to do with the css overflow property.
estimate: 30 min
