### ISSUE TITLE
@embed does not accept quoted identifier

### ISSUE THREAD

**Issue by nxcc** [cue-lang/cue#3515]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.10.0

go version go1.23.0
      -buildmode exe
       -compiler gc
       -trimpath true
     CGO_ENABLED 0
          GOARCH amd64
            GOOS linux
         GOAMD64 v1
cue.lang.version v0.10.0
</pre>

### Does this issue reproduce with the latest stable release?
yes (but it's an experimental feature)

### What did you do?
```
env CUE_EXPERIMENT=embed
exec cue -e a.b eval
cmp stdout golden

-- a.cue --
@extern(embed)

package example

a: "b": _ @embed(file=c.txt)

-- c.txt --
c

-- golden --
"""
    c


    """
```
([test.testscript.txt](https://github.com/user-attachments/files/17394915/test.testscript.txt))

### What did you expect to see?
```PASS```

### What did you see instead?
```can only define functions for fields with identifier names, found "b"```

**Comment by mvdan** [comment]
It seems like this restriction in `internal/core/runtime/extern.go` has been in place for over a year, and isn't directly caused by the addition of the embed experiment:

```
name, isIdent, err := ast.LabelName(f.Label)
if err != nil || !isIdent {
	b, _ := format.Node(f.Label)
	errs = errors.Append(errs, errors.Newf(x.Pos(),
		"can only define functions for fields with identifier names, found %v", string(b)))
	return true
}
```
