### ISSUE TITLE
cmd/cue: build tags are broken with named CUE files when used inside a module

### ISSUE THREAD

**Issue by jpluscplusm** [cue-lang/cue#3520]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.10.0

go version go1.23.0
      -buildmode exe
       -compiler gc
       -trimpath true
     CGO_ENABLED 0
          GOARCH amd64
            GOOS linux
         GOAMD64 v1
cue.lang.version v0.10.0

</pre>

### Does this issue reproduce with the latest stable release?

n/a

### What did you do?

```
# passes - no module
exec cue export -t foo .:foo 
exec cue export -t foo foo.cue

# set up module
exec cue mod init

# passes - with module
exec cue export -t foo .:foo 

# fails - with module
exec cue export -t foo foo.cue

-- foo.cue --
@if(foo)
package foo

x: 1
```

### What did you expect to see?

A passing test.

### What did you see instead?

```
# passes - no module (0.095s)
# set up module (0.036s)
# passes - with module (0.040s)
# fails - with module (0.039s)
> exec cue export -t foo foo.cue
[stderr]
build constraints exclude all CUE files in command-line-arguments:
    foo.cue: @if(foo) did not match
tag "foo" not used in any file
[exit status 1]
FAIL: /tmp/testscript2974807695/build-tags-named-files-with-module.txtar/script.txtar:12: unexpected command failure
```

The reporter in Slack mentioned that they git bisected this to https://github.com/cue-lang/cue/commit/79c1739e7415f40b0ea91e7cd36715c9287f21d3, but I've not confirmed this independently.

**Comment by mvdan** [comment]
Note that this got fixed by @rogpeppe in 4642d77a2d329fcf6ae1ab5e3e27f0ba5b63f897, but it didn't mark this issue as closed as it said "fixed" instead of "fixes". Closing manually.
