### ISSUE TITLE
cue fix transforms multiple list `+` into deeply nested Concat

### ISSUE THREAD

**Issue by nyarly** [cue-lang/cue#3523]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.11.0-alpha.3

go version go1.22.5
      -buildmode exe
       -compiler gc
       -trimpath true
     CGO_ENABLED 0
          GOARCH amd64
            GOOS linux
         GOAMD64 v1
cue.lang.version v0.11.0
</pre>

### Does this issue reproduce with the latest stable release?

List addition is only disallowed in 0.11 afaik

### What did you do?

```cue
// pre 0.11
l: ["a"] + ["b"] + ["c"] + ["d"]
```

`cue fix`

```cue
import 'list'
l: list.Concat([list.Concat([list.Concat([["a"], ["b"]]), ["c"]), ["d"]])
```

At top levels and in complex configurations, this is impossible to read or reason about clear enough to repair.

### What did you expect to see?

```cue
import "list"
l: list.Concat([["a"], ["b"], ["c"], ["d"]])
```

**Comment by cuematthew** [comment]
Thanks for the report - I definitely missed this when implementing the `cue fix` transform. I agree it's not easy to read the result; plus I think fixing the `cue fix` transform should be quite straightforward.
