### ISSUE TITLE
evalv3: "field not allowed" regression with fields under two comprehensions

### ISSUE THREAD

**Issue by mvdan** [cue-lang/cue#3533]
```
env CUE_EXPERIMENT=evalv3=0
exec cue export

env CUE_EXPERIMENT=evalv3=1
exec cue export

-- main.cue --
package p

#ObjectMeta: namespace?: string
out: {
	for i, _ in ["iter-once"] {
		metadata: #ObjectMeta
		if false {
			metadata: namespace: "foo"
		}
	}
}

out: metadata: namespace: *"default" | string
```

as of 62b21c8c44e84ca6b45224562298b1102b825766:

```
> env CUE_EXPERIMENT=evalv3=0
> exec cue export
[stdout]
{
    "out": {
        "metadata": {
            "namespace": "default"
        }
    }
}
> env CUE_EXPERIMENT=evalv3=1
> exec cue export
[stderr]
out.metadata.namespace: field not allowed:
    ./main.cue:8:25
    ./main.cue:3:14
    ./main.cue:8:14
    ./main.cue:13:16
[exit status 1]
```

**Comment by mvdan** [comment]
As far as I can tell, evalv2 is right in accepting the CUE as valid here.

**Comment by mpvl** [comment]
FTR: slight simplification (less fields, removed optional when possible, rename commensurate with nesting etc.) and added comments:
```
#X: y: string // needs to be outside the for comprehension
x: y: string
x: {
	for _ in ["iter-once"] {
		#X // needs to be definition
		if false {
			y: "foo"
		}
	}
}
```

**Comment by mpvl** [comment]
See node `2ecb40` in the given diagram (towards bottom of x.y node). This is marked as `P(ending)`, even though at the time of creation it is already known to be `M(ember)`. The reason for this is that when the `closeContext` for the inner comprehension is created, which creates field `y` with mode `ArcPending`, the `ArcPending` is propagated to all nodes that were not created yet, regardless of their current context. This causes, in some cases, the arcs to be ignored for closedness checking.

![allows](https://github.com/user-attachments/assets/453eca81-92b9-4938-b74b-606d736ec2c2)
