### ISSUE TITLE
Cue import panics with type alias

### ISSUE THREAD

**Issue by lorenzofelletti** [cue-lang/cue#3539]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.10.1

go version go1.23.2
      -buildmode exe
       -compiler gc
       -trimpath true
     CGO_ENABLED 0
          GOARCH arm64
            GOOS darwin
         GOARM64 v8.0
cue.lang.version v0.10.1
</pre>

### Does this issue reproduce with the latest stable release?
/   

### What did you do?

I am trying to import Tektoncd pipelines schemas.

My `deps.go` contains:
```golang
//go:build deps

package deps

import (
	_ "github.com/tektoncd/pipeline/pkg/apis/pipeline"
	_ "github.com/tektoncd/pipeline/pkg/apis/pipeline/v1"
	_ "github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1"
)

```

The `go.mod` file contains:
```golang
module go.k8s

go 1.22.5

require (
	github.com/tektoncd/pipeline v0.64.0
)

// ...
```

I ran:
```sh
go mod init go.k8s
cue mod init cue.k8s

go mod tidy

cue get go github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1
```

### What did you expect to see?

The command not to error

### What did you see instead?

When I run `cue get go github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1` I get:
```
panic: unsupported type *types.Alias

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.(*extractor).makeType(0x14040c93ab0?, {0x103223d90?, 0x14040c25ec0?})
        cuelang.org/go@v0.10.1/cmd/cue/cmd/get_go.go:1261 +0xea8
cuelang.org/go/cmd/cue/cmd.(*extractor).makeField(0x14040c93ab0, {0x1403f3105ef, 0x4}, 0x1, {0x103223d90?, 0x14040c25ec0?}, 0x0, 0x1)
        cuelang.org/go@v0.10.1/cmd/cue/cmd/get_go.go:1006 +0x48
cuelang.org/go/cmd/cue/cmd.(*extractor).addFields(0x14040c93ab0, 0x14040aa12f0, 0x14042100870)
        cuelang.org/go@v0.10.1/cmd/cue/cmd/get_go.go:1334 +0x2e4
cuelang.org/go/cmd/cue/cmd.(*extractor).makeType(0x14040c93ab0, {0x103222330?, 0x14040aa12f0})
        cuelang.org/go@v0.10.1/cmd/cue/cmd/get_go.go:1167 +0xc3c
cuelang.org/go/cmd/cue/cmd.(*extractor).makeField(0x14040c93ab0, {0x1403ea7dd10, 0x4}, 0x2, {0x103222330?, 0x14040aa12f0?}, 0x1403f32a198, 0x1)
        cuelang.org/go@v0.10.1/cmd/cue/cmd/get_go.go:1006 +0x48
cuelang.org/go/cmd/cue/cmd.(*extractor).reportDecl(0x14040c93ab0, 0x1403f3408c0)
        cuelang.org/go@v0.10.1/cmd/cue/cmd/get_go.go:709 +0x354
cuelang.org/go/cmd/cue/cmd.(*extractor).extractPkg(0x14040c93ab0, {0x14000040054, 0x3d}, 0x140008a8a80)
        cuelang.org/go@v0.10.1/cmd/cue/cmd/get_go.go:509 +0xb38
cuelang.org/go/cmd/cue/cmd.extract(0x14000262870, {0x140002941a0, 0x1, 0x1})
        cuelang.org/go@v0.10.1/cmd/cue/cmd/get_go.go:412 +0x2dc
cuelang.org/go/cmd/cue/cmd.newGoCmd.mkRunE.func1(0x140001ad000?, {0x140002941a0, 0x1, 0x1})
        cuelang.org/go@v0.10.1/cmd/cue/cmd/root.go:132 +0x1f0
github.com/spf13/cobra.(*Command).execute(0x14000288008, {0x14000294160, 0x1, 0x1})
        github.com/spf13/cobra@v1.8.1/command.go:985 +0x834
github.com/spf13/cobra.(*Command).ExecuteC(0x14000260308)
        github.com/spf13/cobra@v1.8.1/command.go:1117 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.8.1/command.go:1041
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0x14000262870, {0x1037e4ec0?, 0x103137320?})
        cuelang.org/go@v0.10.1/cmd/cue/cmd/root.go:397 +0x28
cuelang.org/go/cmd/cue/cmd.Main()
        cuelang.org/go@v0.10.1/cmd/cue/cmd/root.go:305 +0x9c
main.main()
        cuelang.org/go@v0.10.1/cmd/cue/main.go:24 +0x1c
```

I suppose the issue arise with this particular line ([here](https://github.com/tektoncd/pipeline/blob/main/pkg/apis/pipeline/v1beta1/container_types.go#L265)):
```golang
type OnErrorType string
```

The same error goes if I try to run `cue get go github.com/tektoncd/pipeline/pkg/apis/pipeline/v1`. Both generates the `.cue` files up until the file containing that type alias definition, that's why I'm supposing it is it causing the problem, that paired with the panic message `panic: unsupported type *types.Alias`.

**Comment by mvdan** [comment]
This should have been resolved by https://review.gerrithub.io/c/cue-lang/cue/+/1199529, can you try v0.11.0-alpha.4? We just haven't done v0.11.0 with these changes yet, and they're a bit too large and risky to backport.

Note that you can work around this panic with CUE v0.10.0 with `GODEBUG=gotypesalias=0` as an alternative.

**Comment by mvdan** [comment]
Closing per the above, but please say if I misunderstood.

**Comment by lorenzofelletti** [comment]
Thanks @mvdan! I just tried with `v0.11.0-alpha.4` and it worked!
