### ISSUE TITLE
evaluator: unexpected behaviour from `list.Sum`

### ISSUE THREAD

**Issue by de-odex** [cue-lang/cue#3541]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.10.1

go version go1.23.2
      -buildmode exe
       -compiler gc
       -trimpath true
     CGO_ENABLED 0
          GOARCH amd64
            GOOS windows
         GOAMD64 v1
cue.lang.version v0.10.1
</pre>

### Does this issue reproduce with the latest stable release?

Yes. Tested in playground as of today.

### What did you do?

```
import "list"

_test: {
  one: {
    num: 2
    test: num: 6
  }
  two: {
    num: 3
    test: num: 7
  } 
  three: {
    num: 4
    test: num: 8
  } 
  four: {
    num: 5
    test: num: 9
  }
}

list.Sum([for key, val in _test {
  val.num + val.test
}])
```
Evaluate this.

### What did you expect to see?

Invalid operands error (int and struct)

### What did you see instead?

Evaluates to 0

**Comment by de-odex** [comment]
works in evalv3, perhaps a non-issue

**Comment by de-odex** [comment]
perhaps it is better to leave it to your discretion whether to close this as a non-issue or not

**Comment by mvdan** [comment]
Thanks for reporting - good to hear that evalv3 fixes this issue. We will add a regression test to ensure our test suite covers this edge case.
