### ISSUE TITLE
evalv2: error from invalid regexp is lost when inside pattern constraint

### ISSUE THREAD

**Issue by rogpeppe** [cue-lang/cue#3555]
### What version of CUE are you using (`cue version`)?

<pre>
deed7d5c90d56f7468906f293494eb099f2c37a2
</pre>

### Does this issue reproduce with the latest stable release?

Yes (v0.10.0)

### What did you do?

```
! exec cue vet schema.cue

-- schema.cue --
[=~"BAD)" & =~"x"]: string
y: 123
```

### What did you expect to see?

A passing test. The regular expression `BAD)` has invalid syntax and should be rejected up front.
`evalv3` behaves correctly here.

### What did you see instead?

```
> ! exec cue vet schema.cue
FAIL: z.txtar:1: unexpected command success
```

**Comment by mvdan** [comment]
Do we want to add an evalv3 regression test before closing this evalv3-win issue like the rest, or are the tests in jsonschema enough?
