### ISSUE TITLE
evalv2: strings.Join swallow compilation error

### ISSUE THREAD

**Issue by davireis** [cue-lang/cue#3567]
### What version of CUE are you using (`cue version`)?

<pre>
cue version v0.10.0

go version go1.23.0
      -buildmode exe
       -compiler gc
        -ldflags -s -w -X cuelang.org/go/cmd/cue/cmd.version=v0.10.0
  DefaultGODEBUG asynctimerchan=1,gotypesalias=0,httpservecontentkeepheaders=1,tls3des=1,tlskyber=0,x509keypairleaf=0,x509negativeserial=1
     CGO_ENABLED 1
          GOARCH arm64
            GOOS darwin
         GOARM64 v8.0
             vcs git
    vcs.revision a7c37ee1eeb84546552bcc70aa280ab7c748e9e9
        vcs.time 2024-08-14T21:53:19Z
    vcs.modified false
cue.lang.version v0.10.0
</pre>

### Does this issue reproduce with the latest stable release?

Yes

### What did you do?

Notice the missing second parameter in the nested strings.Join call.

```
echo 'import "strings"' > f1.cue
echo 'a: strings.Join( [ strings.Join(["1"]), "2" ], "\n")' >> f1.cue
cue eval f1.cue
a: "2"
```

### What did you expect to see?

if I extract the strings.Join from the nested context I get the right error.

```
echo 'import "strings"' > f2.cue
echo '_a: strings.Join(["1"])' >> f2.cue
echo 'a: strings.Join( [ _a, "2" ], "\n")' >> f2.cue
cue eval f2.cue
_a: not enough arguments in call to strings.Join (have 1, want 2):
    ./f2.cue:2:5
```    

### What did you see instead?

I saw an incorrect output with no error signaling, which is hard to track down in an extensive configuration.

**Comment by myitcv** [comment]
Thanks for the report @davireis. Noting that as of 432c1141e6e7 this only appears to affect evalv2:

```
env CUE_EXPERIMENT=evalv3=0
! exec cue eval f1.cue
stderr 'not enough arguments in call to strings.Join \(have 1, want 2\)'

-- f1.cue --
import "strings"
a: strings.Join( [ strings.Join(["1"]), "2" ], "\n")
```

i.e. setting `CUE_EXPERIMENT=evalv3` causes the error to be reported as expected, allowing that test to pass.

I've locked in the v3 behaviour via https://review.gerrithub.io/c/cue-lang/cue/+/1205366. 

For transparency, given that we are focussing almost all of our attention on evalv3, we are unlikely to fix this in evalv2.
