### ISSUE TITLE
evalv3: unexpected structural cycle regression

### ISSUE THREAD

**Issue by rogpeppe** [cue-lang/cue#3571]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version

</pre>

### Does this issue reproduce with the latest stable release?

No (v0.10.0)

### What did you do?

```
exec cue vet x.cue

env CUE_EXPERIMENT=evalv3
exec cue vet x.cue

-- x.cue --
a: #T
a: in: f: true
a: #in: {
	g: #T
	g: #in: f: #T
	g: #in: f: #in: x: true
	f?: _
}

#T: {
	in:  #in
	#in: _
}
```

### What did you expect to see?

Passing test.

### What did you see instead?

```
> exec cue vet x.cue
> env CUE_EXPERIMENT=evalv3
> exec cue vet x.cue
[stderr]
a.in.g.in.f: structural cycle
[exit status 1]
FAIL: /tmp/z.txtar:4: unexpected command failure
```

This seems like it might well be a bug in evalv3.
As supporting evidence for that, if I duplicate the `#T` definition and change any one of the references to refer to a difference version, we don't see the structural cycle any more, but that _shouldn't_ make any difference AFAICS.

**Comment by mpvl** [comment]
Here is a simplification:
```
#T
in: _
x: #T
x: x: #T

#T: {
	in: x
	x: _
}
```
