### ISSUE TITLE
evalv2: matchN fails with list argument

### ISSUE THREAD

**Issue by rogpeppe** [cue-lang/cue#3575]
### What version of CUE are you using (`cue version`)?

<pre>
82995bbb
</pre>

### Does this issue reproduce with the latest stable release?

N/A (v0.10.0 doesn't implement matchN)

### What did you do?

```
env CUE_EXPERIMENT=evalv3
exec cue vet x.cue

env CUE_EXPERIMENT=evalv3=0
exec cue vet x.cue

-- x.cue --
test1: {
	#x: matchN(1, [
		[{}],
	])

	x: #x
	x: [{a: 1}]
}

test2: {
	#x: matchN(1, [
		{},
	])
	x: #x
	x: {a: 1}
}
```

### What did you expect to see?

Passing test. The struct should match with extra fields whether it's in a struct literal or not.

### What did you see instead?

```
> env CUE_EXPERIMENT=evalv3
> exec cue vet x.cue
> env CUE_EXPERIMENT=evalv3=0
> exec cue vet x.cue
[stderr]
test1.x: invalid value [{a:1}] (does not satisfy matchN): 0 matched, expected 1:
    ./x.cue:2:6
    ./x.cue:2:13
    ./x.cue:6:5
    ./x.cue:7:5
[exit status 1]
FAIL: /tmp/x.txtar:5: unexpected command failure
```

**Comment by myitcv** [comment]
cc @mvdan for the general view here: do we commit an evaluator test to lock in the v3 behaviour and close this, as the problem only affects v2?

**Comment by mvdan** [comment]
Yes. I've just sent such a change, along with three others for other evalv3-win issues.
