### ISSUE TITLE
evalv3: tools/flow: unexpected error, when flow task result field use as list item.

### ISSUE THREAD

**Issue by morlay** [cue-lang/cue#3581]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version

0.11.0
</pre>

### Does this issue reproduce with the latest stable release?

yes

### What did you do?

```txtar
$ CUE_EXPERIMENT=evalv3 cue cmd build ./x_tool.cue

-- x_tool.cue --
package x

import (
	"strings"

	"tool/exec"
	"tool/cli"
)

command: build: X = {
	#Project & {
		"main": "./cmd/x"

		"ldflags": [
			"-s", "-w",
			"-X \(X.module)/internal/version.version=v0.0.0",
		]
	}

	print: cli.Print & {
		text: strings.Join(X.ldflags, " ")
	}
}

#Project: {
	main!: string
	ldflags: [...string] | *["-s", "-w"]

	load_module: exec.Run & {
		cmd: ["echo", "path/to/x"]
		mustSucceed: true
		stdout:      string
	}

	module: strings.TrimSpace(load_module.stdout)
}
```

### What did you expect to see?

print the joined `ldflags` same as `evalv2` did

```bash
$ cue cmd build ./x_tool.cue
-s -w -X path/to/x/internal/version.version=v0.0.0
```

### What did you see instead?
got unexpected error

```bash
$ CUE_EXPERIMENT=evalv3 cue cmd build ./x_tool.cue
command.build.ldflags: incompatible list lengths (2 and 3):
    ./x_tool.cue:14:14
command.build.ldflags.2: field not allowed:
    ./x_tool.cue:14:14
```

**Comment by mpvl** [comment]
Quick analysis: this is not specific to flow, but an evaluation error, albeit a subtle one. It can be boiled down to this:
```
list: [...string] | *["a", "b"]
list: [ "a", "b", "c\(c)" ]
c: _
```
Eval V3 makes this a permanent error, which causes flow to fail immediately. Eval V2 makes this an "incomplete" error, which allows flow to run to ultimately satisfy the value.

Note that for
```
a: "c\(c)"
c: _
```
both evaluators report an incomplete error, so at the very least V3's behavior seems to be inconsistent here.
