### ISSUE TITLE
evaluator: conflicting values in for loop with let expressions

### ISSUE THREAD

**Issue by timspeetjens** [cue-lang/cue#3590]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.11.0

go version go1.23.3
      -buildmode exe
       -compiler gc
       -trimpath true
     CGO_ENABLED 0
          GOARCH amd64
            GOOS linux
         GOAMD64 v1
cue.lang.version v0.11.0
</pre>

### Does this issue reproduce with the latest stable release?

Yes (0.11.0). 0.10.1 runs as expected

### What did you do?

```
exec cue eval -c conflicting.cue
cmp stdout stdout.golden

-- conflicting.cue --
#Result: [_]: {[string]: string}

result: #Result

#Input: {
	p: "A" | "B"
}

_input: [Parm=_]: #Input & {
	p: Parm
}

_input: {
	A: {}
	B: {}
}

for _, v in _input {
	let Var1 = v.p
	let Var2 = Var1

	let Items = {
		"item": Var2
	}

	result: "conflicting-\(v.p)": Items
}
-- stdout.golden --
result: {
    "conflicting-A": {
        item: "A"
    }
    "conflicting-B": {
        item: "B"
    }
}
```

### What did you expect to see?

Passing test

### What did you see instead?

```
[stderr]
result."conflicting-A".item: conflicting values "B" and "A":
    ./conflicting.cue:10:5
    ./conflicting.cue:18:1
    ./conflicting.cue:19:13
    ./conflicting.cue:20:13
    ./conflicting.cue:23:11
    ./conflicting.cue:26:33
[exit status 1]
```

**Comment by timspeetjens** [comment]
Bisected to 396557964a4b90af732b19cea142b550d84f39e4

**Comment by timspeetjens** [comment]
Would you be willing to revert 396557964a4b90af732b19cea142b550d84f39e4 ? It appears to be a one-liner, not counting the additional test cases.

**Comment by PierreR** [comment]
I was able to reproduce this issue.
I believe it affects both the old and the new evaluator. Correct ?

**Comment by myitcv** [comment]
@timspeetjens @PierreR - thanks for raising and looking into this. I can indeed confirm that 396557964a4b90af732b19cea142b550d84f39e4 is the point at which this broke, with the slightly simpler reducer:

```
exec cue eval conflicting.cue
cmp stdout stdout.golden

-- conflicting.cue --
result: [_]: [string]: string

_input: {
	A: p: "A"
	B: p: "B"
}

for _, v in _input {
	let Var1 = v.p

	// Second let variable required here; just using Var1 with Items not
	// sufficient
	let Var2 = Var1

	let Items = {
		item: Var2
	}

	result: "conflicting-\(v.p)": Items
}
-- stdout.golden --
result: {
    "conflicting-A": {
        item: "A"
    }
    "conflicting-B": {
        item: "B"
    }
}
```

Marcel is deep debugging another issue right now, but I will mark this for the first alpha of v0.12.

**Comment by myitcv** [comment]
Apologies, I should have been clearer earlier; this affects both v2 and v3 of the evaluator.
