### ISSUE TITLE
cue eval - missing items in for loop with let expressions

### ISSUE THREAD

**Issue by timspeetjens** [cue-lang/cue#3591]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.11.0

go version go1.23.3
      -buildmode exe
       -compiler gc
       -trimpath true
     CGO_ENABLED 0
          GOARCH amd64
            GOOS linux
         GOAMD64 v1
cue.lang.version v0.11.0
</pre>

### Does this issue reproduce with the latest stable release?

Yes, 0.11.0, works as expected with 0.10.1

### What did you do?

```
exec cue eval -c missing.cue
cmp stdout stdout.golden

-- missing.cue --
#Result: [_]: {[string]: string}

result: #Result

#Input: {
	p: "A" | "B"
}

_input: [Parm=_]: #Input & {
	p: Parm
}

_input: {
	A: {}
	B: {}
}

for _, v in _input {
	let Var1 = v.p
	let Var2 = Var1

	let Items = {
		"item": {
			key1: Var2
		}
	}

	result: "missing-items-\(v.p)": {
		for s, attr in Items {
			if attr.key1 != _|_ {(s): attr.key1}
		}
	}
}
-- stdout.golden --
result: {
    "missing-items-A": {
        item: "A"
    }
    "missing-items-B": {
        item: "B"
    }
}
```

### What did you expect to see?

Passing test

### What did you see instead?

```
result: {
    "missing-items-A": {}
    "missing-items-B": {}
}
```

It looks like this issue is related with #3590 - trying to simplify the reproducer even more, no more output was seen, but a `conflicting values` error was returned instead.

**Comment by timspeetjens** [comment]
Bisected to 396557964a4b90af732b19cea142b550d84f39e4

**Comment by myitcv** [comment]
Thanks again, @timspeetjens - let's indeed await the response to #3590 and see where we stand here. We can always add a separate regression test based on this repro if needed.
