### ISSUE TITLE
cuelang.org: mobile rendering of JSON and CUE has inconsistent font sizes

### ISSUE THREAD

**Issue by jpluscplusm** [cue-lang/cue#3602]
### What page were you looking at?

https://cuelang.org/docs/concept/how-cue-works-with-json/

### What version of the site were you looking at?

https://github.com/cue-lang/cuelang.org/commit/597542b2fe96f0cfa65f1958d13fe58b4b7cbe7b

### What did you do?

I viewed the page on a mobile device (an iPhone 14 running iOS 18.0.1 with the default Mobile Safari browser).

### What did you expect?

That the page would have code rendered consistently, and similarly to a desktop device.

### What did you see instead?

Some code and comments inside CUE and JSON code tabs is rendered with a larger font size than other code and comments. There's no pattern I can discern that decides which code will be larger, but it's consistent across page loads and doesn't occur on the same page on a desktop device.

![IMG_6836](https://github.com/user-attachments/assets/73c8b1e0-71aa-451c-91cf-ea1b53dd062a)
![IMG_6837](https://github.com/user-attachments/assets/1feb7572-d9fb-44d3-8b37-5026c39d07e5)

**Comment by JorindeUsMedia** [comment]
Could not reproduce on Android or Browser responsive mode. Tested on safari desktop and there's no problem there. The problem seems to be on Safari on Iphone. It needs further debugging.

**Comment by JorindeUsMedia** [comment]
Found it: safari does this when it thinks a piece of text is too small.  Can be turned off: https://stackoverflow.com/questions/3226001/some-font-sizes-rendered-larger-on-safari-iphone
