### ISSUE TITLE
cuelang.org: clicking a same-page fragment link breaks the browser's usual "back" button behaviour

### ISSUE THREAD

**Issue by jpluscplusm** [cue-lang/cue#3615]
### What page were you looking at?

https://cuelang.org/docs/reference/modules/#resolve-pkg-mod

### What version of the site were you looking at?

https://github.com/cue-lang/cuelang.org/commit/af18aba7da2b63787ad7b8e1af55c904c4de6232

### What did you do?

- I was reading the section ["Resolving a package to a module"](https://cuelang.org/docs/reference/modules/#resolve-pkg-mod). Its first sentence contains a link to a glossary entry on the same page, linked from the words "package page".
- I clicked on this link, and was taken to the glossary entry near the bottom of the same page. My browser URL was updated to include the fragment relating to the glossary entry.
- I finished reading the glossary entry, and clicked my browser's "back" button to return to the paragraph that had linked me to the glossary.

### What did you expect?

I expected the page to return to my previous position, right before I clicked the link to the glossary entry.

### What did you see instead?

I was sent to the page which I had been reading before I visited the modules reference guide.

### Extra info

I don't think I'm imagining that the expected behaviour I describe is the browser's normal behaviour.

For an example of this working as expected, visit this [Docker documentation page](https://docs.docker.com/reference/dockerfile/); visit several of the right-hand-TOC entries; then use the "back" button to reverse back through the list of sections you just visited.

**Comment by JorindeUsMedia** [comment]
This is an easy fix:
For developer: in main.ts change window.history.replaceState(null, '', target);  to window.location.href = target

**Comment by myitcv** [comment]
The fix was quick: I've raised https://review.gerrithub.io/c/cue-lang/cuelang.org/+/1205727 to cover this.
