### ISSUE TITLE
Clarification on openness of appending open lists

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#364]
_Originally opened by @philipdexter in https://github.com/cuelang/cue/issues/364_

### What version of CUE are you using (`cue version`)?

commit #1370f0a

### Does this issue reproduce with the latest release?
yes

### What did you do?

```cue
$ ~/projects/golang/cue/cmd/cue/cue repl
cue version (devel) linux/amd64
(running in freestyle mode)
Type ':help' for help (type ^C or ^D to exit)
> [1,...] & [1,2,3]
[1, 2, 3]
> ([1,...]) & [1,2,3]
[1, 2, 3]
> ([1,...] + []) & [1,2,3]
conflicting list lengths: conflicting values 1 and 3
> ([1,...] + [...]) & [1,2,3]
conflicting list lengths: conflicting values 1 and 3
```

### What did you expect to see?

Not sure. What is expected here?

### What did you see instead?

Those errors above.

**Comment by cueckoo** [comment]
_Original reply by @seh in https://github.com/cuelang/cue/issues/364#issuecomment-620581839_

Thank you for the succinct examples. I expect that appending anything to an open list should result in an open list (such that `[1,...] + []` would result in `[1,...]`, as the empty list is the identity value for `+`). Likewise, `[...]` added to an open list shouldn't change its length.

Experimenting as you did, I see that adding any two lists—`[]` and `[]`, `[]` and `[...]`, `[...]` and `[]`, or `[...]` and `[...]`—results in a list of length zero when attempting to unify it with another concrete list.

**Comment by cueckoo** [comment]
_Original reply by @philipdexter in https://github.com/cuelang/cue/issues/364#issuecomment-620590876_

I wonder if this would open a can of worms regarding the `list` functions. Like `list.FlattenN`, should the openness of the output depend on the inputs? And then what about `list.Drop`, or `list.Sort`, or list comprehension? Perhaps it's simplest to just allow concatenation to preserve openness, but `list` functions and list comprehension should not.

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/364#issuecomment-620747492_

Right now the semantics is to close the lists with the `+` operator. Like all other binary expression other than `&` and `|`, defaults selected before evaluation. As an open list is considered to have a default value of a list without any other elements, the concatenation of these inputs is itself also closed.

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/364#issuecomment-620753267_

In the past it worked more the way @seh mentioned. This seemed to be hard to justify given how binary expressions worked elsewhere and complicated the spec. 

Either way, whatever one would pick, it will remain confusing. 

I'm therefore inclined to disallow list concatenation using `+` altogether. The alternative would be to use multiple comprehensions (once implemented). To concatenate list `a` and `b` one would write:
```
[ for x in a { x }, for x in b { x } ]
```
to get a closed list and
```
[ for x in a { x }, for x in b { x }, ... ]
```
to get an open list. In both cases it is syntactically quite clear what they would mean.

This is still somewhat verbose, though. With a query extension like the one proposed, one could write something like  `[ a.*, b.* ]` and `[ a.*, b.* , ...]` to achieve the same.

**Comment by cueckoo** [comment]
_Original reply by @philipdexter in https://github.com/cuelang/cue/issues/364#issuecomment-621002506_

I like that. Then it becomes very clear whether the result is open or not. Also the query extension syntax is slick here.

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/364#issuecomment-762672679_

List addition and multiplication has been removed from the language spec. There are now the `list.Concat` and `list.Repeat` as a substitute. We'll be adding an automated rewrite soon and then start phasing out these features. At a later point, we can rewrite these functions to use the query syntax. We could rewrite them now using comprehensions, but that seems a bit verbose.

**Comment by myitcv** [comment]
Given https://github.com/cue-lang/cue/issues/364#issuecomment-873388699, I think this issue can be closed. But please shout if I've missed anything above.
