### ISSUE TITLE
Support discriminator fields for OpenAPI

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#395]
_Originally opened by @wroge in https://github.com/cuelang/cue/issues/395_

### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.1.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What did you do?

I can't reproduce the behavior, so I'm linking the code from my gist..

I want to convert [this](https://gist.github.com/wroge/7cabe0d7e4b5f09be75453950aadf860#file-schema-cue-L124) Cuelang definition to the OpenAPI specification.

```
Element :: MatrixDropdown | Matrix | MatrixDynamic | Checkbox | Radiogroup | ImagePicker | Dropdown | Expression | Text | MultipleText | PanelDynamic | Panel | Html | Empty | Comment | File |Rating | Boolean
```

### What did you expect to see?

```
Element:
    oneOf:
    - $ref: '#/components/schemas/Matrix'
    - $ref: '#/components/schemas/MatrixDynamic'
    - $ref: '#/components/schemas/Checkbox'
    - $ref: '#/components/schemas/Radiogroup'
    - $ref: '#/components/schemas/ImagePicker'
    - $ref: '#/components/schemas/Dropdown'
    - $ref: '#/components/schemas/Expression'
    - $ref: '#/components/schemas/Text'
    - $ref: '#/components/schemas/MultipleText'
    - $ref: '#/components/schemas/PanelDynamic'
    - $ref: '#/components/schemas/Panel'
    - $ref: '#/components/schemas/Html'
    - $ref: '#/components/schemas/Empty'
    - $ref: '#/components/schemas/Comment'
    - $ref: '#/components/schemas/File'
    - $ref: '#/components/schemas/Rating'
    - $ref: '#/components/schemas/Boolean'
```
### What did you see instead?

[Gist](https://gist.github.com/wroge/3b27b875976c9d57dd2580196208779e#file-surveyjs-yaml-L358)

```
Element:
  oneOf:
  - allOf:
    - $ref: '#/components/schemas/MatrixDropdown'
    - not:
        anyOf:
        - $ref: '#/components/schemas/Matrix'
        - $ref: '#/components/schemas/MatrixDynamic'
        - $ref: '#/components/schemas/Checkbox'
        - $ref: '#/components/schemas/Radiogroup'
        - $ref: '#/components/schemas/ImagePicker'
        - $ref: '#/components/schemas/Dropdown'
        - $ref: '#/components/schemas/Expression'
        - $ref: '#/components/schemas/Text'
        - $ref: '#/components/schemas/MultipleText'
        - $ref: '#/components/schemas/PanelDynamic'
        - $ref: '#/components/schemas/Panel'
        - $ref: '#/components/schemas/Html'
        - $ref: '#/components/schemas/Empty'
        - $ref: '#/components/schemas/Comment'
        - $ref: '#/components/schemas/File'
        - $ref: '#/components/schemas/Rating'
        - $ref: '#/components/schemas/Boolean'
  - allOf:
    - $ref: '#/components/schemas/Matrix'
    - not:
        anyOf:
        - $ref: '#/components/schemas/MatrixDropdown'
        - $ref: '#/components/schemas/MatrixDynamic'
...
```

Is this a bug? If not, how can I prevent this behavior?

Thank You!

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/395#issuecomment-630836136_

CUE sometimes resorts to this pattern if it finds that it cannot represent the CUE expression in OpenAPI using oneOf or anyOf. This particular pattern was designed to handle Protobuf oneOf fields, which cannot straightforwardly be represented in OpenAPI (not correctly at least). 

So it seems that CUE's logic has detected such a case. The configs are rather large, so not sure why it thinks it should use this pattern. I tried reducing the example and it switched to oneOf. 

Might be illustrative to eliminate elements from Element to see which disjuncts are triggering this.

**Comment by cueckoo** [comment]
_Original reply by @wroge in https://github.com/cuelang/cue/issues/395#issuecomment-630854417_

Most ```Elements``` inherit or are based on ```Question```. When I comment out all the fields in Question, the result I want is displayed.
```
Question :: {
	//description?:             LocaleString
	//requiredText?:            string
	//title?:                   LocaleString
	//enableIf?:                ExpressionString
	...
}
```
Perhaps the similarity of the schemes (all based on Question) is a problem. I would like to add another example:
```
X :: A | B
A :: {
    x: string
}
B :: {
    x: string
    b: string
}
```
This results in:
```
X:
  oneOf:
  - allOf:
    - $ref: '#/components/schemas/A'
    - not:
        anyOf:
        - $ref: '#/components/schemas/B'
  - $ref: '#/components/schemas/B'
  type: object
```
What I actually want is to map the discriminator keyword from OpenAPI in CUE. I saw in the source code that this functionality might be built in.
Thank you very much!

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/395#issuecomment-631303856_

With your trimmed down example, at least, the conversion is correct. Note that in JSON Schema, the presence of extra fields is allowed. So an instance of A would also match B. So a `oneOf` would fail. One can also not use `anyOf`, as a faulty `b` would then just pass as an `a`.

One other solution would be to add `additionalField: false` to each struct. This is, however, also problematic. It means that unrecognized fields will be treated as errors. This means that the schema will be not be able to handle backwards compatibility. This is an absolute must to encode Protobuf, but it is generally a good idea.

Using discriminator field directives may indeed be an option. I wonder if you can't already try that by setting the fields of the structs in the disjunct already to their concrete values. If they packages were imported in `cue.mod/gen` you can define a parallel file in `cue.mod/usr` to just set these fields. The OpenAPI conversion should be able to handle enums. (See the modules, packages, and instances concept topic on cuelang.org.)

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/395#issuecomment-631304893_

In other words, it may be that you can already achieve the discriminator approach by just fixing the names manually.

**Comment by cueckoo** [comment]
_Original reply by @wroge in https://github.com/cuelang/cue/issues/395#issuecomment-631459001_

I think the trimmed example doesn't quite clarify the problem. It actually looks more like this:
```
X :: A | B
A :: {
    type: "a"
    value: string
}
B :: {
    type: "b"
    value: string
}
```
I noticed that if I reduce the complexity of the scheme, OneOf is used again. For example, if I set all fields that use LocaleString to string, the scheme is correct again. [gist](https://gist.github.com/wroge/7cabe0d7e4b5f09be75453950aadf860#file-z_reduced_schema-cue)
```
LocaleString :: string //| {[Locale]: string}
```
```
Element:
  oneOf:
  - $ref: '#/components/schemas/MatrixDropdown'
  - $ref: '#/components/schemas/Matrix'
  - $ref: '#/components/schemas/MatrixDynamic'
  - $ref: '#/components/schemas/Checkbox'
  - $ref: '#/components/schemas/Radiogroup'
  - $ref: '#/components/schemas/ImagePicker'
  - $ref: '#/components/schemas/Dropdown'
  - $ref: '#/components/schemas/Expression'
  - $ref: '#/components/schemas/Text'
  - $ref: '#/components/schemas/MultipleText'
  - $ref: '#/components/schemas/PanelDynamic'
  - $ref: '#/components/schemas/Panel'
  - $ref: '#/components/schemas/Html'
  - $ref: '#/components/schemas/Empty'
  - $ref: '#/components/schemas/Comment'
  - $ref: '#/components/schemas/File'
  - $ref: '#/components/schemas/Rating'
  - $ref: '#/components/schemas/Boolean'
  type: object
```

**Comment by myitcv** [comment]
I have just created https://github.com/cue-lang/cue/issues/3165. In the interests of consolidating discussion about how we could/should encode JSON Schema (and other) oneofs in CUE, I'm going to suggest we close this issue and consolidate conversation from this and other issues there.
