### ISSUE TITLE
MkdirAll function in tool/ package

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#420]
_Originally opened by @mikelnrd in https://github.com/cuelang/cue/issues/420_

**Is your feature request related to a problem? Please describe.**

I'm trying to write a command in a _tool.cue file in order to create a whole file tree. Some of the files are in sub directories and these sub directories don't yet exist.

**Describe the solution you'd like**
The feature request is for `tool/file.Create` to support some way of creating a file along with any non-existent parent directories of that file.

**Example:**
I have a list like the one below in cue. I loop through the list in cue and create a `file.Create` `Task` for each path in the list. This works fine for files where the directory already exists (like file1 in output/ as I create ./output first).

["./output/file1.txt", "./output/dir1/file2.txt", "./output/dir2/dir3/file3.txt", ... (many more files...)]

However I get an error for file2 and file3 as the directories under ./output don't exist. I'm hoping in the future I can tell cue to create these sub directories if they don't exist when it is creating the file. 

(Like how `mkdir -p "./nested/folder/deep"` works).

**Describe alternatives you've considered**
I could probably do some fancy splitting by '/' and looping and creating directories in the cue tool as separate tasks (assuming there's a way to create directories at the moment?)... but I think this would be a useful feature to have built into the cue tooling.

**Comment by cueckoo** [comment]
_Original reply by @verdverm in https://github.com/cuelang/cue/issues/420#issuecomment-642294242_

I think I would find it surprising if creating a file also created a folder as I don't know of any programming languages or operating systems where this happens.

I have been using the exec command to create directories. Having a Mkdir that acted like Go's MkdirAll would be a fine addition

**Comment by cueckoo** [comment]
_Original reply by @mikelnrd in https://github.com/cuelang/cue/issues/420#issuecomment-642627243_

@verdverm yes I think go's `MkdirAll` is what I was looking for.  https://golang.org/pkg/os/#MkdirAll

I've just got it working as you suggested by using an exec.Run task followed by a file.Create task. Thanks.

```
exampleTask: {
    _dir: "./some/nested/path/to/a/"
    _filename: "file.yaml"
    _contents: {
        hello: "world"
    }

    mkdir: exec.Run & {
        cmd: "mkdir -p \(_dir)"
    }
    create: file.Create & {
        filename: _dir + _filename
        contents: yaml.Marshal(_contents)
        $after: mkdir
    }
}
```

Feel free to close this issue, or keep open as a feature request for MkdirAll in cue's stdlib. Cheers.

**Comment by cueckoo** [comment]
_Original reply by @vikstrous2 in https://github.com/cuelang/cue/issues/420#issuecomment-823400278_

@mikelnrd your solution works when the name of the mkdir task is constant, but not if I need a dynamically generated list of tasks. With a dynamically generated list of tasks (one per file), I can't refer to another dynamically generated task in $after. For now I'll work around this issue by creating the folders outside cue, but this can get annoying in the future.

**Comment by cueckoo** [comment]
_Original reply by @myitcv in https://github.com/cuelang/cue/issues/420#issuecomment-849771675_

Having `os.Mkdir` as part of [`pkg/tool/os`](https://pkg.go.dev/cuelang.org/go@v0.4.1-0.20210525150538-aa61ee7f7c7c/pkg/tool/os) would seem to make sense to my mind. I would further suggest we don't need `MkdirAll` because we can have a `createParents` "parameter" to `Mkdir` that defaults to `false`.

**Comment by cueckoo** [comment]
_Original reply by @myitcv in https://github.com/cuelang/cue/issues/420#issuecomment-849772355_

(sent that too early)

If anyone would like to work on this, would be happy to help if there are any questions about the [contribution process](https://github.com/cuelang/cue/blob/master/doc/contribute.md)

**Comment by mpvl** [comment]
> Having os.Mkdir as part of pkg/tool/os would seem to make sense to my mind.
I think it makes more sense to put it in `pkg/tool/file`, where the other file-related functionality lives. Maybe the naming of that package was wrong in the end.

**Comment by eonpatapon** [comment]
> > Maybe the naming of that package was wrong in the end.

Do you talk about the file package ?

**Comment by myitcv** [comment]
For anyone following along, further discussion happening in https://review.gerrithub.io/c/cue-lang/cue/+/530736

**Comment by myitcv** [comment]
Re-opening because 079985f got reverted
