### ISSUE TITLE
load: race condition when running load.Instances

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#460]
_Originally opened by @myitcv in https://github.com/cuelang/cue/issues/460_

### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
v0.3.0-alpha1.0.20200730155834-304b02e40842
</pre>

### Does this issue reproduce with the latest release?

Yes (noted that API is currently not certified as concurrency safe).

### What did you do?

```
exec go run main.go

-- cue.mod/module.cue --
module: "mod.com"
-- go.mod --
module mod.com

go 1.15

require cuelang.org/go v0.3.0-alpha1.0.20200730155834-304b02e40842
-- main.go --
package main

import (
 "sync"

 "cuelang.org/go/cue/load"
)

func main() {
 var wg sync.WaitGroup
 for i := 0; i < 2; i++ {
  wg.Add(1)
  go func() {
   load.Instances([]string{"."}, nil)
   wg.Done()
  }()
 }
 wg.Wait()
}
-- x.cue --
package x

x: 5
```

### What did you expect to see?

A passing test (i.e. zero exit code)

### What did you see instead?

```
panic: not properly initialized (state: 0, value: <nil>)

goroutine 20 [running]:
cuelang.org/go/cue.makeValue(0xc0003c7620, 0xc0003ea2d0, 0xc0003ea2d0, 0x0)
        $WORK/gopath/pkg/mod/cuelang.org/go@v0.3.0-alpha1.0.20200730155834-304b02e40842/cue/types.go:614 +0x127
cuelang.org/go/cue.newChildValue(0xc0000ece80, 0x0, 0x5, 0xc00000e100)
        $WORK/gopath/pkg/mod/cuelang.org/go@v0.3.0-alpha1.0.20200730155834-304b02e40842/cue/types.go:587 +0x51
cuelang.org/go/cue.(*structValue).Lookup(0xc0000ece80, 0x8a94fa, 0x5, 0x10101000000, 0xc000000000)
        $WORK/gopath/pkg/mod/cuelang.org/go@v0.3.0-alpha1.0.20200730155834-304b02e40842/cue/types.go:140 +0x1d8
cuelang.org/go/cue.Value.Lookup(0xc0003c7620, 0xc00034fd40, 0xc0000ecfa8, 0x2, 0x2, 0xc000030000, 0xc0000ecf68)
        $WORK/gopath/pkg/mod/cuelang.org/go@v0.3.0-alpha1.0.20200730155834-304b02e40842/cue/types.go:1429 +0x19d
cuelang.org/go/internal/filetypes.parseType(0x0, 0x0, 0x0, 0xffffffffffffffff, 0x2a, 0xc00002410d, 0xd)
        $WORK/gopath/pkg/mod/cuelang.org/go@v0.3.0-alpha1.0.20200730155834-304b02e40842/internal/filetypes/filetypes.go:227 +0xe5
cuelang.org/go/internal/filetypes.ParseFile(0xc00002a4ab, 0x6, 0x0, 0xc000408230, 0x7, 0x7)
        $WORK/gopath/pkg/mod/cuelang.org/go@v0.3.0-alpha1.0.20200730155834-304b02e40842/internal/filetypes/filetypes.go:190 +0x2ef
cuelang.org/go/cue/load.(*loader).importPkg(0xc00000e040, 0x0, 0x0, 0xc000412000, 0x0)
        $WORK/gopath/pkg/mod/cuelang.org/go@v0.3.0-alpha1.0.20200730155834-304b02e40842/cue/load/import.go:153 +0xc32
cuelang.org/go/cue/load.(*loader).importPathsQuiet(0xc00000e040, 0xc0000edfb8, 0x1, 0x1, 0x0, 0x0, 0xc00007c0c0)
        $WORK/gopath/pkg/mod/cuelang.org/go@v0.3.0-alpha1.0.20200730155834-304b02e40842/cue/load/search.go:368 +0x658
cuelang.org/go/cue/load.(*loader).importPaths(0xc00000e040, 0xc0000edfb8, 0x1, 0x1, 0x0, 0x0, 0x0)
        $WORK/gopath/pkg/mod/cuelang.org/go@v0.3.0-alpha1.0.20200730155834-304b02e40842/cue/load/search.go:326 +0x4d
cuelang.org/go/cue/load.Instances(0xc0000edfb8, 0x1, 0x1, 0xc0000ede98, 0x0, 0x0, 0x0)
        $WORK/gopath/pkg/mod/cuelang.org/go@v0.3.0-alpha1.0.20200730155834-304b02e40842/cue/load/loader.go:62 +0x15e
main.main.func1(0xc00032b340)
        $WORK/main.go:14 +0x65
created by main.main
        $WORK/main.go:13 +0x78
exit status 2
[exit status 1]
FAIL: /tmp/testscript299275306/0/script.txt:1: unexpected command failure
error running race.txt in /tmp/testscript299275306/0
```

**Comment by cueckoo** [comment]
_Original reply by @myitcv in https://github.com/cuelang/cue/issues/460#issuecomment-684728820_

Just ran into this again. Whilst the API is not concurrency safe, might it be worth putting place a few mutexes in key places?

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/460#issuecomment-729657543_

Update:
The biggest impediment to concurrent running was updating string indices concurrently. This is now fixed. It previously used a two-layered approach, to manage strings for builtin packages in a separate layer. This has been replaced with using a single layer and a sync.Map. This proved to be equally fast. Coincidentally, it also allows lazy loading of packages.

Another problem is the potential double evaluation of `cuegenInstance` in filetypes. This is easily solved.

But the trickiest problem seems to be related to the use of scratch registers in Vertices. This is quite hard to prevent a race on, other than changing the cycle detection to not use this fields (a TODO already). Once that is addressed, it should be possible to load in parallel.

**Comment by cueckoo** [comment]
_Original reply by @Ereski in https://github.com/cuelang/cue/issues/460#issuecomment-752727827_

Both `Compile` and `CompileFile` suffer this as well even between completely separate `Runtime`s

**Comment by cueckoo** [comment]
_Original reply by @verdverm in https://github.com/cuelang/cue/issues/460#issuecomment-752739012_

@mpvl commented on the main impediments here: https://github.com/cuelang/cue/discussions/613

**Comment by mvdan** [comment]
I believe @rogpeppe fixed this particular race in https://review.gerrithub.io/c/cue-lang/cue/+/556519 and added a test. We should use https://github.com/cue-lang/cue/issues/1746 to track the safe concurrent use of `cue.Value` objects.
