### ISSUE TITLE
Request: More verbose examples

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#674]
_Originally opened by @olingern in https://github.com/cuelang/cue/issues/674_

**Is your feature request related to a problem? Please describe.**
I was looking over the [documentation](https://cuelang.org/docs/usecases/configuration/), and it wasn't immediately clear to me how I could use cue for my specific use-cases.

**Describe the solution you'd like**
While listening to the [Go Time](https://changelog.com/gotime/163) podcast, I did hear that cue could be used for Github Actions and thought that was a really interesting. It would be great to see an example like this on the website.

Also, I'd love to see something like a "cue workflow" so that I know where/how to start, i.e.:
- Using a remote JSON schema like Github Actions
- How can I validate my Github Action `.yml`
- Is the desired goal of cue to have configuration files live alongside cue files, be an eventual replacement, or both?
- Using cue locally

**Describe alternatives you've considered**
n/a

**Additional context**
I heard about cue on [Go Time](https://changelog.com/gotime/163).

Thanks for the neat tool and great work!

**Comment by mvdan** [comment]
The new website has a number of [tutorials](https://cuelang.org/docs/tutorial/), [how-to guides](https://cuelang.org/docs/howto/), and [concept guides](https://cuelang.org/docs/concept/) - that should be much more helpful than the content on the old site :) If you find any particular gap or issue with those, please file a new issue with a specific request and we'll take a look. Thanks!
