### ISSUE TITLE
encoding: missing support for toml

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#68]
_Originally opened by @xinau in https://github.com/cuelang/cue/issues/68_

(Go) Tools like InfluxDB, GitLab CI (Runner), Traefik use [TOML](https://github.com/toml-lang/toml) as their configuration language. Atm. CUE has no encoding support for TOML configuration files to be imported or exported. Since Go doesn't have native support for TOML, a [third-party implementation](https://github.com/toml-lang/toml/wiki#implementations) needs to be imported as it's the case for YAML. Another thing to be aware of is that the native support for Date-Time, Date, Time values in TOML. Maybe this could be something CUE might want to support in the future as well. Also a mapping of [array of tables](https://github.com/toml-lang/toml#array-of-tables) to a appropriate CUE representation might be needed.

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/68#issuecomment-517231849_

I'm fine with TOML, being as common as it is, to be one of the few more configuration formats that's natively supported. At the moment, YAML, JSON, Go, Proto, and OpenAPI are higher on the list to complete support for, though.

Note that generating TOML output should already not be too hard using the text/template builtin package.

CUE has some limited support for time and date parsing through the time builtin package. It is high on the list to complete this support as part of the OpenAPI support effort. With this, a time field is indicated as:
```
import "time"

meetingTime: time.Time
```
where meetingTime is a string with the respective time format.

I don't understand why arrays of tables are not just lists of values. It seems to be a special TOML notation that needs no special treatment in CUE. I do plan to add support for associative lists at some point, which would allow one to define different items of a list at different locations, though, sticking to CUE's associativity and commutativity properties, without any guarantee of order other than adhering to some topological sort.

**Comment by jmgilman** [comment]
Is this feature request on the radar for getting some attention soon? Using text/template works in simple cases but can get out of hand pretty quickly.

**Comment by myitcv** [comment]
This is not currently a priority because there are aspects like package management that are higher priority. But we would very much welcome community contributions in this space.

**Comment by yujunz** [comment]
MVP in cue. 

```cue
import (
    "strings"
    "encoding/json"
)

cue: {
	tables: {
		global_tags: {
			cluster:      "foo"
			environment?: string
		}
		agent: {
			interval: "interval"
		}
	}

	table_arrays: {
		"inputs.prometheus": [
			{
				metric_version: 2
			}, {
				metric_version: 2
			},
		]
	}
}

toml: strings.Join([ for table, kv in cue.tables {
	strings.Join(["[\(table)]"]+[ for k, v in kv {"\(k) = \(json.Marshal(v))"}], "\n")
}]+[ for table, array in cue.table_arrays {
	strings.Join([ for kv in array {
		strings.Join(["[[\(table)]]"]+[ for k, v in kv {"\(k) = \(json.Marshal(v))"}], "\n")
	}], "\n\n")
}], "\n\n")
```

renders

```toml
[global_tags]
cluster = "foo"

[agent]
interval = "interval"

[[inputs.prometheus]]
metric_version = 2

[[inputs.prometheus]]
metric_version = 2
```
https://cuelang.org/play/?id=YEIedqgEzNT#cue@export@cue

Nesting tables are hard to implement and likely requires extension in cue.

**Comment by mvdan** [comment]
A TOML decoder and encoder are now in master and wired up to `cmd/cue`, so they should work for most basic use cases. Please let us know if you find any bugs either in master or in the upcoming alpha, or if anything doesn't behave like you would expect it to :)

Given that initial support is now merged, we have closed this issue, but we have opened a number of others for follow-up tasks:
* https://github.com/cue-lang/cue/issues/3339
* https://github.com/cue-lang/cue/issues/3342
* https://github.com/cue-lang/cue/issues/3343
* https://github.com/cue-lang/cue/issues/3344

**Comment by bjackman** [comment]
I don't have the `toml` option in the `cue export` command - am I missing anything? I got this from `go install cuelang.org/go/cmd/cue@master`.

```
❯❯  cue version
cue version v0.12.0-alpha.1.0.20241227103556-b0c6204c4df0

go version go1.22.2
      -buildmode exe
       -compiler gc
     CGO_ENABLED 1
          GOARCH amd64
            GOOS linux
         GOAMD64 v1
cue.lang.version v0.12.0

❯❯  cue export -o toml limmat.cue
no encoding specified for file "toml"
```

**Comment by bjackman** [comment]
Oh, yes I was indeed missing something - I wanted `-o out.toml` or `--out toml`. 

I was rather quick to assume something was wrong (other than me being stupid) because it's not in the help string:

```
❯❯  cue help export                                                                                                                                                                     

..

Formats

The following formats are recognized:

    cue  output as CUE
              Outputs any CUE value.

   json  output as JSON
              Outputs any CUE value.

   yaml  output as YAML
              Outputs any CUE value.

   text  output as raw text
              The evaluated value must be of type string.

 binary  output as raw binary
              The evaluated value must be of type string or bytes.
```
```

**Comment by mvdan** [comment]
@bjackman the issue there is the flag name, not the value you passed:

```
$ cue export -h
[...]
      --out string               output format (run 'cue help filetypes' for more info)
  -o, --outfile string           filename or - for stdout with optional file prefix (run 'cue help filetypes' for more info)
```
