### ISSUE TITLE
alpha.cuelang.org: automated testing of all docs

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#712]
_Originally opened by @myitcv in https://github.com/cuelang/cue/issues/712_

This is an umbrella issue for ensuring that all of our docs are covered by automated tests in some way, including things like the [project README](https://github.com/cuelang/cue/blob/master/README.md). 

For this we could well leverage [`preguide`](https://github.com/play-with-go/preguide).

**Comment by mvdan** [comment]
Is this issue obsoleted by the new website work? I don't think the README has (nor should have) anything complex enough to need this.

**Comment by myitcv** [comment]
> Is this issue obsoleted by the new website work

Yes, it's covered by it. Almost "done" from the perspective of the first version of the [`preprocessor`](https://github.com/cue-lang/cuelang.org/tree/alpha/internal/cmd/preprocessor), at which point this will be closed. I will relabel accordingly to cuelang.org.

**Comment by myitcv** [comment]
Closing this PR. This work is actively in progress and will be a key part of alpha.cuelang.org.
