### ISSUE TITLE
Cannot "pass" value to imported module's hidden field

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#771]
_Originally opened by @viennem in https://github.com/cuelang/cue/issues/771_

### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version 0.3.0-beta.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes, can reproduce with `cue version v0.3.0-beta.5 linux/amd64`

### What did you do?

I have a `main.cue` file, and a `mymodule` module with a `mymodule.cue` file.

```
├── cue.mod
│   ├── module.cue
│   ├── pkg
│   └── usr
├── main.cue
└── mymodule
    └── mymodule.cue
```

```bash
cue mod init example.com
```

```bash
cat << EOF > main.cue
package test

import "example.com/mymodule"

result: mymodule & {_passed: 1}
EOF
```
- main.cue uses `mymodule` by passing hidden field `_passed`

```bash
mkdir mymodule
cat << EOF > mymodule/mymodule.cue 
package mymodule

_passed: int
use: _passed
EOF
```
- mymodule declares `_passed` field, and uses it to produce a value for main

### What did you expect to see?

```
{
    "result": {
        "use": 1
    }
}
```

### What did you see instead?

```
result.use: incomplete value int
```

If I replace `_passed` with `#passed`, I get the expected result.
Moreover, this exemple was working as expected in cue 0.2.

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/771#issuecomment-779274671_

The fact that it worked in v0.2 was a bug in v0.2. Hidden fields were, also in v0.2, defined to be not visible in other packages (this is why they are called hidden, in fact). There was an issue open back then (#503) to track this, which was closed when they were properly implemented.

Use a definition if you want a field that is settable by other packages, yet not part of the data output.

**Comment by harpratap** [comment]
> Use a definition if you want a field that is settable by other packages, yet not part of the data output.

@mpvl Is there any example somewhere on what you mean by this? From what I can understand I can do this 
```
use: {
    #passed 
}
```
But this will also not work in case I want `#passed` to be hidden in `use` and then compute another field using it like `myValue: "\(_#passed)"`

**Comment by verdverm** [comment]
Hidden fields include both structs (`_name: _`) and definitions (`_#name: _`), both are not accessible from outside of the package they exist in.

The ideas is to set a visible definition (`#name: _`), as definitions will not appear when exported.
