### ISSUE TITLE
`for` errors out on solvable cycles

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#779]
_Originally opened by @Ereski in https://github.com/cuelang/cue/issues/779_

Current master (2c86835)

Similar to the previous issues I've opened, this time it's `for` that is having trouble with cycles:

```
X: Y.message

STATE: {
    for k, v in Y {
        if k != "message" {
            "\(k)": v
        }
    }
}

Y: STATE & {
    message: X
}
```

This is a simple stateful bidirectional projection expressed in CUE (`STATE` is saved and restored as needed). In one way, `Y` is forked into `X` and `STATE`. In the other way, `X` and `STATE` are joined into `Y`. Two usage examples are:

```
X: "test"

STATE: {
    code: 101
}
```

and

```
Y: {
    message: "test"
    code: 101
}
```

Both of which errors out with a cycle error. Even defining `X`, `STATE`, and `Y` all at the same time causes a cycle error.

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/779#issuecomment-782848104_

Another interesting one. :)

The cycle here is detected here because the `for` comprehension iterators over the the very struct in which it embeds.

Arguably, of course, that should be okay as long as it does not add new fields that then should have been used during evaluation. 

FTR, in v0.2 the cycle check did not work correctly and this construct would produce inaccurate results.

**Comment by mpvl** [comment]
We could probably break this cycle if we allow comprehensions that insert fields in structs that are used as a source that do not introduce any new fields.

**Comment by mpvl** [comment]
@ereski We could probably break this cycle if we allow comprehensions that insert fields in structs that are used as a source that do not introduce any new fields.
