### ISSUE TITLE
cmd/cue: multi-byte characters in YAML result in bad formatting

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#826]
_Originally opened by @uhthomas in https://github.com/cuelang/cue/issues/826_

### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.3.0-beta.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What did you do?

```sh
curl -Lfv https://github.com/jetstack/cert-manager/releases/download/v1.2.0/cert-manager.yaml > t.yaml
cue import --list t.yaml
```

### What did you expect to see?

A nicely formatted CUE file.

### What did you see instead?

![](https://kipp.6f.io/n4JI0s8Cg8rH.png)

**Comment by cueckoo** [comment]
_Original reply by @uhthomas in https://github.com/cuelang/cue/issues/826#issuecomment-797121973_

Another example

![](https://kipp.6f.io/g7nBt0f3f_Pd.png)

**Comment by cueckoo** [comment]
_Original reply by @myitcv in https://github.com/cuelang/cue/issues/826#issuecomment-797879468_

Confirmed with 7c5d28e6721a260dc2efdf623a015b5aea195d9e

**Comment by mpvl** [comment]
Formatting looks fine to me. A more specific example is welcome.

**Comment by uhthomas** [comment]
@mpvl Sorry, I must not have seen your comment.

Given https://github.com/cert-manager/cert-manager/releases/download/v1.11.0/cert-manager.crds.yaml

```sh
❯ cue import --list cert-manager.yaml
```

Produces https://gist.github.com/uhthomas/da3842ef5880be0e26f05a00272a3ae4

The formatting is initially fine, but then looks really weird around here: https://gist.github.com/uhthomas/da3842ef5880be0e26f05a00272a3ae4#file-cert-manager-cue-L3081

```cue
apiVersion:
	"apiextensions.k8s.io/v1", kind:
	"CustomResourceDefinition", metadata: {

	name: "certificaterequests.cert-manager.io"
	labels: {
		app:                          "cert-manager"
		"app.kubernetes.io/name":     "cert-manager"
		"app.kubernetes.io/instance": "cert-manager"
		// Generated labels
		"app.kubernetes.io/version": "v1.11.0"
	}
}, spec: {

	group: "cert-manager.io"
```

I hope it's clear that something is wrong here.
