### ISSUE TITLE
doc/spec: binary_lit production incorrectly omits "_" separator

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#828]
_Originally opened by @zombiezen in https://github.com/cuelang/cue/issues/828_

The production for `binary_lit` is:

```
binary_lit  = "0b" binary_digit { binary_digit } .
```

However, the example below permits:

```
0b0101_0001
```

I believe the correct production is:

```
binary_lit  = "0b" binary_digit { [ "_" ] binary_digit } .
```

**Comment by cueckoo** [comment]
_Original reply by @myitcv in https://github.com/cuelang/cue/issues/828#issuecomment-797605794_

Thanks for raising this, @zombiezen. Sorry, this got "lost" in the cuelang.org repo.

**Comment by mvdan** [comment]
Someone sent a PR to fix this last year, so we can mark this as solved :) https://github.com/cue-lang/cue/pull/1782
