### ISSUE TITLE
suggest adding code samples to the README

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#89]
_Originally opened by @dcsan in https://github.com/cuelang/cue/issues/89_

i came from hackernews and it took me a lot of digging before i could actually see what the format/language looks like... would really suggest putting at least some simple examples on the first page, the readme. that would be much quicker to grok than trying to decode the front page.

esp with the tutorial, it's like one idea per page. 
one nice condensed example that shows a few ideas together would be great for quickly getting the idea across.

https://github.com/cuelang/cue/blob/master/doc/tutorial/basics/curly.md

**Comment by mvdan** [comment]
@myitcv I think this one could be solved by the new website landing page and its docs. I don't imagine we want to also add examples with docs to the README, given the limits of markdown.

**Comment by myitcv** [comment]
Agreed. I'd suggest we close this on the understanding that docs will be better served from https://alpha.cuelang.org/ (which will become the default at https://cuelang.org/.
