### ISSUE TITLE
Validation error for concreteness doesn't include position information

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#905]
_Originally opened by @j-maxi in https://github.com/cuelang/cue/issues/905_

### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.4.0-alpha.1.0.20210415183916-c5c9125d9970 linux/amd64
</pre>

### What did you do?

<pre>
$ cat test.cue 
parameters: {
        foo: string
}

$ cue eval -c test.cue
</pre>

### What did you expect to see?

Error message with position information where a value is not concrete.

### What did you see instead?

No position information included.

<pre>
parameters.foo: incomplete value string
</pre>

With v0.2.2, I got position information as follows.
<pre>
$ cue version v0.2.2 linux/amd64

$ cue eval -c test.cue
parameters.foo: incomplete value (string):
    ./test.cue:2:7

</pre>

**Comment by j-maxi** [comment]
@mpvl 
I am afraid I still don't see a position information with v0.4.0. Am I missing something?

```bash
$ cue version
cue version v0.4.0 linux/amd64

$ cat test.cue 
parameters: {
        foo: string
}

$ cue eval -c test.cue 
parameters.foo: incomplete value string
```

**Comment by myitcv** [comment]
Hmm, it does seem like a mistake that the original issue got closed via 276ce26, not least because that commit does not include the original test case.

Confirmed with 0f53054d that:

```
! exec cue eval -c test.cue
stderr 'test\.cue:2'

-- test.cue --
parameters: {
	foo: string
}
```

still fails with:

```
> ! exec cue eval -c test.cue
[stderr]
parameters.foo: incomplete value string
[exit status 1]
> stderr 'test\.cue:2'
FAIL: /tmp/testscript197403372/repro.txt/script.txt:2: no match for `test\.cue:2` found in stderr
```

 So re-opening.

**Comment by rogpeppe** [comment]
Here's another test case: this one caused by a conflict between two default values. When this happens in a large config, it's hard to find out what the issue is:

```
x: *"b" | string
x: *"a" | string
```

**Comment by mvdan** [comment]
This appears to be fixed as of CUE v0.6.0-beta.1; using Paul's testscript, I see:

```

> ! exec cue eval -c test.cue
[stderr]
parameters.foo: incomplete value string:
    ./test.cue:2:7
[exit status 1]
```

**Comment by rogpeppe** [comment]
@mvdan That last test case I mentioned isn't fixed yet though. I'll raise another issue for that.

**Comment by mvdan** [comment]
Yes, please do, with a testscript :)

**Comment by rogpeppe** [comment]
@mvdan 
> This appears to be fixed as of CUE v0.6.0-beta.1

Arguably there's still a slight regression from v0.2.2, as that version prints _both_ locations of `x`, not just one.
It's not entirely clear to me whether it should be surfacing all locations of the non-concrete value - I think it probably should, given that neither is technically more important than the other.

**Comment by mvdan** [comment]
Sorry, are you talking about https://github.com/cue-lang/cue/issues/2507 now? The original reproducer here has no `x` declaration.

**Comment by rogpeppe** [comment]
@mvdan ah yes, sorry, I am - should've checked. I'll mention it in that issue.
