### ISSUE TITLE
Cannot find concrete value

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#926]
_Originally opened by @kumorid in https://github.com/cuelang/cue/issues/926_

### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version 0.4.0-alpha.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What did you do?

I run 
<pre>
cue export tst.cue
</pre>

Where tst.cue is

<pre>

#Volatile: size: uint
#Persistent: volume: string

#Volume: #Volatile | #Persistent
//==========

#Spec: {
  config: {
    resource: [string]: #Volume
    param: [string]: _
  }
}

#Real: {
  obj: #Spec
  config: _
}

//==========

#Apply: {
  $p = #params: #Real
  out: {
    $p.obj.config
    $p.config
  }
}

//========

#MyObj: #Spec & {
  config: resource: logvolume: #Volume
  config: param: size: >10
}

#MyReal: {
  obj: #MyObj
  config: resource: logvolume: {size: 5}
  config: param: size: 11
}

real: (#Apply &  {#params: #MyReal}).out

</pre>

### What did you expect to see?
<pre>
{
    "real": {
        "resource": {
            "logvolume": {
                "size": 5
            }
        },
        "param": {
            "size": 11
        }
    }
}
</pre>

### What did you see instead?
<pre>
real.resource.logvolume: incomplete value {size:5} | {size:5,volume:string}
</pre>

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/926#issuecomment-828184999_

First analysis: it looks like the field `size: 5` gets erroneously unified with the `#Persistent` definition, which, in turn, leads to the disjunction not being resolved.

**Comment by cueckoo** [comment]
_Original reply by @kumorid in https://github.com/cuelang/cue/issues/926#issuecomment-828463057_

The thing is that
<pre>
real: {size: 5} | {size:5, volume: string}
</pre>

resolves nicely to 
<pre>
real: {size: 5}
</pre>

So, fixing that is an improvement, or an error on how it is supposed to work?

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/926#issuecomment-828573832_

`real: {size: 5} | {size:5, volume: string}` only resolved to `real: {size: 5}` in v0.2. This was problematic, though (long story).

But it should never get to this point in the first place: since `#Persistent: volume: string` is closed, unifying it with `size: 5` eliminates it from the disjunction.

So this seems to be a CUE closedness bug. Fixing that would make it resolve as you expect.

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/926#issuecomment-828722508_

Ah, it is not a bug: the problem is the line `$p.config`, which ends up embedding `_` (or "any") into the `out` struct, indicating it is allowed to be any value. This, in turn, disables all closedness checking for `out`, and thus disables the mechanism, for eliminating the disjunction.

I'm not sure what the purpose is of this line. I would in general suggest removing some of the indirections in the above config and simplify it down a bit. What is it you're trying to accomplish here?

**Comment by myitcv** [comment]
@kumorid - I'm doing a bit of combing through old issues, and I see this is marked as "working as intended" so I will close this on that basis, but please shout if you think there is more here to resolve. Thanks
