### ISSUE TITLE
Examples in the documentation

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#936]
_Originally opened by @Thiht in https://github.com/cuelang/cue/issues/936_

**Is your feature request related to a problem? Please describe.**
I spent 10 minutes navigating on https://cuelang.org/ and still have no idea what Cue is or what it looks like. The documentation desperately needs examples.

The animated example on the landing page is not great because:

- it's too long
- it's not scrollable
- it's not pauseable
- it's not documented, I have no idea what it does (and I tried to copypaste what I don't understand but the scrolling prevents it)                                                                            

**Describe the solution you'd like**
Please add a few simple and more complex examples on the landing page, so that it's clear what the project is about.

- - -

I think it would be way clearer and more efficient if you just presented en example YAML and the example CUE validating it side by side.

**Comment by cueckoo** [comment]
_Original reply by @marcellanz in https://github.com/cuelang/cue/issues/936#issuecomment-831442318_

While this issue be solved might be very valuable, I found this part of the documentation very helpful to understand what CUE is:
https://cuelang.org/docs/concepts/logic/

**Comment by cueckoo** [comment]
_Original reply by @myitcv in https://github.com/cuelang/cue/issues/936#issuecomment-848890905_

@Thiht thank you for the feedback. I'd be keen to understand how you think we can improve things.

On the homepage there is a "Learn more" button that links to the docs page. On that index page is a link to tutorials, which then links through to the introductory tour of the language. Did you manage to find the tutorials? If not, it sound like we could make that a simpler journey. 

> Please add a few simple and more complex examples on the landing page, so that it's clear what the project is about.

What tricky about this is that the homepage could easily become overwhelmed with examples. The animated "example" is just a teaser in that respect.

> I think it would be way clearer and more efficient if you just presented en example YAML and the example CUE validating it side by side.

This is one use case for CUE, and that example is present in the tutorial. There are, however, lots of other use cases, which is one of the main challenges when it comes to explaining CUE. Nonetheless, it is a challenge we need to tackle, so your feedback and ideas are very much welcomed.

**Comment by cueckoo** [comment]
_Original reply by @Thiht in https://github.com/cuelang/cue/issues/936#issuecomment-848907534_

> On the homepage there is a "Learn more" button that links to the docs page. On that index page is a link to tutorials, which then links through to the introductory tour of the language. Did you manage to find the tutorials? If not, it sound like we could make that a simpler journey.

To be completely honest, I clicked "Learn More", then "Tutorial", I paused because I hesitated between "Basics" and "Introduction", I finally clicked "Introduction" and then I lost interest because the list seemed unordered and I didn't know what to click next. There's actually some code samples with one more click, but I think it was already to many clicks for a basic "what is this?".

> What tricky about this is that the homepage could easily become overwhelmed with examples. The animated "example" is just a teaser in that respect.

I understand that, documentation is hard. The "teaser" idea is good, but the animated example might not be a good way to present it IMO (unless I can pause it/copy paste it). Maybe you could just focus on one or two features of cue ("data validation"/"schema definition" seems like a good candidate from a naive point of view, although I'm still not completely sure what cue is about) and present easy code?
A good example of what I like as a user is the landing page of Rocket (a Rust web framework): https://rocket.rs/
Their three examples ("Hello, Rocket!", "Forms? Check!", and "JSON, out of the box.") are a neat way to show how a few basic features look like and what they can do. This doesn't cover all the use cases obviously, but a few common ones are covered and it gives a "feeling" to the reader.
In your case, the landing page lists six categories (Data validation, Configuration, etc.), maybe an illustrative example for each one would work.

**Comment by cueckoo** [comment]
_Original reply by @myitcv in https://github.com/cuelang/cue/issues/936#issuecomment-848975488_

> A good example of what I like as a user is the landing page of Rocket (a Rust web framework): https://rocket.rs/

An example like this is excellent feedback, thank you.

> In your case, the landing page lists six categories (Data validation, Configuration, etc.), maybe an illustrative example for each one would work.

Indeed, a short-form presentation like you suggest might work well.

**Comment by chancez** [comment]
I found this to be a huge problem as well. Look at https://jsonnet.org and https://dhall-lang.org for two configuration languages that have prominent examples, right on the homepage. I still don't know what cue code even looks like 🤷

**Comment by myitcv** [comment]
Thanks for the feedback, @chancez. This is on our radar to be improved.

**Comment by myitcv** [comment]
We have recently launched a revised version of https://cuelang.org/ which has an improved tour (https://cuelang.org/docs/tour), along with lots of other improved documentation which can be found via search: https://cuelang.org/search/. If there are things that you would like to see on the new site or problems, please report via the "Report an issue" link at the bottom of each page.

**Comment by myitcv** [comment]
cc @jpluscplusm
