### ISSUE TITLE
documentation: Modify the confusing tour/references/aliases page

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#948]
_Originally opened by @PierreR in https://github.com/cuelang/cue/issues/948_

**Documentation of aliases & let**

The following page of the doc refering to `aliases` is using the `let` construct:
https://cuelang.org/docs/tutorials/tour/references/aliases/

But to be honest I am not sure if the page is meant to introduce the concept of `aliases` or the `let` construct. These two are treated in the spec.md as two different concepts (with different use cases).

**Describe the solution you'd like**

I suggest to align the page with the spec.md to avoid confusion.

To the best of my knowledge a more idiomatic way to write the code snippet of the aliases page would be:
```
A=a: {
    d: 3
}
b: {
    a: {
        // A provides access to the outer "a" which would
        // otherwise be hidden by the inner one.
        c: A.d
    }
}
```

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/948#issuecomment-837922840_

This is an artifact of the time when there was no `let` and the same syntax/terminology was used to describe both. 

This is indeed very misleading and should be fixed.

**Comment by mvdan** [comment]
The latest version of https://cuelang.org/docs/tour/references/aliases/ does not make use of any `let` declarations, so I believe this issue is fuxed.
