### ISSUE TITLE
Never ending export

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#951]
_Originally opened by @kumorid in https://github.com/cuelang/cue/issues/951_

### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version 0.4.0-beta.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What did you do?

I ran

<pre>
cue export -e configed
</pre>

on the couple of files that follow:

<pre>
-- model.cue --
package k

#Volatile: size: uint
#Persistent: volume: string
#Volume: #Volatile | #Persistent

#Secret: secret: string 

#Resource: #Volume | #Secret

#Configurable: {
	parameter:  [string]:  _         
	resource:   [string]: #Resource
}

#Component: {

	#FileMap: {
		path:   string
		data:   _ 
	} | {
		path:   string
		#Secret
	}

	#FolderMap: {
		path: string
		{tree: [...#FSMap]} | {volumeref: string }
	}

  #FSMap: #FileMap | #FolderMap

	
	#Mapping: filesystem: [...#FSMap]

	#Container: {
		name:  string
		mapping: #Mapping
	}

	config: #Configurable

	code: [cn=string]: #Container & {name: cn}
}

#Artifact: {
  ref: {...}
  description: #Component
}

#ConfigureArtifact: {
	 $p = #params: {
		artifact: #Artifact
		config: #Configurable
	}
	out: $p.artifact & {description: config: $p.config}
}
-- frontend.cue --
package k

#Frontend : #Artifact & {
  ref: {
    name: "frontend"
    version: [0,0,3]
  }

  description:   {

    config: {
      parameter: {
        frontendcfg: a: 2
      }
      resource: {
        logvolume: #Volume
      }
    }

    code: mainfrontend: {
      name: "mainfrontend"

      mapping: {
        filesystem: [
          {
            path: "/config/config.json"
            data: config.parameter.frontendcfg
          },
          {
            path: "/workspace"
            volumeref: "logvolume"
          }
        ]
      }
    }
  }
}

configed: (#ConfigureArtifact & {
  #params: {
    artifact: #Frontend
    config: resource: logvolume: volume: "myvol"
  }
}).out

</pre>

The above code is an extensive simplification of the original code we had.
Eliminating the `configed` field and running, e.g., `cue eval -e \#Frontend` produces the expected output.
Leaving the `configed` field as shown above, produces the effect describe: a never-ending computation.

### What did you expect to see?
I expected the command to end with a suitable result

### What did you see instead?

The command never ends (apparently)

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/951#issuecomment-836489117_

Confirmed the issue, needs investigation what causes it.

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/951#issuecomment-836690546_

Quick analysis, not sure yet what is going on, but reduced the issue to:
```
#Component: {
	#FolderMap: {tree: [...#FSMap]}  | {b: _}

 	#FSMap: { a: _ } | #FolderMap

	#Container: mapping: [...#FSMap]

	code: #Container
}

configed: #Component
configed: #Frontend

#Frontend: #Component
#Frontend: code: mapping: [{ }]
```
All elements seem to be necessary.

As a temporary workaround, if that works for you, you could move `#FileMap`, `#FSMap`, and `#FolderMap` to outside of `#Component`.  Clearly it should work as is, and this is not the same, but it does remove the issue.

**Comment by mvdan** [comment]
The original reproducer now finishes quickly for me, on v0.6.0-beta.1:

```
> exec cue export -e configed
[stdout]
{
    "ref": {
        "name": "frontend",
        "version": [
            0,
            0,
            3
        ]
    },
    "description": {
        "config": {
            "parameter": {
                "frontendcfg": {
                    "a": 2
                }
            },
            "resource": {
                "logvolume": {
                    "volume": "myvol"
                }
            }
        },
        "code": {
            "mainfrontend": {
                "name": "mainfrontend",
                "mapping": {
                    "filesystem": [
                        {
                            "path": "/config/config.json",
                            "data": {
                                "a": 2
                            }
                        },
                        {
                            "path": "/workspace",
                            "volumeref": "logvolume"
                        }
                    ]
                }
            }
        }
    }
}
PASS
```

We must have fixed this at some point in the past two years :)
